HTTP/1.1 200 OK
Transfer-Encoding: chunked
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Cache-Control: no-cache
Content-Security-Policy: default-src 'none'
Content-Type: application/json; charset=utf-8
Date: Sat, 31 Mar 2018 23:18:47 GMT
Link: <https://api.github.com/search/issues?q=repo%3APylons%2Fpyramid+type%3Aissue+state%3Aclosed&page=2>; rel="next", <https://api.github.com/search/issues?q=repo%3APylons%2Fpyramid+type%3Aissue+state%3Aclosed&page=28>; rel="last"
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Server: GitHub.com
Status: 200 OK
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Accepted-Oauth-Scopes: 
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Github-Media-Type: github.v3; format=json
X-Github-Request-Id: D7C7:094A:143E66A:2CD5A66:5AC01756
X-Oauth-Scopes: 
X-Ratelimit-Limit: 30
X-Ratelimit-Remaining: 27
X-Ratelimit-Reset: 1522538387
X-Runtime-Rack: 0.489545
X-Xss-Protection: 1; mode=block

8000
{"total_count":816,"incomplete_results":false,"items":[{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3233","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3233/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3233/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3233/events","html_url":"https://github.com/Pylons/pyramid/issues/3233","id":300150292,"number":3233,"title":"Sphinx build fails for sphinxcontrib.autoprogram","user":{"login":"stevepiercy","id":102112,"avatar_url":"https://avatars1.githubusercontent.com/u/102112?v=4","gravatar_id":"","url":"https://api.github.com/users/stevepiercy","html_url":"https://github.com/stevepiercy","followers_url":"https://api.github.com/users/stevepiercy/followers","following_url":"https://api.github.com/users/stevepiercy/following{/other_user}","gists_url":"https://api.github.com/users/stevepiercy/gists{/gist_id}","starred_url":"https://api.github.com/users/stevepiercy/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/stevepiercy/subscriptions","organizations_url":"https://api.github.com/users/stevepiercy/orgs","repos_url":"https://api.github.com/users/stevepiercy/repos","events_url":"https://api.github.com/users/stevepiercy/events{/privacy}","received_events_url":"https://api.github.com/users/stevepiercy/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-02-26T08:42:48Z","updated_at":"2018-02-27T20:28:48Z","closed_at":"2018-02-27T20:28:47Z","author_association":"OWNER","body":"sphinx error: Could not import extension sphinxcontrib.autoprogram (exception: cannot import name 'Directive')\r\n\r\nSee SO post:\r\nhttps://stackoverflow.com/questions/48892261/sphinx-no-module-named-compat\r\n\r\nAnd open PR:\r\nhttps://github.com/sphinx-contrib/autoprogram/pull/2\r\n\r\nNew release should be out soon.","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3232","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3232/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3232/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3232/events","html_url":"https://github.com/Pylons/pyramid/issues/3232","id":297630898,"number":3232,"title":"chameleon: semi misleading template error messages","user":{"login":"castilma","id":17392981,"avatar_url":"https://avatars3.githubusercontent.com/u/17392981?v=4","gravatar_id":"","url":"https://api.github.com/users/castilma","html_url":"https://github.com/castilma","followers_url":"https://api.github.com/users/castilma/followers","following_url":"https://api.github.com/users/castilma/following{/other_user}","gists_url":"https://api.github.com/users/castilma/gists{/gist_id}","starred_url":"https://api.github.com/users/castilma/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/castilma/subscriptions","organizations_url":"https://api.github.com/users/castilma/orgs","repos_url":"https://api.github.com/users/castilma/repos","events_url":"https://api.github.com/users/castilma/events{/privacy}","received_events_url":"https://api.github.com/users/castilma/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-02-15T23:13:28Z","updated_at":"2018-02-16T12:34:23Z","closed_at":"2018-02-16T12:34:23Z","author_association":"NONE","body":"I'm not sure if this is the right place for this.\r\n\r\nif you run the attached server and visit localhost:8080/myroute/foo, you get a template error:\r\n```\r\nwill now serve on port  8080\r\nTraceback (most recent call last):\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/tweens.py\", line 12, in _error_handler\r\n    response = request.invoke_exception_view(exc_info)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/view.py\", line 756, in invoke_exception_view\r\n    raise HTTPNotFound\r\npyramid.httpexceptions.HTTPNotFound: The resource could not be found.\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/usr/lib/python3.5/wsgiref/handlers.py\", line 137, in run\r\n    self.result = application(self.environ, self.start_response)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/router.py\", line 270, in __call__\r\n    response = self.execution_policy(environ, self)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/router.py\", line 278, in default_execution_policy\r\n    return request.invoke_exception_view(reraise=True)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/view.py\", line 755, in invoke_exception_view\r\n    reraise_(*exc_info)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/compat.py\", line 148, in reraise\r\n    raise value\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/router.py\", line 276, in default_execution_policy\r\n    return router.invoke_request(request)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/router.py\", line 249, in invoke_request\r\n    response = handle_request(request)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/tweens.py\", line 41, in excview_tween\r\n    response = _error_handler(request, exc)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/tweens.py\", line 16, in _error_handler\r\n    reraise(*exc_info)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/compat.py\", line 148, in reraise\r\n    raise value\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/tweens.py\", line 39, in excview_tween\r\n    response = handler(request)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/router.py\", line 156, in handle_request\r\n    view_name\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/view.py\", line 642, in _call_view\r\n    response = view_callable(context, request)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/viewderivers.py\", line 462, in rendered_view\r\n    request, result, view_inst, context)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/renderers.py\", line 435, in render_view\r\n    return self.render_to_response(response, system, request=request)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/renderers.py\", line 458, in render_to_response\r\n    result = self.render(value, system_values, request=request)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/renderers.py\", line 454, in render\r\n    result = renderer(value, system_values)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid_chameleon/zpt.py\", line 47, in __call__\r\n    result = self.template(**system)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/chameleon/template.py\", line 124, in __call__\r\n    return self.render(**kwargs)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/chameleon/zpt/template.py\", line 297, in render\r\n    return super(PageTemplate, self).render(**_kw)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/chameleon/template.py\", line 191, in render\r\n    raise_with_traceback(exc, tb)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/chameleon/utils.py\", line 75, in raise_with_traceback\r\n    raise exc\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/chameleon/template.py\", line 171, in render\r\n    self._render(stream, econtext, rcontext)\r\n  File \"index_161d98e17b5a3f24d86304929b34b0af.py\", line 200, in render\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/chameleon/zpt/template.py\", line 301, in include\r\n    self._render(*args, **kwargs)\r\n  File \"base_9068126ef4690e8b4198d76bc88e1dfb.py\", line 305, in render\r\n  File \"index_161d98e17b5a3f24d86304929b34b0af.py\", line 136, in __fill_content\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/chameleon/utils.py\", line 406, in __getitem__\r\n    raise NameError(key)\r\nNameError: undecl_name\r\n\r\n - Expression: \"pair[0]\"\r\n - Filename:   /home/pi/code/pathbug/project/templates/base.pt\r\n - Location:   (line 14: col 75)\r\n - Source:     ... oute/${pair[1]}\" tal:content=\"pair[0]\" /></li>\r\n                                                 ^^^^^^^\r\n - Expression: \"load: base.pt\"\r\n - Filename:   /home/pi/code/pathbug/project/templates/index.pt\r\n - Location:   (line 1: col 23)\r\n - Source:     <metal:main use-macro=\"load: base.pt\">\r\n                                      ^^^^^^^^^^^^^\r\n - Arguments:  get_csrf_token: <partial - at 0x75deab70>\r\n               content: some spec content\r\n               request: <Request - at 0x75dd4b90>\r\n               repeat: {...} (0)\r\n               current_spec: sec\r\n               view: <function art_desc at 0x75dd38e8>\r\n               target_language: <NoneType - at 0x3e5788>\r\n               macroname: load: base.pt\r\n               context: <DefaultRootFactory None at 0x75dd4bb0>\r\n               renderer_name: templates/index.pt\r\n               renderer_info: <RendererHelper - at 0x75dd4e50>\r\n               req: <Request - at 0x75dd4b90>\r\n               tuples: <list - at 0x75e47328>\r\n192.168.178.5 - - [16/Feb/2018 00:07:10] \"GET /myroute/sec HTTP/1.1\" 500 59\r\n```\r\nthe problem is the 'undecl_name' in the file `templates/index.pt`. The NameError mentions that, but the following info is misleading. It looks like the error is in base.pt in the expression pair[0]. but that is not the case!\r\n\r\nI think you only need chameleon, waitress and pyramid to run this project.\r\n[bad_err.tar.gz](https://github.com/Pylons/pyramid/files/1729692/bad_err.tar.gz)\r\n","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3231","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3231/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3231/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3231/events","html_url":"https://github.com/Pylons/pyramid/issues/3231","id":297202707,"number":3231,"title":"p.security.remember() raises a TypeError ","user":{"login":"rmeno","id":34033243,"avatar_url":"https://avatars3.githubusercontent.com/u/34033243?v=4","gravatar_id":"","url":"https://api.github.com/users/rmeno","html_url":"https://github.com/rmeno","followers_url":"https://api.github.com/users/rmeno/followers","following_url":"https://api.github.com/users/rmeno/following{/other_user}","gists_url":"https://api.github.com/users/rmeno/gists{/gist_id}","starred_url":"https://api.github.com/users/rmeno/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/rmeno/subscriptions","organizations_url":"https://api.github.com/users/rmeno/orgs","repos_url":"https://api.github.com/users/rmeno/repos","events_url":"https://api.github.com/users/rmeno/events{/privacy}","received_events_url":"https://api.github.com/users/rmeno/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-02-14T18:41:58Z","updated_at":"2018-02-26T01:48:51Z","closed_at":"2018-02-26T01:48:51Z","author_association":"NONE","body":"Ref: #1530 \r\n\r\nHello,\r\nI get the same error as the one referenced above if I pass a str or int to remember(). Code and full traceback below. Ideas/suggestions? Thanks in advance.\r\n\r\n```\r\n    @view_config(\r\n        route_name='login',\r\n        renderer='myproj:templates/auth/login.jinja2',\r\n    )\r\n    def login(self):\r\n        message = ''\r\n        email = ''\r\n        self.log.info(self.request.method)\r\n        if self.request.method == 'POST' and 'form.submitted' in self.request.POST:\r\n            email = self.request.POST['email']\r\n            password = self.request.POST['password']\r\n            user = self.request.dbsession.query(User).filter_by(email=email).first()\r\n            self.log.info('login_POST.user: {0} : {1}'.format(user, type(user)))\r\n            if user is not None and user.check_password(password):\r\n                user_id = user.user_id\r\n                self.log.info(\r\n                    'login_POST.userid: {0}, type: {1}'.format(user_id, type(user_id)))\r\n                next_url = self.request.route_url('home')\r\n                self.log.info('login_POST.next_url: {0}'.format(next_url,))\r\n                headers = remember(self.request, user.user_id)\r\n                return HTTPFound(location=next_url, headers=headers)\r\n            else:\r\n                message = 'Failed login'\r\n        \r\n\r\n        return dict(\r\n            message=message,\r\n            url=self.request.route_url('login'),\r\n            email=email,\r\n        )\r\n\r\n```\r\n\r\n\r\n```\r\n2018-02-14 13:25:22,547 INFO  [views.auth:46][waitress] login_POST.userid: 5, type: <class 'int'>\r\n2018-02-14 13:25:22,547 INFO  [views.auth:48][waitress] login_POST.next_url: http://localhost:6543/\r\n2018-02-14 13:25:22,548 INFO  [sqlalchemy.engine.base.Engine:702][waitress] ROLLBACK\r\n2018-02-14 13:25:22,550 ERROR [pyramid_debugtoolbar:267][waitress] Uncaught Exception at http://localhost:6543/login\r\ntraceback url: http://localhost:6543/_debug_toolbar/313430373134353837373135343536/exception\r\nTraceback (most recent call last):\r\n  File \"/lib/python3.5/site-packages/pyramid/tweens.py\", line 12, in _error_handler\r\n    response = request.invoke_exception_view(exc_info)\r\n  File \"/lib/python3.5/site-packages/pyramid/view.py\", line 756, in invoke_exception_view\r\n    raise HTTPNotFound\r\npyramid.httpexceptions.HTTPNotFound: The resource could not be found.\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/lib/python3.5/site-packages/pyramid_debugtoolbar/toolbar.py\", line 247, in toolbar_tween\r\n    response = _handler(request)\r\n  File \"/lib/python3.5/site-packages/pyramid_debugtoolbar/panels/performance.py\", line 58, in resource_timer_handler\r\n    result = handler(request)\r\n  File \"/lib/python3.5/site-packages/pyramid_tm/__init__.py\", line 171, in tm_tween\r\n    reraise(*exc_info)\r\n  File \"lib/python3.5/site-packages/pyramid_tm/compat.py\", line 36, in reraise\r\n    raise value\r\n  File \"lib/python3.5/site-packages/pyramid_tm/__init__.py\", line 136, in tm_tween\r\n    response = handler(request)\r\n  File \"/lib/python3.5/site-packages/pyramid/tweens.py\", line 41, in excview_tween\r\n    response = _error_handler(request, exc)\r\n  File \"/lib/python3.5/site-packages/pyramid/tweens.py\", line 16, in _error_handler\r\n    reraise(*exc_info)\r\n  File \"/lib/python3.5/site-packages/pyramid/compat.py\", line 148, in reraise\r\n    raise value\r\n  File \"/lib/python3.5/site-packages/pyramid/tweens.py\", line 39, in excview_tween\r\n    response = handler(request)\r\n  File \"/lib/python3.5/site-packages/pyramid/router.py\", line 156, in handle_request\r\n    view_name\r\n  File \"/lib/python3.5/site-packages/pyramid/view.py\", line 642, in _call_view\r\n    response = view_callable(context, request)\r\n  File \"/lib/python3.5/site-packages/pyramid/viewderivers.py\", line 439, in rendered_view\r\n    result = view(context, request)\r\n  File \"/lib/python3.5/site-packages/pyramid/viewderivers.py\", line 124, in _class_requestonly_view\r\n    response = getattr(inst, attr)()\r\n  File \"/views/auth.py\", line 49, in login\r\n    headers = remember(self.request, user.user_id)\r\n  File \"/lib/python3.5/site-packages/pyramid/security.py\", line 167, in remember\r\n    return policy.remember(request, userid, **kw)\r\n  File \"/lib/python3.5/site-packages/pyramid/authentication.py\", line 621, in remember\r\n    return self.cookie.remember(request, userid, **kw)\r\n  File \"/lib/python3.5/site-packages/pyramid/authentication.py\", line 992, in remember\r\n    cookie_value = ticket.cookie_value()\r\n  File \"/lib/python3.5/site-packages/pyramid/authentication.py\", line 676, in cookie_value\r\n    v = '%s%08x%s!' % (self.digest(), int(self.time),\r\n  File \"lib/python3.5/site-packages/pyramid/authentication.py\", line 673, in digest\r\n    self.user_data, self.hashalg)\r\n  File \"/lib/python3.5/site-packages/pyramid/authentication.py\", line 752, in calculate_digest\r\n    tokens + b'\\0' + user_data)\r\nTypeError: can't concat bytes to list\r\n```","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3230","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3230/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3230/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3230/events","html_url":"https://github.com/Pylons/pyramid/issues/3230","id":296376092,"number":3230,"title":"zodbpickle build error when creating a new project","user":{"login":"TWry","id":2758765,"avatar_url":"https://avatars2.githubusercontent.com/u/2758765?v=4","gravatar_id":"","url":"https://api.github.com/users/TWry","html_url":"https://github.com/TWry","followers_url":"https://api.github.com/users/TWry/followers","following_url":"https://api.github.com/users/TWry/following{/other_user}","gists_url":"https://api.github.com/users/TWry/gists{/gist_id}","starred_url":"https://api.github.com/users/TWry/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/TWry/subscriptions","organizations_url":"https://api.github.com/users/TWry/orgs","repos_url":"https://api.github.com/users/TWry/repos","events_url":"https://api.github.com/users/TWry/events{/privacy}","received_events_url":"https://api.github.com/users/TWry/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-02-12T13:34:08Z","updated_at":"2018-02-12T21:50:21Z","closed_at":"2018-02-12T17:04:49Z","author_association":"NONE","body":"I already posted an issue for ZODB but I'm not sure if this gets attention. Feel free to close or delete this one if it is inappropriate.\r\n\r\nWhen installing pyramid, I'm getting the following error: \r\n\r\n```\r\nBuilding wheels for collected packages: zodbpickle\r\n  Running setup.py bdist_wheel for zodbpickle ... error\r\n  Complete output from command /Users/twry/development/t1/env/bin/python -u -c \"import setuptools, tokenize;__file__='/private/var/folders/1z/g4q5gcbn4q39hktz7y24n7wr0000gp/T/pip-build-dX1rA4/zodbpickle/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" bdist_wheel -d /var/folders/1z/g4q5gcbn4q39hktz7y24n7wr0000gp/T/tmpo_RNB8pip-wheel- --python-tag cp27:\r\n  running bdist_wheel\r\n  running build\r\n  running build_py\r\n  creating build\r\n  creating build/lib.macosx-10.13-intel-2.7\r\n  creating build/lib.macosx-10.13-intel-2.7/zodbpickle\r\n  copying src/zodbpickle/slowpickle.py -> build/lib.macosx-10.13-intel-2.7/zodbpickle\r\n  copying src/zodbpickle/fastpickle.py -> build/lib.macosx-10.13-intel-2.7/zodbpickle\r\n  copying src/zodbpickle/pickle_2.py -> build/lib.macosx-10.13-intel-2.7/zodbpickle\r\n  copying src/zodbpickle/__init__.py -> build/lib.macosx-10.13-intel-2.7/zodbpickle\r\n  copying src/zodbpickle/pickle_3.py -> build/lib.macosx-10.13-intel-2.7/zodbpickle\r\n  copying src/zodbpickle/pickle.py -> build/lib.macosx-10.13-intel-2.7/zodbpickle\r\n  copying src/zodbpickle/pickletools_2.py -> build/lib.macosx-10.13-intel-2.7/zodbpickle\r\n  copying src/zodbpickle/pickletools_3.py -> build/lib.macosx-10.13-intel-2.7/zodbpickle\r\n  creating build/lib.macosx-10.13-intel-2.7/zodbpickle/tests\r\n  copying src/zodbpickle/tests/pickletester_2.py -> build/lib.macosx-10.13-intel-2.7/zodbpickle/tests\r\n  copying src/zodbpickle/tests/test_pickle_2.py -> build/lib.macosx-10.13-intel-2.7/zodbpickle/tests\r\n  copying src/zodbpickle/tests/test_pickle_3.py -> build/lib.macosx-10.13-intel-2.7/zodbpickle/tests\r\n  copying src/zodbpickle/tests/pickletester_3.py -> build/lib.macosx-10.13-intel-2.7/zodbpickle/tests\r\n  copying src/zodbpickle/tests/test_pickle.py -> build/lib.macosx-10.13-intel-2.7/zodbpickle/tests\r\n  copying src/zodbpickle/tests/__init__.py -> build/lib.macosx-10.13-intel-2.7/zodbpickle/tests\r\n  running egg_info\r\n  writing requirements to src/zodbpickle.egg-info/requires.txt\r\n  writing src/zodbpickle.egg-info/PKG-INFO\r\n  writing top-level names to src/zodbpickle.egg-info/top_level.txt\r\n  writing dependency_links to src/zodbpickle.egg-info/dependency_links.txt\r\n  reading manifest file 'src/zodbpickle.egg-info/SOURCES.txt'\r\n  reading manifest template 'MANIFEST.in'\r\n  warning: no previously-included files matching '*.dll' found anywhere in distribution\r\n  warning: no previously-included files matching '*.pyc' found anywhere in distribution\r\n  warning: no previously-included files matching '*.pyo' found anywhere in distribution\r\n  warning: no previously-included files matching '*.so' found anywhere in distribution\r\n  writing manifest file 'src/zodbpickle.egg-info/SOURCES.txt'\r\n  copying src/zodbpickle/_pickle_27.c -> build/lib.macosx-10.13-intel-2.7/zodbpickle\r\n  copying src/zodbpickle/_pickle_33.c -> build/lib.macosx-10.13-intel-2.7/zodbpickle\r\n  running build_ext\r\n  building 'zodbpickle._pickle' extension\r\n  creating build/temp.macosx-10.13-intel-2.7\r\n  creating build/temp.macosx-10.13-intel-2.7/src\r\n  creating build/temp.macosx-10.13-intel-2.7/src/zodbpickle\r\n  cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/zodbpickle/_pickle_27.c -o build/temp.macosx-10.13-intel-2.7/src/zodbpickle/_pickle_27.o\r\n  In file included from src/zodbpickle/_pickle_27.c:1:\r\n  In file included from /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/Python.h:42:\r\n  In file included from /usr/include/stdlib.h:65:\r\n  In file included from /usr/include/sys/wait.h:110:\r\n  In file included from /usr/include/sys/resource.h:72:\r\n  In file included from /usr/local/include/stdint.h:59:\r\n[this line repeating many times]\r\n  In file included from /usr/local/include/stdint.h:59:\r\n  /usr/local/include/stdint.h:2:10: error: #include nested too deeply\r\n  #include <stddef.h>\r\n           ^\r\n  /usr/local/include/stdint.h:59:11: error: #include nested too deeply\r\n  # include <stdint.h>\r\n            ^\r\n  /usr/local/include/stdint.h:72:11: error: #include nested too deeply\r\n  # include <sys/types.h>\r\n            ^\r\n  /usr/local/include/stdint.h:76:10: error: #include nested too deeply\r\n  #include <limits.h>\r\n           ^\r\n  /usr/local/include/stdint.h:82:11: error: #include nested too deeply\r\n  # include <inttypes.h>\r\n            ^\r\n  In file included from src/zodbpickle/_pickle_27.c:1:\r\n  In file included from /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/Python.h:42:\r\n  In file included from /usr/include/stdlib.h:65:\r\n  In file included from /usr/include/sys/wait.h:110:\r\n  /usr/include/sys/resource.h:197:2: error: unknown type name 'uint64_t'\r\n          uint64_t ri_user_time;\r\n          ^\r\n  /usr/include/sys/resource.h:198:2: error: unknown type name 'uint64_t'\r\n          uint64_t ri_system_time;\r\n          ^\r\n  /usr/include/sys/resource.h:199:2: error: unknown type name 'uint64_t'\r\n          uint64_t ri_pkg_idle_wkups;\r\n          ^\r\n  /usr/include/sys/resource.h:200:2: error: unknown type name 'uint64_t'\r\n          uint64_t ri_interrupt_wkups;\r\n          ^\r\n  /usr/include/sys/resource.h:201:2: error: unknown type name 'uint64_t'\r\n          uint64_t ri_pageins;\r\n          ^\r\n  /usr/include/sys/resource.h:202:2: error: unknown type name 'uint64_t'\r\n          uint64_t ri_wired_size;\r\n          ^\r\n  /usr/include/sys/resource.h:203:2: error: unknown type name 'uint64_t'\r\n          uint64_t ri_resident_size;\r\n          ^\r\n  /usr/include/sys/resource.h:204:2: error: unknown type name 'uint64_t'\r\n          uint64_t ri_phys_footprint;\r\n          ^\r\n  /usr/include/sys/resource.h:205:2: error: unknown type name 'uint64_t'\r\n          uint64_t ri_proc_start_abstime;\r\n          ^\r\n  /usr/include/sys/resource.h:206:2: error: unknown type name 'uint64_t'\r\n          uint64_t ri_proc_exit_abstime;\r\n          ^\r\n  /usr/include/sys/resource.h:211:2: error: unknown type name 'uint64_t'\r\n          uint64_t ri_user_time;\r\n          ^\r\n  /usr/include/sys/resource.h:212:2: error: unknown type name 'uint64_t'\r\n          uint64_t ri_system_time;\r\n          ^\r\n  /usr/include/sys/resource.h:213:2: error: unknown type name 'uint64_t'\r\n          uint64_t ri_pkg_idle_wkups;\r\n          ^\r\n  /usr/include/sys/resource.h:214:2: error: unknown type name 'uint64_t'\r\n          uint64_t ri_interrupt_wkups;\r\n          ^\r\n  fatal error: too many errors emitted, stopping now [-ferror-limit=]\r\n  20 errors generated.\r\n  error: command 'cc' failed with exit status 1\r\n```\r\n\r\nVersions:\r\n- OS: MacOS 10.3.3\r\n- Python Versions:\r\n> Python 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin\r\n> Python 3.6.4 (default, Jan  6 2018, 11:51:59) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin\r\n- Compiler: \r\n> Apple LLVM version 9.0.0 (clang-900.0.39.2)\r\n> Target: x86_64-apple-darwin17.4.0\r\n> Thread model: posix\r\n> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin\r\n\r\nThis does happen on Python 2.7 and 3.6, system and virtualenv. \r\n\r\nAny pointers, please?","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3228","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3228/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3228/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3228/events","html_url":"https://github.com/Pylons/pyramid/issues/3228","id":294732201,"number":3228,"title":"Wish: issue a warning when some Traversal path is matched against a static view","user":{"login":"silenius","id":1225348,"avatar_url":"https://avatars2.githubusercontent.com/u/1225348?v=4","gravatar_id":"","url":"https://api.github.com/users/silenius","html_url":"https://github.com/silenius","followers_url":"https://api.github.com/users/silenius/followers","following_url":"https://api.github.com/users/silenius/following{/other_user}","gists_url":"https://api.github.com/users/silenius/gists{/gist_id}","starred_url":"https://api.github.com/users/silenius/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/silenius/subscriptions","organizations_url":"https://api.github.com/users/silenius/orgs","repos_url":"https://api.github.com/users/silenius/repos","events_url":"https://api.github.com/users/silenius/events{/privacy}","received_events_url":"https://api.github.com/users/silenius/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-02-06T11:54:00Z","updated_at":"2018-02-06T16:40:03Z","closed_at":"2018-02-06T16:40:03Z","author_association":"CONTRIBUTOR","body":"While extending a Pyramid app I accidentally used the same name for a Traversal path and a static view (which gave strange results), as in the following code:\r\n\r\n```python\r\n~/code/projects/amnesiabbpf/ more amnesiabbpf/__init__.py \r\n# -*- coding: utf-8 -*-\r\n\r\nfrom pyramid.config import Configurator\r\nfrom amnesia.resources import Resource\r\nfrom amnesia.resources import get_root\r\nfrom amnesiabbpf.phc import PHCResource\r\n\r\nclass BBPFRoot(Resource):\r\n\r\n    __name__ = ''\r\n    __parent__ = None\r\n\r\n    def __getitem__(self, path):\r\n        if path == 'phc':\r\n            return PHCResource(self.request, self)\r\n        return get_root(self.request)\r\n\r\ndef bbpf_root(request):\r\n    return BBPFRoot(request)\r\n\r\ndef main(global_config, **settings):\r\n    config = Configurator(settings=settings, root_factory=bbpf_root)\r\n    config.include('amnesia')\r\n    config.include('amnesiabbpf.widgets')\r\n    config.include('amnesiabbpf.views')\r\n    config.include('amnesiabbpf.phc')\r\n    config.add_static_view(name='static', path='amnesiabbpf:static/')\r\n    config.override_asset(\r\n        to_override='amnesia:templates/',\r\n        override_with='amnesiabbpf:templates/'\r\n    )\r\n\r\n    return config.make_wsgi_app()\r\n```\r\n\r\n```python\r\n~/code/projects/amnesiabbpf/amnesiabbpf/phc/ more __init__.py \r\n# -*- coding: utf-8 -*-\r\n\r\nfrom .resources import PHCResource\r\n\r\ndef includeme(config):\r\n    config.include('.views')\r\n    config.add_static_view(name='phc', path='amnesiabbpf:phc/templates')\r\n```\r\n\r\n```python\r\n~/code/projects/amnesiabbpf/amnesiabbpf/phc/ more resources.py \r\n# -*- coding: utf-8 -*-\r\n\r\nfrom amnesia.resources import Resource\r\n\r\nclass PHCResource(Resource):\r\n\r\n    __name__ = 'phc'\r\n\r\n    def __init__(self, request, parent=None):\r\n        super().__init__(request)\r\n        self.parent = parent\r\n    \r\n    @property\r\n    def __parent__(self):\r\n        return self.parent if self.parent else self.request.root\r\n```\r\nIn such case, the context was:\r\n * /phc => PHCResource\r\n * /phc/ => BBPFRoot\r\n * /phc/somepath => BBPFRoot\r\n\r\nIt would maybe be good if Pyramid could emit a warning in such case 😃 ","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3227","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3227/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3227/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3227/events","html_url":"https://github.com/Pylons/pyramid/issues/3227","id":293979134,"number":3227,"title":"Traversal returns factory when match name is single period","user":{"login":"di","id":294415,"avatar_url":"https://avatars1.githubusercontent.com/u/294415?v=4","gravatar_id":"","url":"https://api.github.com/users/di","html_url":"https://github.com/di","followers_url":"https://api.github.com/users/di/followers","following_url":"https://api.github.com/users/di/following{/other_user}","gists_url":"https://api.github.com/users/di/gists{/gist_id}","starred_url":"https://api.github.com/users/di/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/di/subscriptions","organizations_url":"https://api.github.com/users/di/orgs","repos_url":"https://api.github.com/users/di/repos","events_url":"https://api.github.com/users/di/events{/privacy}","received_events_url":"https://api.github.com/users/di/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-02-02T18:21:38Z","updated_at":"2018-02-02T23:17:06Z","closed_at":"2018-02-02T23:17:06Z","author_association":"CONTRIBUTOR","body":"With `pyramid==1.9.1` and the following example:\r\n\r\n```python\r\nfrom waitress import serve\r\nfrom pyramid.config import Configurator\r\nfrom pyramid.response import Response\r\n\r\nclass Factory:\r\n    def __init__(self, request):\r\n        pass\r\n\r\n    def __getitem__(self, thing):\r\n        return thing\r\n\r\nwith Configurator() as config:\r\n    config.add_route(\r\n        'traverse',\r\n        '/{thing}/',\r\n        traverse=\"/{thing}\",\r\n        factory=Factory\r\n    )\r\n    config.add_view(\r\n        lambda thing, request: Response(str(thing)),\r\n        route_name='traverse'\r\n    )\r\n    app = config.make_wsgi_app()\r\n\r\nserve(app, host='0.0.0.0', port=6543)\r\n```\r\n\r\nAnd 
8000
the following requests:\r\n```python\r\n>>> import requests\r\n>>> requests.get('http://localhost:6543/foo/').text\r\n'foo'\r\n>>> requests.get('http://localhost:6543/./').text\r\n'<__main__.Factory object at 0x1088c81d0>'\r\n```\r\n\r\nI think I would have expected the second request to 404 because the path is equivalent to `http://localhost:6543/`, but perhaps I'm missing something here?\r\n\r\nIf this is truly a bug I'd be happy to work on it.","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3219","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3219/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3219/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3219/events","html_url":"https://github.com/Pylons/pyramid/issues/3219","id":288711634,"number":3219,"title":"NoTransaction error when using bootstrap in script","user":{"login":"viraptor","id":188063,"avatar_url":"https://avatars1.githubusercontent.com/u/188063?v=4","gravatar_id":"","url":"https://api.github.com/users/viraptor","html_url":"https://github.com/viraptor","followers_url":"https://api.github.com/users/viraptor/followers","following_url":"https://api.github.com/users/viraptor/following{/other_user}","gists_url":"https://api.github.com/users/viraptor/gists{/gist_id}","starred_url":"https://api.github.com/users/viraptor/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/viraptor/subscriptions","organizations_url":"https://api.github.com/users/viraptor/orgs","repos_url":"https://api.github.com/users/viraptor/repos","events_url":"https://api.github.com/users/viraptor/events{/privacy}","received_events_url":"https://api.github.com/users/viraptor/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-01-15T20:44:36Z","updated_at":"2018-01-15T22:31:13Z","closed_at":"2018-01-15T22:30:38Z","author_association":"NONE","body":"I'm trying to create a console script using bootstrap as explained in https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/commandline.html#writing-a-script\r\n\r\nI'm running into an issue with access to the database though. The basic expected use like:\r\n```\r\nwith bootstrap(sys.argv[1]) as env:\r\n    dbsession = env['request'].dbsession\r\n    with dbsession.begin_nested() as transaction:\r\n        res = dbsession.execute('''SELECT ...''')\r\n```\r\nThrows a `transaction.interfaces.NoTransaction`. I should probably do something better here, but the documentation doesn't really help me :( Could you add something about the db initialisation in this use case?","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3214","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3214/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3214/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3214/events","html_url":"https://github.com/Pylons/pyramid/issues/3214","id":287928305,"number":3214,"title":"Pyramid documentation links broken","user":{"login":"chrismcmacken","id":445683,"avatar_url":"https://avatars2.githubusercontent.com/u/445683?v=4","gravatar_id":"","url":"https://api.github.com/users/chrismcmacken","html_url":"https://github.com/chrismcmacken","followers_url":"https://api.github.com/users/chrismcmacken/followers","following_url":"https://api.github.com/users/chrismcmacken/following{/other_user}","gists_url":"https://api.github.com/users/chrismcmacken/gists{/gist_id}","starred_url":"https://api.github.com/users/chrismcmacken/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/chrismcmacken/subscriptions","organizations_url":"https://api.github.com/users/chrismcmacken/orgs","repos_url":"https://api.github.com/users/chrismcmacken/repos","events_url":"https://api.github.com/users/chrismcmacken/events{/privacy}","received_events_url":"https://api.github.com/users/chrismcmacken/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-01-11T21:21:52Z","updated_at":"2018-01-11T21:44:29Z","closed_at":"2018-01-11T21:44:29Z","author_association":"NONE","body":"When looking through documentation many of the links seem to return broken pages. For example, on this page https://docs.pylonsproject.org/projects/pyramid/en/latest/ if you click on the Installing Pyramid documentation it links to https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/install.html#installing-chapter. Which doesn't load, it returns an empty page. ","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3211","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3211/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3211/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3211/events","html_url":"https://github.com/Pylons/pyramid/issues/3211","id":282692298,"number":3211,"title":"Security - Session - Support SameSite","user":{"login":"AvnerCohen","id":1297254,"avatar_url":"https://avatars2.githubusercontent.com/u/1297254?v=4","gravatar_id":"","url":"https://api.github.com/users/AvnerCohen","html_url":"https://github.com/AvnerCohen","followers_url":"https://api.github.com/users/AvnerCohen/followers","following_url":"https://api.github.com/users/AvnerCohen/following{/other_user}","gists_url":"https://api.github.com/users/AvnerCohen/gists{/gist_id}","starred_url":"https://api.github.com/users/AvnerCohen/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AvnerCohen/subscriptions","organizations_url":"https://api.github.com/users/AvnerCohen/orgs","repos_url":"https://api.github.com/users/AvnerCohen/repos","events_url":"https://api.github.com/users/AvnerCohen/events{/privacy}","received_events_url":"https://api.github.com/users/AvnerCohen/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2017-12-17T13:04:21Z","updated_at":"2018-02-26T02:24:27Z","closed_at":"2018-02-26T02:24:27Z","author_association":"NONE","body":"For a while now - There is a support SameSite cookie attribute - This should help reduce CSRF concerns:\r\nhttps://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie\r\nSee SameSite support:\r\nhttps://caniuse.com/#search=SameSite\r\n\r\nAre there plans to support that in the session module?\r\n","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3207","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3207/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3207/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3207/events","html_url":"https://github.com/Pylons/pyramid/issues/3207","id":278034593,"number":3207,"title":"NewResponse after exception: event.request.response is not event.response","user":{"login":"tjwudi","id":5257816,"avatar_url":"https://avatars0.githubusercontent.com/u/5257816?v=4","gravatar_id":"","url":"https://api.github.com/users/tjwudi","html_url":"https://github.com/tjwudi","followers_url":"https://api.github.com/users/tjwudi/followers","following_url":"https://api.github.com/users/tjwudi/following{/other_user}","gists_url":"https://api.github.com/users/tjwudi/gists{/gist_id}","starred_url":"https://api.github.com/users/tjwudi/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/tjwudi/subscriptions","organizations_url":"https://api.github.com/users/tjwudi/orgs","repos_url":"https://api.github.com/users/tjwudi/repos","events_url":"https://api.github.com/users/tjwudi/events{/privacy}","received_events_url":"https://api.github.com/users/tjwudi/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":5,"created_at":"2017-11-30T08:24:19Z","updated_at":"2018-02-21T07:10:36Z","closed_at":"2018-02-21T07:10:36Z","author_association":"CONTRIBUTOR","body":"When NewResponse event is fired, `event.request.response` is not `event.response`.\r\n\r\nSimple test code\r\n\r\n```py\r\nfrom wsgiref.simple_server import make_server\r\nfrom pyramid.config import Configurator\r\nimport pyramid.httpexceptions as exc\r\nfrom pyramid.events import NewResponse\r\n\r\ndef hello_404(request):\r\n    raise exc.HTTPNotFound()\r\n    return {}\r\n\r\ndef handle_event(event):\r\n    print(event.response is event.request.response)\r\n    print(event.response.status_code == event.request.response.status_code)\r\n\r\nif __name__ == '__main__':\r\n    config = Configurator()\r\n    config.add_route('404', '/404')\r\n    config.add_view(hello_404, renderer='json', route_name='404')\r\n    config.add_subscriber(handle_event, NewResponse)\r\n    app = config.make_wsgi_app()\r\n    server = make_server('0.0.0.0', 6543, app)\r\n    server.serve_forever()\r\n```\r\n\r\nBoth of the expressions in `print` statements yield `False`. **event.response turns out the be the correct response object because it has the correct response code.**\r\n\r\n```bash\r\n[pyramid-playground] $ python server.py \r\nFalse\r\nFalse\r\n```\r\n\r\nSeems to be related to #1633. I'm using pyramid 1.9.","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3206","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3206/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3206/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3206/events","html_url":"https://github.com/Pylons/pyramid/issues/3206","id":277813600,"number":3206,"title":"Q:  Why does the pyramid.request object have no `content_encoding` attribute ?","user":{"login":"jakubczaplicki","id":147901,"avatar_url":"https://avatars3.githubusercontent.com/u/147901?v=4","gravatar_id":"","url":"https://api.github.com/users/jakubczaplicki","html_url":"https://github.com/jakubczaplicki","followers_url":"https://api.github.com/users/jakubczaplicki/followers","following_url":"https://api.github.com/users/jakubczaplicki/following{/other_user}","gists_url":"https://api.github.com/users/jakubczaplicki/gists{/gist_id}","starred_url":"https://api.github.com/users/jakubczaplicki/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jakubczaplicki/subscriptions","organizations_url":"https://api.github.com/users/jakubczaplicki/orgs","repos_url":"https://api.github.com/users/jakubczaplicki/repos","events_url":"https://api.github.com/users/jakubczaplicki/events{/privacy}","received_events_url":"https://api.github.com/users/jakubczaplicki/received_events","type":"User","site_admin":false},"labels":[{"id":235821,"url":"https://api.github.com/repos/Pylons/pyramid/labels/question","name":"question","color":"ededed","default":true}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":13,"created_at":"2017-11-29T16:12:28Z","updated_at":"2017-11-30T19:06:44Z","closed_at":"2017-11-30T19:06:43Z","author_association":"NONE","body":"`Content-Encoding` as in https://tools.ietf.org/html/rfc2616#section-14.11","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3202","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3202/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3202/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3202/events","html_url":"https://github.com/Pylons/pyramid/issues/3202","id":274320632,"number":3202,"title":"add_request_method only accepts property descriptor that subclasses property","user":{"login":"tjwudi","id":5257816,"avatar_url":"https://avatars0.githubusercontent.com/u/5257816?v=4","gravatar_id":"","url":"https://api.github.com/users/tjwudi","html_url":"https://github.com/tjwudi","followers_url":"https://api.github.com/users/tjwudi/followers","following_url":"https://api.github.com/users/tjwudi/following{/other_user}","gists_url":"https://api.github.com/users/tjwudi/gists{/gist_id}","starred_url":"https://api.github.com/users/tjwudi/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/tjwudi/subscriptions","organizations_url":"https://api.github.com/users/tjwudi/orgs","repos_url":"https://api.github.com/users/tjwudi/repos","events_url":"https://api.github.com/users/tjwudi/events{/privacy}","received_events_url":"https://api.github.com/users/tjwudi/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2017-11-15T22:03:43Z","updated_at":"2017-11-17T00:21:39Z","closed_at":"2017-11-16T22:56:52Z","author_association":"CONTRIBUTOR","body":"https://github.com/Pylons/pyramid/blob/cc6a6ed60260b0391aa38f372b26311d58edf0d6/pyramid/util.py#L70\r\n\r\nLooks like we check the type of a property descriptor by `isinstance(callable, property)`. This is not true for property descriptors subclasses from `object` which is pretty common. Maybe we should document this behavior [here](https://docs.pylonsproject.org/projects/pyramid/en/latest/api/config.html#pyramid.config.Configurator.add_request_method).\r\n","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3191","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3191/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3191/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3191/events","html_url":"https://github.com/Pylons/pyramid/issues/3191","id":268151160,"number":3191,"title":"upgrade 1.8 -> 1.9 won't start.","user":{"login":"kgk","id":1790880,"avatar_url":"https://avatars3.githubusercontent.com/u/1790880?v=4","gravatar_id":"","url":"https://api.github.com/users/kgk","html_url":"https://github.com/kgk","followers_url":"https://api.github.com/users/kgk/followers","following_url":"https://api.github.com/users/kgk/following{/other_user}","gists_url":"https://api.github.com/users/kgk/gists{/gist_id}","starred_url":"https://api.github.com/users/kgk/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/kgk/subscriptions","organizations_url":"https://api.github.com/users/kgk/orgs","repos_url":"https://api.github.com/users/kgk/repos","events_url":"https://api.github.com/users/kgk/events{/privacy}","received_events_url":"https://api.github.com/users/kgk/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2017-10-24T19:08:58Z","updated_at":"2017-10-24T23:25:02Z","closed_at":"2017-10-24T21:21:30Z","author_association":"NONE","body":"We tend to use .cfg instead of .ini which used to work.  Is this broken on purpose ?\r\nRenaming cfg -> ini doesn't seem to have an effect.\r\n\r\nThanks,\r\nKris \r\n\r\n\r\n```\r\npserve -v config/h1_pserve.cfg \r\nTraceback (most recent call last):\r\n  File \"/home/kgk/Envs/bq06new/bin/pserve\", line 11, in <module>\r\n    sys.exit(main())\r\n  File \"/home/kgk/Envs/bq06new/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py\", line 32, in main\r\n    return command.run()\r\n  File \"/home/kgk/Envs/bq06new/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py\", line 167, in run\r\n    loader = self._get_config_loader(config_uri)\r\n  File \"/home/kgk/Envs/bq06new/local/lib/python2.7/site-packages/pyramid/scripts/common.py\", line 23, in get_config_loader\r\n    return plaster.get_loader(config_uri, protocols=['wsgi'])\r\n  File \"/home/kgk/Envs/bq06new/local/lib/python2.7/site-packages/plaster/loaders.py\", line 109, in get_loader\r\n    raise LoaderNotFound(requested_scheme, protocols=protocols)\r\nplaster.exceptions.LoaderNotFound: Could not find a matching loader for the scheme \"file+cfg\", protocol \"wsgi\".\r\n\r\n```","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3176","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3176/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3176/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3176/events","html_url":"https://github.com/Pylons/pyramid/issues/3176","id":262559920,"number":3176,"title":"trypyramid.com typo","user":{"login":"gomezhyuuga","id":1633839,"avatar_url":"https://avatars2.githubusercontent.com/u/1633839?v=4","gravatar_id":"","url":"https://api.github.com/users/gomezhyuuga","html_url":"https://github.com/gomezhyuuga","followers_url":"https://api.github.com/users/gomezhyuuga/followers","following_url":"https://api.github.com/users/gomezhyuuga/following{/other_user}","gists_url":"https://api.github.com/users/gomezhyuuga/gists{/gist_id}","starred_url":"https://api.github.com/users/gomezhyuuga/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/gomezhyuuga/subscriptions","organizations_url":"https://api.github.com/users/gomezhyuuga/orgs","repos_url":"https://api.github.com/users/gomezhyuuga/repos","events_url":"https://api.github.com/users/gomezhyuuga/events{/privacy}","received_events_url":"https://api.github.com/users/gomezhyuuga/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2017-10-03T19:41:09Z","updated_at":"2017-10-03T20:02:35Z","closed_at":"2017-10-03T20:02:35Z","author_association":"NONE","body":"In the website https://trypyramid.com/, at the part of *Pyramid Features*:\r\n> [...] curl or a browser to request http://0.0.0.0:8080\r\n\r\nShouldn't the port be `6543` ?","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3170","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3170/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3170/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3170/events","html_url":"https://github.com/Pylons/pyramid/issues/3170","id":258867800,"number":3170,"title":"CSRF Setup with beaker","user":{"login":"AvnerCohen","id":1297254,"avatar_url":"https://avatars2.githubusercontent.com/u/1297254?v=4","gravatar_id":"","url":"https://api.github.com/users/AvnerCohen","html_url":"https://github.com/AvnerCohen","followers_url":"https://api.github.com/users/AvnerCohen/followers","following_url":"https://api.github.com/users/AvnerCohen/following{/other_user}","gists_url":"https://api.github.com/users/AvnerCohen/gists{/gist_id}","starred_url":"https://api.github.com/users/AvnerCohen/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AvnerCohen/subscriptions","organizations_url":"https://api.github.com/users/AvnerCohen/orgs","repos_url":"https://api.github.com/users/AvnerCohen/repos","events_url":"https://api.github.com/users/AvnerCohen/events{/privacy}","received_events_url":"https://api.github.com/users/AvnerCohen/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":6,"created_at":"2017-09-19T15:39:04Z","updated_at":"2017-09-20T10:07:07Z","closed_at":"2017-09-19T16:30:02Z","author_association":"NONE","body":"Thanks for all the work Pyramid !\r\n\r\nI'm really confused about the setup to fully support CSRF in an app.\r\nFrom XHR to form hidden fields, session type cookie and beaker.\r\nI tried to find any reference I could find, but so far failed.\r\n\r\nI tried to follow the basic setup as per:\r\nhttps://docs.pylonsproject.org/projects/pyramid/en/latest/narr/security.html#checking-csrf-tokens-automatically\r\nBasically:\r\n```\r\n    config.set_default_csrf_options(require_csrf=True)\r\n```\r\nand than, in my mako template:\r\n```\r\n          <input type=\"hidden\" name=\"csrf_token\" value=\"${get_csrf_token()}\">\r\n```\r\nHowever, regardless of the setup I tested, I couldn't get this to work.\r\n\r\nI suspect there is some conflict when I setup:\r\n```\r\n    config.set_csrf_storage_policy(SessionCSRFStoragePolicy())    \r\n    config.include(\"pyramid_beaker\")\r\n```\r\nBecause I see crft token being setup here:\r\nhttps://github.com/Pylons/pyramid_beaker/blob/master/pyramid_beaker/__init__.py#L90\r\nBut also here:\r\nhttps://github.com/Pylons/pyramid/blob/master/pyramid/csrf.py#L80\r\n\r\nWhen I print out the tokens on each post, I see that when I try to manually run:\r\n```\r\nfrom pyramid.csrf import check_csrf_token\r\n\r\nprint \"GOT: %s\" % request.params.get('csrf_token')\r\nprint \"FROM SESSION: %s\" % request.session.get_csrf_token()\r\nprint \"Inside check %s\" % check_csrf_token(request)\r\n````\r\n\r\nThe form sends the token from SessionCSRFStoragePolicy, but get_csrf_token returns the one from pyramid_beaker (end as a result check_csrf_token fails with BadCSRFToken.\r\n\r\n\r\nAny thoughts?\r\nAny additional info I should be providing?\r\n\r\n\r\n\r\n\r\n\r\n\r\n","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3169","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3169/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3169/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3169/events","html_url":"https://github.com/Pylons/pyramid/issues/3169","id":258528965,"number":3169,"title":"pserve development.ini --reload: fails in windows 10 64bit","user":{"login":"mdaadil","id":1292758,"avatar_url":"https://avatars0.githubusercontent.com/u/1292758?v=4","gravatar_id":"","url":"https://api.github.com/users/mdaadil","html_url":"https://github.com/mdaadil","followers_url":"https://api.github.com/users/mdaadil/followers","following_url":"https://api.github.com/users/mdaadil/following{/other_user}","gists_url":"https://api.github.com/users/mdaadil/gists{/gist_id}","starred_url":"https://api.github.com/users/mdaadil/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/mdaadil/subscriptions","organizations_url":"https://api.github.com/users/mdaadil/orgs","repos_url":"https://api.github.com/users/mdaadil/repos","events_url":"https://api.github.com/users/mdaadil/events{/privacy}","received_events_url":"https://api.github.com/users/mdaadil/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2017-09-18T15:49:56Z","updated_at":"2017-09-18T20:05:51Z","closed_at":"2017-09-18T20:05:51Z","author_association":"NONE","body":"I am following [an article](http://www.brettdangerfield.com/post/creating_a_blog_with_pyramid_mongdb_bootstrap/) and creating my first project, \r\n\r\nwhile i try the below command the process gets into a loop and starts a server and kills it and again starts a server and kills and it keeps doing this continuously without breaking the loop and exiting.\r\n\r\npserve development.ini --reload\r\n\r\nBelow is the log\r\n//---------------------------------------------------------\r\nStarting monitor for PID 18084.\r\nTraceback (most recent call last):\r\n  File \"<string>\", line 1, in <module>\r\n  File \"D:\\Others\\Python\\myBlog\\lib\\site-packages\\hupper\\ipc.py\", line 322, in spawn_main\r\n    func(**kwargs)\r\n  File \"D:\\Others\\Python\\myBlog\\lib\\site-packages\\hupper\\worker.py\", line 237, in worker_main\r\n    func(*spec_args, **spec_kwargs)\r\n  File \"D:\\Others\\Python\\myBlog\\lib\\site-packages\\pyramid\\scripts\\pserve.py\", line 32, in main\r\n    return command.run()\r\n  File \"D:\\Others\\Python\\myBlog\\lib\\site-packages\\pyramid\\scripts\\pserve.py\", line 229, in run\r\n    app = loader.get_wsgi_app(app_name, config_vars)\r\n  File \"D:\\Others\\Python\\myBlog\\lib\\site-packages\\plaster_pastedeploy\\__init__.py\", line 131, in get_wsgi_app\r\n    global_conf=defaults)\r\n  File \"d:\\others\\python\\myblog\\lib\\site-packages\\paste\\deploy\\loadwsgi.py\", line 247, in loadapp\r\n    return loadobj(APP, uri, name=name, **kw)\r\n  File \"d:\\others\\python\\myblog\\lib\\site-packages\\paste\\deploy\\loadwsgi.py\", line 271, in loadobj\r\n    global_conf=global_conf)\r\n  File \"d:\\others\\python\\myblog\\lib\\site-packages\\paste\\deploy\\loadwsgi.py\", line 296, in loadcontext\r\n    global_conf=global_conf)\r\n  File \"d:\\others\\python\\myblog\\lib\\site-packages\\paste\\deploy\\loadwsgi.py\", line 320, in _loadconfig\r\n    return loader.get_context(object_type, name, global_conf)\r\n  File \"d:\\others\\python\\myblog\\lib\\site-packages\\paste\\deploy\\loadwsgi.py\", line 450, in get_context\r\n    global_additions=global_additions)\r\n  File \"d:\\others\\python\\myblog\\lib\\site-packages\\paste\\deploy\\loadwsgi.py\", line 562, in _pipeline_app_context\r\n    for name in pipeline[:-1]]\r\n  File \"d:\\others\\python\\myblog\\lib\\site-packages\\paste\\deploy\\loadwsgi.py\", line 562, in <listcomp>\r\n    for name in pipeline[:-1]]\r\n  File \"d:\\others\\python\\myblog\\lib\\site-packages\\paste\\deploy\\loadwsgi.py\", line 406, in get_context\r\n    global_conf=global_conf)\r\n  File \"d:\\others\\python\\myblog\\lib\\site-packages\\paste\\deploy\\loadwsgi.py\", line 296, in loadcontext\r\n    global_conf=global_conf)\r\n  File \"d:\\others\\python\\myblog\\lib\\site-packages\\paste\\deploy\\loadwsgi.py\", line 328, in _loadegg\r\n    return loader.get_context(object_type, name, global_conf)\r\n  File \"d:\\others\\python\\myblog\\lib\\site-packages\\paste\\deploy\\loadwsgi.py\", line 620, in get_context\r\n    object_type, name=name)\r\n  File \"d:\\others\\python\\myblog\\lib\\site-packages\\paste\\deploy\\loadwsgi.py\", line 646, in find_egg_entry_point\r\n    possible.append((entry.load(), protocol, entry.name))\r\n  File \"D:\\Others\\Python\\myBlog\\lib\\site-packages\\pkg_resources\\__init__.py\", line 2405, in load\r\n    return self.resolve()\r\n  File \"D:\\Others\\Python\\myBlog\\lib\\site-packages\\pkg_resources\\__init__.py\", line 2411, in resolve\r\n    module = __import__(self.module_name, fromlist=['__name__'], level=0)\r\n  File \"D:\\Others\\Python\\myBlog\\lib\\site-packages\\weberror-0.13.1-py3.6.egg\\weberror\\evalexception.py\", line 127\r\n    except ValueError, ve:\r\n                     ^\r\nSyntaxError: invalid syntax\r\nKilling server with PID 18084.\r\nStarting monitor for PID 18600.\r\nTraceback (most recent call last):\r\n\r\n\r\n\r\n","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3167","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3167/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3167/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3167/events","html_url":"https://github.com/Pylons/pyramid/issues/3167","id":256964585,"number":3167,"title":"create first pyramid application","user":{"login":"Rajanani044","id":31839716,"avatar_url":"https://avatars1.githubusercontent.com/u/31839716?v=4","gravatar_id":"","url":"https://api.github.com/users/Rajanani044","html_url":"https://github.com/Rajanani044","followers_url":"https://api.github.com/users/Rajanani044/followers","following_url":"https://api.github.com/users/Rajanani044/following{/other_user}","gists_url":"https://api.github.com/users/Rajanani044/gists{/gist_id}","starred_url":"https://api.github.com/users/Rajanani044/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Rajanani044/subscriptions","organizations_url":"https://api.github.com/users/Rajanani044/orgs","repos_url":"https://api.github.com/users/Rajanani044/repos","events_url":"https://api.github.com/users/Rajanani044/events{/privacy}","received_events_url":"https://api.github.com/users/Rajanani044/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2017-09-12T08:46:09Z","updated_at":"2017-09-15T15:16:48Z","closed_at":"2017-09-15T15:16:48Z","author_association":"NONE","body":"Hi,thanks for tutorial!\r\ncreate first pyramid application, i get following error in commad line\r\nc:>%VENV%/Scripts/python helloworld.py\r\nC:\\env/Scripts/python: can't open file 'helloworld.py':[Error 2] No such file or directory\r\n![screenshot_1](https://user-images.githubusercontent.com/31839716/30316451-e8cdd786-97c4-11e7-9954-f7481cfbaa43.png)\r\n","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3166","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3166/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3166/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3166/events","html_url":"https://github.com/Pylons/pyramid/issues/3166","id":254600124,"number":3166,"title":"Should be possible to *remove* variables in pshell","user":{"login":"ztane","id":704200,"avatar_url":"https://avatars1.githubusercontent.com/u/704200?v=4","gravatar_id":"","url":"https://api.github.com/users/ztane","html_url":"https://github.com/ztane","followers_url":"https://api.github.com/users/ztane/followers","following_url":"https://api.github.com/users/ztane/following{/other_user}","gists_url":"https://api.github.com/users/ztane/gists{/gist_id}","starred_url":"https://api.github.com/users/ztane/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ztane/subscriptions","organizations_url":"https://api.github.com/users/ztane/orgs","repos_url":"https://api.github.com/users/ztane/repos","events_url":"https://api.github.com/users/ztane/events{/privacy}","received_events_url":"https://api.github.com/users/ztane/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2017-09-01T10:26:18Z","updated_at":"2018-02-26T01:49:18Z","closed_at":"2018-02-26T01:49:18Z","author_association":"CONTRIBUTOR","body":"This is rather minor, but i.e. if traversal is not used, the `root` and `root_factory` could be gone from the injected env as the list of things after my additions is rather long already. However while a `setup` method within the `[pshell]` section *can* pop these keys, the changes are not reflected in the shell globals. Alternatively, they could be set to `None`, so remove `None`s as they'd hardly useful anyway.","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3164","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3164/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3164/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3164/events","html_url":"https://github.com/Pylons/pyramid/issues/3164","id":251900888,"number":3164,"title":"Request is not pickleable","user":{"login":"diefans","id":513316,"avatar_url":"https://avatars3.githubusercontent.com/u/513316?v=4","gravatar_id":"","url":"https://api.github.com/users/diefans","html_url":"https://github.com/diefans","followers_url":"https://api.github.com/users/diefans/followers","following_url":"https://api.github.com/users/diefans/following{/other_user}","gists_url":"https://api.github.com/users/diefans/gists{/gist_id}","starred_url":"https://api.github.com/users/diefans/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/diefans/subscriptions","organizations_url":"https://api.github.com/users/diefans/orgs","repos_url":"https://api.github.com/users/diefans/repos","events_url":"https://api.github.com/users/diefans/events{/privacy}","received_events_url":"https://api.github.com/users/diefan
8000
s/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2017-08-22T09:53:09Z","updated_at":"2017-08-24T09:50:02Z","closed_at":"2017-08-22T22:38:38Z","author_association":"NONE","body":"```\r\n# pshell local.ini \r\nPython 2.7.12 (default, Nov 19 2016, 06:48:10) \r\nType \"copyright\", \"credits\" or \"license\" for more information.\r\n\r\nIPython 5.4.1 -- An enhanced Interactive Python.\r\n?         -> Introduction and overview of IPython's features.\r\n%quickref -> Quick reference.\r\nhelp      -> Python's own help system.\r\nobject?   -> Details about 'object', use 'object??' for extra details.\r\n\r\nEnvironment:\r\n  app          The WSGI application.\r\n  registry     Active Pyramid registry.\r\n  request      Active request object.\r\n  root         Root of the default resource tree.\r\n  root_factory Default root factory used to create `root`.\r\n\r\nIn [1]: import pickle\r\n\r\nIn [2]: pickle.dumps(request)\r\n---------------------------------------------------------------------------\r\nPicklingError                             Traceback (most recent call last)\r\n<ipython-input-2-a408e123f25b> in <module>()\r\n----> 1 pickle.dumps(request)\r\n\r\n/usr/lib/python2.7/pickle.pyc in dumps(obj, protocol)\r\n   1378 def dumps(obj, protocol=None):\r\n   1379     file = StringIO()\r\n-> 1380     Pickler(file, protocol).dump(obj)\r\n   1381     return file.getvalue()\r\n   1382 \r\n\r\n/usr/lib/python2.7/pickle.pyc in dump(self, obj)\r\n    222         if self.proto >= 2:\r\n    223             self.write(PROTO + chr(self.proto))\r\n--> 224         self.save(obj)\r\n    225         self.write(STOP)\r\n    226 \r\n\r\n/usr/lib/python2.7/pickle.pyc in save(self, obj)\r\n    329 \r\n    330         # Save the reduce() output and finally memoize the object\r\n--> 331         self.save_reduce(obj=obj, *rv)\r\n    332 \r\n    333     def persistent_id(self, obj):\r\n\r\n/usr/lib/python2.7/pickle.pyc in save_reduce(self, func, args, state, listitems, dictitems, obj)\r\n    399         else:\r\n    400             save(func)\r\n--> 401             save(args)\r\n    402             write(REDUCE)\r\n    403 \r\n\r\n/usr/lib/python2.7/pickle.pyc in save(self, obj)\r\n    284         f = self.dispatch.get(t)\r\n    285         if f:\r\n--> 286             f(self, obj) # Call unbound method with explicit self\r\n    287             return\r\n    288 \r\n\r\n/usr/lib/python2.7/pickle.pyc in save_tuple(self, obj)\r\n    566         write(MARK)\r\n    567         for element in obj:\r\n--> 568             save(element)\r\n    569 \r\n    570         if id(obj) in memo:\r\n\r\n/usr/lib/python2.7/pickle.pyc in save(self, obj)\r\n    284         f = self.dispatch.get(t)\r\n    285         if f:\r\n--> 286             f(self, obj) # Call unbound method with explicit self\r\n    287             return\r\n    288 \r\n\r\n/usr/lib/python2.7/pickle.pyc in save_global(self, obj, name, pack)\r\n    752             raise PicklingError(\r\n    753                 \"Can't pickle %r: it's not found as %s.%s\" %\r\n--> 754                 (obj, module, name))\r\n    755         else:\r\n    756             if klass is not obj:\r\n\r\nPicklingError: Can't pickle <class 'pyramid.util.Request'>: it's not found as pyramid.util.Request\r\n```","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3150","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3150/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3150/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3150/events","html_url":"https://github.com/Pylons/pyramid/issues/3150","id":249947272,"number":3150,"title":"Phrasing in tutorial on views sounds broken","user":{"login":"larsblumberg","id":5980316,"avatar_url":"https://avatars3.githubusercontent.com/u/5980316?v=4","gravatar_id":"","url":"https://api.github.com/users/larsblumberg","html_url":"https://github.com/larsblumberg","followers_url":"https://api.github.com/users/larsblumberg/followers","following_url":"https://api.github.com/users/larsblumberg/following{/other_user}","gists_url":"https://api.github.com/users/larsblumberg/gists{/gist_id}","starred_url":"https://api.github.com/users/larsblumberg/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/larsblumberg/subscriptions","organizations_url":"https://api.github.com/users/larsblumberg/orgs","repos_url":"https://api.github.com/users/larsblumberg/repos","events_url":"https://api.github.com/users/larsblumberg/events{/privacy}","received_events_url":"https://api.github.com/users/larsblumberg/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2017-08-14T07:00:58Z","updated_at":"2017-10-12T03:09:34Z","closed_at":"2017-10-12T03:09:24Z","author_association":"CONTRIBUTOR","body":"On https://github.com/Pylons/pyramid/blob/4acd85dc98fb2a43eae54d2116cc4bf383157269/docs/quick_tutorial/view_classes.rst#L15 it states:\r\n\r\n_They may be different ways to look at or work on the same data, or be a REST API that handles multiple operations._\r\n\r\nI'm not a native English speaker, but that phrase sounds broken to me. Since I'm not able to guess what the author intends to express, I can't provide a PR.\r\n\r\nBy the way, Pyramid's tutorial pages are an excellent help to get started.","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3148","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3148/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3148/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3148/events","html_url":"https://github.com/Pylons/pyramid/issues/3148","id":249730202,"number":3148,"title":"request: make pyramid.session's CookieSession scoped publicly","user":{"login":"jvanasco","id":204779,"avatar_url":"https://avatars3.githubusercontent.com/u/204779?v=4","gravatar_id":"","url":"https://api.github.com/users/jvanasco","html_url":"https://github.com/jvanasco","followers_url":"https://api.github.com/users/jvanasco/followers","following_url":"https://api.github.com/users/jvanasco/following{/other_user}","gists_url":"https://api.github.com/users/jvanasco/gists{/gist_id}","starred_url":"https://api.github.com/users/jvanasco/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jvanasco/subscriptions","organizations_url":"https://api.github.com/users/jvanasco/orgs","repos_url":"https://api.github.com/users/jvanasco/repos","events_url":"https://api.github.com/users/jvanasco/events{/privacy}","received_events_url":"https://api.github.com/users/jvanasco/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":6,"created_at":"2017-08-11T19:45:19Z","updated_at":"2017-08-16T02:29:04Z","closed_at":"2017-08-16T02:29:04Z","author_association":"NONE","body":"the current behavior:\r\n\r\n`pyramid.session.BaseCookieSessionFactory` is a def, which defines a privately scoped class `CookieSession(dict)`.  \r\n\r\n`type(request.session)` will return `pyramid.session.CookieSession`, however this can not be accessed as a class for comparison due to scoping issues, since CookieSession doesn't exist on the scope.  e.g. this will raise an exception:\r\n\r\n   if isinstance(request.session, pyramid.session.CookieSession)\r\n\r\nThe change I would like to propose, is creating a public `BaseCookieSession` (or similar) class, and having the current CookieSession inherit it.  That would allow for full backwards compatibility.\r\n\r\n    +class BaseCookieSession(dict):\r\n    +    \"core class for inheritance\"\r\n    +    pass\r\n\r\n    .def BaseCookieSessionFactory(\r\n    ...\r\n    .    @implementer(ISession)\r\n    -    class CookieSession(dict):\r\n    +    class CookieSession(BaseCookieSession):\r\n","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3147","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3147/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3147/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3147/events","html_url":"https://github.com/Pylons/pyramid/issues/3147","id":249677693,"number":3147,"title":"pserve --reload needs an option to force polling","user":{"login":"dpopowich","id":6783372,"avatar_url":"https://avatars3.githubusercontent.com/u/6783372?v=4","gravatar_id":"","url":"https://api.github.com/users/dpopowich","html_url":"https://github.com/dpopowich","followers_url":"https://api.github.com/users/dpopowich/followers","following_url":"https://api.github.com/users/dpopowich/following{/other_user}","gists_url":"https://api.github.com/users/dpopowich/gists{/gist_id}","starred_url":"https://api.github.com/users/dpopowich/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/dpopowich/subscriptions","organizations_url":"https://api.github.com/users/dpopowich/orgs","repos_url":"https://api.github.com/users/dpopowich/repos","events_url":"https://api.github.com/users/dpopowich/events{/privacy}","received_events_url":"https://api.github.com/users/dpopowich/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":6,"created_at":"2017-08-11T15:57:04Z","updated_at":"2018-02-21T07:13:32Z","closed_at":"2018-02-21T07:13:32Z","author_association":"NONE","body":"This is slightly different than #2920...\r\n\r\nI am part of a team developing a single-page webapp.  Server-side is pyramid, client-side is a javascript app built into a one-file bundle with browserify.\r\n\r\nI have a development setup where I'm running my pyramid server in a vagrant vm (virtualbox, ubuntu 16.04), accessing the running application via port-forwarding from host computer to vm. I edit my files on my host.  With pyramid 1.7 running `pserve --reload` worked fine.  \r\n\r\nMeanwhile I have watchdog installed in my vm for use with the non-python code: when js files are modified, watchdog (*using polling*) kicks off browserify to rebuild the client-side app. Note how I said using watchdog with polling. There is an issue with virtualbox, inotify, and modifying files from the host computer...inotify in the vm does not recognize the file updates. So I *have* to use polling.\r\n\r\nI updated pyramid to 1.9 and now `pserve --reload` no longer works because it detects watchdog and uses it and **there is no way to tell pserve (or, rather, hupper) not to use watchdog if it exists.** Uninstalling watchdog is not an option as I need it elsewhere.\r\n\r\nIn a nutshell: **I need an option to force polling regardless of the existence of watchdog in the virtualenv.**\r\n\r\nMeanwhile, this is my hack script to get around the issue:\r\n\r\n```python\r\n#!/usr/bin/env python\r\n\r\nimport sys\r\nimport builtins\r\nfrom pyramid.scripts.pserve import main\r\n\r\ndef no_watchdog():\r\n   \"\"\"We have watchdog installed for client-side watching of file changes\r\n   via polling. Meanwhile, pyramid (since 1.8) will use watchdog, if it is\r\n   installed, for file watching and use inotify which doesn't work\r\n   well when watching within a vm and files are edited on the host.\r\n   We need polling.  HOWEVER, there is no way to force polling from\r\n   the pserve commandline: if it can import watchdog it uses it with\r\n   inotify.  Herein we force the importing of watchdog to raise an\r\n   ImportError which will force the use of polling.\r\n   \"\"\"\r\n   \r\n   def prevent_watchdog_import(name, *args, **kwargs):\r\n      \"\"\"Force ImportError when importing watchdog.\r\n      \"\"\"\r\n      if name.split('.')[0] == 'watchdog':\r\n         raise ImportError\r\n      # call out to real builtin importer\r\n      return real_import(name, *args, **kwargs)\r\n   \r\n   # get handle to __import__ builtin\r\n   real_import = builtins.__import__\r\n   # replace  __import__ with our custom importer\r\n   builtins.__import__ = prevent_watchdog_import\r\n\r\nif __name__ == '__main__':\r\n   no_watchdog()\r\n   sys.exit(main())\r\n```","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3145","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3145/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3145/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3145/events","html_url":"https://github.com/Pylons/pyramid/issues/3145","id":248734994,"number":3145,"title":"Pyramid CORS doest not serve PUT AND DELETE","user":{"login":"adouani","id":8411437,"avatar_url":"https://avatars0.githubusercontent.com/u/8411437?v=4","gravatar_id":"","url":"https://api.github.com/users/adouani","html_url":"https://github.com/adouani","followers_url":"https://api.github.com/users/adouani/followers","following_url":"https://api.github.com/users/adouani/following{/other_user}","gists_url":"https://api.github.com/users/adouani/gists{/gist_id}","starred_url":"https://api.github.com/users/adouani/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/adouani/subscriptions","organizations_url":"https://api.github.com/users/adouani/orgs","repos_url":"https://api.github.com/users/adouani/repos","events_url":"https://api.github.com/users/adouani/events{/privacy}","received_events_url":"https://api.github.com/users/adouani/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":5,"created_at":"2017-08-08T14:30:23Z","updated_at":"2017-08-08T20:27:24Z","closed_at":"2017-08-08T16:26:34Z","author_association":"NONE","body":"I have a serious problem with pyramid framework. I add this function to pyramid\r\n\r\n```\r\nadd_cors_headers_response_callback(event):\r\n    def cors_headers(request, response):\r\n        response.headers.update({\r\n        'Access-Control-Allow-Origin': '*',\r\n        'Access-Control-Allow-Methods': 'POST,GET,DELETE,PUT,OPTIONS',\r\n        # 'Access-Control-Allow-Methods': 'DELETE, OPTIONS',\r\n        'Access-Control-Allow-Headers': 'Origin, Content-Type, Accept, Authorization',\r\n        'Access-Control-Allow-Credentials': 'true',\r\n        'Access-Control-Max-Age': '1728000',\r\n        })\r\n    event.request.add_response_callback(cors_headers)\r\n\r\nfrom pyramid.events import NewRequest\r\nconfig.add_subscriber(add_cors_headers_response_callback, NewRequest)\r\n\r\n```\r\n\r\n```\r\n@view_config(route_name='gm', renderer='json',request_method=\"GET\")\r\ndef get(request):\r\n    return dict(hello=\"GET\")\r\n\r\n\r\n@view_config(route_name='gm', renderer='json',request_method=\"POST\")\r\ndef post(request):\r\n    return dict(hello=\"POST\")\r\n\r\n\r\n@view_config(route_name='gm', renderer='json',request_method=\"PUT\")\r\ndef put(request):\r\n    return dict(hello=\"PUT\")\r\n\r\n\r\n@view_config(route_name='gm', renderer='json',request_method=\"DELETE\")\r\ndef delete(request):\r\n    return dict(hello=\"DELETE\")\r\n\r\n```\r\nAnd I can make request to my server using GET, POST methods. The problem is when I use PUT AND DELETE methods the server sends HTTP status 404, but when I curl the route I get the answer (or using POSTMAN).\r\n\r\nI use the same Angular http query with Node.JS and it accepts my request. I don't know why pyramid refuse to serve the view\r\n\r\n\r\n```\r\nimport { Injectable } from '@angular/core';\r\nimport {Http} from \"@angular/http\";\r\n\r\nimport \"rxjs/add/operator/map\"\r\n\r\n@Injectable()\r\nexport class AppService {\r\n  baseUrl : string = \"http://10.0.0.34:8880\"\r\n  constructor(public http:Http) { }\r\n\r\n  getData(url) {\r\n    console.log('hi');\r\n    let full_url= this.baseUrl + url;\r\n    return this.http.get(full_url)\r\n      .map(response => response.json());\r\n  }\r\n  postData(url) {\r\n    console.log('hello');\r\n    let full_url= this.baseUrl + url;\r\n    return this.http.post(full_url,null)\r\n      .map(response => response.json());\r\n  }\r\n  putData(url) {\r\n    console.log('hello');\r\n    let full_url= this.baseUrl + url;\r\n    return this.http.put(full_url,null)\r\n      .map(response => response.json());\r\n  }\r\n  deleteData(url) {\r\n    console.log('hello');\r\n    let full_url= this.baseUrl + url;\r\n    return this.http.delete(full_url)\r\n      .map(response => response.json());\r\n  }\r\n\r\n}\r\n```\r\n","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3143","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3143/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3143/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3143/events","html_url":"https://github.com/Pylons/pyramid/issues/3143","id":248043858,"number":3143,"title":"Make it possible to set serializer for cookies","user":{"login":"piotr-dobrogost","id":92239,"avatar_url":"https://avatars2.githubusercontent.com/u/92239?v=4","gravatar_id":"","url":"https://api.github.com/users/piotr-dobrogost","html_url":"https://github.com/piotr-dobrogost","followers_url":"https://api.github.com/users/piotr-dobrogost/followers","following_url":"https://api.github.com/users/piotr-dobrogost/following{/other_user}","gists_url":"https://api.github.com/users/piotr-dobrogost/gists{/gist_id}","starred_url":"https://api.github.com/users/piotr-dobrogost/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/piotr-dobrogost/subscriptions","organizations_url":"https://api.github.com/users/piotr-dobrogost/orgs","repos_url":"https://api.github.com/users/piotr-dobrogost/repos","events_url":"https://api.github.com/users/piotr-dobrogost/events{/privacy}","received_events_url":"https://api.github.com/users/piotr-dobrogost/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2017-08-04T15:43:20Z","updated_at":"2017-08-11T11:42:44Z","closed_at":"2017-08-04T17:37:52Z","author_association":"NONE","body":"It would be handy if one could set serializer used to serialize/deserialize cookies being set/read. This could probably be implemented using cookie profiles from WebOb which store such serializer.","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3137","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3137/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3137/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3137/events","html_url":"https://github.com/Pylons/pyramid/issues/3137","id":245380802,"number":3137,"title":"Object persistence issue","user":{"login":"TWry","id":2758765,"avatar_url":"https://avatars2.githubusercontent.com/u/2758765?v=4","gravatar_id":"","url":"https://api.github.com/users/TWry","html_url":"https://github.com/TWry","followers_url":"https://api.github.com/users/TWry/followers","following_url":"https://api.github.com/users/TWry/following{/other_user}","gists_url":"https://api.github.com/users/TWry/gists{/gist_id}","starred_url":"https://api.github.com/users/TWry/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/TWry/subscriptions","organizations_url":"https://api.github.com/users/TWry/orgs","repos_url":"https://api.github.com/users/TWry/repos","events_url":"https://api.github.com/users/TWry/events{/privacy}","received_events_url":"https://api.github.com/users/TWry/received_events","type":"User","site_admin":false},"labels":[{"id":196520,"url":"https://api.github.com/repos/Pylons/pyramid/labels/bugs","name":"bugs","color":"e10c02","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":8,"created_at":"2017-07-25T12:12:40Z","updated_at":"2017-07-25T15:35:25Z","closed_at":"2017-07-25T15:35:25Z","author_association":"NONE","body":"See code below. I'd expect that the `add_event` method would automatically persist new events. That is not the case. I have to add a call to transaction.commit in order for this to work. The project has been set up from the cookiecutter template, pyramid version is 1.9.1. Any ideas what's going wrong here, please?\r\n    \r\n\r\n    from repoze.folder import Folder\r\n    \r\n    \r\n    class FooRoot(Folder):\r\n        __name__ = None\r\n        __parent__ = None\r\n    \r\n        def add_event(self, **kwargs):\r\n            title = kwargs.get('title')\r\n            event = Event(**kwargs)\r\n            self[title] = event\r\n            return event\r\n    \r\n        \r\n    class Event(Folder):\r\n        def __init__(self, **kwargs):\r\n            super().__init__()\r\n            for key, val in kwargs.items():\r\n                setattr(self, key, val)\r\n    \r\n    \r\n    def appmaker(zodb_root):\r\n        if 'app_root' not in zodb_root:\r\n            app_root = FooRoot()\r\n            zodb_root['app_root'] = app_root\r\n            import transaction\r\n            transaction.commit()\r\n        return zodb_root['app_root']\r\n\r\n","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3130","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3130/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3130/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3130/events","html_url":"https://github.com/Pylons/pyramid/issues/3130","id":244030444,"number":3130,"title":"Pyramid 1.9.1, pserve and ConfigParser","user":{"login":"kalbermattenm","id":1681332,"avatar_url":"https://avatars1.githubusercontent.com/u/1681332?v=4","gravatar_id":"","url":"https://api.github.com/users/kalbermattenm","html_url":"https://github.com/kalbermattenm","followers_url":"https://api.github.com/users/kalbermattenm/followers","following_url":"https://api.github.com/users/kalbermattenm/following{/other_user}","gists_url":"https://api.github.com/users/kalbermattenm/gists{/gist_id}","starred_url":"https://api.github.com/users/kalbermattenm/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/kalbermattenm/subscriptions","organizations_url":"https://api.github.com/users/kalbermattenm/orgs","repos_url":"https://api.github.com/users/kalbermattenm/repos","events_url":"https://api.github.com/users/kalbermattenm/events{/privacy}","received_events_url":"https://api.github.com/users/kalbermattenm/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2017-07-19T12:54:17Z","updated_at":"2017-08-07T09:22:07Z","closed_at":"2017-07-19T13:00:46Z","author_association":"NONE","body":"I get some kind of strange issue using Pyramid 1.9.1 in a project on Windows 10\r\n\r\nI have a project in which I would like to use `flake8`. If I add this one to my `setup.py` file in my pyramid app, then it installs `configparser` as a dependency (which is OK...). I used to do so in other Pyramid projects (Pyramid<1.8) and I did not encounter any issue.\r\n\r\nBut with Pyramid 1.9.1, as soon as I install `configparser`, I get the here under error.\r\n\r\nDoes anyone have any hint on what is going on ?\r\n\r\n```\r\n:\\git_projects\\sitn_portal>.build\\venv\\Scripts\\pserve development.ini --reload\r\nTraceback (most recent call last):\r\n  File \"c:\\python27\\Lib\\runpy.py\", line 162, in _run_module_as_main\r\n    \"__main__\", fname, loader, pkg_name)\r\n  File \"c:\\python27\\Lib\\runpy.py\", line 72, in _run_code\r\n    exec code in run_globals\r\n  File \"C:\\git_projects\\sitn_portal\\.build\\venv\\Scripts\\pserve.exe\\__main__.py\", line 9, in <module>\r\n  File \"c:\\git_projects\\sitn_portal\\.build\\venv\\lib\\site-packages\\pyramid\\scripts\\pserve.py\", line 32, in main\r\n    return command.run()\r\n  File \"c:\\git_projects\\sitn_portal\\.build\\venv\\lib\\site-packages\\pyramid\\scripts\\pserve.py\", line 170, in run\r\n    self.pserve_file_config(loader, global_conf=config_vars)\r\n  File \"c:\\git_projects\\sitn_portal\\.build\\venv\\lib\\site-packages\\pyramid\\scripts\\pserve.py\", line 133, in pserve_file_config\r\n    settings = loader.get_settings('pserve', global_conf)\r\n  File \"c:\\git_projects\\sitn_portal\\.build\\venv\\lib\\site-packages\\plaster_pastedeploy\\__init__.py\", line 72, in get_settings\r\n    return OrderedDict(parser.items(section))\r\n  File \"c:\\python27\\Lib\\ConfigParser.py\", line 642, in items\r\n    raise NoSectionError(section)\r\nConfigParser.NoSectionError: No section: 'pserve'\r\n```","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3115","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3115/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3115/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3115/events","html_url":"https://github.com/Pylons/pyramid/issues/3115","id":239970730,"number":3115,"title":"1.8.4 tests hang on interactive prompt 'Really use \"distro\"?:  [y|N]: '","user":{"login":"bowlofeggs","id":354506,"avatar_url":"https://avatars2.githubusercontent.com/u/354506?v=4","gravatar_id":"","url":"https://api.github.com/users/bowlofeggs","html_url":"https://github.com/bowlofeggs","followers_url":"https://api.github.com/users/bowlofeggs/followers","following_url":"https://api.github.com/users/bowlofeggs/following{/other_user}","gists_url":"https://api.github.com/users/bowlofeggs/gists{/gist_id}","starred_url":"https://api.github.com/users/bowlofeggs/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/bowlofeggs/subscriptions","organizations_url":"https://api.github.com/users/bowlofeggs/orgs","repos_url":"https://api.github.com/users/bowlofeggs/repos","events_url":"https://api.github.com/users/bowlofeggs/events{/privacy}","received_events_url":"https://api.github.com/users/bowlofeggs/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2017-07-01T20:28:25Z","updated_at":"2017-07-01T21:50:05Z","closed_at":"2017-07-01T21:28:28Z","author_association":"NONE","body":"I am working on packaging 1.8.4 for Fedora 26. When the tests are run during the build, some of them print a message:\r\n\r\n```\r\nReally use \"distro\"?:  [y|N]:\r\n```\r\n\r\nThe tests will not continue without input to this question. I've tried running the tests two ways:\r\n\r\n1. ```python setup.py test```\r\n2. ```nosetests```\r\n\r\nThis happens either way.","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3114","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3114/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3114/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3114/events","html_url":"https://github.com/Pylons/pyramid/issues/3114","id":239970111,"number":3114,"title":"Please tag the 1.9 release on GitHub","user":{"login":"bowlofeggs","id":354506,"avatar_url":"https://avatars2.githubusercontent.com/u/354506?v=4","gravatar_id":"","url":"https://api.github.com/users/bowlofeggs","html_url":"https://github.com/bowlofeggs","followers_url":"https://api.github.com/users/bowlofeggs/followers","following_url":"https://api.github.com/users/bowlofeggs/following{/other_user}","gists_url":"https://api.github.com/users/bowlofeggs/gists{/gist_id}","starred_url":"https://api.github.com/users/bowlofeggs/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/bowlofeggs/subscriptions","organizations_url":"https://api.github.com/users/bowlofeggs/orgs","repos_url":"https://api.github.com/users/bowlofeggs/repos","events_url":"https://api.github.com/users/bowlofeggs/events{/privacy}","received_events_url":"https://api.github.com/users/bowlofeggs/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2017-07-01T20:14:28Z","updated_at":"2017-07-01T21:49:05Z","closed_at":"2017-07-01T21:09:00Z","author_association":"NONE","body":"Hello!\r\n\r\nI am working on [packaging 1.9 for Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1465428), and we currently use your git tags to pull the source code for your releases. Could you make a ```1.9``` tag in git that corresponds to the [build found in PyPI](https://pypi.python.org/pypi/pyramid/1.9)? Thanks!","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3112","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3112/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3112/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3112/events","html_url":"https://github.com/Pylons/pyramid/issues/3112","id":239422649,"number":3112,"title":"Circular import in pyramid.viewderivers","user":{"login":"philpep","id":387511,"avatar_url":"https://avatars3.githubusercontent.com/u/387511?v=4","gravatar_id":"","url":"https://api.github.com/users/philpep","html_url":"https://github.com/philpep","followers_url":"https://api.github.com/users/philpep/followers","following_url":"https://api.github.com/users/philpep/following{/other_user}","gists_url":"https://api.github.com/users/philpep/gists{/gist_id}","starred_url":"https://api.github.com/users/philpep/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/philpep/subscriptions","organizations_url":"https://api.github.com/users/philpep/orgs","repos_url":"https://api.github.com/users/philpep/repos","events_url":"https://api.github.com/users/philpep/events{/privacy}","received_events_url":"https://api.github.com/users/philpep/received_events","type":"User","site_admin":false},"labels":[{"id":196520,"url":"https://api.github.com/repos/Pylons/pyramid/labels/bugs","name":"bugs","color":"e10c02","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2017-06-29T09:45:54Z","updated_at":"2017-07-16T10:41:16Z","closed_at":"2017-07-15T17:29:49Z","author_association":"NONE","body":"Hello, importing `pyramid.viewderivers` trigger a circular import error:\r\n\r\n```\r\n>>> import pyramid.viewderivers\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \".../lib/python2.7/site-packages/pyramid/viewderivers.py\", line 31, in <module>\r\n    from pyramid.config.util import (\r\n  File \".../lib/python2.7/site-packages/pyramid/config/__init__.py\", line 78, in <module>\r\n    from pyramid.config.views import ViewsConfiguratorMixin\r\n  File \".../lib/python2.7/site-packages/pyramid/config/views.py\", line 80, in <module>\r\n    from pyramid.viewderivers import (\r\nImportError: cannot import name INGRESS\r\n```","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3102","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3102/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3102/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3102/events","html_url":"https://github.com/Pylons/pyramid/issues/3102","id":237984477,"number":3102,"title":"How do I add font-awesome to pyramid? ","user":{"login":"jorge90mtz","id":8257990,"avatar_url":"https://avatars2.githubusercontent.com/u/8257990?v=4","gravatar_id":"","url":"https://api.github.com/users/jorge90mtz","html_url":"https://github.com/jorge90mtz","followers_url":"https://api.github.com/users/jorge90mtz/followers","following_url":"https://api.github.com/users/jorge90mtz/following{/othe
5e6
r_user}","gists_url":"https://api.github.com/users/jorge90mtz/gists{/gist_id}","starred_url":"https://api.github.com/users/jorge90mtz/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jorge90mtz/subscriptions","organizations_url":"https://api.github.com/users/jorge90mtz/orgs","repos_url":"https://api.github.com/users/jorge90mtz/repos","events_url":"https://api.github.com/users/jorge90mtz/events{/privacy}","received_events_url":"https://api.github.com/users/jorge90mtz/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":9,"created_at":"2017-06-22T21:51:32Z","updated_at":"2017-06-26T14:41:50Z","closed_at":"2017-06-26T14:41:50Z","author_association":"NONE","body":"I tried to use font-awesome to my project. I added the font types to the Manifest.in and I call it like:\r\n`<link href=\"${request.static_url('project:static/font-awesome/css/font-awesome.min.css')}\" rel=\"stylesheet\" type=\"text/css\">`  and in that file the url is as follows:\r\n`url('../fonts/fontawesome-webfont.woff?v=4.2.0') `\r\nbut I still get the 404 not found when I run it with **pserve**. What else can I do? Do I add it as a static view, if so, how would I do it? \r\nI also added the line:\r\n`config.add_static_view('static', 'static', cache_max_age=3600)` to my file.\r\n\r\nI would **IMMENSELY** appreciate any pointers or any help with this. Thank you very much to all.\r\n\r\n","score":1.0}]}
0

