HTTP/1.1 200 OK
Transfer-Encoding: chunked
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Cache-Control: no-cache
Content-Security-Policy: default-src 'none'
Content-Type: application/json; charset=utf-8
Date: Sun, 13 May 2018 13:01:07 GMT
Link: <https://api.github.com/search/issues?q=repo%3APylons%2Fpyramid+type%3Aissue+state%3Aclosed&page=2>; rel="next", <https://api.github.com/search/issues?q=repo%3APylons%2Fpyramid+type%3Aissue+state%3Aclosed&page=28>; rel="last"
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Server: GitHub.com
Status: 200 OK
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Accepted-Oauth-Scopes: 
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Github-Media-Type: github.v3; format=json
X-Github-Request-Id: CDDF:4F3F:1A90E62:3F5E310:5AF83712
X-Oauth-Scopes: 
X-Ratelimit-Limit: 30
X-Ratelimit-Remaining: 23
X-Ratelimit-Reset: 1526216518
X-Runtime-Rack: 0.456856
X-Xss-Protection: 1; mode=block

8000
{"total_count":833,"incomplete_results":false,"items":[{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3273","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3273/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3273/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3273/events","html_url":"https://github.com/Pylons/pyramid/issues/3273","id":318544137,"number":3273,"title":"pytest and settings in .ini file","user":{"login":"jgmtzmd","id":25892177,"avatar_url":"https://avatars3.githubusercontent.com/u/25892177?v=4","gravatar_id":"","url":"https://api.github.com/users/jgmtzmd","html_url":"https://github.com/jgmtzmd","followers_url":"https://api.github.com/users/jgmtzmd/followers","following_url":"https://api.github.com/users/jgmtzmd/following{/other_user}","gists_url":"https://api.github.com/users/jgmtzmd/gists{/gist_id}","starred_url":"https://api.github.com/users/jgmtzmd/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jgmtzmd/subscriptions","organizations_url":"https://api.github.com/users/jgmtzmd/orgs","repos_url":"https://api.github.com/users/jgmtzmd/repos","events_url":"https://api.github.com/users/jgmtzmd/events{/privacy}","received_events_url":"https://api.github.com/users/jgmtzmd/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":8,"created_at":"2018-04-27T20:44:19Z","updated_at":"2018-04-28T03:40:19Z","closed_at":"2018-04-28T03:40:19Z","author_association":"NONE","body":"hi.\r\ni followed your tutorial and then started teaking some thing (learning method).\r\n\r\ni found this:\r\n\r\ni can run tests and everithing works fine if in __init__ i include the pyramid_chameleon connector.\r\n`app.include( 'pyramid_chameleon' )`\r\nbut if i want to include the connector trough the .ini file it doesn't. \r\ni wrote\r\n`pyramid.include = pyramid_chameleon`\r\nin development.ini and pytest.ini`\r\n\r\nthe application works fine in the browser but the test seems not to grab that value from the .ini.\r\nwhat am i doing wrong?`\r\n\r\n","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3269","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3269/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3269/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3269/events","html_url":"https://github.com/Pylons/pyramid/issues/3269","id":317557198,"number":3269,"title":"Bump Sphinx to >=1.7.2","user":{"login":"stevepiercy","id":102112,"avatar_url":"https://avatars1.githubusercontent.com/u/102112?v=4","gravatar_id":"","url":"https://api.github.com/users/stevepiercy","html_url":"https://github.com/stevepiercy","followers_url":"https://api.github.com/users/stevepiercy/followers","following_url":"https://api.github.com/users/stevepiercy/following{/other_user}","gists_url":"https://api.github.com/users/stevepiercy/gists{/gist_id}","starred_url":"https://api.github.com/users/stevepiercy/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/stevepiercy/subscriptions","organizations_url":"https://api.github.com/users/stevepiercy/orgs","repos_url":"https://api.github.com/users/stevepiercy/repos","events_url":"https://api.github.com/users/stevepiercy/events{/privacy}","received_events_url":"https://api.github.com/users/stevepiercy/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-04-25T09:54:46Z","updated_at":"2018-04-26T03:37:50Z","closed_at":"2018-04-26T03:37:50Z","author_association":"OWNER","body":"Would anyone be opposed to bumping Sphinx to >=1.7.2, != 1.7.3 in `setup.py`? I really want our PDFs to have `emphasize-lines` support, at long last, and bring in support for Unicode characters in PDFs via xelatex.\r\n\r\nRefs:\r\n* #667\r\n* #2572\r\n* https://github.com/rtfd/readthedocs.org/issues/4015\r\n","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3262","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3262/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3262/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3262/events","html_url":"https://github.com/Pylons/pyramid/issues/3262","id":316892904,"number":3262,"title":"pyramid.scripting.get_root() triggers AttributeError ","user":{"login":"hathawsh","id":637806,"avatar_url":"https://avatars3.githubusercontent.com/u/637806?v=4","gravatar_id":"","url":"https://api.github.com/users/hathawsh","html_url":"https://github.com/hathawsh","followers_url":"https://api.github.com/users/hathawsh/followers","following_url":"https://api.github.com/users/hathawsh/following{/other_user}","gists_url":"https://api.github.com/users/hathawsh/gists{/gist_id}","starred_url":"https://api.github.com/users/hathawsh/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/hathawsh/subscriptions","organizations_url":"https://api.github.com/users/hathawsh/orgs","repos_url":"https://api.github.com/users/hathawsh/repos","events_url":"https://api.github.com/users/hathawsh/events{/privacy}","received_events_url":"https://api.github.com/users/hathawsh/received_events","type":"User","site_admin":false},"labels":[{"id":196520,"url":"https://api.github.com/repos/Pylons/pyramid/labels/bugs","name":"bugs","color":"e10c02","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-04-23T16:41:58Z","updated_at":"2018-04-24T16:22:22Z","closed_at":"2018-04-24T01:14:56Z","author_association":"MEMBER","body":"In Pyramid 1.9.1, get_root() triggers an AttributeError on threadlocal_manager:\r\n\r\n```\r\n# bin/pshell mything/development.ini \r\nPython 3.5.2 (default, Nov 23 2017, 16:37:01) \r\n[GCC 5.4.0 20160609] on linux\r\nType \"help\" for more information.\r\n\r\nEnvironment:\r\n  app          The WSGI application.\r\n  registry     Active Pyramid registry.\r\n  request      Active request object.\r\n  root         Root of the default resource tree.\r\n  root_factory Default root factory used to create `root`.\r\n\r\n>>> from pyramid.scripting import get_root\r\n>>> x = get_root(app)\r\nTraceback (most recent call last):\r\n  File \"<console>\", line 1, in <module>\r\n  File \"/home/shane/src/pyramidtest/eggs/pyramid-1.9.1-py3.5.egg/pyramid/scripting.py\", line 30, in get_root\r\n    app.threadlocal_manager.push(threadlocals)\r\nAttributeError: 'Router' object has no attribute 'threadlocal_manager'\r\n>>>\r\n```","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3260","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3260/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3260/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3260/events","html_url":"https://github.com/Pylons/pyramid/issues/3260","id":315957456,"number":3260,"title":"Tutorial instructions for windows may not work correctly in Powershell","user":{"login":"vagnerr","id":88375,"avatar_url":"https://avatars2.githubusercontent.com/u/88375?v=4","gravatar_id":"","url":"https://api.github.com/users/vagnerr","html_url":"https://github.com/vagnerr","followers_url":"https://api.github.com/users/vagnerr/followers","following_url":"https://api.github.com/users/vagnerr/following{/other_user}","gists_url":"https://api.github.com/users/vagnerr/gists{/gist_id}","starred_url":"https://api.github.com/users/vagnerr/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/vagnerr/subscriptions","organizations_url":"https://api.github.com/users/vagnerr/orgs","repos_url":"https://api.github.com/users/vagnerr/repos","events_url":"https://api.github.com/users/vagnerr/events{/privacy}","received_events_url":"https://api.github.com/users/vagnerr/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":25,"created_at":"2018-04-19T16:46:42Z","updated_at":"2018-04-26T07:52:43Z","closed_at":"2018-04-26T07:52:43Z","author_association":"NONE","body":"The current windows instructions seem to be orientated towards using the older Windows Command Prompt (CMD), rather than the more modern Powershell which is likely to become the default.\r\n\r\nThey are reasonably compatible with each other but there are some differences which may cause issues, such as Environment variables...\r\n\r\nFor example in https://docs.pylonsproject.org/projects/pyramid/en/latest/tutorials/wiki2/installation.html\r\n\r\n> c:\\tutorial> set VENV=c:\\tutorial\r\n> ...\r\n> c:\\tutorial> python -m venv %VENV%`\r\n\r\nWill not function as expected instead you will get a `%VENV%` directory in the current one. Instead you need a powershell alternative such as\r\n\r\n> c:\\tutorial> $env:VENV=\"c:\\tutorial\"\r\n> ...\r\n> c:\\tutorial> python -m venv $env:VENV`\r\n\r\nI think we still need to retain the CMD versions but it should be clear there that CMD and Powershell need different approaches.\r\n\r\n\r\n","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3256","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3256/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3256/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3256/events","html_url":"https://github.com/Pylons/pyramid/issues/3256","id":314630589,"number":3256,"title":"Exceptions as json","user":{"login":"robinharms","id":737216,"avatar_url":"https://avatars2.githubusercontent.com/u/737216?v=4","gravatar_id":"","url":"https://api.github.com/users/robinharms","html_url":"https://github.com/robinharms","followers_url":"https://api.github.com/users/robinharms/followers","following_url":"https://api.github.com/users/robinharms/following{/other_user}","gists_url":"https://api.github.com/users/robinharms/gists{/gist_id}","starred_url":"https://api.github.com/users/robinharms/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/robinharms/subscriptions","organizations_url":"https://api.github.com/users/robinharms/orgs","repos_url":"https://api.github.com/users/robinharms/repos","events_url":"https://api.github.com/users/robinharms/events{/privacy}","received_events_url":"https://api.github.com/users/robinharms/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2018-04-16T12:34:11Z","updated_at":"2018-04-17T08:04:28Z","closed_at":"2018-04-17T08:04:28Z","author_association":"NONE","body":"Pyramid already has the convention that objects with the method __json__ can be handled with the json renderer.\r\n\r\nIt would be nice if all the HTTP exceptions would pass to a json renderer and simply render as json, if they have the same method.\r\n\r\nWould this be something the framework team fancied? In that case I'd be up for the work.","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3252","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3252/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3252/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3252/events","html_url":"https://github.com/Pylons/pyramid/issues/3252","id":312697635,"number":3252,"title":"New to python, tutorial doesn't work","user":{"login":"datatalking","id":11813209,"avatar_url":"https://avatars3.githubusercontent.com/u/11813209?v=4","gravatar_id":"","url":"https://api.github.com/users/datatalking","html_url":"https://github.com/datatalking","followers_url":"https://api.github.com/users/datatalking/followers","following_url":"https://api.github.com/users/datatalking/following{/other_user}","gists_url":"https://api.github.com/users/datatalking/gists{/gist_id}","starred_url":"https://api.github.com/users/datatalking/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/datatalking/subscriptions","organizations_url":"https://api.github.com/users/datatalking/orgs","repos_url":"https://api.github.com/users/datatalking/repos","events_url":"https://api.github.com/users/datatalking/events{/privacy}","received_events_url":"https://api.github.com/users/datatalking/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-04-09T21:40:41Z","updated_at":"2018-04-09T22:42:54Z","closed_at":"2018-04-09T22:42:54Z","author_association":"NONE","body":"cookiecutter gh:Pylons/pyramid-cookiecutter-starter\r\nbash: cookiecutter: command not found\r\n\r\nis the error when I run your readme.md instructions\r\n\r\nIs there supposed to be an assumption of additional code or some kind of fancy something that makes this run?\r\n\r\nI installed cookie cutter and no command downloads or create the cookiecutter so how does it work?\r\n\r\n","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3250","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3250/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3250/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3250/events","html_url":"https://github.com/Pylons/pyramid/issues/3250","id":311746782,"number":3250,"title":"Unhandled exception when returning/raising error response if request contains invalid Accept: header","user":{"login":"dairiki","id":495018,"avatar_url":"https://avatars2.githubusercontent.com/u/495018?v=4","gravatar_id":"","url":"https://api.github.com/users/dairiki","html_url":"https://github.com/dairiki","followers_url":"https://api.github.com/users/dairiki/followers","following_url":"https://api.github.com/users/dairiki/following{/other_user}","gists_url":"https://api.github.com/users/dairiki/gists{/gist_id}","starred_url":"https://api.github.com/users/dairiki/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/dairiki/subscriptions","organizations_url":"https://api.github.com/users/dairiki/orgs","repos_url":"https://api.github.com/users/dairiki/repos","events_url":"https://api.github.com/users/dairiki/events{/privacy}","received_events_url":"https://api.github.com/users/dairiki/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-04-05T19:52:55Z","updated_at":"2018-04-24T05:09:31Z","closed_at":"2018-04-24T05:09:31Z","author_association":"CONTRIBUTOR","body":"As of WebOb 1.8, `webob.acceptparse.MIMEAccept` throws an exception if fed an invalid value for an Accept: header.  As part of generating an HTTP response from an HTTPException, HTTPException.prepare [constructs a MIMEAccept object](https://github.com/Pylons/pyramid/blob/309e6be0e83b5ed08f954c7dd66c5e8cf959a006/pyramid/httpexceptions.py#L253).  This means that, if a request includes a malformed Accept header, any attempt to convert an `HTTPException` (or subclass thereof) to a response will result in an unhandled exception.\r\n\r\n\r\nI'm not completely sure whether this should be fixed in pyramid or in WebOb.  WebOb's [changelog](https://docs.pylonsproject.org/projects/webob/en/1.8-branch/whatsnew-1.8.html#backwards-incompatibilities), however, does seem to indicate that `webob.acceptparse.create_accept_header` should be used going forward, rather than constructing a `MIMEAccept` directly.","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3248","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3248/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3248/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3248/events","html_url":"https://github.com/Pylons/pyramid/issues/3248","id":310309379,"number":3248,"title":"Tests in \"Creating functional tests\" fail","user":{"login":"stevepiercy","id":102112,"avatar_url":"https://avatars1.githubusercontent.com/u/102112?v=4","gravatar_id":"","url":"https://api.github.com/users/stevepiercy","html_url":"https://github.com/stevepiercy","followers_url":"https://api.github.com/users/stevepiercy/followers","following_url":"https://api.github.com/users/stevepiercy/following{/other_user}","gists_url":"https://api.github.com/users/stevepiercy/gists{/gist_id}","starred_url":"https://api.github.com/users/stevepiercy/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/stevepiercy/subscriptions","organizations_url":"https://api.github.com/users/stevepiercy/orgs","repos_url":"https://api.github.com/users/stevepiercy/repos","events_url":"https://api.github.com/users/stevepiercy/events{/privacy}","received_events_url":"https://api.github.com/users/stevepiercy/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-04-01T09:02:01Z","updated_at":"2018-04-01T09:26:15Z","closed_at":"2018-04-01T09:26:15Z","author_association":"OWNER","body":"See: https://github.com/Pylons/pyramid-cookiecutter-alchemy/issues/31\r\n\r\nThe functional tests here:\r\nhttps://docs.pylonsproject.org/projects/pyramid/en/latest/narr/testing.html#creating-functional-tests\r\n\r\nShould follow the example from the wiki tutorial:\r\nhttps://docs.pylonsproject.org/projects/pyramid/en/latest/tutorials/wiki2/tests.html","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3247","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3247/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3247/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3247/events","html_url":"https://github.com/Pylons/pyramid/issues/3247","id":306433340,"number":3247,"title":"Request.copy() removes Pyramid-added attributes","user":{"login":"rbu","id":65913,"avatar_url":"https://avatars2.githubusercontent.com/u/65913?v=4","gravatar_id":"","url":"https://api.github.com/users/rbu","html_url":"https://github.com/rbu","followers_url":"https://api.github.com/users/rbu/followers","following_url":"https://api.github.com/users/rbu/following{/other_user}","gists_url":"https://api.github.com/users/rbu/gists{/gist_id}","starred_url":"https://api.github.com/users/rbu/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/rbu/subscriptions","organizations_url":"https://api.github.com/users/rbu/orgs","repos_url":"https://api.github.com/users/rbu/repos","events_url":"https://api.github.com/users/rbu/events{/privacy}","received_events_url":"https://api.github.com/users/rbu/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":6,"created_at":"2018-03-19T11:58:41Z","updated_at":"2018-04-18T15:05:52Z","closed_at":"2018-04-18T15:05:52Z","author_association":"CONTRIBUTOR","body":"Pyramid's documentation [states that ```Request.copy``` can be used to make a copy of a request](https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/webob.html#methods). The method returns a ```pyramid.request.Request```, but that copy is missing essential request attributes such as ```registry```.\r\n\r\nBackground:\r\nThe method is purely ```webob.copy``` which only make a copy of environment and body. Pyramid does not override it to copy attributes it sets itself.\r\n\r\n## Expected behavior:\r\n```py\r\nr1 = get_current_request()\r\nr2 = r1.copy()\r\nassert r1.registry is r2.registry\r\n```\r\n\r\n## Actual behavior:\r\nRaises ```AttributeError: 'Request' object has no attribute 'registry'``` (from ```r2.registry```)\r\n","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3234","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3234/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3234/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3234/events","html_url":"https://github.com/Pylons/pyramid/issues/3234","id":302955303,"number":3234,"title":"Secret length for SignedCookieSessionFactory","user":{"login":"hongyuan1306","id":10390407,"avatar_url":"https://avatars0.githubusercontent.com/u/10390407?v=4","gravatar_id":"","url":"https://api.github.com/users/hongyuan1306","html_url":"https://github.com/hongyuan1306","followers_url":"https://api.github.com/users/hongyuan1306/followers","following_url":"https://api.github.com/users/hongyuan1306/following{/other_user}","gists_url":"https://api.github.com/users/hongyuan1306/gists{/gist_id}","starred_url":"https://api.github.com/users/hongyuan1306/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/hongyuan1306/subscriptions","organizations_url":"https://api.github.com/users/hongyuan1306/orgs","repos_url":"https://api.github.com/users/hongyuan1306/repos","events_url":"https://api.github.com/users/hongyuan1306/events{/privacy}","received_events_url":"https://api.github.com/users/hongyuan1306/received_events","type":"User","site_admin":false},"labels":[{"id":196521,"url":"https://api.github.com/repos/Pylons/pyramid/labels/docs","name":"docs","color":"e102d8","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-03-07T03:49:51Z","updated_at":"2018-04-17T00:14:10Z","closed_at":"2018-04-17T00:14:10Z","author_association":"CONTRIBUTOR","body":"The doc of `SignedCookieSessionFactory` in pyramid.session says:\r\n\r\n```\r\n    ``secret``\r\n      A string which is used to sign the cookie. The secret should be at\r\n      least as long as the block size of the selected hash algorithm. For\r\n      ``sha512`` this would mean a 128 bit (64 character) secret.  It should\r\n      be unique within the set of secret values provided to Pyramid for\r\n      its various subsystems (see :ref:`admonishment_against_secret_sharing`).\r\n```\r\n\r\nShouldn't it be 512 bit (64 characters)??\r\n","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3233","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3233/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3233/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3233/events","html_url":"https://github.com/Pylons/pyramid/issues/3233","id":300150292,"number":3233,"title":"Sphinx build fails for sphinxcontrib.autoprogram","user":{"login":"stevepiercy","id":102112,"avatar_url":"https://avatars1.githubusercontent.com/u/102112?v=4","gravatar_id":"","url":"https://api.github.com/users/stevepiercy","html_url":"https://github.com/stevepiercy","followers_url":"https://api.github.com/users/stevepiercy/followers","following_url":"https://api.github.com/users/stevepiercy/following{/other_user}","gists_url":"https://api.github.com/users/stevepiercy/gists{/gist_id}","starred_url":"https://api.github.com/users/stevepiercy/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/stevepiercy/subscriptions","organizations_url":"https://api.github.com/users/stevepiercy/orgs","repos_url":"https://api.github.com/users/stevepiercy/repos","events_url":"https://api.github.com/users/stevepiercy/events{/privacy}","received_events_url":"https://api.github.com/users/stevepiercy/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-02-26T08:42:48Z","updated_at":"2018-02-27T20:28:48Z","closed_at":"2018-02-27T20:28:47Z","author_association":"OWNER","body":"sphinx error: Could not import extension sphinxcontrib.autoprogram (exception: cannot import name 'Directive')\r\n\r\nSee SO post:\r\nhttps://stackoverflow.com/questions/48892261/sphinx-no-module-named-compat\r\n\r\nAnd open PR:\r\nhttps://github.com/sphinx-contrib/autoprogram/pull/2\r\n\r\nNew release should be out soon.","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3232","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3232/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3232/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3232/events","html_url":"https://github.com/Pylons/pyramid/issues/3232","id":297630898,"number":3232,"title":"chameleon: semi misleading template error messages","user":{"login":"castilma","id":17392981,"avatar_url":"https://avatars3.githubusercontent.com/u/17392981?v=4","gravatar_id":"","url":"https://api.github.com/users/castilma","html_url":"https://github.com/castilma","followers_url":"https://api.github.com/users/castilma/followers","following_url":"https://api.github.com/users/castilma/following{/other_user}","gists_url":"https://api.github.com/users/castilma/gists{/gist_id}","starred_url":"https://api.github.com/users/castilma/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/castilma/subscriptions","organizations_url":"https://api.github.com/users/castilma/orgs","repos_url":"https://api.github.com/users/castilma/repos","events_url":"https://api.github.com/users/castilma/events{/privacy}","received_events_url":"https://api.github.com/users/castilma/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-02-15T23:13:28Z","updated_at":"2018-02-16T12:34:23Z","closed_at":"2018-02-16T12:34:23Z","author_association":"NONE","body":"I'm not sure if this is the right place for this.\r\n\r\nif you run the attached server and visit localhost:8080/myroute/foo, you get a template error:\r\n```\r\nwill now serve on port  8080\r\nTraceback (most recent call last):\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/tweens.py\", line 12, in _error_handler\r\n    response = request.invoke_exception_view(exc_info)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/view.py\", line 756, in invoke_exception_view\r\n    raise HTTPNotFound\r\npyramid.httpexceptions.HTTPNotFound: The resource could not be found.\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/usr/lib/python3.5/wsgiref/handlers.py\", line 137, in run\r\n    self.result = application(self.environ, self.start_response)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/router.py\", line 270, in __call__\r\n    response = self.execution_policy(environ, self)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/router.py\", line 278, in default_execution_policy\r\n    return request.invoke_exception_view(reraise=True)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/view.py\", line 755, in invoke_exception_view\r\n    reraise_(*exc_info)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/compat.py\", line 148, in reraise\r\n    raise value\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/router.py\", line 276, in default_execution_policy\r\n    return router.invoke_request(request)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/router.py\", line 249, in invoke_request\r\n    response = handle_request(request)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/tweens.py\", line 41, in excview_tween\r\n    response = _error_handler(request, exc)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/tweens.py\", line 16, in _error_handler\r\n    reraise(*exc_info)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/compat.py\", line 148, in reraise\r\n    raise value\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/tweens.py\", line 39, in excview_tween\r\n    response = handler(request)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/router.py\", line 156, in handle_request\r\n    view_name\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/view.py\", line 642, in _call_view\r\n    response = view_callable(context, request)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/viewderivers.py\", line 462, in rendered_view\r\n    request, result, view_inst, context)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/renderers.py\", line 435, in render_view\r\n    return self.render_to_response(response, system, request=request)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/renderers.py\", line 458, in render_to_response\r\n    result = self.render(value, system_values, request=request)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid/renderers.py\", line 454, in render\r\n    result = renderer(value, system_values)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/pyramid_chameleon/zpt.py\", line 47, in __call__\r\n    result = self.template(**system)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/chameleon/template.py\", line 124, in __call__\r\n    return self.render(**kwargs)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/chameleon/zpt/template.py\", line 297, in render\r\n    return super(PageTemplate, self).render(**_kw)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/chameleon/template.py\", line 191, in render\r\n    raise_with_traceback(exc, tb)\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/chameleon/utils.py\", line 75, in raise_with_traceback\r\n    raise exc\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/chameleon/template.py\", line 171, in render\r\n    self._render(stream, econtext, rcontext)\r\n  File \"index_161d98e17b5a3f24d86304929b34b0af.py\", line 200, in render\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/chameleon/zpt/template.py\", line 301, in include\r\n    self._render(*args, **kwargs)\r\n  File \"base_9068126ef4690e8b4198d76bc88e1dfb.py\", line 305, in render\r\n  File \"index_161d98e17b5a3f24d86304929b34b0af.py\", line 136, in __fill_content\r\n  File \"/home/pi/.local/lib/python3.5/site-packages/chameleon/utils.py\", line 406, in __getitem__\r\n    raise NameError(key)\r\nNameError: undecl_name\r\n\r\n - Expression: \"pair[0]\"\r\n - Filename:   /home/pi/code/pathbug/project/templates/base.pt\r\n - Location:   (line 14: col 75)\r\n - Source:     ... oute/${pair[1]}\" tal:content=\"pair[0]\" /></li>\r\n                                                 ^^^^^^^\r\n - Expression: \"load: base.pt\"\r\n - Filename:   /home/pi/code/pathbug/project/templates/index.pt\r\n - Location:   (line 1: col 23)\r\n - Source:     <metal:main use-macro=\"load: base.pt\">\r\n                                      ^^^^^^^^^^^^^\r\n - Arguments:  get_csrf_token: <partial - at 0x75deab70>\r\n               content: some spec content\r\n               request: <Request - at 0x75dd4b90>\r\n               repeat: {...} (0)\r\n               current_spec: sec\r\n               view: <function art_desc at 0x75dd38e8>\r\n               target_language: <NoneType - at 0x3e5788>\r\n               macroname: load: base.pt\r\n               context: <DefaultRootFactory None at 0x75dd4bb0>\r\n               renderer_name: templates/index.pt\r\n               renderer_info: <RendererHelper - at 0x75dd4e50>\r\n               req: <Request - at 0x75dd4b90>\r\n               tuples: <list - at 0x75e47328>\r\n192.168.178.5 - - [16/Feb/2018 00:07:10] \"GET /myroute/sec HTTP/1.1\" 500 59\r\n```\r\nthe problem is the 'undecl_name' in the file `templates/index.pt`. The NameError mentions that, but the following info is misleading. It looks like the error is in base.pt in t
8000
he expression pair[0]. but that is not the case!\r\n\r\nI think you only need chameleon, waitress and pyramid to run this project.\r\n[bad_err.tar.gz](https://github.com/Pylons/pyramid/files/1729692/bad_err.tar.gz)\r\n","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3231","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3231/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3231/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3231/events","html_url":"https://github.com/Pylons/pyramid/issues/3231","id":297202707,"number":3231,"title":"p.security.remember() raises a TypeError ","user":{"login":"rmeno","id":34033243,"avatar_url":"https://avatars3.githubusercontent.com/u/34033243?v=4","gravatar_id":"","url":"https://api.github.com/users/rmeno","html_url":"https://github.com/rmeno","followers_url":"https://api.github.com/users/rmeno/followers","following_url":"https://api.github.com/users/rmeno/following{/other_user}","gists_url":"https://api.github.com/users/rmeno/gists{/gist_id}","starred_url":"https://api.github.com/users/rmeno/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/rmeno/subscriptions","organizations_url":"https://api.github.com/users/rmeno/orgs","repos_url":"https://api.github.com/users/rmeno/repos","events_url":"https://api.github.com/users/rmeno/events{/privacy}","received_events_url":"https://api.github.com/users/rmeno/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-02-14T18:41:58Z","updated_at":"2018-02-26T01:48:51Z","closed_at":"2018-02-26T01:48:51Z","author_association":"NONE","body":"Ref: #1530 \r\n\r\nHello,\r\nI get the same error as the one referenced above if I pass a str or int to remember(). Code and full traceback below. Ideas/suggestions? Thanks in advance.\r\n\r\n```\r\n    @view_config(\r\n        route_name='login',\r\n        renderer='myproj:templates/auth/login.jinja2',\r\n    )\r\n    def login(self):\r\n        message = ''\r\n        email = ''\r\n        self.log.info(self.request.method)\r\n        if self.request.method == 'POST' and 'form.submitted' in self.request.POST:\r\n            email = self.request.POST['email']\r\n            password = self.request.POST['password']\r\n            user = self.request.dbsession.query(User).filter_by(email=email).first()\r\n            self.log.info('login_POST.user: {0} : {1}'.format(user, type(user)))\r\n            if user is not None and user.check_password(password):\r\n                user_id = user.user_id\r\n                self.log.info(\r\n                    'login_POST.userid: {0}, type: {1}'.format(user_id, type(user_id)))\r\n                next_url = self.request.route_url('home')\r\n                self.log.info('login_POST.next_url: {0}'.format(next_url,))\r\n                headers = remember(self.request, user.user_id)\r\n                return HTTPFound(location=next_url, headers=headers)\r\n            else:\r\n                message = 'Failed login'\r\n        \r\n\r\n        return dict(\r\n            message=message,\r\n            url=self.request.route_url('login'),\r\n            email=email,\r\n        )\r\n\r\n```\r\n\r\n\r\n```\r\n2018-02-14 13:25:22,547 INFO  [views.auth:46][waitress] login_POST.userid: 5, type: <class 'int'>\r\n2018-02-14 13:25:22,547 INFO  [views.auth:48][waitress] login_POST.next_url: http://localhost:6543/\r\n2018-02-14 13:25:22,548 INFO  [sqlalchemy.engine.base.Engine:702][waitress] ROLLBACK\r\n2018-02-14 13:25:22,550 ERROR [pyramid_debugtoolbar:267][waitress] Uncaught Exception at http://localhost:6543/login\r\ntraceback url: http://localhost:6543/_debug_toolbar/313430373134353837373135343536/exception\r\nTraceback (most recent call last):\r\n  File \"/lib/python3.5/site-packages/pyramid/tweens.py\", line 12, in _error_handler\r\n    response = request.invoke_exception_view(exc_info)\r\n  File \"/lib/python3.5/site-packages/pyramid/view.py\", line 756, in invoke_exception_view\r\n    raise HTTPNotFound\r\npyramid.httpexceptions.HTTPNotFound: The resource could not be found.\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/lib/python3.5/site-packages/pyramid_debugtoolbar/toolbar.py\", line 247, in toolbar_tween\r\n    response = _handler(request)\r\n  File \"/lib/python3.5/site-packages/pyramid_debugtoolbar/panels/performance.py\", line 58, in resource_timer_handler\r\n    result = handler(request)\r\n  File \"/lib/python3.5/site-packages/pyramid_tm/__init__.py\", line 171, in tm_tween\r\n    reraise(*exc_info)\r\n  File \"lib/python3.5/site-packages/pyramid_tm/compat.py\", line 36, in reraise\r\n    raise value\r\n  File \"lib/python3.5/site-packages/pyramid_tm/__init__.py\", line 136, in tm_tween\r\n    response = handler(request)\r\n  File \"/lib/python3.5/site-packages/pyramid/tweens.py\", line 41, in excview_tween\r\n    response = _error_handler(request, exc)\r\n  File \"/lib/python3.5/site-packages/pyramid/tweens.py\", line 16, in _error_handler\r\n    reraise(*exc_info)\r\n  File \"/lib/python3.5/site-packages/pyramid/compat.py\", line 148, in reraise\r\n    raise value\r\n  File \"/lib/python3.5/site-packages/pyramid/tweens.py\", line 39, in excview_tween\r\n    response = handler(request)\r\n  File \"/lib/python3.5/site-packages/pyramid/router.py\", line 156, in handle_request\r\n    view_name\r\n  File \"/lib/python3.5/site-packages/pyramid/view.py\", line 642, in _call_view\r\n    response = view_callable(context, request)\r\n  File \"/lib/python3.5/site-packages/pyramid/viewderivers.py\", line 439, in rendered_view\r\n    result = view(context, request)\r\n  File \"/lib/python3.5/site-packages/pyramid/viewderivers.py\", line 124, in _class_requestonly_view\r\n    response = getattr(inst, attr)()\r\n  File \"/views/auth.py\", line 49, in login\r\n    headers = remember(self.request, user.user_id)\r\n  File \"/lib/python3.5/site-packages/pyramid/security.py\", line 167, in remember\r\n    return policy.remember(request, userid, **kw)\r\n  File \"/lib/python3.5/site-packages/pyramid/authentication.py\", line 621, in remember\r\n    return self.cookie.remember(request, userid, **kw)\r\n  File \"/lib/python3.5/site-packages/pyramid/authentication.py\", line 992, in remember\r\n    cookie_value = ticket.cookie_value()\r\n  File \"/lib/python3.5/site-packages/pyramid/authentication.py\", line 676, in cookie_value\r\n    v = '%s%08x%s!' % (self.digest(), int(self.time),\r\n  File \"lib/python3.5/site-packages/pyramid/authentication.py\", line 673, in digest\r\n    self.user_data, self.hashalg)\r\n  File \"/lib/python3.5/site-packages/pyramid/authentication.py\", line 752, in calculate_digest\r\n    tokens + b'\\0' + user_data)\r\nTypeError: can't concat bytes to list\r\n```","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3230","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3230/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3230/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3230/events","html_url":"https://github.com/Pylons/pyramid/issues/3230","id":296376092,"number":3230,"title":"zodbpickle build error when creating a new project","user":{"login":"TWry","id":2758765,"avatar_url":"https://avatars2.githubusercontent.com/u/2758765?v=4","gravatar_id":"","url":"https://api.github.com/users/TWry","html_url":"https://github.com/TWry","followers_url":"https://api.github.com/users/TWry/followers","following_url":"https://api.github.com/users/TWry/following{/other_user}","gists_url":"https://api.github.com/users/TWry/gists{/gist_id}","starred_url":"https://api.github.com/users/TWry/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/TWry/subscriptions","organizations_url":"https://api.github.com/users/TWry/orgs","repos_url":"https://api.github.com/users/TWry/repos","events_url":"https://api.github.com/users/TWry/events{/privacy}","received_events_url":"https://api.github.com/users/TWry/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-02-12T13:34:08Z","updated_at":"2018-02-12T21:50:21Z","closed_at":"2018-02-12T17:04:49Z","author_association":"NONE","body":"I already posted an issue for ZODB but I'm not sure if this gets attention. Feel free to close or delete this one if it is inappropriate.\r\n\r\nWhen installing pyramid, I'm getting the following error: \r\n\r\n```\r\nBuilding wheels for collected packages: zodbpickle\r\n  Running setup.py bdist_wheel for zodbpickle ... error\r\n  Complete output from command /Users/twry/development/t1/env/bin/python -u -c \"import setuptools, tokenize;__file__='/private/var/folders/1z/g4q5gcbn4q39hktz7y24n7wr0000gp/T/pip-build-dX1rA4/zodbpickle/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" bdist_wheel -d /var/folders/1z/g4q5gcbn4q39hktz7y24n7wr0000gp/T/tmpo_RNB8pip-wheel- --python-tag cp27:\r\n  running bdist_wheel\r\n  running build\r\n  running build_py\r\n  creating build\r\n  creating build/lib.macosx-10.13-intel-2.7\r\n  creating build/lib.macosx-10.13-intel-2.7/zodbpickle\r\n  copying src/zodbpickle/slowpickle.py -> build/lib.macosx-10.13-intel-2.7/zodbpickle\r\n  copying src/zodbpickle/fastpickle.py -> build/lib.macosx-10.13-intel-2.7/zodbpickle\r\n  copying src/zodbpickle/pickle_2.py -> build/lib.macosx-10.13-intel-2.7/zodbpickle\r\n  copying src/zodbpickle/__init__.py -> build/lib.macosx-10.13-intel-2.7/zodbpickle\r\n  copying src/zodbpickle/pickle_3.py -> build/lib.macosx-10.13-intel-2.7/zodbpickle\r\n  copying src/zodbpickle/pickle.py -> build/lib.macosx-10.13-intel-2.7/zodbpickle\r\n  copying src/zodbpickle/pickletools_2.py -> build/lib.macosx-10.13-intel-2.7/zodbpickle\r\n  copying src/zodbpickle/pickletools_3.py -> build/lib.macosx-10.13-intel-2.7/zodbpickle\r\n  creating build/lib.macosx-10.13-intel-2.7/zodbpickle/tests\r\n  copying src/zodbpickle/tests/pickletester_2.py -> build/lib.macosx-10.13-intel-2.7/zodbpickle/tests\r\n  copying src/zodbpickle/tests/test_pickle_2.py -> build/lib.macosx-10.13-intel-2.7/zodbpickle/tests\r\n  copying src/zodbpickle/tests/test_pickle_3.py -> build/lib.macosx-10.13-intel-2.7/zodbpickle/tests\r\n  copying src/zodbpickle/tests/pickletester_3.py -> build/lib.macosx-10.13-intel-2.7/zodbpickle/tests\r\n  copying src/zodbpickle/tests/test_pickle.py -> build/lib.macosx-10.13-intel-2.7/zodbpickle/tests\r\n  copying src/zodbpickle/tests/__init__.py -> build/lib.macosx-10.13-intel-2.7/zodbpickle/tests\r\n  running egg_info\r\n  writing requirements to src/zodbpickle.egg-info/requires.txt\r\n  writing src/zodbpickle.egg-info/PKG-INFO\r\n  writing top-level names to src/zodbpickle.egg-info/top_level.txt\r\n  writing dependency_links to src/zodbpickle.egg-info/dependency_links.txt\r\n  reading manifest file 'src/zodbpickle.egg-info/SOURCES.txt'\r\n  reading manifest template 'MANIFEST.in'\r\n  warning: no previously-included files matching '*.dll' found anywhere in distribution\r\n  warning: no previously-included files matching '*.pyc' found anywhere in distribution\r\n  warning: no previously-included files matching '*.pyo' found anywhere in distribution\r\n  warning: no previously-included files matching '*.so' found anywhere in distribution\r\n  writing manifest file 'src/zodbpickle.egg-info/SOURCES.txt'\r\n  copying src/zodbpickle/_pickle_27.c -> build/lib.macosx-10.13-intel-2.7/zodbpickle\r\n  copying src/zodbpickle/_pickle_33.c -> build/lib.macosx-10.13-intel-2.7/zodbpickle\r\n  running build_ext\r\n  building 'zodbpickle._pickle' extension\r\n  creating build/temp.macosx-10.13-intel-2.7\r\n  creating build/temp.macosx-10.13-intel-2.7/src\r\n  creating build/temp.macosx-10.13-intel-2.7/src/zodbpickle\r\n  cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/zodbpickle/_pickle_27.c -o build/temp.macosx-10.13-intel-2.7/src/zodbpickle/_pickle_27.o\r\n  In file included from src/zodbpickle/_pickle_27.c:1:\r\n  In file included from /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/Python.h:42:\r\n  In file included from /usr/include/stdlib.h:65:\r\n  In file included from /usr/include/sys/wait.h:110:\r\n  In file included from /usr/include/sys/resource.h:72:\r\n  In file included from /usr/local/include/stdint.h:59:\r\n[this line repeating many times]\r\n  In file included from /usr/local/include/stdint.h:59:\r\n  /usr/local/include/stdint.h:2:10: error: #include nested too deeply\r\n  #include <stddef.h>\r\n           ^\r\n  /usr/local/include/stdint.h:59:11: error: #include nested too deeply\r\n  # include <stdint.h>\r\n            ^\r\n  /usr/local/include/stdint.h:72:11: error: #include nested too deeply\r\n  # include <sys/types.h>\r\n            ^\r\n  /usr/local/include/stdint.h:76:10: error: #include nested too deeply\r\n  #include <limits.h>\r\n           ^\r\n  /usr/local/include/stdint.h:82:11: error: #include nested too deeply\r\n  # include <inttypes.h>\r\n            ^\r\n  In file included from src/zodbpickle/_pickle_27.c:1:\r\n  In file included from /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/Python.h:42:\r\n  In file included from /usr/include/stdlib.h:65:\r\n  In file included from /usr/include/sys/wait.h:110:\r\n  /usr/include/sys/resource.h:197:2: error: unknown type name 'uint64_t'\r\n          uint64_t ri_user_time;\r\n          ^\r\n  /usr/include/sys/resource.h:198:2: error: unknown type name 'uint64_t'\r\n          uint64_t ri_system_time;\r\n          ^\r\n  /usr/include/sys/resource.h:199:2: error: unknown type name 'uint64_t'\r\n          uint64_t ri_pkg_idle_wkups;\r\n          ^\r\n  /usr/include/sys/resource.h:200:2: error: unknown type name 'uint64_t'\r\n          uint64_t ri_interrupt_wkups;\r\n          ^\r\n  /usr/include/sys/resource.h:201:2: error: unknown type name 'uint64_t'\r\n          uint64_t ri_pageins;\r\n          ^\r\n  /usr/include/sys/resource.h:202:2: error: unknown type name 'uint64_t'\r\n          uint64_t ri_wired_size;\r\n          ^\r\n  /usr/include/sys/resource.h:203:2: error: unknown type name 'uint64_t'\r\n          uint64_t ri_resident_size;\r\n          ^\r\n  /usr/include/sys/resource.h:204:2: error: unknown type name 'uint64_t'\r\n          uint64_t ri_phys_footprint;\r\n          ^\r\n  /usr/include/sys/resource.h:205:2: error: unknown type name 'uint64_t'\r\n          uint64_t ri_proc_start_abstime;\r\n          ^\r\n  /usr/include/sys/resource.h:206:2: error: unknown type name 'uint64_t'\r\n          uint64_t ri_proc_exit_abstime;\r\n          ^\r\n  /usr/include/sys/resource.h:211:2: error: unknown type name 'uint64_t'\r\n          uint64_t ri_user_time;\r\n          ^\r\n  /usr/include/sys/resource.h:212:2: error: unknown type name 'uint64_t'\r\n          uint64_t ri_system_time;\r\n          ^\r\n  /usr/include/sys/resource.h:213:2: error: unknown type name 'uint64_t'\r\n          uint64_t ri_pkg_idle_wkups;\r\n          ^\r\n  /usr/include/sys/resource.h:214:2: error: unknown type name 'uint64_t'\r\n          uint64_t ri_interrupt_wkups;\r\n          ^\r\n  fatal error: too many errors emitted, stopping now [-ferror-limit=]\r\n  20 errors generated.\r\n  error: command 'cc' failed with exit status 1\r\n```\r\n\r\nVersions:\r\n- OS: MacOS 10.3.3\r\n- Python Versions:\r\n> Python 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin\r\n> Python 3.6.4 (default, Jan  6 2018, 11:51:59) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin\r\n- Compiler: \r\n> Apple LLVM version 9.0.0 (clang-900.0.39.2)\r\n> Target: x86_64-apple-darwin17.4.0\r\n> Thread model: posix\r\n> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin\r\n\r\nThis does happen on Python 2.7 and 3.6, system and virtualenv. \r\n\r\nAny pointers, please?","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3229","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3229/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3229/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3229/events","html_url":"https://github.com/Pylons/pyramid/issues/3229","id":294862416,"number":3229,"title":"pyramid.request.route_url docs incorrect, request query not passed if _query omitted","user":{"login":"arteedecco","id":969468,"avatar_url":"https://avatars3.githubusercontent.com/u/969468?v=4","gravatar_id":"","url":"https://api.github.com/users/arteedecco","html_url":"https://github.com/arteedecco","followers_url":"https://api.github.com/users/arteedecco/followers","following_url":"https://api.github.com/users/arteedecco/following{/other_user}","gists_url":"https://api.github.com/users/arteedecco/gists{/gist_id}","starred_url":"https://api.github.com/users/arteedecco/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/arteedecco/subscriptions","organizations_url":"https://api.github.com/users/arteedecco/orgs","repos_url":"https://api.github.com/users/arteedecco/repos","events_url":"https://api.github.com/users/arteedecco/events{/privacy}","received_events_url":"https://api.github.com/users/arteedecco/received_events","type":"User","site_admin":false},"labels":[{"id":196521,"url":"https://api.github.com/repos/Pylons/pyramid/labels/docs","name":"docs","color":"e102d8","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-02-06T18:19:17Z","updated_at":"2018-04-20T02:50:49Z","closed_at":"2018-04-20T02:50:49Z","author_association":"NONE","body":"RE: documentation on `Request.route_url` for handling query string\r\nhttps://docs.pylonsproject.org/projects/pyramid/en/latest/api/request.html#pyramid.request.Request.route_url\r\n\r\nDiscussed with @raydeo who confirmed issue in #pyramid IRC on (Tues Feb 6, 2018 around 12p Central US).\r\n\r\n`route_url` docs state, \"If no `_query` keyword argument is provided, the request query string will be returned in the URL.\"\r\n\r\nThat is not correct. If `_query` is omitted, no query is added to generated URL.\r\n\r\nNeed to check and see if it was ever correct and this functionality is broken, or if this was just never correct (or possibly intended but never implemented).\r\n\r\nBackground is that I was running through the v1.9.1 [Quick Tutorial for Pyramid, 10: Handling Web Requests and Responses](https://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/request_response.html)\r\n\r\nIt has you do a redirect using exception handling via `HTTPFound`, but the query string is stripped in the redirect.\r\n\r\nI wanted to learn more about how to redirect but in a more useful sense where the query and anchor are maintained, so more like what a user would expect in a true 302.\r\n\r\nAt the bottom of the tutorial it has the Extra Credit section and lists some links to further documentation, including [Request and Response Objects](https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/webob.html#webob-chapter).\r\n\r\nI followed and then took it one step deeper to the `pyramid.request` API documentation linked from [that page](https://docs.pylonsproject.org/projects/pyramid/en/latest/api/request.html#request-module).\r\n\r\nFurther recommendations are to update the documentation for `query_string` parameter of [pyramid.request](https://docs.pylonsproject.org/projects/pyramid/en/latest/api/request.html#pyramid.request.Request.query_string) that tells us what kind of data structure is returned (quoted string, determined by empirically).\r\n\r\nI would also recommend updating the documentation for the `route_url` to include a recommended approach for passing the `request` query string. It seems the best way would be via something like @raydeo suggested:\r\n`request.route_url(..., _query=request.GET.items())`\r\n\r\nI had found that `_query=self.request.query_string` worked, but @raydo pointed out that this could present issues because as mentioned previously `query_string` is just a quoted string and not properly urlencoded.","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3228","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3228/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3228/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3228/events","html_url":"https://github.com/Pylons/pyramid/issues/3228","id":294732201,"number":3228,"title":"Wish: issue a warning when some Traversal path is matched against a static view","user":{"login":"silenius","id":1225348,"avatar_url":"https://avatars2.githubusercontent.com/u/1225348?v=4","gravatar_id":"","url":"https://api.github.com/users/silenius","html_url":"https://github.com/silenius","followers_url":"https://api.github.com/users/silenius/followers","following_url":"https://api.github.com/users/silenius/following{/other_user}","gists_url":"https://api.github.com/users/silenius/gists{/gist_id}","starred_url":"https://api.github.com/users/silenius/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/silenius/subscriptions","organizations_url":"https://api.github.com/users/silenius/orgs","repos_url":"https://api.github.com/users/silenius/repos","events_url":"https://api.github.com/users/silenius/events{/privacy}","received_events_url":"https://api.github.com/users/silenius/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-02-06T11:54:00Z","updated_at":"2018-02-06T16:40:03Z","closed_at":"2018-02-06T16:40:03Z","author_association":"CONTRIBUTOR","body":"While extending a Pyramid app I accidentally used the same name for a Traversal path and a static view (which gave strange results), as in the following code:\r\n\r\n```python\r\n~/code/projects/amnesiabbpf/ more amnesiabbpf/__init__.py \r\n# -*- coding: utf-8 -*-\r\n\r\nfrom pyramid.config import Configurator\r\nfrom amnesia.resources import Resource\r\nfrom amnesia.resources import get_root\r\nfrom amnesiabbpf.phc import PHCResource\r\n\r\nclass BBPFRoot(Resource):\r\n\r\n    __name__ = ''\r\n    __parent__ = None\r\n\r\n    def __getitem__(self, path):\r\n        if path == 'phc':\r\n            return PHCResource(self.request, self)\r\n        return get_root(self.request)\r\n\r\ndef bbpf_root(request):\r\n    return BBPFRoot(request)\r\n\r\ndef main(global_config, **settings):\r\n    config = Configurator(settings=settings, root_factory=bbpf_root)\r\n    config.include('amnesia')\r\n    config.include('amnesiabbpf.widgets')\r\n    config.include('amnesiabbpf.views')\r\n    config.include('amnesiabbpf.phc')\r\n    config.add_static_view(name='static', path='amnesiabbpf:static/')\r\n    config.override_asset(\r\n        to_override='amnesia:templates/',\r\n        override_with='amnesiabbpf:templates/'\r\n    )\r\n\r\n    return config.make_wsgi_app()\r\n```\r\n\r\n```python\r\n~/code/projects/amnesiabbpf/amnesiabbpf/phc/ more __init__.py \r\n# -*- coding: utf-8 -*-\r\n\r\nfrom .resources import PHCResource\r\n\r\ndef includeme(config):\r\n    config.include('.views')\r\n    config.add_static_view(name='phc', path='amnesiabbpf:phc/templates')\r\n```\r\n\r\n```python\r\n~/code/projects/amnesiabbpf/amnesiabbpf/phc/ more resources.py \r\n# -*- coding: utf-8 -*-\r\n\r\nfrom amnesia.resources import Resource\r\n\r\nclass PHCResource(Resource):\r\n\r\n    __name__ = 'phc'\r\n\r\n    def __init__(self, request, parent=None):\r\n        super().__init__(request)\r\n        self.parent = parent\r\n    \r\n    @property\r\n    def __parent__(self):\r\n        return self.parent if self.parent else self.request.root\r\n```\r\nIn such case, the context was:\r\n * /phc => PHCResource\r\n * /phc/ => BBPFRoot\r\n * /phc/somepath => BBPFRoot\r\n\r\nIt would maybe be good if Pyramid could emit a warning in such case 😃 ","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3227","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3227/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3227/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3227/events","html_url":"https://github.com/Pylons/pyramid/issues/3227","id":293979134,"number":3227,"title":"Traversal returns factory when match name is single period","user":{"login":"di","id":294415,"avatar_url":"https://avatars1.githubusercontent.com/u/294415?v=4","gravatar_id":"","url":"https://api.github.com/users/di","html_url":"https://github.com/di","followers_url":"https://api.github.com/users/di/followers","following_url":"https://api.github.com/users/di/following{/other_user}","gists_url":"https://api.github.com/users/di/gists{/gist_id}","starred_url":"https://api.github.com/users/di/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/di/subscriptions","organizations_url":"https://api.github.com/users/di/orgs","repos_url":"https://api.github.com/users/di/repos","events_url":"https://api.github.com/users/di/events{/privacy}","received_events_url":"https://api.github.com/users/di/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-02-02T18:21:38Z","updated_at":"2018-02-02T23:17:06Z","closed_at":"2018-02-02T23:17:06Z","author_association":"CONTRIBUTOR","body":"With `pyramid==1.9.1` and the following example:\r\n\r\n```python\r\nfrom waitress import serve\r\nfrom pyramid.config import Configurator\r\nfrom pyramid.response import Response\r\n\r\nclass Factory:\r\n    def __init__(self, request):\r\n        pass\r\n\r\n    def __getitem__(self, thing):\r\n        return thing\r\n\r\nwith Configurator() as config:\r\n    config.add_route(\r\n        'traverse',\r\n        '/{thing}/',\r\n        traverse=\"/{thing}\",\r\n        factory=Factory\r\n    )\r\n    config.add_view(\r\n        lambda thing, request: Response(str(thing)),\r\n        route_name='traverse'\r\n    )\r\n    app = config.make_wsgi_app()\r\n\r\nserve(app, host='0.0.0.0', port=6543)\r\n```\r\n\r\nAnd the following requests:\r\n```python\r\n>>> import requests\r\n>>> requests.get('http://localhost:6543/foo/').text\r\n'foo'\r\n>>> requests.get('http://localhost:6543/./').text\r\n'<__main__.Factory object at 0x1088c81d0>'\r\n```\r\n\r\nI think I would have expected the second request to 404 because the path is equivalent to `http://localhost:6543/`, but perhaps I'm missing something here?\r\n\r\nIf this is truly a bug I'd be happy to work on it.","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3220","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3220/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3220/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3220/events","html_url":"https://github.com/Pylons/pyramid/issues/3220","id":289334209,"number":3220,"title":"Pyramid 1.8.x and 1.9.x installs release candidate version of WebOb","user":{"login":"hyperknot","id":494223,"avatar_url":"https://avatars2.githubusercontent.com/u/494223?v=4","gravatar_id":"","url":"https://api.github.com/users/hyperknot","html_url":"https://github.com/hyperknot","followers_url":"https://api.github.com/users/hyperknot/followers","following_url":"https://api.github.com/users/hyperknot/following{/other_user}","gists_url":"https://api.github.com/users/hyperknot/gists{/gist_id}","starred_url":"https://api.github.com/users/hyperknot/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/hyperknot/subscriptions","organizations_url":"https://api.github.com/users/hyperknot/orgs","repos_url":"https://api.github.com/users/hyperknot/repos","events_url":"https://api.github.com/users/hyperknot/events{/privacy}","received_events_url":"https://api.github.com/users/hyperknot/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":14,"created_at":"2018-01-17T16:43:05Z","updated_at":"2018-04-24T16:35:03Z","closed_at":"2018-04-06T01:55:59Z","author_association":"CONTRIBUTOR","body":"Since WebOb 1.8.0rc1 is released, Pyramid 1.8 and 1.9 versions install a the rc version of WebOb, instead of the latest stable 1.7.4.\r\n\r\n**1.7**\r\n```\r\npip install 'pyramid < 1.8'\r\nCollecting WebOb>=1.3.1 (from pyramid<1.8)\r\n  Using cached WebOb-1.7.4-py2.py3-none-any.whl\r\n```\r\n\r\n**1.8**\r\n```\r\npip install 'pyramid < 1.9'\r\nCollecting WebOb>=1.7.0rc2 (from pyramid<1.9)\r\n  Using cached WebOb-1.8.0rc1-py2.py3-none-any.whl\r\n```\r\n\r\n**1.9**\r\n```\r\npip install 'pyramid' \r\nCollecting WebOb>=1.7.0rc2 (from pyramid)\r\n  Using cached WebOb-1.8.0rc1-py2.py3-none-any.whl\r\n```\r\n\r\nThis behaviour is exactly the same with pip-tools / pip-compile.\r\n\r\nA simple `pip install webob` installs the stable 1.7.4.\r\n\r\nIs this a bug in pip?\r\n\r\n","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3219","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3219/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3219/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3219/events","html_url":"https://github.com/Pylons/pyramid/issues/3219","id":288711634,"number":3219,"title":"NoTransaction error when using bootstrap in script","user":{"login":"viraptor","id":188063,"avatar_url":"https://avatars1.githubusercontent.com/u/188063?v=4","gravatar_id":"","url":"https://api.github.com/users/viraptor","html_url":"https://github.com/viraptor","followers_url":"https://api.github.com/users/viraptor/followers","following_url":"https://api.github.com/users/viraptor/following{/other_user}","gists_url":"https://api.github.com/users/viraptor/gists{/gist_id}","starred_url":"https://api.github.com/users/viraptor/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/viraptor/subscriptions","organizations_url":"https://api.github.com/users/viraptor/orgs","repos_url":"https://api.github.com/users/viraptor/repos","events_url":"https://api.github.com/users/viraptor/events{/privacy}","received_events_url":"https://api.github.com/users/viraptor/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-01-15T20:44:36Z","updated_at":"2018-01-15T22:31:13Z","closed_at":"2018-01-15T22:30:38Z","author_association":"NONE","body":"I'm trying to create a console script using bootstrap as explained in https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/commandline.html#writing-a-script\r\n\r\nI'm running into an issue with access to the database though. The basic expected use like:\r\n```\r\nwith bootstrap(sys.argv[1]) as env:\r\n    dbsession = env['request'].dbsession\r\n    with dbsession.begin_nested() as transaction:\r\n        res = dbsession.execute('''SELECT ...''')\r\n```\r\nThrows a `transaction.interfaces.NoTransaction`. I should probably do something better here, but the documentation doesn't really help me :( Could you add something about the db initialisation in this use case?","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3214","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/py
703e
ramid/issues/3214/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3214/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3214/events","html_url":"https://github.com/Pylons/pyramid/issues/3214","id":287928305,"number":3214,"title":"Pyramid documentation links broken","user":{"login":"chrismcmacken","id":445683,"avatar_url":"https://avatars2.githubusercontent.com/u/445683?v=4","gravatar_id":"","url":"https://api.github.com/users/chrismcmacken","html_url":"https://github.com/chrismcmacken","followers_url":"https://api.github.com/users/chrismcmacken/followers","following_url":"https://api.github.com/users/chrismcmacken/following{/other_user}","gists_url":"https://api.github.com/users/chrismcmacken/gists{/gist_id}","starred_url":"https://api.github.com/users/chrismcmacken/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/chrismcmacken/subscriptions","organizations_url":"https://api.github.com/users/chrismcmacken/orgs","repos_url":"https://api.github.com/users/chrismcmacken/repos","events_url":"https://api.github.com/users/chrismcmacken/events{/privacy}","received_events_url":"https://api.github.com/users/chrismcmacken/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-01-11T21:21:52Z","updated_at":"2018-01-11T21:44:29Z","closed_at":"2018-01-11T21:44:29Z","author_association":"NONE","body":"When looking through documentation many of the links seem to return broken pages. For example, on this page https://docs.pylonsproject.org/projects/pyramid/en/latest/ if you click on the Installing Pyramid documentation it links to https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/install.html#installing-chapter. Which doesn't load, it returns an empty page. ","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3211","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3211/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3211/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3211/events","html_url":"https://github.com/Pylons/pyramid/issues/3211","id":282692298,"number":3211,"title":"Security - Session - Support SameSite","user":{"login":"AvnerCohen","id":1297254,"avatar_url":"https://avatars2.githubusercontent.com/u/1297254?v=4","gravatar_id":"","url":"https://api.github.com/users/AvnerCohen","html_url":"https://github.com/AvnerCohen","followers_url":"https://api.github.com/users/AvnerCohen/followers","following_url":"https://api.github.com/users/AvnerCohen/following{/other_user}","gists_url":"https://api.github.com/users/AvnerCohen/gists{/gist_id}","starred_url":"https://api.github.com/users/AvnerCohen/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AvnerCohen/subscriptions","organizations_url":"https://api.github.com/users/AvnerCohen/orgs","repos_url":"https://api.github.com/users/AvnerCohen/repos","events_url":"https://api.github.com/users/AvnerCohen/events{/privacy}","received_events_url":"https://api.github.com/users/AvnerCohen/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2017-12-17T13:04:21Z","updated_at":"2018-02-26T02:24:27Z","closed_at":"2018-02-26T02:24:27Z","author_association":"NONE","body":"For a while now - There is a support SameSite cookie attribute - This should help reduce CSRF concerns:\r\nhttps://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie\r\nSee SameSite support:\r\nhttps://caniuse.com/#search=SameSite\r\n\r\nAre there plans to support that in the session module?\r\n","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3207","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3207/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3207/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3207/events","html_url":"https://github.com/Pylons/pyramid/issues/3207","id":278034593,"number":3207,"title":"NewResponse after exception: event.request.response is not event.response","user":{"login":"tjwudi","id":5257816,"avatar_url":"https://avatars0.githubusercontent.com/u/5257816?v=4","gravatar_id":"","url":"https://api.github.com/users/tjwudi","html_url":"https://github.com/tjwudi","followers_url":"https://api.github.com/users/tjwudi/followers","following_url":"https://api.github.com/users/tjwudi/following{/other_user}","gists_url":"https://api.github.com/users/tjwudi/gists{/gist_id}","starred_url":"https://api.github.com/users/tjwudi/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/tjwudi/subscriptions","organizations_url":"https://api.github.com/users/tjwudi/orgs","repos_url":"https://api.github.com/users/tjwudi/repos","events_url":"https://api.github.com/users/tjwudi/events{/privacy}","received_events_url":"https://api.github.com/users/tjwudi/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":5,"created_at":"2017-11-30T08:24:19Z","updated_at":"2018-02-21T07:10:36Z","closed_at":"2018-02-21T07:10:36Z","author_association":"CONTRIBUTOR","body":"When NewResponse event is fired, `event.request.response` is not `event.response`.\r\n\r\nSimple test code\r\n\r\n```py\r\nfrom wsgiref.simple_server import make_server\r\nfrom pyramid.config import Configurator\r\nimport pyramid.httpexceptions as exc\r\nfrom pyramid.events import NewResponse\r\n\r\ndef hello_404(request):\r\n    raise exc.HTTPNotFound()\r\n    return {}\r\n\r\ndef handle_event(event):\r\n    print(event.response is event.request.response)\r\n    print(event.response.status_code == event.request.response.status_code)\r\n\r\nif __name__ == '__main__':\r\n    config = Configurator()\r\n    config.add_route('404', '/404')\r\n    config.add_view(hello_404, renderer='json', route_name='404')\r\n    config.add_subscriber(handle_event, NewResponse)\r\n    app = config.make_wsgi_app()\r\n    server = make_server('0.0.0.0', 6543, app)\r\n    server.serve_forever()\r\n```\r\n\r\nBoth of the expressions in `print` statements yield `False`. **event.response turns out the be the correct response object because it has the correct response code.**\r\n\r\n```bash\r\n[pyramid-playground] $ python server.py \r\nFalse\r\nFalse\r\n```\r\n\r\nSeems to be related to #1633. I'm using pyramid 1.9.","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3206","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3206/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3206/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3206/events","html_url":"https://github.com/Pylons/pyramid/issues/3206","id":277813600,"number":3206,"title":"Q:  Why does the pyramid.request object have no `content_encoding` attribute ?","user":{"login":"jakubczaplicki","id":147901,"avatar_url":"https://avatars3.githubusercontent.com/u/147901?v=4","gravatar_id":"","url":"https://api.github.com/users/jakubczaplicki","html_url":"https://github.com/jakubczaplicki","followers_url":"https://api.github.com/users/jakubczaplicki/followers","following_url":"https://api.github.com/users/jakubczaplicki/following{/other_user}","gists_url":"https://api.github.com/users/jakubczaplicki/gists{/gist_id}","starred_url":"https://api.github.com/users/jakubczaplicki/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jakubczaplicki/subscriptions","organizations_url":"https://api.github.com/users/jakubczaplicki/orgs","repos_url":"https://api.github.com/users/jakubczaplicki/repos","events_url":"https://api.github.com/users/jakubczaplicki/events{/privacy}","received_events_url":"https://api.github.com/users/jakubczaplicki/received_events","type":"User","site_admin":false},"labels":[{"id":235821,"url":"https://api.github.com/repos/Pylons/pyramid/labels/question","name":"question","color":"ededed","default":true}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":13,"created_at":"2017-11-29T16:12:28Z","updated_at":"2017-11-30T19:06:44Z","closed_at":"2017-11-30T19:06:43Z","author_association":"NONE","body":"`Content-Encoding` as in https://tools.ietf.org/html/rfc2616#section-14.11","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3202","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3202/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3202/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3202/events","html_url":"https://github.com/Pylons/pyramid/issues/3202","id":274320632,"number":3202,"title":"add_request_method only accepts property descriptor that subclasses property","user":{"login":"tjwudi","id":5257816,"avatar_url":"https://avatars0.githubusercontent.com/u/5257816?v=4","gravatar_id":"","url":"https://api.github.com/users/tjwudi","html_url":"https://github.com/tjwudi","followers_url":"https://api.github.com/users/tjwudi/followers","following_url":"https://api.github.com/users/tjwudi/following{/other_user}","gists_url":"https://api.github.com/users/tjwudi/gists{/gist_id}","starred_url":"https://api.github.com/users/tjwudi/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/tjwudi/subscriptions","organizations_url":"https://api.github.com/users/tjwudi/orgs","repos_url":"https://api.github.com/users/tjwudi/repos","events_url":"https://api.github.com/users/tjwudi/events{/privacy}","received_events_url":"https://api.github.com/users/tjwudi/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2017-11-15T22:03:43Z","updated_at":"2017-11-17T00:21:39Z","closed_at":"2017-11-16T22:56:52Z","author_association":"CONTRIBUTOR","body":"https://github.com/Pylons/pyramid/blob/cc6a6ed60260b0391aa38f372b26311d58edf0d6/pyramid/util.py#L70\r\n\r\nLooks like we check the type of a property descriptor by `isinstance(callable, property)`. This is not true for property descriptors subclasses from `object` which is pretty common. Maybe we should document this behavior [here](https://docs.pylonsproject.org/projects/pyramid/en/latest/api/config.html#pyramid.config.Configurator.add_request_method).\r\n","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3195","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3195/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3195/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3195/events","html_url":"https://github.com/Pylons/pyramid/issues/3195","id":269392234,"number":3195,"title":"wsgiserver has been moved to cheroot","user":{"login":"jardakotesovec","id":1590681,"avatar_url":"https://avatars3.githubusercontent.com/u/1590681?v=4","gravatar_id":"","url":"https://api.github.com/users/jardakotesovec","html_url":"https://github.com/jardakotesovec","followers_url":"https://api.github.com/users/jardakotesovec/followers","following_url":"https://api.github.com/users/jardakotesovec/following{/other_user}","gists_url":"https://api.github.com/users/jardakotesovec/gists{/gist_id}","starred_url":"https://api.github.com/users/jardakotesovec/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jardakotesovec/subscriptions","organizations_url":"https://api.github.com/users/jardakotesovec/orgs","repos_url":"https://api.github.com/users/jardakotesovec/repos","events_url":"https://api.github.com/users/jardakotesovec/events{/privacy}","received_events_url":"https://api.github.com/users/jardakotesovec/received_events","type":"User","site_admin":false},"labels":[{"id":51477784,"url":"https://api.github.com/repos/Pylons/pyramid/labels/sprintable","name":"sprintable","color":"fbca04","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2017-10-29T11:45:30Z","updated_at":"2018-04-17T03:44:55Z","closed_at":"2018-04-17T03:44:55Z","author_association":"NONE","body":"As explained here https://github.com/cherrypy/cherrypy/issues/1585  `wsgiserver ` has been moved to `cheroot`.\r\n\r\nTherefore importing in `https://github.com/Pylons/pyramid/blob/e78aa24cda85368c3507c145e1e604e7335778dc/pyramid/scripts/pserve.py#L344` should probably look like:\r\n\r\n```\r\ntry:\r\n    from cheroot.wsgi import Server as WSGIServer\r\nexcept ImportError:\r\n    from cherrypy.wsgiserver import CherryPyWSGIServer as WSGIServer \r\n```","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3191","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3191/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3191/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3191/events","html_url":"https://github.com/Pylons/pyramid/issues/3191","id":268151160,"number":3191,"title":"upgrade 1.8 -> 1.9 won't start.","user":{"login":"kgk","id":1790880,"avatar_url":"https://avatars3.githubusercontent.com/u/1790880?v=4","gravatar_id":"","url":"https://api.github.com/users/kgk","html_url":"https://github.com/kgk","followers_url":"https://api.github.com/users/kgk/followers","following_url":"https://api.github.com/users/kgk/following{/other_user}","gists_url":"https://api.github.com/users/kgk/gists{/gist_id}","starred_url":"https://api.github.com/users/kgk/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/kgk/subscriptions","organizations_url":"https://api.github.com/users/kgk/orgs","repos_url":"https://api.github.com/users/kgk/repos","events_url":"https://api.github.com/users/kgk/events{/privacy}","received_events_url":"https://api.github.com/users/kgk/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2017-10-24T19:08:58Z","updated_at":"2017-10-24T23:25:02Z","closed_at":"2017-10-24T21:21:30Z","author_association":"NONE","body":"We tend to use .cfg instead of .ini which used to work.  Is this broken on purpose ?\r\nRenaming cfg -> ini doesn't seem to have an effect.\r\n\r\nThanks,\r\nKris \r\n\r\n\r\n```\r\npserve -v config/h1_pserve.cfg \r\nTraceback (most recent call last):\r\n  File \"/home/kgk/Envs/bq06new/bin/pserve\", line 11, in <module>\r\n    sys.exit(main())\r\n  File \"/home/kgk/Envs/bq06new/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py\", line 32, in main\r\n    return command.run()\r\n  File \"/home/kgk/Envs/bq06new/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py\", line 167, in run\r\n    loader = self._get_config_loader(config_uri)\r\n  File \"/home/kgk/Envs/bq06new/local/lib/python2.7/site-packages/pyramid/scripts/common.py\", line 23, in get_config_loader\r\n    return plaster.get_loader(config_uri, protocols=['wsgi'])\r\n  File \"/home/kgk/Envs/bq06new/local/lib/python2.7/site-packages/plaster/loaders.py\", line 109, in get_loader\r\n    raise LoaderNotFound(requested_scheme, protocols=protocols)\r\nplaster.exceptions.LoaderNotFound: Could not find a matching loader for the scheme \"file+cfg\", protocol \"wsgi\".\r\n\r\n```","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3176","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3176/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3176/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3176/events","html_url":"https://github.com/Pylons/pyramid/issues/3176","id":262559920,"number":3176,"title":"trypyramid.com typo","user":{"login":"gomezhyuuga","id":1633839,"avatar_url":"https://avatars2.githubusercontent.com/u/1633839?v=4","gravatar_id":"","url":"https://api.github.com/users/gomezhyuuga","html_url":"https://github.com/gomezhyuuga","followers_url":"https://api.github.com/users/gomezhyuuga/followers","following_url":"https://api.github.com/users/gomezhyuuga/following{/other_user}","gists_url":"https://api.github.com/users/gomezhyuuga/gists{/gist_id}","starred_url":"https://api.github.com/users/gomezhyuuga/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/gomezhyuuga/subscriptions","organizations_url":"https://api.github.com/users/gomezhyuuga/orgs","repos_url":"https://api.github.com/users/gomezhyuuga/repos","events_url":"https://api.github.com/users/gomezhyuuga/events{/privacy}","received_events_url":"https://api.github.com/users/gomezhyuuga/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2017-10-03T19:41:09Z","updated_at":"2017-10-03T20:02:35Z","closed_at":"2017-10-03T20:02:35Z","author_association":"NONE","body":"In the website https://trypyramid.com/, at the part of *Pyramid Features*:\r\n> [...] curl or a browser to request http://0.0.0.0:8080\r\n\r\nShouldn't the port be `6543` ?","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3170","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3170/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3170/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3170/events","html_url":"https://github.com/Pylons/pyramid/issues/3170","id":258867800,"number":3170,"title":"CSRF Setup with beaker","user":{"login":"AvnerCohen","id":1297254,"avatar_url":"https://avatars2.githubusercontent.com/u/1297254?v=4","gravatar_id":"","url":"https://api.github.com/users/AvnerCohen","html_url":"https://github.com/AvnerCohen","followers_url":"https://api.github.com/users/AvnerCohen/followers","following_url":"https://api.github.com/users/AvnerCohen/following{/other_user}","gists_url":"https://api.github.com/users/AvnerCohen/gists{/gist_id}","starred_url":"https://api.github.com/users/AvnerCohen/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AvnerCohen/subscriptions","organizations_url":"https://api.github.com/users/AvnerCohen/orgs","repos_url":"https://api.github.com/users/AvnerCohen/repos","events_url":"https://api.github.com/users/AvnerCohen/events{/privacy}","received_events_url":"https://api.github.com/users/AvnerCohen/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":6,"created_at":"2017-09-19T15:39:04Z","updated_at":"2017-09-20T10:07:07Z","closed_at":"2017-09-19T16:30:02Z","author_association":"NONE","body":"Thanks for all the work Pyramid !\r\n\r\nI'm really confused about the setup to fully support CSRF in an app.\r\nFrom XHR to form hidden fields, session type cookie and beaker.\r\nI tried to find any reference I could find, but so far failed.\r\n\r\nI tried to follow the basic setup as per:\r\nhttps://docs.pylonsproject.org/projects/pyramid/en/latest/narr/security.html#checking-csrf-tokens-automatically\r\nBasically:\r\n```\r\n    config.set_default_csrf_options(require_csrf=True)\r\n```\r\nand than, in my mako template:\r\n```\r\n          <input type=\"hidden\" name=\"csrf_token\" value=\"${get_csrf_token()}\">\r\n```\r\nHowever, regardless of the setup I tested, I couldn't get this to work.\r\n\r\nI suspect there is some conflict when I setup:\r\n```\r\n    config.set_csrf_storage_policy(SessionCSRFStoragePolicy())    \r\n    config.include(\"pyramid_beaker\")\r\n```\r\nBecause I see crft token being setup here:\r\nhttps://github.com/Pylons/pyramid_beaker/blob/master/pyramid_beaker/__init__.py#L90\r\nBut also here:\r\nhttps://github.com/Pylons/pyramid/blob/master/pyramid/csrf.py#L80\r\n\r\nWhen I print out the tokens on each post, I see that when I try to manually run:\r\n```\r\nfrom pyramid.csrf import check_csrf_token\r\n\r\nprint \"GOT: %s\" % request.params.get('csrf_token')\r\nprint \"FROM SESSION: %s\" % request.session.get_csrf_token()\r\nprint \"Inside check %s\" % check_csrf_token(request)\r\n````\r\n\r\nThe form sends the token from SessionCSRFStoragePolicy, but get_csrf_token returns the one from pyramid_beaker (end as a result check_csrf_token fails with BadCSRFToken.\r\n\r\n\r\nAny thoughts?\r\nAny additional info I should be providing?\r\n\r\n\r\n\r\n\r\n\r\n\r\n","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3169","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3169/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3169/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3169/events","html_url":"https://github.com/Pylons/pyramid/issues/3169","id":258528965,"number":3169,"title":"pserve development.ini --reload: fails in windows 10 64bit","user":{"login":"mdaadil","id":1292758,"avatar_url":"https://avatars0.githubusercontent.com/u/1292758?v=4","gravatar_id":"","url":"https://api.github.com/users/mdaadil","html_url":"https://github.com/mdaadil","followers_url":"https://api.github.com/users/mdaadil/followers","following_url":"https://api.github.com/users/mdaadil/following{/other_user}","gists_url":"https://api.github.com/users/mdaadil/gists{/gist_id}","starred_url":"https://api.github.com/users/mdaadil/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/mdaadil/subscriptions","organizations_url":"https://api.github.com/users/mdaadil/orgs","repos_url":"https://api.github.com/users/mdaadil/repos","events_url":"https://api.github.com/users/mdaadil/events{/privacy}","received_events_url":"https://api.github.com/users/mdaadil/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2017-09-18T15:49:56Z","updated_at":"2017-09-18T20:05:51Z","closed_at":"2017-09-18T20:05:51Z","author_association":"NONE","body":"I am following [an article](http://www.brettdangerfield.com/post/creating_a_blog_with_pyramid_mongdb_bootstrap/) and creating my first project, \r\n\r\nwhile i try the below command the process gets into a loop and starts a server and kills it and again starts a server and kills and it keeps doing this continuously without breaking the loop and exiting.\r\n\r\npserve development.ini --reload\r\n\r\nBelow is the log\r\n//---------------------------------------------------------\r\nStarting monitor for PID 18084.\r\nTraceback (most recent call last):\r\n  File \"<string>\", line 1, in <module>\r\n  File \"D:\\Others\\Python\\myBlog\\lib\\site-packages\\hupper\\ipc.py\", line 322, in spawn_main\r\n    func(**kwargs)\r\n  File \"D:\\Others\\Python\\myBlog\\lib\\site-packages\\hupper\\worker.py\", line 237, in worker_main\r\n    func(*spec_args, **spec_kwargs)\r\n  File \"D:\\Others\\Python\\myBlog\\lib\\site-packages\\pyramid\\scripts\\pserve.py\", line 32, in main\r\n    return command.run()\r\n  File \"D:\\Others\\Python\\myBlog\\lib\\site-packages\\pyramid\\scripts\\pserve.py\", line 229, in run\r\n    app = loader.get_wsgi_app(app_name, config_vars)\r\n  File \"D:\\Others\\Python\\myBlog\\lib\\site-packages\\plaster_pastedeploy\\__init__.py\", line 131, in get_wsgi_app\r\n    global_conf=defaults)\r\n  File \"d:\\others\\python\\myblog\\lib\\site-packages\\paste\\deploy\\loadwsgi.py\", line 247, in loadapp\r\n    return loadobj(APP, uri, name=name, **kw)\r\n  File \"d:\\others\\python\\myblog\\lib\\site-packages\\paste\\deploy\\loadwsgi.py\", line 271, in loadobj\r\n    global_conf=global_conf)\r\n  File \"d:\\others\\python\\myblog\\lib\\site-packages\\paste\\deploy\\loadwsgi.py\", line 296, in loadcontext\r\n    global_conf=global_conf)\r\n  File \"d:\\others\\python\\myblog\\lib\\site-packages\\paste\\deploy\\loadwsgi.py\", line 320, in _loadconfig\r\n    return loader.get_context(object_type, name, global_conf)\r\n  File \"d:\\others\\python\\myblog\\lib\\site-packages\\paste\\deploy\\loadwsgi.py\", line 450, in get_context\r\n    global_additions=global_additions)\r\n  File \"d:\\others\\python\\myblog\\lib\\site-packages\\paste\\deploy\\loadwsgi.py\", line 562, in _pipeline_app_context\r\n    for name in pipeline[:-1]]\r\n  File \"d:\\others\\python\\myblog\\lib\\site-packages\\paste\\deploy\\loadwsgi.py\", line 562, in <listcomp>\r\n    for name in pipeline[:-1]]\r\n  File \"d:\\others\\python\\myblog\\lib\\site-packages\\paste\\deploy\\loadwsgi.py\", line 406, in get_context\r\n    global_conf=global_conf)\r\n  File \"d:\\others\\python\\myblog\\lib\\site-packages\\paste\\deploy\\loadwsgi.py\", line 296, in loadcontext\r\n    global_conf=global_conf)\r\n  File \"d:\\others\\python\\myblog\\lib\\site-packages\\paste\\deploy\\loadwsgi.py\", line 328, in _loadegg\r\n    return loader.get_context(object_type, name, global_conf)\r\n  File \"d:\\others\\python\\myblog\\lib\\site-packages\\paste\\deploy\\loadwsgi.py\", line 620, in get_context\r\n    object_type, name=name)\r\n  File \"d:\\others\\python\\myblog\\lib\\site-packages\\paste\\deploy\\loadwsgi.py\", line 646, in find_egg_entry_point\r\n    possible.append((entry.load(), protocol, entry.name))\r\n  File \"D:\\Others\\Python\\myBlog\\lib\\site-packages\\pkg_resources\\__init__.py\", line 2405, in load\r\n    return self.resolve()\r\n  File \"D:\\Others\\Python\\myBlog\\lib\\site-packages\\pkg_resources\\__init__.py\", line 2411, in resolve\r\n    module = __import__(self.module_name, fromlist=['__name__'], level=0)\r\n  File \"D:\\Others\\Python\\myBlog\\lib\\site-packages\\weberror-0.13.1-py3.6.egg\\weberror\\evalexception.py\", line 127\r\n    except ValueError, ve:\r\n                     ^\r\nSyntaxError: invalid syntax\r\nKilling server with PID 18084.\r\nStarting monitor for PID 18600.\r\nTraceback (most recent call last):\r\n\r\n\r\n\r\n","score":1.0},{"url":"https://api.github.com/repos/Pylons/pyramid/issues/3167","repository_url":"https://api.github.com/repos/Pylons/pyramid","labels_url":"https://api.github.com/repos/Pylons/pyramid/issues/3167/labels{/name}","comments_url":"https://api.github.com/repos/Pylons/pyramid/issues/3167/comments","events_url":"https://api.github.com/repos/Pylons/pyramid/issues/3167/events","html_url":"https://github.com/Pylons/pyramid/issues/3167","id":256964585,"number":3167,"title":"create first pyramid application","user":{"login":"Rajanani044","id":31839716,"avatar_url":"https://avatars1.githubusercontent.com/u/31839716?v=4","gravatar_id":"","url":"https://api.github.com/users/Rajanani044","html_url":"https://github.com/Rajanani044","followers_url":"https://api.github.com/users/Rajanani044/followers","following_url":"https://api.github.com/users/Rajanani044/following{/other_user}","gists_url":"https://api.github.com/users/Rajanani044/gists{/gist_id}","starred_url":"https://api.github.com/users/Rajanani044/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Rajanani044/subscriptions","organizations_url":"https://api.github.com/users/Rajanani044/orgs","repos_url":"https://api.github.com/users/Rajanani044/repos","events_url":"https://api.github.com/users/Rajanani044/events{/privacy}","received_events_url":"https://api.github.com/users/Rajanani044/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2017-09-12T08:46:09Z","updated_at":"2017-09-15T15:16:48Z","closed_at":"2017-09-15T15:16:48Z","author_association":"NONE","body":"Hi,thanks for tutorial!\r\ncreate first pyramid application, i get following error in commad line\r\nc:>%VENV%/Scripts/python helloworld.py\r\nC:\\env/Scripts/python: can't open file 'helloworld.py':[Error 2] No such file or directory\r\n![screenshot_1](https://user-images.githubusercontent.com/31839716/30316451-e8cdd786-97c4-11e7-9954-f7481cfbaa43.png)\r\n","score":1.0}]}
0

