HTTP/1.1 200 OK
Transfer-Encoding: chunked
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Cache-Control: no-cache
Content-Security-Policy: default-src 'none'
Content-Type: application/json; charset=utf-8
Date: Sun, 13 May 2018 13:15:47 GMT
Link: <https://api.github.com/search/issues?q=repo%3Asymfony%2Fsymfony+type%3Aissue+state%3Aclosed&page=2>; rel="next", <https://api.github.com/search/issues?q=repo%3Asymfony%2Fsymfony+type%3Aissue+state%3Aclosed&page=34>; rel="last"
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Server: GitHub.com
Status: 200 OK
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Accepted-Oauth-Scopes: 
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Github-Media-Type: github.v3; format=json
X-Github-Request-Id: D256:4F42:44FD75E:8AFFF47:5AF83A82
X-Oauth-Scopes: 
X-Ratelimit-Limit: 30
X-Ratelimit-Remaining: 17
X-Ratelimit-Reset: 1526217397
X-Runtime-Rack: 0.457176
X-Xss-Protection: 1; mode=block

8000
{"total_count":9656,"incomplete_results":false,"items":[{"url":"https://api.github.com/repos/symfony/symfony/issues/27234","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27234/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27234/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27234/events","html_url":"https://github.com/symfony/symfony/issues/27234","id":322199217,"number":27234,"title":"Warning on cache:warmup with empty var/cache dir","user":{"login":"antonmedv","id":141232,"avatar_url":"https://avatars0.githubusercontent.com/u/141232?v=4","gravatar_id":"","url":"https://api.github.com/users/antonmedv","html_url":"https://github.com/antonmedv","followers_url":"https://api.github.com/users/antonmedv/followers","following_url":"https://api.github.com/users/antonmedv/following{/other_user}","gists_url":"https://api.github.com/users/antonmedv/gists{/gist_id}","starred_url":"https://api.github.com/users/antonmedv/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/antonmedv/subscriptions","organizations_url":"https://api.github.com/users/antonmedv/orgs","repos_url":"https://api.github.com/users/antonmedv/repos","events_url":"https://api.github.com/users/antonmedv/events{/privacy}","received_events_url":"https://api.github.com/users/antonmedv/received_events","type":"User","site_admin":false},"labels":[{"id":100079,"url":"https://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":131507,"url":"https://api.github.com/repos/symfony/symfony/labels/HttpKernel","name":"HttpKernel","color":"DDDDDD","default":false},{"id":237003792,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Needs%20Review","name":"Status: Needs Review","color":"ededed","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":5,"created_at":"2018-05-11T07:39:18Z","updated_at":"2018-05-13T11:53:11Z","closed_at":"2018-05-13T10:36:38Z","author_association":"NONE","body":"**Symfony version(s) affected**: 4.1.x\r\n\r\n**Description**  \r\nRunning  `bin/console cache:warmup` on empty cache dir triggers error reporting to rollbar, really annoying.\r\n\r\n**How to reproduce**  \r\n* Remove/or create empty `var/cache` dir\r\n* Run `bin/console cache:warmup`\r\n* **E_WARNING**\r\n  ```\r\n  include(/.../var/cache/prod/srcProdProjectContainer.php):: include(...): failed to open stream: No such file or directory\r\n  ```\r\n**Possible Solution**  \r\nDo NOT trigger **E_WARNING**.\r\n\r\n**Additional context**  \r\nhttps://github.com/symfony/symfony/blob/226e2f3949c5843b67826aca4839c2c6b95743cf/src/Symfony/Component/HttpKernel/Kernel.php#L531-L540\r\n","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27223","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27223/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27223/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27223/events","html_url":"https://github.com/symfony/symfony/issues/27223","id":321960534,"number":27223,"title":"unable to make select in formtype  symfony4","user":{"login":"valdanioDanio","id":38763412,"avatar_url":"https://avatars3.githubusercontent.com/u/38763412?v=4","gravatar_id":"","url":"https://api.github.com/users/valdanioDanio","html_url":"https://github.com/valdanioDanio","followers_url":"https://api.github.com/users/valdanioDanio/followers","following_url":"https://api.github.com/users/valdanioDanio/following{/other_user}","gists_url":"https://api.github.com/users/valdanioDanio/gists{/gist_id}","starred_url":"https://api.github.com/users/valdanioDanio/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/valdanioDanio/subscriptions","organizations_url":"https://api.github.com/users/valdanioDanio/orgs","repos_url":"https://api.github.com/users/valdanioDanio/repos","events_url":"https://api.github.com/users/valdanioDanio/events{/privacy}","received_events_url":"https://api.github.com/users/valdanioDanio/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-05-10T14:51:04Z","updated_at":"2018-05-10T16:10:59Z","closed_at":"2018-05-10T16:10:59Z","author_association":"NONE","body":"i am get this error: Type error: Return value of App\\Entity\\Estante::getDeposito() must be an instance of App\\Entity\\App\\Deposito, null returned\r\n\r\nthis my code:\r\n\r\npublic function buildForm(FormBuilderInterface $builder, array $options) {\r\n        $builder\r\n                ->add('numero', NumberType::class)\r\n                ->add('deposito', EntityType::class, array(\r\n                    'class' => Deposito::class,\r\n                    'choice_label' => 'numero',\r\n                ))\r\n        ;\r\n    }","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27219","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27219/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27219/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27219/events","html_url":"https://github.com/symfony/symfony/issues/27219","id":321900600,"number":27219,"title":"about symfony 3.4 autowring ","user":{"login":"lcp0578","id":10859621,"avatar_url":"https://avatars2.githubusercontent.com/u/10859621?v=4","gravatar_id":"","url":"https://api.github.com/users/lcp0578","html_url":"https://github.com/lcp0578","followers_url":"https://api.github.com/users/lcp0578/followers","following_url":"https://api.github.com/users/lcp0578/following{/other_user}","gists_url":"https://api.github.com/users/lcp0578/gists{/gist_id}","starred_url":"https://api.github.com/users/lcp0578/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/lcp0578/subscriptions","organizations_url":"https://api.github.com/users/lcp0578/orgs","repos_url":"https://api.github.com/users/lcp0578/repos","events_url":"https://api.github.com/users/lcp0578/events{/privacy}","received_events_url":"https://api.github.com/users/lcp0578/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-05-10T11:33:17Z","updated_at":"2018-05-10T12:01:25Z","closed_at":"2018-05-10T11:59:29Z","author_association":"NONE","body":"symfony 3.4.8\r\n```\r\nCannot autowire service \"ProblemBundle\\EntityManager\\ProblemManager\": argument \"$paginator\" of metho  \r\n  d \"__construct()\" references interface \"Knp\\Component\\Pager\\PaginatorInterface\" but no such service   \r\n  exists. Did you create a class that implements this interface?\r\n```\r\nProblemManager.php\r\n\r\n`public function (PaginatorInterface $page){}`\r\n\r\napp/config/services.yml\r\n\r\n```\r\n# Learn more about services, parameters and containers at\r\n# https://symfony.com/doc/current/service_container.html\r\nparameters:\r\n    #parameter_name: value\r\n\r\nservices:\r\n    # default configuration for services in *this* file\r\n    _defaults:\r\n        # automatically injects dependencies in your services\r\n        autowire: true\r\n        # automatically registers your services as commands, event subscribers, etc.\r\n        autoconfigure: true\r\n        # this means you cannot fetch services directly from the container via $container->get()\r\n        # if you need to do this, you can override this setting on individual services\r\n        public: true\r\n\r\n    # makes classes in src/AppBundle available to be used as services\r\n    # this creates a service per class whose id is the fully-qualified class name\r\n    # add more services, or override services that need manual wiring\r\n    # AppBundle\\Service\\ExampleService:\r\n    #     arguments:\r\n    #         $someArgument: 'some_value'\r\n\r\n\r\n    UserBundle\\Controller\\:\r\n        resource: '../../src/UserBundle/Controller'\r\n        public: true\r\n        autowire: true\r\n        tags: ['controller.service_arguments']\r\n\r\n    UserBundle\\EntityManager\\UserManager:\r\n        autowire: true\r\n\r\n    ProblemBundle\\EntityManager\\ProblemManager:\r\n        autowire: true\r\n        public: true\r\n\r\n\r\n```\r\nhow can i config for all to autowring(include third party bundle)?","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27218","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27218/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27218/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27218/events","html_url":"https://github.com/symfony/symfony/issues/27218","id":321850463,"number":27218,"title":"Unknown database type enum requested","user":{"login":"flik","id":900323,"avatar_url":"https://avatars3.githubusercontent.com/u/900323?v=4","gravatar_id":"","url":"https://api.github.com/users/flik","html_url":"https://github.com/flik","followers_url":"https://api.github.com/users/flik/followers","following_url":"https://api.github.com/users/flik/following{/other_user}","gists_url":"https://api.github.com/users/flik/gists{/gist_id}","starred_url":"https://api.github.com/users/flik/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/flik/subscriptions","organizations_url":"https://api.github.com/users/flik/orgs","repos_url":"https://api.github.com/users/flik/repos","events_url":"https://api.github.com/users/flik/events{/privacy}","received_events_url":"https://api.github.com/users/flik/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-05-10T08:24:56Z","updated_at":"2018-05-10T12:04:46Z","closed_at":"2018-05-10T12:04:46Z","author_association":"NONE","body":"\r\n\r\n**Symfony version(s) affected**: 3.4\r\n\r\n**Description**  \r\n php bin/console doctrine:schema:update --force\r\n\r\nUnknown database type enum requested, Doctrine\\DBAL\\Platforms\\MariaDb1027Pl\r\n atform may not support it.\r\n\r\n**How to reproduce**  \r\n php bin/console doctrine:schema:update --force\r\n\r\n**Possible Solution**  \r\nhttps://stackoverflow.com/questions/8312271/how-to-enable-enums-in-symfony-2-doctrine\r\n\r\n**Additional context**  \r\n<!-- Optional: any other context about the problem: log messages, screenshots, etc. -->\r\n","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27186","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27186/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27186/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27186/events","html_url":"https://github.com/symfony/symfony/issues/27186","id":320920419,"number":27186,"title":"[PropertyAccessor] What is the return value of getValue method if index does not exists ?","user":{"login":"nicolaspetitjean","id":11570379,"avatar_url":"https://avatars2.githubusercontent.com/u/11570379?v=4","gravatar_id":"","url":"https://api.github.com/users/nicolaspetitjean","html_url":"https://github.com/nicolaspetitjean","followers_url":"https://api.github.com/users/nicolaspetitjean/followers","following_url":"https://api.github.com/users/nicolaspetitjean/following{/other_user}","gists_url":"https://api.github.com/users/nicolaspetitjean/gists{/gist_id}","starred_url":"https://api.github.com/users/nicolaspetitjean/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/nicolaspetitjean/subscriptions","organizations_url":"https://api.github.com/users/nicolaspetitjean/orgs","repos_url":"https://api.github.com/users/nicolaspetitjean/repos","events_url":"https://api.github.com/users/nicolaspetitjean/events{/privacy}","received_events_url":"https://api.github.com/users/nicolaspetitjean/received_events","type":"User","site_admin":false},"labels":[{"id":28502152,"url":"https://api.github.com/repos/symfony/symfony/labels/PropertyAccess","name":"PropertyAccess","color":"DDDDDD","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-05-07T19:09:55Z","updated_at":"2018-05-08T06:40:45Z","closed_at":"2018-05-07T19:12:34Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      |no\r\n| Feature request? | no\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 4.0.8\r\n\r\nAccording to [symfony doc](https://symfony.com/doc/current/components/property_access.html) : \r\n> As you can see, the method will return null if the index does not exists.\r\n\r\nAccording to [api doc](https://api.symfony.com/master/Symfony/Component/PropertyAccess/PropertyAccessor.html):\r\n> AccessException | If a property/index does not exist or is not public\r\n\r\n\r\n\r\n","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27180","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27180/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27180/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27180/events","html_url":"https://github.com/symfony/symfony/issues/27180","id":320849218,"number":27180,"title":"dump() breaks web debug toolbar","user":{"login":"kbond","id":127811,"avatar_url":"https://avatars0.githubusercontent.com/u/127811?v=4","gravatar_id":"","url":"https://api.github.com/users/kbond","html_url":"https://github.com/kbond","followers_url":"https://api.github.com/users/kbond/followers","following_url":"https://api.github.com/users/kbond/following{/other_user}","gists_url":"https://api.github.com/users/kbond/gists{/gist_id}","starred_url":"https://api.github.com/users/kbond/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/kbond/subscriptions","organizations_url":"https://api.github.com/users/kbond/orgs","repos_url":"https://api.github.com/users/kbond/repos","events_url":"https://api.github.com/users/kbond/events{/privacy}","received_events_url":"https://api.github.com/users/kbond/received_events","type":"User","site_admin":false},"labels":[{"id":100079,"url":"https://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":237550465,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Reviewed","name":"Status: Reviewed","color":"bfe5bf","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":{"url":"https://api.github.com/repos/symfony/symfony/milestones/17","html_url":"https://github.com/symfony/symfony/milestone/17","labels_url":"https://api.github.com/repos/symfony/symfony/milestones/17/labels","id":2795131,"number":17,"title":"4.1","description":"https://symfony.com/roadmap?version=4.1#checker","creator":{"login":"nicolas-grekas","id":243674,"avatar_url":"https://avatars3.githubusercontent.com/u/243674?v=4","gravatar_id":"","url":"https://api.github.com/users/nicolas-grekas","html_url":"https://github.com/nicolas-grekas","followers_url":"https://api.github.com/users/nicolas-grekas/followers","following_url":"https://api.github.com/users/nicolas-grekas/following{/other_user}","gists_url":"https://api.github.com/users/nicolas-grekas/gists{/gist_id}","starred_url":"https://api.github.com/users/nicolas-grekas/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/nicolas-grekas/subscriptions","organizations_url":"https://api.github.com/users/nicolas-grekas/orgs","repos_url":"https://api.github.com/users/nicolas-grekas/repos","events_url":"https://api.github.com/users/nicolas-grekas/events{/privacy}","received_events_url":"https://api.github.com/users/nicolas-grekas/received_events","type":"User","site_admin":false},"open_issues":8,"closed_issues":421,"state":"open","created_at":"2017-09-26T15:40:00Z","updated_at":"2018-05-13T11:36:20Z","due_on":"2018-05-31T07:00:00Z","closed_at":null},"comments":3,"created_at":"2018-05-07T15:29:20Z","updated_at":"2018-05-09T06:14:37Z","closed_at":"2018-05-09T06:14:37Z","author_association":"CONTRIBUTOR","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 4.1\r\n\r\nWhen calling `dump('foo')` in my code, the web debug toolbar doesn't load and I get this error in my console:\r\n\r\n```\r\nUncaught ReferenceError: Sfdump is not defined\r\n    at eval (eval at load.maxTries ((index):1), <anonymous>:1:9)\r\n    at load.maxTries ((index):23)\r\n    at (index):23\r\n    at XMLHttpRequest.xhr.onreadystatechange ((index):23)\r\n```\r\n","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27173","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27173/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27173/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27173/events","html_url":"https://github.com/symfony/symfony/issues/27173","id":320705877,"number":27173,"title":"Labels in CheckboxType are not translated","user":{"login":"plecler","id":39046973,"avatar_url":"https://avatars1.githubusercontent.com/u/39046973?v=4","gravatar_id":"","url":"https://api.github.com/users/plecler","html_url":"https://github.com/plecler","followers_url":"https://api.github.com/users/plecler/followers","following_url":"https://api.github.com/users/plecler/following{/other_user}","gists_url":"https://api.github.com/users/plecler/gists{/gist_id}","starred_url":"https://api.github.com/users/plecler/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/plecler/subscriptions","organizations_url":"https://api.github.com/users/plecler/orgs","repos_url":"https://api.github.com/users/plecler/repos","events_url":"https://api.github.com/users/plecler/events{/privacy}","received_events_url":"https://api.github.com/users/plecler/received_events","type":"User","site_admin":false},"labels":[{"id":100079,"url":"https://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":99594,"url":"https://api.github.com/repos/symfony/symfony/labels/Form","name":"Form","color":"DDDDDD","default":false},{"id":237003792,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Needs%20Review","name":"Status: Needs Review","color":"ededed","default":false},{"id":520300257,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Waiting%20feedback","name":"Status: Waiting feedback","color":"fef2c0","default":false},{"id":337187802,"url":"https://api.github.com/repos/symfony/symfony/labels/TwigBridge","name":"TwigBridge","color":"dddddd","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-05-07T07:45:13Z","updated_at":"2018-05-07T10:49:03Z","closed_at":"2018-05-07T10:49:03Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 3.4.8\r\n\r\nThe label in a CheckboxType are not translated:\r\n\r\n```\r\n    public function buildForm(FormBuilderInterface $builder, array $options)\r\n    {\r\n        $builder->add('available',\r\n                                \"Symfony\\Component\\Form\\Extension\\Core\\Type\\CheckboxType\",\r\n                                array('label' => 'form.label.available'));\r\n    }\r\n```\r\n```\r\n# messages.fr.yml\r\n\"form.label.available\": \"Disponible\"\r\n```\r\nThe label displayed in the form view is _form.label.available_.\r\n\r\nIf I replace _Symfony\\Component\\Form\\Extension\\Core\\Type\\CheckboxType_ by _Symfony\\Component\\Form\\Extension\\Core\\Type\\TextType_, it is OK. The label displayed is _Disponible_","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27169","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27169/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27169/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27169/events","html_url":"https://github.com/symfony/symfony/issues/27169","id":320575518,"number":27169,"title":"No mapping file found for Doctrine embedded class?","user":{"login":"BonBonSlick","id":12422720,"avatar_url":"https://avatars2.githubusercontent.com/u/12422720?v=4","gravatar_id":"","url":"https://api.github.com/users/BonBonSlick","html_url":"https://github.com/BonBonSlick","followers_url":"https://api.github.com/users/BonBonSlick/followers","following_url":"https://api.github.com/users/BonBonSlick/following{/other_user}","gists_url":"https://api.github.com/users/BonBonSlick/gists{/gist_id}","starred_url":"https://api.github.com/users/BonBonSlick/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/BonBonSlick/subscriptions","organizations_url":"https://api.github.com/users/BonBonSlick/orgs","repos_url":"https://api.github.com/users/BonBonSlick/repos","events_url":"https://api.github.com/users/BonBonSlick/events{/privacy}","received_events_url":"https://api.github.com/users/BonBonSlick/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-05-06T09:04:08Z","updated_at":"2018-05-06T17:21:35Z","closed_at":"2018-05-06T17:21:35Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | no\r\n| Feature request? | yes (docs improvement)\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 4.0.9\r\n\r\n\r\n**User.orm.xml**\r\n```\r\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n<doctrine-mapping xmlns=\"http://doctrine-project.org/schemas/orm/doctrine-mapping\"\r\n                  xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\r\n                  xsi:schemaLocation=\"http://doctrine-project.org/schemas/orm/doctrine-mapping\r\n                   https://raw.github.com/doctrine/doctrine2/master/doctrine-mapping.xsd\">\r\n\r\n    <entity name=\"App\\Domain\\User\\Entity\\User\">\r\n        <embedded name=\"uuid\" class=\"App\\Domain\\User\\ValueObject\\UserId\"/>\r\n\r\n    </entity>\r\n\r\n    <embeddable name=\"UserId\">\r\n        <id name=\"uuid\"\r\n            type=\"guid\"\r\n            length=\"100\"\r\n            column=\"uuid\">\r\n            <generator strategy=\"NONE\"/>\r\n        </id>\r\n    </embeddable>\r\n</doctrine-mapping>\r\n\r\n```\r\n\r\n**Error**\r\n```\r\nphp bin/console doctrine:mapping:info\r\n\r\n Found 2 mapped entities:\r\n\r\nIn MappingException.php line 75:\r\n                                                                                                \r\n  No mapping file found named 'UserId.orm.xml' for class 'App\\Entity\\User\\ValueObject\\UserId'.\r\n```\r\nOf course, because it is embedded\r\n\r\n\r\nUser docs\r\nhttps://symfony.com/doc/2.1/cookbook/doctrine/reverse_engineering.html\r\nhttps://symfony.com/doc/current/doctrine/associations.html\r\nhttps://www.doctrine-project.org/projects/doctrine-orm/en/2.6/tutorials/embeddables.html\r\n\r\nIs symfony ORM support embedded in xml??? Or i am doing something wrong?","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27166","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27166/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27166/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27166/events","html_url":"https://github.com/symfony/symfony/issues/27166","id":320494745,"number":27166,"title":"[ERROR] The database schema is not in sync with the current mapping file.","user":{"login":"MikSDigital","id":1351612,"avatar_url":"https://avatars2.githubusercontent.com/u/1351612?v=4","gravatar_id":"","url":"https://api.github.com/users/MikSDigital","html_url":"https://github.com/MikSDigital","followers_url":"https://api.github.com/users/MikSDigital/followers","following_url":"https://api.github.com/users/MikSDigital/following{/other_user}","gists_url":"https://api.github.com/users/MikSDigital/gists{/gist_id}","starred_url":"https://api.github.com/users/MikSDigital/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/MikSDigital/subscriptions","organizations_url":"https://api.github.com/users/MikSDigital/orgs","repos_url":"https://api.github.com/users/MikSDigital/repos","events_url":"https://api.github.com/users/MikSDigital/events{/privacy}","received_events_url":"https://api.github.com/users/MikSDigital/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-05-05T09:33:27Z","updated_at":"2018-05-06T09:49:47Z","closed_at":"2018-05-06T00:16:49Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 4.0.9\r\n\r\n```\r\n[ERROR] The database schema is not in sync with the current mapping file.\r\n```\r\nWhen using ```@ORM\\Column(type=\"string\", nullable=true)``` Doctrine annotation there is still error \r\nafter executing ```php bin/console doctrine:schema:validate``` console command.\r\n\r\nTested with databases: SQLite, MariaDB.\r\n\r\nBut in the application itself all queries are working fine.\r\n\r\nIf ```nullable=true``` is not using, then schema validation runs without error.\r\nAlso if using ```@ORM\\Column(type=\"text\", nullable=true)``` (type=TEXT) there is no validation error.\r\n","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27161","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27161/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27161/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27161/events","html_url":"https://github.com/symfony/symfony/issues/27161","id":320425120,"number":27161,"title":"isXmlHttpRequest dont work with jQuery ajax requests.","user":{"login":"marceloxp","id":2043045,"avatar_url":"https://avatars3.githubusercontent.com/u/2043045?v=4","gravatar_id":"","url":"https://api.github.com/users/marceloxp","html_url":"https://github.com/marceloxp","followers_url":"https://api.github.com/users/marceloxp/followers","following_url":"https://api.github.com/users/marceloxp/following{/other_user}","gists_url":"https://api.github.com/users/marceloxp/gists{/gist_id}","starred_url":"https://api.github.com/users/marceloxp/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/marceloxp/subscriptions","organizations_url":"https://api.github.com/users/marceloxp/orgs","repos_url":"https://api.github.com/users/marceloxp/repos","events_url":"https://api.github.com/users/marceloxp/events{/privacy}","received_events_url":"https://api.github.com/users/marceloxp/received_events","type":"User","site_admin":false},"labels":[{"id":100378,"url":"https://api.github.com/repos/symfony/symfony/labels/Feature","name":"Feature","color":"02e10c","default":false},{"id":125366,"url":"https://api.github.com/repos/symfony/symfony/labels/HttpFoundation","name":"HttpFoundation","color":"DDDDDD","default":false},{"id":520300257,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Waiting%20feedback","name":"Status: Waiting feedback","color":"fef2c0","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":5,"created_at":"2018-05-04T20:49:58Z","updated_at":"2018-05-07T17:00:06Z","closed_at":"2018-05-07T17:00:06Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | no\r\n| Feature request? | yes\r\n| Symfony version  | 3.4.6\r\n\r\nThe function `isXmlHttpRequest` on `symfony\\http-foundation\\Request.php` uses only one parameter to return if request is an Ajax.\r\nA simlpe jQuery ajax returns false unless add *X-Requested-With* on header.\r\n\r\nsee: <https://bugs.jquery.com/ticket/2356>\r\n```plain\r\nChanged 10 anos ago by flesler\r\nEstado:\tnew -> closed\r\nResolução: -> invalid\r\nScript and json requests just can't have X-Requested-With (XMLHttpRequest) and adding that would be a lie :)\r\n```\r\n\r\n> To call an API as a json request, the header *X-Requested-With* is not sent.\r\n\r\n```php\r\n    public function isXmlHttpRequest()\r\n    {\r\n        return 'XMLHttpRequest' == $this->headers->get('X-Requested-With');\r\n    }\r\n```\r\nsee: <https://benjaminlistwon.com/blog/adding-more-robust-ajax-detection-in-laravel/>\r\n\r\nThis function is used on Laravel 5.5:  `laravel\\framework\\src\\Illuminate\\Http\\Request.php`\r\n\r\n```php\r\n    class Request extends SymfonyRequest implements Arrayable, ArrayAccess\r\n\r\n    ...\r\n\r\n    /**\r\n     * Determine if the request is the result of an AJAX call.\r\n     *\r\n     * @return bool\r\n     */\r\n    public function ajax()\r\n    {\r\n        return $this->isXmlHttpRequest();\r\n    }\r\n```\r\n\r\nThanks ;)","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27154","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27154/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27154/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27154/events","html_url":"https://github.com/symfony/symfony/issues/27154","id":320265565,"number":27154,"title":"Script cache:clear returned with error code 1","user":{"login":"lperry65","id":281669,"avatar_url":"https://avatars2.githubusercontent.com/u/281669?v=4","gravatar_id":"","url":"https://api.github.com/users/lperry65","html_url":"https://github.com/lperry65","followers_url":"https://api.github.com/users/lperry65/followers","following_url":"https://api.github.com/users/lperry65/following{/other_user}","gists_url":"https://api.github.com/users/lperry65/gists{/gist_id}","starred_url":"https://api.github.com/users/lperry65/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/lperry65/subscriptions","organizations_url":"https://api.github.com/users/lperry65/orgs","repos_url":"https://api.github.com/users/lperry65/repos","events_url":"https://api.github.com/users/lperry65/events{/privacy}","received_events_url":"https://api.github.com/users/lperry65/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":5,"created_at":"2018-05-04T12:59:08Z","updated_at":"2018-05-11T15:46:04Z","closed_at":"2018-05-11T15:41:33Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| Symfony version  |  4.0.9 \r\n\r\n In Filesystem.php line 182:\r\n!!\r\n!!    Failed to remove directory \"/home/vagrant/Code/symfony/my-project/var/cache\r\n!!    /loca~/pools\": unlink(/home/vagrant/Code/symfony/my-project/var/cache/local\r\n!!    /ContainerLzydxqx.legacy): No such file or directory.\r\n!!\r\n","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27153","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27153/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27153/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27153/events","html_url":"https://github.com/symfony/symfony/iss
8000
ues/27153","id":320263300,"number":27153,"title":"Config component documentation ","user":{"login":"daaru00","id":8782994,"avatar_url":"https://avatars1.githubusercontent.com/u/8782994?v=4","gravatar_id":"","url":"https://api.github.com/users/daaru00","html_url":"https://github.com/daaru00","followers_url":"https://api.github.com/users/daaru00/followers","following_url":"https://api.github.com/users/daaru00/following{/other_user}","gists_url":"https://api.github.com/users/daaru00/gists{/gist_id}","starred_url":"https://api.github.com/users/daaru00/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/daaru00/subscriptions","organizations_url":"https://api.github.com/users/daaru00/orgs","repos_url":"https://api.github.com/users/daaru00/repos","events_url":"https://api.github.com/users/daaru00/events{/privacy}","received_events_url":"https://api.github.com/users/daaru00/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-05-04T12:51:40Z","updated_at":"2018-05-04T13:56:21Z","closed_at":"2018-05-04T13:56:21Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | no\r\n| Feature request? | yes\r\n| Symfony version  | 3.4.6\r\n\r\nHi,\r\n\r\nI'm searching for Config component's documentation about INI files parsing but I can't find it.\r\nThe [Symfony documentation](https://symfony.com/doc/current/components/config.html) page is empty expect a description:\r\n\r\n> The Config component provides several classes to help you find, load, combine, autofill and validate configuration values of any kind, whatever their source may be (YAML, XML, INI files, or for instance a database).\r\n\r\nThe [Github repository](https://github.com/symfony/config) readme has only the links for documentation page (the page described above).\r\n\r\nCan someone explain to me how to parse an INI file?\r\n\r\n------------------------------------------------------\r\nP.S.\r\nOf course there's [parse_ini_file](http://php.net/manual/en/function.parse-ini-file.php) function from \"vanilla\" PHP but I can't understand the Config component's description that mentions INI files.. \r\n\r\n","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27151","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27151/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27151/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27151/events","html_url":"https://github.com/symfony/symfony/issues/27151","id":320216410,"number":27151,"title":"[Yaml] Multiple blocks in same file are not merged","user":{"login":"metamaker","id":5102404,"avatar_url":"https://avatars1.githubusercontent.com/u/5102404?v=4","gravatar_id":"","url":"https://api.github.com/users/metamaker","html_url":"https://github.com/metamaker","followers_url":"https://api.github.com/users/metamaker/followers","following_url":"https://api.github.com/users/metamaker/following{/other_user}","gists_url":"https://api.github.com/users/metamaker/gists{/gist_id}","starred_url":"https://api.github.com/users/metamaker/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/metamaker/subscriptions","organizations_url":"https://api.github.com/users/metamaker/orgs","repos_url":"https://api.github.com/users/metamaker/repos","events_url":"https://api.github.com/users/metamaker/events{/privacy}","received_events_url":"https://api.github.com/users/metamaker/received_events","type":"User","site_admin":false},"labels":[{"id":100079,"url":"https://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":237003792,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Needs%20Review","name":"Status: Needs Review","color":"ededed","default":false},{"id":3536874,"url":"https://api.github.com/repos/symfony/symfony/labels/Yaml","name":"Yaml","color":"DDDDDD","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-05-04T09:57:10Z","updated_at":"2018-05-04T10:03:49Z","closed_at":"2018-05-04T10:00:29Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 3.4.8\r\n\r\nI expect that parsing\r\n\r\n```\r\nblocks:\r\n    foo:\r\n        key1: val1\r\n        key2: val2\r\n        \r\nblocks:\r\n    bar:\r\n        key1: val3\r\n        key2: val4\r\n```\r\n\r\nmust provide same array as parsing\r\n\r\n```\r\nblocks:\r\n    foo:\r\n        key1: val1\r\n        key2: val2\r\n\r\n    bar:\r\n        key1: val3\r\n        key2: val4\r\n```\r\n\r\nHowever, running unit test proves that Yaml parser only returns first `blocks` definition and **silently** ignores second part.\r\n\r\n```\r\n<?php\r\n\r\nnamespace Sio\\Configuration\\Tests\\Yaml;\r\n\r\nuse Symfony\\Component\\Yaml\\Yaml;\r\n\r\nclass YamlParserMultipleBlocksSameNameTest extends \\PHPUnit_Framework_TestCase\r\n{\r\n    private $fixtureMultipleBlocksSameName = <<<YAML\r\nblocks:\r\n    foo:\r\n        key1: val1\r\n        key2: val2\r\n        \r\nblocks:\r\n    bar:\r\n        key1: val3\r\n        key2: val4\r\nYAML;\r\n\r\n    public function test_multipleBlocksWithSameNameInYaml_ReturnsOnlyFirstBlock_correct()\r\n    {\r\n        $result = Yaml::parse($this->fixtureMultipleBlocksSameName);\r\n\r\n        $this->assertCount(1, $result['blocks']);\r\n        $this->assertEquals(['foo'], array_keys($result['blocks']));\r\n    }\r\n\r\n    public function test_multipleBlocksWithSameNameInYaml_ReturnsAllBlocks_failing()\r\n    {\r\n        $result = Yaml::parse($this->fixtureMultipleBlocksSameName);\r\n\r\n        $this->assertNotCount(2, $result['blocks']);\r\n        $this->assertNotEquals(['foo', 'bar'], array_keys($result['blocks']));\r\n    }\r\n}\r\n```","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27149","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27149/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27149/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27149/events","html_url":"https://github.com/symfony/symfony/issues/27149","id":320204015,"number":27149,"title":"Tag invalidation doesn't seem to work across requests anymore","user":{"login":"harmbandstra","id":9076844,"avatar_url":"https://avatars1.githubusercontent.com/u/9076844?v=4","gravatar_id":"","url":"https://api.github.com/users/harmbandstra","html_url":"https://github.com/harmbandstra","followers_url":"https://api.github.com/users/harmbandstra/followers","following_url":"https://api.github.com/users/harmbandstra/following{/other_user}","gists_url":"https://api.github.com/users/harmbandstra/gists{/gist_id}","starred_url":"https://api.github.com/users/harmbandstra/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/harmbandstra/subscriptions","organizations_url":"https://api.github.com/users/harmbandstra/orgs","repos_url":"https://api.github.com/users/harmbandstra/repos","events_url":"https://api.github.com/users/harmbandstra/events{/privacy}","received_events_url":"https://api.github.com/users/harmbandstra/received_events","type":"User","site_admin":false},"labels":[{"id":100079,"url":"https://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":313658463,"url":"https://api.github.com/repos/symfony/symfony/labels/Cache","name":"Cache","color":"dddddd","default":false},{"id":237003792,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Needs%20Review","name":"Status: Needs Review","color":"ededed","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-05-04T09:15:10Z","updated_at":"2018-05-04T09:26:06Z","closed_at":"2018-05-04T09:26:06Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 4.0.9\r\n\r\nThere was a change in the TagAwareAdapter from version 4.0.8 to 4.0.9 which seems to break the tag invalidation. I included a unit test which runs fine with version 4.0.8 of the cache component but breaks with version 4.0.9.\r\n\r\nExpected behavior (this is how it works in 4.0.8)\r\n- Get cache key \"item1\" (isHit == false)\r\n- Write a cache key \"item1\" with \"tag1\"\r\n- Get cache key (isHit == true)\r\n- Invalidate tag \"tag1\"\r\n- Get cache key (isHit == false)\r\n- Now get the key in a new request, simulated by `$tagAwareAdapter2 = new TagAwareAdapter`), and get will result in a isHit == false.\r\n\r\nActual behavior (right now in 4.0.9)\r\n- Get cache key \"item1\" (isHit == false)\r\n- Write a cache key \"item1\" with \"tag1\"\r\n- Get cache key (isHit == true)\r\n- Invalidate tag \"tag1\"\r\n- Get cache key (isHit == false)\r\n- Now get the key in a new request, simulated by `$tagAwareAdapter2 = new TagAwareAdapter`), and get will result in a isHit == true.\r\n\r\nYou can use this unit test to reproduce\r\n\r\n```\r\n<?php\r\n\r\nnamespace App\\Tests;\r\n\r\nuse Symfony\\Bundle\\FrameworkBundle\\Test\\KernelTestCase;\r\nuse Symfony\\Component\\Cache\\Adapter\\FilesystemAdapter;\r\nuse Symfony\\Component\\Cache\\Adapter\\TagAwareAdapter;\r\n\r\nclass TagCacheTest extends KernelTestCase\r\n{\r\n    const ITEM = 'item1';\r\n    const TAG = 'tag1';\r\n\r\n    public function testInvalidateTags()\r\n    {\r\n        $tagAwareAdapter1 = new TagAwareAdapter(new FilesystemAdapter('', 0));\r\n        $tagAwareAdapter1->clear();\r\n\r\n        $cacheItem1 = $tagAwareAdapter1->getItem(self::ITEM);\r\n        $this->assertFalse($cacheItem1->isHit(), 'Item should not have been hit (1)');\r\n\r\n        $cacheItem1->tag([self::TAG]);\r\n        $cacheItem1->set('this is the value of [' . self::ITEM . ']');\r\n\r\n        $saved = $tagAwareAdapter1->save($cacheItem1);\r\n        $this->assertTrue($saved);\r\n\r\n        $cacheItem2 = $tagAwareAdapter1->getItem(self::ITEM);\r\n        $this->assertTrue($cacheItem2->isHit(), 'Item should have been hit');\r\n\r\n        $success = $tagAwareAdapter1->invalidateTags([self::TAG]);\r\n        $this->assertTrue($success);\r\n\r\n        $cacheItem3 = $tagAwareAdapter1->getItem(self::ITEM);\r\n        $this->assertFalse($cacheItem3->isHit(), 'Item should not have been hit (2)');\r\n\r\n        $tagAwareAdapter2 = new TagAwareAdapter(new FilesystemAdapter('', 0));\r\n        $cacheItem4 = $tagAwareAdapter2->getItem(self::ITEM);\r\n        $this->assertFalse($cacheItem4->isHit(), 'Item should not have been hit (3)');\r\n    }\r\n}\r\n```\r\n\r\n","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27148","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27148/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27148/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27148/events","html_url":"https://github.com/symfony/symfony/issues/27148","id":320203437,"number":27148,"title":"How to know what route have installed plugin","user":{"login":"argoitz","id":19209969,"avatar_url":"https://avatars3.githubusercontent.com/u/19209969?v=4","gravatar_id":"","url":"https://api.github.com/users/argoitz","html_url":"https://github.com/argoitz","followers_url":"https://api.github.com/users/argoitz/followers","following_url":"https://api.github.com/users/argoitz/following{/other_user}","gists_url":"https://api.github.com/users/argoitz/gists{/gist_id}","starred_url":"https://api.github.com/users/argoitz/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/argoitz/subscriptions","organizations_url":"https://api.github.com/users/argoitz/orgs","repos_url":"https://api.github.com/users/argoitz/repos","events_url":"https://api.github.com/users/argoitz/events{/privacy}","received_events_url":"https://api.github.com/users/argoitz/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-05-04T09:13:28Z","updated_at":"2018-05-04T09:22:14Z","closed_at":"2018-05-04T09:22:14Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | no\r\n| Feature request? | yes\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 3.0.9\r\n\r\nHi there,\r\nI install Myallocator in symfony 3.0.9 with composer (https://github.com/MyAllocator/myallocator-pms-php) but now I don't know how to include in app/AppKernel.php file. \r\n\r\nThis is my AppKernel's registerBundle function:\r\n\r\n    public function registerBundles()\r\n    {\r\n        $bundles = [\r\n            new Symfony\\Bundle\\FrameworkBundle\\FrameworkBundle(),\r\n            new Symfony\\Bundle\\SecurityBundle\\SecurityBundle(),\r\n            new Symfony\\Bundle\\TwigBundle\\TwigBundle(),\r\n            new Symfony\\Bundle\\MonologBundle\\MonologBundle(),\r\n            new Symfony\\Bundle\\SwiftmailerBundle\\SwiftmailerBundle(),\r\n            new Doctrine\\Bundle\\DoctrineBundle\\DoctrineBundle(),\r\n            new Sensio\\Bundle\\FrameworkExtraBundle\\SensioFrameworkExtraBundle(),\r\n            new AppBundle\\AppBundle(),\r\n            new FOS\\UserBundle\\FOSUserBundle(),\r\n            new AppBundle\\Myallocator\\Myallocator(),\r\n        ];\r\n\r\n        if (in_array($this->getEnvironment(), ['dev', 'test'], true)) {\r\n            $bundles[] = new Symfony\\Bundle\\DebugBundle\\DebugBundle();\r\n            $bundles[] = new Symfony\\Bundle\\WebProfilerBundle\\WebProfilerBundle();\r\n            $bundles[] = new Sensio\\Bundle\\DistributionBundle\\SensioDistributionBundle();\r\n            $bundles[] = new Sensio\\Bundle\\GeneratorBundle\\SensioGeneratorBundle();\r\n        }\r\n\r\n        return $bundles;\r\n    }  \r\n\r\nI include it as  \"new AppBundle\\Myallocator\\Myallocator(),\" but it doesn't work. I dont know what namespace have this plugin. \r\nHow can I know the namespace of Myallocator bundle?\r\n\r\nPlease I need help.\r\nThank you.","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27147","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27147/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27147/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27147/events","html_url":"https://github.com/symfony/symfony/issues/27147","id":320200931,"number":27147,"title":"[Cache] Tag invalidation does not persist after script execution","user":{"login":"Loupax","id":551675,"avatar_url":"https://avatars0.githubusercontent.com/u/551675?v=4","gravatar_id":"","url":"https://api.github.com/users/Loupax","html_url":"https://github.com/Loupax","followers_url":"https://api.github.com/users/Loupax/followers","following_url":"https://api.github.com/users/Loupax/following{/other_user}","gists_url":"https://api.github.com/users/Loupax/gists{/gist_id}","starred_url":"https://api.github.com/users/Loupax/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Loupax/subscriptions","organizations_url":"https://api.github.com/users/Loupax/orgs","repos_url":"https://api.github.com/users/Loupax/repos","events_url":"https://api.github.com/users/Loupax/events{/privacy}","received_events_url":"https://api.github.com/users/Loupax/received_events","type":"User","site_admin":false},"labels":[{"id":100079,"url":"https://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":313658463,"url":"https://api.github.com/repos/symfony/symfony/labels/Cache","name":"Cache","color":"dddddd","default":false},{"id":237003792,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Needs%20Review","name":"Status: Needs Review","color":"ededed","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-05-04T09:04:29Z","updated_at":"2018-05-05T02:05:51Z","closed_at":"2018-05-05T02:05:51Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | ^4.0\r\n\r\nI am using the `TagAwareAdapter` so I can invalidate my REDIS cache by tag. The problem is that, while the cache item gets invalidated, this change does not persist between requests.\r\n\r\nSee this reproduction [repo](https://github.com/Loupax/CachingTagInvalidationBug) , it has four commands:\r\nOne that populates the cache, one that invalidates the cache by tag, one that fetches the keys and one that does all three in a single command.\r\n\r\nExpected behaviour:\r\n```\r\n$ bin/console app:add\r\n$ bin/console app:invalidate\r\n$ bin/console app:get\r\n```\r\nThe final command should output:\r\n```\r\nitem-0, isHit:false\r\nitem-1, isHit:false\r\nitem-2, isHit:false\r\nitem-3, isHit:false\r\nitem-4, isHit:false\r\n```\r\nActual output:\r\n```\r\nitem-0, isHit:true\r\nitem-1, isHit:true\r\nitem-2, isHit:true\r\nitem-3, isHit:true\r\nitem-4, isHit:true\r\n```\r\n\r\nRunning the command `$ bin/console app:add-invalidate-and-get` works as expected","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27146","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27146/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27146/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27146/events","html_url":"https://github.com/symfony/symfony/issues/27146","id":320185664,"number":27146,"title":"[DependencyInjection] Wrong error message when using bindings on a service with missing parents","user":{"login":"jvasseur","id":849295,"avatar_url":"https://avatars1.githubusercontent.com/u/849295?v=4","gravatar_id":"","url":"https://api.github.com/users/jvasseur","html_url":"https://github.com/jvasseur","followers_url":"https://api.github.com/users/jvasseur/followers","following_url":"https://api.github.com/users/jvasseur/following{/other_user}","gists_url":"https://api.github.com/users/jvasseur/gists{/gist_id}","starred_url":"https://api.github.com/users/jvasseur/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jvasseur/subscriptions","organizations_url":"https://api.github.com/users/jvasseur/orgs","repos_url":"https://api.github.com/users/jvasseur/repos","events_url":"https://api.github.com/users/jvasseur/events{/privacy}","received_events_url":"https://api.github.com/users/jvasseur/received_events","type":"User","site_admin":false},"labels":[{"id":100079,"url":"https://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":99863,"url":"https://api.github.com/repos/symfony/symfony/labels/DependencyInjection","name":"DependencyInjection","color":"DDDDDD","default":false},{"id":237003792,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Needs%20Review","name":"Status: Needs Review","color":"ededed","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-05-04T08:06:27Z","updated_at":"2018-05-12T09:35:39Z","closed_at":"2018-05-12T09:35:39Z","author_association":"CONTRIBUTOR","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 4.1\r\n\r\nWhen you use bindings on a service with a missing parent class or interface you get the unused binding error which doesn't point to the real problem (a parent is missing).\r\n\r\nThis is probably related to #27088.","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27137","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27137/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27137/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27137/events","html_url":"https://github.com/symfony/symfony/issues/27137","id":319910278,"number":27137,"title":"[DX] Improve the \"the controller must return a response (null given)\" exception page","user":{"login":"lyrixx","id":408368,"avatar_url":"https://avatars1.githubusercontent.com/u/408368?v=4","gravatar_id":"","url":"https://api.github.com/users/lyrixx","html_url":"https://github.com/lyrixx","followers_url":"https://api.github.com/users/lyrixx/followers","following_url":"https://api.github.com/users/lyrixx/following{/other_user}","gists_url":"https://api.github.com/users/lyrixx/gists{/gist_id}","starred_url":"https://api.github.com/users/lyrixx/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/lyrixx/subscriptions","organizations_url":"https://api.github.com/users/lyrixx/orgs","repos_url":"https://api.github.com/users/lyrixx/repos","events_url":"https://api.github.com/users/lyrixx/events{/privacy}","received_events_url":"https://api.github.com/users/lyrixx/received_events","type":"User","site_admin":false},"labels":[{"id":107512439,"url":"https://api.github.com/repos/symfony/symfony/labels/DX","name":"DX","color":"5319e7","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":5,"created_at":"2018-05-03T13:00:11Z","updated_at":"2018-05-09T05:57:49Z","closed_at":"2018-05-09T05:57:49Z","author_association":"MEMBER","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | no\r\n| Feature request? | yes\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | all \r\n\r\n---\r\n\r\n![image](https://user-images.githubusercontent.com/408368/39577693-4e09f754-4ee2-11e8-9d02-e01ad08e77fa.png)\r\n\r\nI think we can improve a lot this page by showing the controller that is responsible of this exception.\r\nI guess many new-comers hit this page, and it could be complicated to find the controller, even if it's name is in the debug bar.\r\n\r\nDo you think it worth it or should we close?","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27134","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27134/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27134/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27134/events","html_url":"https://github.com/symfony/symfony/issues/27134","id":319827922,"number":27134,"title":"[Cache] CachePoolPrunerPass uses wrong service id in 3.4","user":{"login":"DemonTPx","id":2570835,"avatar_url":"https://avatars2.githubusercontent.com/u/2570835?v=4","gravatar_id":"","url":"https://api.github.com/users/DemonTPx","html_url":"https://github.com/DemonTPx","followers_url":"https://api.github.com/users/DemonTPx/followers","following_url":"https://api.github.com/users/DemonTPx/following{/other_user}","gists_url":"https://api.github.com/users/DemonTPx/gists{/gist_id}","starred_url":"https://api.github.com/users/DemonTPx/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/DemonTPx/subscriptions","organizations_url":"https://api.github.com/users/DemonTPx/orgs","repos_url":"https://api.github.com/users/DemonTPx/repos","events_url":"https://api.github.com/users/DemonTPx/events{/privacy}","received_events_url":"https://api.github.com/users/DemonTPx/received_events","type":"User","site_admin":false},"labels":[{"id":100079,"url":"https://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":148416,"url":"https://api.github.com/repos/symfony/symfony/labels/FrameworkBundle","name":"FrameworkBundle","color":"DDDDDD","default":false},{"id":237003792,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Needs%20Review","name":"Status: Needs Review","color":"ededed","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2018-05-03T08:26:04Z","updated_at":"2018-05-03T23:57:44Z","closed_at":"2018-05-03T23:57:44Z","author_association":"CONTRIBUTOR","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 3.4.9\r\n\r\nI was running the `cache:pool:prune` command and nothing was pruned. I discovered that no pools were added to the command even though I have about 6 of them in my application.\r\n\r\nThe `CachePoolPrunerPass` is responsible for adding the pools to the command, but uses the class name of the command to find its service. This might be fine for Symfony 4, but in my 3.4 application it cannot find the service. After I changed the service id to `console.command.cache_pool_prune` the compiler pass worked correctly again and I could prune my cache pools.\r\n\r\nI could make a PR for this, but I think it might break it on Symfony 4. What would be the best way to proceed with this?","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27125","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27125/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27125/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27125/events","html_url":"https://github.com/symfony/symfony/issues/27125","id":319542095,"number":27125,"title":"multiple entity managers are all the same","user":{"login":"jtleon","id":9757844,"avatar_url":"https://avatars0.githubusercontent.com/u/9757844?v=4","gravatar_id":"","url":"https://api.github.com/users/jtleon","html_url":"https://github.com/jtleon","followers_url":"https://api.github.com/users/jtleon/followers","following_url":"https://api.github.com/users/jtleon/following{/other_user}","gists_url":"https://api.github.com/users/jtleon/gists{/gist_id}","starred_url":"https://api.github.com/users/jtleon/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jtleon/subscriptions","organizations_url":"https://api.github.com/users/jtleon/orgs","repos_url":"https://api.github.com/users/jtleon/repos","events_url":"https://api.github.com/users/jtleon/events{/privacy}","received_events_url":"https://api.github.com/users/jtleon/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-05-02T12:59:35Z","updated_at":"2018-05-02T17:23:38Z","closed_at":"2018-05-02T17:23:38Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | vague\r\n| Feature request? | no\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 4.0.8\r\n\r\nI have two databases. There are same in structure. So they have the same entity. \r\nI follow the steps [Multiple Entity Managers](http://symfony.com/doc/current/doctrine/multiple_entity_managers.html)\r\n\r\nbut not expected\r\n\r\n### doctrine config\r\n```yaml\r\ndoctrine:\r\n    dbal:\r\n        default_connection: default\r\n        connections:\r\n            default:\r\n                driver: 'pdo_mysql'\r\n                server_version: '5.7'\r\n                charset: utf8mb4\r\n                url: '%env(resolve:DATABASE_URL)%'\r\n            abroad:\r\n                driver: 'pdo_mysql'\r\n                server_version: '5.7'\r\n                charset: utf8mb4\r\n                url: '%env(resolve:DATABASE_ABROAD)%'\r\n    orm:\r\n        auto_generate_proxy_classes: '%kernel.debug%'\r\n        default_entity_manager: default\r\n        entity_managers:\r\n            default:\r\n                connection: default\r\n                naming_strategy: doctrine.orm.naming_strategy.underscore\r\n                mappings:\r\n                    DefaultApp:\r\n                        is_bundle: false\r\n                        type: annotation\r\n                        dir: '%kernel.project_dir%/src/Entity'\r\n                        prefix: App\\Entity\r\n                        alias: DefaultApp\r\n                    DefaultBsw:\r\n                        is_bundle: false\r\n                        type: annotation\r\n                        dir: '%kernel.project_dir%/src/Bsw/Entity'\r\n                        prefix: App\\Bsw\\Entity\r\n                        alias: DefaultBsw\r\n            abroad:\r\n                connection: abroad\r\n                naming_strategy: doctrine.orm.naming_strategy.underscore\r\n                mappings:\r\n                    AbroadApp:\r\n                        is_bundle: false\r\n                        type: annotation\r\n                        dir: '%kernel.project_dir%/src/Entity'\r\n                        prefix: App\\Entity\r\n                        alias: AbroadApp\r\n                    AbroadBsw:\r\n                        is_bundle: false\r\n                        type: annotation\r\n                        dir: '%kernel.project_dir%/src/Bsw/Entity'\r\n                        prefix: App\\Bsw\\Entity\r\n                        alias: AbroadBsw\r\n```\r\n\r\n### controller\r\n```php\r\n<?php\r\n\r\nnamespace App\\Controller;\r\n\r\nuse App\\Entity\\AdminInfo;\r\nuse Symfony\\Component\\Routing\\Annotation\\Route;\r\nuse App\\Bsw\\Annotation\\AccessControl;\r\n\r\nclass TestController extends MasterController\r\n{\r\n    /**\r\n     * For test\r\n     *\r\n     * @Route(\"/users\", name=\"app_users\")\r\n     * @AccessControl()\r\n     */\r\n    public function users()\r\n    {\r\n        $emA = $this->getDoctrine()->getManager('default');\r\n        $emB = $this->getDoctrine()->getManager('abroad');\r\n\r\n        dump($emA, $emB);\r\n\r\n        $listA = $emA->getRepository(AdminInfo::class)->find(1);\r\n        $listB = $emB->getRepository(AdminInfo::class)->find(1);\r\n\r\n        dump($listA, $listB);\r\n        die;\r\n    }\r\n}\r\n```\r\n\r\n### result\r\n\r\n#### got diff entity\r\n![a](https://user-images.githubusercontent.com/9757844/39524348-42f9d268-4e4b-11e8-920f-41f9661eef5c.png)\r\n\r\n#### but got same result\r\n![b](https://user-images.githubusercontent.com/9757844/39524345-3e5b8a26-4e4b-11e8-924b-43b9dd210a6b.png)\r\n\r\nwhat wrong with my config?","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27120","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27120/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27120/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27120/events","html_url":"https://github.com/symfony/symfony/issues/27120","id":319488197,"number":27120,"title":"[YAML] Underscores are removed from strings treating them as integers.","user":{"login":"tzfrs","id":3509557,"avatar_url":"https://avatars1.githubusercontent.com/u/3509557?v=4","gravatar_id":"","url":"https://api.github.com/users/tzfrs","html_url":"https://github.com/tzfrs","followers_url":"https://api.github.com/users/tzfrs/followers","following_url":"https://api.github.com/users/tzfrs/following{/other_user}","gists_url":"https://api.github.com/users/tzfrs/gists{/gist_id}","starred_url":"https://api.github.com/users/tzfrs/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/tzfrs/subscriptions","organizations_url":"https://api.github.com/users/tzfrs/orgs","repos_url":"https://api.github.com/users/tzfrs/repos","events_url":"https://api.github.com/users/tzfrs/events{/privacy}","received_events_url":"https://api.github.com/users/tzfrs/received_events","type":"User","site_admin":false},"labels":[{"id":100079,"url":"htt
8000
ps://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":237003792,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Needs%20Review","name":"Status: Needs Review","color":"ededed","default":false},{"id":3536874,"url":"https://api.github.com/repos/symfony/symfony/labels/Yaml","name":"Yaml","color":"DDDDDD","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":7,"created_at":"2018-05-02T09:58:39Z","updated_at":"2018-05-04T11:49:12Z","closed_at":"2018-05-04T09:26:26Z","author_association":"CONTRIBUTOR","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 3.4.\r\n\r\nHello, I've created a YAML file where the value `6000_5000` was stored. This YAML was simply created for populating database tables with data for test cases. When I wrote the test case, I searched for data containing `6000_5000` but had no results. After some research, I saw, that `6000_5000` was saved as `60005000`, so I digged deep to see why that happens.\r\n\r\nI found [this line (including blame)](https://github.com/symfony/symfony/blame/95ceeab3d718a02317e190a780435822a0bfb03f/src/Symfony/Component/Yaml/Inline.php#L738) and [this PR](https://github.com/symfony/symfony/pull/18486) where it states\r\n\r\n> Allows to use the _ to group \"big\" ints, as suggested in the yaml integer type specification. As discussed in #18094, we should check if it is still part of the 1.2 specification, but I don't really see why not?\r\n\r\nOkay, so I searched a bit and found [this type definition](http://yaml.org/type/int.html) where it states exactly what the PR should do, however this is, as the PR, for YAML version 1.1, so I opened the int specs for 1.2 which you can [find here](http://yaml.org/spec/1.2/spec.html#id2803828)\r\n\r\nIn this definition, there is no mentioning of using `_` as readability help, and I didn't find this recommendation anywhere else, so in order to comply with 1.2 standards of the YAML definition, I'd say Symfony needs to remove this.\r\n\r\nNow I don't know how to handle this correctly. I'd open a PR, but this is a BC break, so it's not possible to  merge this into the `4.x` branch, but this violates the YAML definition, so a user, who reads version 1.2 of the YAML definition and uses Symfony will have NO idea WHY this happens.\r\n\r\nThoughts?","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27114","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27114/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27114/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27114/events","html_url":"https://github.com/symfony/symfony/issues/27114","id":319299001,"number":27114,"title":"Bootstrap 4 Form Theme for PHP Templating Engine?","user":{"login":"chris14465","id":244036,"avatar_url":"https://avatars2.githubusercontent.com/u/244036?v=4","gravatar_id":"","url":"https://api.github.com/users/chris14465","html_url":"https://github.com/chris14465","followers_url":"https://api.github.com/users/chris14465/followers","following_url":"https://api.github.com/users/chris14465/following{/other_user}","gists_url":"https://api.github.com/users/chris14465/gists{/gist_id}","starred_url":"https://api.github.com/users/chris14465/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/chris14465/subscriptions","organizations_url":"https://api.github.com/users/chris14465/orgs","repos_url":"https://api.github.com/users/chris14465/repos","events_url":"https://api.github.com/users/chris14465/events{/privacy}","received_events_url":"https://api.github.com/users/chris14465/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-05-01T19:26:39Z","updated_at":"2018-05-02T07:39:14Z","closed_at":"2018-05-02T07:39:13Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | no\r\n| Feature request? | yes\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 4.0.3\r\n\r\n\r\nAm I missing something, or is there no Bootstrap 4 Form Theme available when using PHP als templating engine?\r\nDocumentation is not mention anything about it, and setting the form theme to \"bootstrap_4_layout.html.php\" isn't working either.\r\n(https://symfony.com/doc/current/form/form_customization.html)","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27107","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27107/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27107/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27107/events","html_url":"https://github.com/symfony/symfony/issues/27107","id":319101077,"number":27107,"title":"preg_match pattern error in symfony/http-foundation/Request.php obfusking the real problem","user":{"login":"Zyigh","id":24964343,"avatar_url":"https://avatars0.githubusercontent.com/u/24964343?v=4","gravatar_id":"","url":"https://api.github.com/users/Zyigh","html_url":"https://github.com/Zyigh","followers_url":"https://api.github.com/users/Zyigh/followers","following_url":"https://api.github.com/users/Zyigh/following{/other_user}","gists_url":"https://api.github.com/users/Zyigh/gists{/gist_id}","starred_url":"https://api.github.com/users/Zyigh/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Zyigh/subscriptions","organizations_url":"https://api.github.com/users/Zyigh/orgs","repos_url":"https://api.github.com/users/Zyigh/repos","events_url":"https://api.github.com/users/Zyigh/events{/privacy}","received_events_url":"https://api.github.com/users/Zyigh/received_events","type":"User","site_admin":false},"labels":[{"id":100079,"url":"https://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":125366,"url":"https://api.github.com/repos/symfony/symfony/labels/HttpFoundation","name":"HttpFoundation","color":"DDDDDD","default":false},{"id":237003792,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Needs%20Review","name":"Status: Needs Review","color":"ededed","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2018-05-01T02:53:07Z","updated_at":"2018-05-06T17:34:48Z","closed_at":"2018-05-06T17:34:48Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 4.0.9\r\n\r\nHi !\r\nFirst of all, thanks for your great framework. More than being a very well designed and usefull tool, it shows the best practices, so it is the best thing to study how PHP work.\r\n\r\nHowever, I've been confronted to a bug while trying to access my route \"/\".  \r\nI got as error : `Exception thrown when handling an exception (ErrorException: Warning: preg_match(): Unknown modifier '#')`\r\n\r\nI couldn't find anything similar on the web so I looked at the logs which were saying  \r\n> Uncaught PHP Exception ErrorException: \"Warning: preg_match(): Unknown modifier '#'\" at ~/vendor/symfony/http-foundation/Request.php line 1171\r\n\r\nI added this code at the specified line to see where the error came from `dump($pattern); die();` and I had \"#localhost##i\". I had to surround the variable `$pattern` with \"/\" to see what was my problem (which was kind of stupid btw...).\r\n\r\nSecond time I reproduced this bug, the dump only showed \"#localhost#i\".\r\n\r\nI'm writting this as an issue as anybody can fall into this bug and this can help them to solve their initial problem instead of losing time on this one. Also it might not be the only case where the error can be found.\r\n\r\n### How to reproduce the bug\r\n\r\nI'm currently on MacOS X High Sierra 10.13.4. My PHP version is 7.2.4 (installed with Homebrew) and I was using the Symfony dev server. I used the [dotenv](https://packagist.org/packages/symfony/dotenv) recipe, and modified two line in the .env file :  \r\n```\r\nTRUSTED_PROXIES=127.0.0.1#,127.0.0.2\r\nTRUSTED_HOSTS=localhost#,example.com\r\n// Moved the # after 127.0.0.1 and after localhost instead of beginning of the line\r\n```\r\n\r\n","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27101","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27101/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27101/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27101/events","html_url":"https://github.com/symfony/symfony/issues/27101","id":318986617,"number":27101,"title":"[BC Break] OptionsResolver::formatTypeOf does not work on Symfony 3.4","user":{"login":"danemacmillan","id":4390491,"avatar_url":"https://avatars2.githubusercontent.com/u/4390491?v=4","gravatar_id":"","url":"https://api.github.com/users/danemacmillan","html_url":"https://github.com/danemacmillan","followers_url":"https://api.github.com/users/danemacmillan/followers","following_url":"https://api.github.com/users/danemacmillan/following{/other_user}","gists_url":"https://api.github.com/users/danemacmillan/gists{/gist_id}","starred_url":"https://api.github.com/users/danemacmillan/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/danemacmillan/subscriptions","organizations_url":"https://api.github.com/users/danemacmillan/orgs","repos_url":"https://api.github.com/users/danemacmillan/repos","events_url":"https://api.github.com/users/danemacmillan/events{/privacy}","received_events_url":"https://api.github.com/users/danemacmillan/received_events","type":"User","site_admin":false},"labels":[{"id":231677,"url":"https://api.github.com/repos/symfony/symfony/labels/BC%20Break","name":"BC Break","color":"e10c02","default":false},{"id":100079,"url":"https://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":5069504,"url":"https://api.github.com/repos/symfony/symfony/labels/OptionsResolver","name":"OptionsResolver","color":"DDDDDD","default":false},{"id":237003792,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Needs%20Review","name":"Status: Needs Review","color":"ededed","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-04-30T18:22:23Z","updated_at":"2018-05-01T09:09:20Z","closed_at":"2018-04-30T18:51:29Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | yes\r\n| RFC?             | no\r\n| Symfony version  | 3.4\r\n\r\nMy project has the following requirements:\r\n\r\n```\r\n    \"require\": {\r\n        \"php\": \">=7.0\",\r\n        \"symfony/config\": \"^3.4\",\r\n        \"symfony/console\": \"^3.4\",\r\n        \"symfony/event-dispatcher\": \"^3.4\",\r\n        \"symfony/filesystem\": \"^3.4\",\r\n        \"symfony/finder\": \"^3.4\",\r\n        \"symfony/lock\": \"^3.4\",\r\n        \"symfony/process\": \"^3.4\",\r\n        \"symfony/yaml\": \"^3.4\"\r\n    }\r\n```\r\n\r\nOne of them also pulls in [`options-resolver`](https://github.com/symfony/options-resolver). Options Resolver specifies that it needs a minimum PHP version of `7.1.3`. Symfony `3.4`'s [`composer.json`](https://github.com/symfony/symfony/blob/3.4/composer.json) file specifies `\"^5.5.9|>=7.0.8\"` as the PHP version.\r\n\r\nSymfony `3.4` is advertised with [minimum support for PHP `5.5.9` and higher](https://symfony.com/doc/3.4/reference/requirements.html).\r\n\r\nGiven this information, I'm getting the following error:\r\n\r\n```\r\nParse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /vagrant/sites/linus/vendor/symfony/options-resolver/OptionsResolver.php on line 980\r\n```\r\n\r\nThe error line is: https://github.com/symfony/options-resolver/blob/master/OptionsResolver.php#L980\r\n\r\nThe error is happening because my version of PHP, `7.0.27`, does not support [nullable types](http://php.net/manual/en/migration71.new-features.php).\r\n\r\nGiven my project requirements for only Symfony `3.4` packages, I should not be getting this error. This is breaking code that is respecting requirements. The nullable type should be allowed to be used when the Symfony requirements specify Symfony `3.4`. If I wanted to use Symfony `4.0`, I would upgrade to PHP `7.1.3` and specify that the Symfony versions for those requirements be bumped to `4.0`. ","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27099","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27099/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27099/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27099/events","html_url":"https://github.com/symfony/symfony/issues/27099","id":318891133,"number":27099,"title":"Hwi oauth bundle and Symfony 3.4 Cannot autowire service : How to use hwi/oauth-bundle in symfony 3.4 + FOSUserBundle fos/user-bundle","user":{"login":"sachaamm","id":11826078,"avatar_url":"https://avatars3.githubusercontent.com/u/11826078?v=4","gravatar_id":"","url":"https://api.github.com/users/sachaamm","html_url":"https://github.com/sachaamm","followers_url":"https://api.github.com/users/sachaamm/followers","following_url":"https://api.github.com/users/sachaamm/following{/other_user}","gists_url":"https://api.github.com/users/sachaamm/gists{/gist_id}","starred_url":"https://api.github.com/users/sachaamm/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/sachaamm/subscriptions","organizations_url":"https://api.github.com/users/sachaamm/orgs","repos_url":"https://api.github.com/users/sachaamm/repos","events_url":"https://api.github.com/users/sachaamm/events{/privacy}","received_events_url":"https://api.github.com/users/sachaamm/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-04-30T13:32:37Z","updated_at":"2018-04-30T15:00:33Z","closed_at":"2018-04-30T15:00:33Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 3.4.8\r\n\r\n\r\nI'm upgrading an application written in Symfony 2.8.5 to Symfony 3.4.8\r\n\r\nI would like to use hwi/oauth-bundle to keep the oauth Facebook / Google login in Symfony 3.4. (My oauth login was working on Symfony 2.8.5 with FOSUserBundle ) \r\nNow I get this error:\r\n\r\n```\r\nCannot autowire service \"App\\Security\\Core\\User\\OAuthUserProvider\": \r\nargument \"$properties\" of method \"__construct()\" must have a type-hint \r\nor be given a value explicitly. \r\n```\r\nOAuthUserProvider extending FOSUSBUserProvider :\r\n```php\r\n\r\nnamespace App\\Security\\Core\\User;\r\n\r\nuse HWI\\Bundle\\OAuthBundle\\OAuth\\Response\\UserResponseInterface;\r\nuse HWI\\Bundle\\OAuthBundle\\Security\\Core\\User\\FOSUBUserProvider as BaseClass;\r\nuse Symfony\\Component\\Security\\Core\\Exception\\AuthenticationException;\r\nuse Symfony\\Component\\Security\\Core\\User\\UserChecker;\r\nuse Symfony\\Component\\Security\\Core\\User\\UserInterface;\r\nuse FOS\\UserBundle\\Model\\UserManagerInterface;\r\n\r\n/**\r\n * Class OAuthUserProvider\r\n * @package AppBundle\\Security\\Core\\User\r\n */\r\nclass OAuthUserProvider extends BaseClass {\r\n\r\n    private $mailer;\r\n    private $container;\r\n\r\n    public function __construct(UserManagerInterface $userManager,array $properties, $mailer, $container) {\r\n\r\n        parent::__construct($userManager, $properties);\r\n        $this->mailer = $mailer;\r\n        $this->container = $container;\r\n    }\r\n```\r\nservices.yaml:\r\n\r\n```yaml\r\napp.provider.oauth:\r\n    class: App\\Security\\Core\\User\\OAuthUserProvider\r\n    arguments: ['@fos_user.user_manager',{facebook: 'myFacebookId', google: 'myGoogleId'},'@mailer','@service_container']\r\n```\r\n\r\nsecurity.yaml:\r\n```yaml\r\nsecurity:\r\n# https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers\r\nproviders:\r\n    in_memory: { memory: ~ }\r\nfirewalls:\r\n    dev:\r\n        pattern: ^/(_(profiler|wdt)|css|images|js)/\r\n        security: false\r\n    main:\r\n        anonymous: true\r\n        oauth:\r\n            resource_owners:\r\n                facebook: \"/login/check-facebook\"\r\n                google: \"/login/check-google\"\r\n\r\n            failure_path: /login\r\n            use_forward: false\r\n            login_path: /login\r\n            check_path: /connect_check\r\n            #provider: fos_userbundle # is oauth:provider is still supported in symfony 3.4 ???\r\n            success_handler: redirect.after.login\r\n\r\n            oauth_user_provider:\r\n                service: app.provider.oauth\r\n\r\nencoders:\r\n    App\\Entity\\User\\User:\r\n        algorithm: bcrypt\r\n\r\n```\r\nI really don't understand because in my services.yaml I'm defining all arguments required even properties as an array ... I guess hwi/oauth-bundle and fos/user-bundle are both not anymore officialy supported in Symfony 3.4.\r\n\r\nThanks for your support, Symfony is great !\r\n( this topic was also opened in https://stackoverflow.com/questions/50100399/hwi-oauth-bundle-and-symfony-3-4-cannot-autowire-service-how-to-use-hwi-oauth ) \r\n","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27097","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27097/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27097/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27097/events","html_url":"https://github.com/symfony/symfony/issues/27097","id":318838471,"number":27097,"title":"rewriting of link on exception page does not work on parse error","user":{"login":"lyrixx","id":408368,"avatar_url":"https://avatars1.githubusercontent.com/u/408368?v=4","gravatar_id":"","url":"https://api.github.com/users/lyrixx","html_url":"https://github.com/lyrixx","followers_url":"https://api.github.com/users/lyrixx/followers","following_url":"https://api.github.com/users/lyrixx/following{/other_user}","gists_url":"https://api.github.com/users/lyrixx/gists{/gist_id}","starred_url":"https://api.github.com/users/lyrixx/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/lyrixx/subscriptions","organizations_url":"https://api.github.com/users/lyrixx/orgs","repos_url":"https://api.github.com/users/lyrixx/repos","events_url":"https://api.github.com/users/lyrixx/events{/privacy}","received_events_url":"https://api.github.com/users/lyrixx/received_events","type":"User","site_admin":false},"labels":[{"id":49125875,"url":"https://api.github.com/repos/symfony/symfony/labels/Debug","name":"Debug","color":"DDDDDD","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-04-30T09:57:02Z","updated_at":"2018-04-30T16:58:40Z","closed_at":"2018-04-30T16:58:40Z","author_association":"MEMBER","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | At least 3.4\r\n\r\n\r\nWhen a parse error occurs, we get this kind of page:\r\n\r\n![image](https://user-images.githubusercontent.com/408368/39422278-01acb724-4c6d-11e8-8981-2d94119ffab2.png)\r\n\r\nAnd when `xdebug.file_link_format` is set to something like:\r\n\r\n> xdebug.file_link_format=\"subl://%f:%l&/var/www>/home/gregoire/dev/github.com/jolicode/project\"\r\n\r\nThe link should be rewritten. It works really well on all errors page (fatal, debug bar, ...), but not on a parse error","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27091","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27091/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27091/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27091/events","html_url":"https://github.com/symfony/symfony/issues/27091","id":318746996,"number":27091,"title":"Routes security not working","user":{"login":"fabionvs","id":8305479,"avatar_url":"https://avatars3.githubusercontent.com/u/8305479?v=4","gravatar_id":"","url":"https://api.github.com/users/fabionvs","html_url":"https://github.com/fabionvs","followers_url":"https://api.github.com/users/fabionvs/followers","following_url":"https://api.github.com/users/fabionvs/following{/other_user}","gists_url":"https://api.github.com/users/fabionvs/gists{/gist_id}","starred_url":"https://api.github.com/users/fabionvs/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/fabionvs/subscriptions","organizations_url":"https://api.github.com/users/fabionvs/orgs","repos_url":"https://api.github.com/users/fabionvs/repos","events_url":"https://api.github.com/users/fabionvs/events{/privacy}","received_events_url":"https://api.github.com/users/fabionvs/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-04-29T20:27:12Z","updated_at":"2018-04-30T06:47:46Z","closed_at":"2018-04-30T06:47:46Z","author_association":"NONE","body":"Hello,\r\nI am working on a project using Symfony 3.4, and it seems access_control routes are not working properly. When I try to access a protected route by access_control, anonymous and users still could get access from a protected route. As the following security.yml:\r\n\r\n\r\n    providers:\r\n        fos_userbundle:\r\n            id: fos_user.user_provider.username_email\r\n\r\n    firewalls:\r\n        secured_area:\r\n            anonymous: true\r\n            pattern:    ^/\r\n            form_login:\r\n                provider: fos_userbundle\r\n                csrf_token_generator: security.csrf.token_manager\r\n                login_path: /login\r\n                check_path: /login_check\r\n            oauth:\r\n                resource_owners:\r\n                    facebook:           \"/login/check-facebook\"\r\n                    linkedin:           \"/login/check-linkedin\"\r\n                login_path:        /login\r\n                failure_path:      /login\r\n\r\n                oauth_user_provider:\r\n                    #this is my custom user provider, created from FOSUBUserProvider - will manage the\r\n                    #automatic user registration on your site, with data from the provider (facebook. google, etc.)\r\n                    service: my_user_provider\r\n\r\n            logout:\r\n                path: /logout\r\n\r\n\r\n    access_control:\r\n        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }\r\n        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }\r\n        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }\r\n        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }\r\n        - { path: ^/client/, role: ROLE_CLIENT }\r\n        - { path: ^/admin/, role: ROLE_ADMIN }`\r\n\r\nBut, if I use annotation inside a controller to prevent acess the security works! \r\n\r\n> /**\r\n> * @Security(\"is_granted('ROLE_ADMIN')\")\r\n> */\r\n>class DefaultController extends Controller {\r\n>}\r\n\r\nAnd, use security annotation in every controller sounds a little bit annoying. What should I do? What could be the error causing acces_control not to work?\r\n\r\n\t\"php\": \">=7.1\",\r\n        \"symfony/symfony\": \"3.4.*\",\r\n        \"doctrine/orm\": \"^2.5\",\r\n        \"doctrine/doctrine-bundle\": \"^1.6\",\r\n        \"doctrine/doctrine-cache-bundle\": \"^1.2\",\r\n        \"symfony/swiftmailer-bundle\": \"^2.3\",\r\n        \"symfony/monolog-bundle\": \"^2.8\",\r\n        \"symfony/polyfill-apcu\": \"^1.0\",\r\n        \"incenteev/composer-parameter-handler\": \"^2.0\",\r\n        \"friendsofsymfony/user-bundle\": \"~2.0@dev\",\r\n        \"hwi/oauth-bundle\": \"^0.6.2\",\r\n","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27081","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27081/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27081/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27081/events","html_url":"https://github.com/symfony/symfony/issues/27081","id":318493554,"number":27081,"title":"[Messenger] can no longer use wildcard (*) in routing","user":{"login":"kbond","id":127811,"avatar_url":"https://avatars0.githubusercontent.com/u/127811?v=4","gravatar_id":"","url":"https://api.github.com/users/kbond","html_url":"https://github.com/kbond","followers_url":"https://api.github.com/users/kbond/followers","following_url":"https://api.github.com/users/kbond/following{/other_user}","gists_url":"https://api.github.com/users/kbond/gists{/gist_id}","starred_url":"https://api.github.com/users/kbond/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/kbond/subscriptions","organizations_url":"https://api.github.com/users/kbond/orgs","repos_url":"https://api.github.com/users/kbond/repos","events_url":"https://api.github.com/users/kbond/events{/privacy}","received_events_url":"https://api.github.com/users/kbond/received_events","type":"User","site_admin":false},"labels":[{"id":100079,"url":"https://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":877085690,"url":"https://api.github.com/repos/symfony/symfony/labels/Messenger","name":"Messenger","color":"dddddd","default":false},{"id":237003792,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Needs%20Review","name":"Status: Needs Review","color":"ededed","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-04-27T17:45:43Z","updated_at":"2018-05-01T09:15:10Z","closed_at":"2018-04-29T06:39:15Z","author_association":"CONTRIBUTOR","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 4.1\r\n\r\n#27032 broke the ability to use `*` in your routing.\r\n\r\nThe configuration:\r\n\r\n```yaml\r\nframework:\r\n    messenger:\r\n        routing:\r\n            '*': amqp\r\n```\r\n\r\nGives the following error:\r\n\r\n`Messenger routing configuration contains a mistake: message \"*\" does not exist. It needs to match an existing class or interface.`\r\n","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27080","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27080/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27080/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27080/events","html_url":"https://github.com/symfony/symfony/issues/27080","id":318488167,"number":27080,"title":"Add example to serializer component docs about XML attribute extraction","user":{"login":"arechsteiner","id":1199486,"avatar_url":"https://avatars3.githubusercontent.com/u/1199486?v=4","gravatar_id":"","url":"https://api.github.com/users/arechsteiner","html_url":"https://github.com/arechsteiner","followers_url":"https://api.github.com/users/arechsteiner/followers","following_url":"https://api.github.com/users/arechsteiner/following{/other_user}","gists_url":"https://api.github.com/users/arechsteiner/gists{/gist_id}","starred_url":"https://api.github.com/users/arechsteiner/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/arechsteiner/subscriptions","organizations_url":"https://api.github.com/users/arechsteiner/orgs","repos_url":"https://api.github.com/users/arechsteiner/repos","events_url":"https://api.github.com/users/arechsteiner/events{/privacy}","received_events_url":"https://api.github.com/users/arechsteiner/received_events","type":"User","site_admin":false},"labels":[{"id":99939,"url":"https://api.github.com/repos/symfony/symfony/labels/Serializer","name":"Serializer","color":"DDDDDD","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-04-27T17:25:20Z","updated_at":"2018-05-01T09:11:21Z","closed_at":"2018-04-30T06:50:26Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | no\r\n| Feature request? | no\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 4.0\r\n\r\nI'm trying to use the package `symfony/serializer` to extract data from this XML structure:\r\n\r\n    <?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n    <result>\r\n      <code><![CDATA[SUCCESS]]></code>\r\n      <message><![CDATA[List of things retrieved.]]></message>\r\n      <data>\r\n        <category id=\"123123123\" name=\"some name\" url=\"/some/url\">\r\n          <category id=\"123123123\" name=\"some name\" url=\"/some/url/\" />\r\n          <category id=\"123123123\" name=\"some name\" url=\"/some/url/\">\r\n            <thing id=\"123123123\" name=\"some name\" url=\"/some/url/\" />\r\n            <thing id=\"123123123\" name=\"some name\" url=\"/some/url/\" />\r\n          </category>\r\n          <category id=\"123123123\" name=\"some name\" url=\"/some/url/\">\r\n            <category id=\"123123123\" name=\"some name\" url=\"/some/url/\">\r\n              <thing id=\"123123123\" name=\"some name\" url=\"/some/url/\" />\r\n              <thing id=\"123123123\" name=\"some name\" url=\"/some/url/\" />\r\n              <thing id=\"123123123\" name=\"some name\" url=\"/some/url/\" />\r\n            </category>\r\n          </category>\r\n        </category>\r\n      </data>\r\n    </result>\r\n\r\nI've been reading this site in the documentation: [The Serializer Component](https://symfony.com/doc/current/components/serializer.html). Unfortunately all the examples deal with data that is stored in child nodes. It would be great if there was a section that explains how to extract data from the XML attributes. The only hint I found was when [serializing from an array to XML](https://symfony.com/doc/current/components/serializer.html#the-xmlencoder) (with the `@` syntax). I'm unable to figure out how to do it in the opposite direction.","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/27078","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/27078/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/27078/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/27078/events","html_url":"https://github.com/symfony/symfony/issues/27078","id":318451118,"number":27078,"title":"Using services in a bundle configuration","user":{"login":"emr","id":7689512,"avatar_url":"https://avatars2.githubusercontent.com/u/7689512?v=4","gravatar_id":"","url":"https://api.github.com/users/emr","html_url":"https://github.com/emr","followers_url":"https://api.github.com/users/emr/followers","following_url":"https://api.github.com/users/emr/following{/other_user}","gists_url":"https://api.github.com/users/emr/gists{/gist_id}","starred_url":"https://api.github.com/users/emr/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/emr/subscriptions","organizations_url":"https://api.github.com/users/emr/orgs","repos_url":"https://api.github.com/users/emr/repos","events_url":"https://api.github.com/users/emr/events{/privacy}"
4f4
,"received_events_url":"https://api.github.com/users/emr/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":5,"created_at":"2018-04-27T15:23:56Z","updated_at":"2018-04-28T10:31:36Z","closed_at":"2018-04-28T10:31:36Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | no\r\n| Feature request? | no\r\n| BC Break report? | no\r\n| Symfony version  | 3.4\r\n\r\n—\r\n\r\n```yml\r\neasy_admin:\r\n    entities:\r\n        MyEntity:\r\n            class: \"@my_config_service.getMyEntityClass()\"\r\n            ...\r\n```\r\n\r\nDoes not compiled expressions in bundle configuration.\r\n\r\nI tried to make php configuration:\r\n```php\r\n$container->loadFromExtension('easy_admin', [\r\n    'entities' => [\r\n        'MyEntity' => [\r\n            'class' => $container->get('my_config_service')->getMyEntityClass()\r\n        ]\r\n    ]\r\n]);\r\n```\r\nI take this error: **`You have requested a non-existent service \"my_config_service\". `**\r\n\r\n—\r\n\r\nHow to inject my service in a bundle configuration?\r\nIs there an alternative way?\r\n\r\n(btw, sorry for my bad english)","score":1.0}]}
0

