HTTP/1.1 200 OK
Transfer-Encoding: chunked
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Cache-Control: no-cache
Content-Security-Policy: default-src 'none'
Content-Type: application/json; charset=utf-8
Date: Sun, 08 Apr 2018 22:39:55 GMT
Link: <https://api.github.com/search/issues?q=repo%3Asymfony%2Fsymfony+type%3Aissue+state%3Aclosed&page=2>; rel="next", <https://api.github.com/search/issues?q=repo%3Asymfony%2Fsymfony+type%3Aissue+state%3Aclosed&page=34>; rel="last"
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Server: GitHub.com
Status: 200 OK
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Accepted-Oauth-Scopes: 
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Github-Media-Type: github.v3; format=json
X-Github-Request-Id: CF84:54B8:F3E13C:21CCD68:5ACA9A3B
X-Oauth-Scopes: 
X-Ratelimit-Limit: 30
X-Ratelimit-Remaining: 16
X-Ratelimit-Reset: 1523227247
X-Runtime-Rack: 0.333048
X-Xss-Protection: 1; mode=block

8000
{"total_count":9510,"incomplete_results":false,"items":[{"url":"https://api.github.com/repos/symfony/symfony/issues/26860","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26860/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26860/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26860/events","html_url":"https://github.com/symfony/symfony/issues/26860","id":312247996,"number":26860,"title":"[Security] remember_me secret cannot access to env(APP_SECRET) or kernel.secret on 4.1","user":{"login":"FroggDev","id":3765812,"avatar_url":"https://avatars3.githubusercontent.com/u/3765812?v=4","gravatar_id":"","url":"https://api.github.com/users/FroggDev","html_url":"https://github.com/FroggDev","followers_url":"https://api.github.com/users/FroggDev/followers","following_url":"https://api.github.com/users/FroggDev/following{/other_user}","gists_url":"https://api.github.com/users/FroggDev/gists{/gist_id}","starred_url":"https://api.github.com/users/FroggDev/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/FroggDev/subscriptions","organizations_url":"https://api.github.com/users/FroggDev/orgs","repos_url":"https://api.github.com/users/FroggDev/repos","events_url":"https://api.github.com/users/FroggDev/events{/privacy}","received_events_url":"https://api.github.com/users/FroggDev/received_events","type":"User","site_admin":false},"labels":[{"id":100079,"url":"https://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":125406,"url":"https://api.github.com/repos/symfony/symfony/labels/Config","name":"Config","color":"DDDDDD","default":false},{"id":237003792,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Needs%20Review","name":"Status: Needs Review","color":"ededed","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-04-07T22:16:37Z","updated_at":"2018-04-08T08:25:03Z","closed_at":"2018-04-08T07:28:26Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 4.1\r\n\r\nIn the version 4.1 the secret parameter cannot read the global secret\r\n\r\n```\r\n            remember_me:\r\n                secret:   '%env(APP_SECRET)%'\r\n```\r\nor even\r\n\r\n```\r\n            remember_me:\r\n                secret:   '%kernel.secret%'\r\n```\r\n\r\nreturn the error \r\n\r\n```\r\nThe path \"security.firewalls.main.remember_me.secret\" cannot contain an empty value, but got \"\".\r\n```\r\n\r\nThe same code works without trouble on 4.0","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26858","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26858/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26858/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26858/events","html_url":"https://github.com/symfony/symfony/issues/26858","id":312222133,"number":26858,"title":"[RFC] Favor 200 OK instead of 404 not found status for default homepage","user":{"login":"ro0NL","id":1047696,"avatar_url":"https://avatars0.githubusercontent.com/u/1047696?v=4","gravatar_id":"","url":"https://api.github.com/users/ro0NL","html_url":"https://github.com/ro0NL","followers_url":"https://api.github.com/users/ro0NL/followers","following_url":"https://api.github.com/users/ro0NL/following{/other_user}","gists_url":"https://api.github.com/users/ro0NL/gists{/gist_id}","starred_url":"https://api.github.com/users/ro0NL/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ro0NL/subscriptions","organizations_url":"https://api.github.com/users/ro0NL/orgs","repos_url":"https://api.github.com/users/ro0NL/repos","events_url":"https://api.github.com/users/ro0NL/events{/privacy}","received_events_url":"https://api.github.com/users/ro0NL/received_events","type":"User","site_admin":false},"labels":[{"id":83934034,"url":"https://api.github.com/repos/symfony/symfony/labels/RFC","name":"RFC","color":"fbca04","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":5,"created_at":"2018-04-07T16:36:00Z","updated_at":"2018-04-08T10:09:51Z","closed_at":"2018-04-08T10:09:51Z","author_association":"CONTRIBUTOR","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | no\r\n| Feature request? | yes\r\n| BC Break report? | no\r\n| RFC?             | yes\r\n| Symfony version  | 4.1\r\n\r\nHi,\r\n\r\nI like to propose a `200 OK` response for the default homepage when no routing is configured. I.e. the page showing:\r\n\r\n```\r\nYou're seeing this page because debug mode is enabled and you haven't configured any homepage URL.\r\n```\r\n\r\nIt currently is a `404 Not Found`.\r\n\r\nI've no strong opinion about one or another, however using 404 causes e.g. [Lando](https://github.com/lando/lando) to think the service is not working, as it checks its URL to see if it's up.\r\n\r\nSo im not sure who's to blame here :) but they said basically:\r\n\r\n> Oh Symfony, everyone else throws a 200\r\n\r\nI think 200 OK is at least reasonable and fixes the Lando \"issue\" (it's just annoying on CLI to see it try and keep checking while in fact the service is working already).\r\n\r\nThoughts?","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26836","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26836/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26836/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26836/events","html_url":"https://github.com/symfony/symfony/issues/26836","id":311978741,"number":26836,"title":"Unable to have choices with same value","user":{"login":"fmagnan","id":589090,"avatar_url":"https://avatars0.githubusercontent.com/u/589090?v=4","gravatar_id":"","url":"https://api.github.com/users/fmagnan","html_url":"https://github.com/fmagnan","followers_url":"https://api.github.com/users/fmagnan/followers","following_url":"https://api.github.com/users/fmagnan/following{/other_user}","gists_url":"https://api.github.com/users/fmagnan/gists{/gist_id}","starred_url":"https://api.github.com/users/fmagnan/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/fmagnan/subscriptions","organizations_url":"https://api.github.com/users/fmagnan/orgs","repos_url":"https://api.github.com/users/fmagnan/repos","events_url":"https://api.github.com/users/fmagnan/events{/privacy}","received_events_url":"https://api.github.com/users/fmagnan/received_events","type":"User","site_admin":false},"labels":[{"id":100079,"url":"https://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":99594,"url":"https://api.github.com/repos/symfony/symfony/labels/Form","name":"Form","color":"DDDDDD","default":false},{"id":237003792,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Needs%20Review","name":"Status: Needs Review","color":"ededed","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-04-06T13:36:52Z","updated_at":"2018-04-08T08:26:44Z","closed_at":"2018-04-08T08:26:44Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 3.3.8\r\n\r\n<!--\r\n- Please fill in this template according to your issue.\r\n- For support request or how-tos, visit https://symfony.com/support\r\n- Otherwise, replace this comment by the description of your issue.\r\n-->\r\n\r\nHello,\r\n\r\nI'm trying to display radio buttons with different labels but same values. In my FormType, I'm using this code:\r\n\r\n```\r\n$builder->add('answers', ChoiceType::class, [\r\n            'choices' => ['yes' => 'y', 'ok' => 'y', 'no' => 'n', 'ko' => 'n'],\r\n            'expanded' => true,\r\n            'multiple' => false,\r\n        ]);\r\n```\r\nThe result is radio buttons but values are 0, 1, 2, 3 instead of y, y, n, n.\r\nIs it possible to have radio buttons with identical values?\r\n\r\n","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26830","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26830/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26830/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26830/events","html_url":"https://github.com/symfony/symfony/issues/26830","id":311897916,"number":26830,"title":"xliff-core-1.2-strict.xsd has Windows line endings in translation","user":{"login":"gemal","id":69105,"avatar_url":"https://avatars3.githubusercontent.com/u/69105?v=4","gravatar_id":"","url":"https://api.github.com/users/gemal","html_url":"https://github.com/gemal","followers_url":"https://api.github.com/users/gemal/followers","following_url":"https://api.github.com/users/gemal/following{/other_user}","gists_url":"https://api.github.com/users/gemal/gists{/gist_id}","starred_url":"https://api.github.com/users/gemal/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/gemal/subscriptions","organizations_url":"https://api.github.com/users/gemal/orgs","repos_url":"https://api.github.com/users/gemal/repos","events_url":"https://api.github.com/users/gemal/events{/privacy}","received_events_url":"https://api.github.com/users/gemal/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-04-06T08:56:42Z","updated_at":"2018-04-07T13:20:50Z","closed_at":"2018-04-07T13:20:50Z","author_association":"NONE","body":"symfony/translation/Resources/schemas/xliff-core-1.2-strict.xsd\r\nhttps://github.com/symfony/translation/blob/master/Resources/schemas/xliff-core-1.2-strict.xsd\r\n\r\nhas Windows line endings checked in.\r\nThis caused problems on git repos which has setup unix line endings upon checkout. So the file will show up as modified.\r\n\r\n","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26815","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26815/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26815/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26815/events","html_url":"https://github.com/symfony/symfony/issues/26815","id":311633696,"number":26815,"title":"Functional Test - Symfony\\Bridge\\Twig\\Extension\\CsrfExtension not found","user":{"login":"silverbackdan","id":25174262,"avatar_url":"https://avatars0.githubusercontent.com/u/25174262?v=4","gravatar_id":"","url":"https://api.github.com/users/silverbackdan","html_url":"https://github.com/silverbackdan","followers_url":"https://api.github.com/users/silverbackdan/followers","following_url":"https://api.github.com/users/silverbackdan/following{/other_user}","gists_url":"https://api.github.com/users/silverbackdan/gists{/gist_id}","starred_url":"https://api.github.com/users/silverbackdan/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/silverbackdan/subscriptions","organizations_url":"https://api.github.com/users/silverbackdan/orgs","repos_url":"https://api.github.com/users/silverbackdan/repos","events_url":"https://api.github.com/users/silverbackdan/events{/privacy}","received_events_url":"https://api.github.com/users/silverbackdan/received_events","type":"User","site_admin":false},"labels":[{"id":100079,"url":"https://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":148416,"url":"https://api.github.com/repos/symfony/symfony/labels/FrameworkBundle","name":"FrameworkBundle","color":"DDDDDD","default":false},{"id":237550465,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Reviewed","name":"Status: Reviewed","color":"bfe5bf","default":false},{"id":337187802,"url":"https://api.github.com/repos/symfony/symfony/labels/TwigBridge","name":"TwigBridge","color":"dddddd","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-04-05T14:27:32Z","updated_at":"2018-04-06T05:26:13Z","closed_at":"2018-04-06T05:26:13Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | yes\r\n| RFC?             | no\r\n| Symfony version  | dev-master\r\n\r\nWhile running CI on dev-master I get\r\n```\r\nError: Class 'Symfony\\Bridge\\Twig\\Extension\\CsrfExtension' not found\r\n```\r\nIn a functional test extending `WebTestCase` when calling `request` on the client.\r\n\r\nIt is working fine on 4.0. Here is my CI results:\r\nhttps://travis-ci.org/silverbackis/ApiComponentBundle/builds/362645681?utm_source=email&utm_medium=notification\r\nIt has been this way for the last 7 days it seems.\r\n\r\nI've had a quick look to see if perhaps I need to change my config for the test bundle or if Twig extensions now need to be installed separately but couldn't see anything. In the test form I have disabled csrf protection as well.","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26812","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26812/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26812/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26812/events","html_url":"https://github.com/symfony/symfony/issues/26812","id":311548457,"number":26812,"title":"[DI] Environment variables lack type","user":{"login":"peter-gribanov","id":1954436,"avatar_url":"https://avatars1.githubusercontent.com/u/1954436?v=4","gravatar_id":"","url":"https://api.github.com/users/peter-gribanov","html_url":"https://github.com/peter-gribanov","followers_url":"https://api.github.com/users/peter-gribanov/followers","following_url":"https://api.github.com/users/peter-gribanov/following{/other_user}","gists_url":"https://api.github.com/users/peter-gribanov/gists{/gist_id}","starred_url":"https://api.github.com/users/peter-gribanov/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/peter-gribanov/subscriptions","organizations_url":"https://api.github.com/users/peter-gribanov/orgs","repos_url":"https://api.github.com/users/peter-gribanov/repos","events_url":"https://api.github.com/users/peter-gribanov/events{/privacy}","received_events_url":"https://api.github.com/users/peter-gribanov/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2018-04-05T10:05:52Z","updated_at":"2018-04-05T13:22:20Z","closed_at":"2018-04-05T10:23:24Z","author_association":"CONTRIBUTOR","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 3.4.7\r\n\r\nI have a problem with the type of environment variables:\r\n\r\n> Invalid type for path \"framework.ssi.enabled\". Expected boolean, but got string.\r\n\r\nMy config\r\n\r\n```yml\r\nparameters:\r\n    env(NGINX_SSI): 0\r\n\r\nframework:\r\n    ssi:\r\n        enabled: '%env(bool:NGINX_SSI)%'\r\n```\r\n\r\nBased on this #23901 PR (in [blog](https://symfony.com/blog/new-in-symfony-3-4-advanced-environment-variables)), everything should work, but no.\r\n\r\nI tried this:\r\n\r\n```yml\r\nparameters:\r\n    env(NGINX_SSI): false\r\n\r\nframework:\r\n    ssi:\r\n        enabled: '%env(bool:NGINX_SSI)%'\r\n```\r\n\r\nAnd this:\r\n\r\n```yml\r\nparameters:\r\n    env(NGINX_SSI): 0\r\n    ssi_enabled: '%env(bool:NGINX_SSI)%'\r\n\r\nframework:\r\n    ssi:\r\n        enabled: '%ssi_enabled%'\r\n```\r\n\r\nBut result does not changed.\r\nWhat am i doing wrong?","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26810","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26810/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26810/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26810/events","html_url":"https://github.com/symfony/symfony/issues/26810","id":311515745,"number":26810,"title":"[EventDispatcher] Possible bug in test","user":{"login":"a-s-y-n-c","id":32012197,"avatar_url":"https://avatars3.githubusercontent.com/u/32012197?v=4","gravatar_id":"","url":"https://api.github.com/users/a-s-y-n-c","html_url":"https://github.com/a-s-y-n-c","followers_url":"https://api.github.com/users/a-s-y-n-c/followers","following_url":"https://api.github.com/users/a-s-y-n-c/following{/other_user}","gists_url":"https://api.github.com/users/a-s-y-n-c/gists{/gist_id}","starred_url":"https://api.github.com/users/a-s-y-n-c/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/a-s-y-n-c/subscriptions","organizations_url":"https://api.github.com/users/a-s-y-n-c/orgs","repos_url":"https://api.github.com/users/a-s-y-n-c/repos","events_url":"https://api.github.com/users/a-s-y-n-c/events{/privacy}","received_events_url":"https://api.github.com/users/a-s-y-n-c/received_events","type":"User","site_admin":false},"labels":[{"id":100079,"url":"https://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":151519,"url":"https://api.github.com/repos/symfony/symfony/labels/EventDispatcher","name":"EventDispatcher","color":"DDDDDD","default":false},{"id":237003792,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Needs%20Review","name":"Status: Needs Review","color":"ededed","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-04-05T08:25:25Z","updated_at":"2018-04-05T14:26:06Z","closed_at":"2018-04-05T14:25:59Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 4.0\r\n\r\nHi, on [this line](https://github.com/symfony/event-dispatcher/blob/606803460db12e1997cbde2504dfdd0175798885/Tests/AbstractEventDispatcherTest.php#L161) `$otherListener->preFoo` is registered as a listener.\r\n\r\nIs this not a bug? 3 lines later, the `$otherListener->postFooInvoked` is checked. The only way it could ever change to `true` is by `$otherListener->postFoo` being called...\r\n\r\nThe test is passing, but I was wondering if this is not a \"false positive\".\r\n\r\nThanks.\r\n","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26809","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26809/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26809/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26809/events","html_url":"https://github.com/symfony/symfony/issues/26809","id":311481573,"number":26809,"title":"Annotation assertions not detected on Windows","user":{"login":"greg0ire","id":657779,"avatar_url":"https://avatars1.githubusercontent.com/u/657779?v=4","gravatar_id":"","url":"https://api.github.com/users/greg0ire","html_url":"https://github.com/greg0ire","followers_url":"https://api.github.com/users/greg0ire/followers","following_url":"https://api.github.com/users/greg0ire/following{/other_user}","gists_url":"https://api.github.com/users/greg0ire/gists{/gist_id}","starred_url":"https://api.github.com/users/greg0ire/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/greg0ire/subscriptions","organizations_url":"https://api.github.com/users/greg0ire/orgs","repos_url":"https://api.github.com/users/greg0ire/repos","events_url":"https://api.github.com/users/greg0ire/events{/privacy}","received_events_url":"https://api.github.com/users/greg0ire/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":7,"created_at":"2018-04-05T05:56:23Z","updated_at":"2018-04-05T06:43:30Z","closed_at":"2018-04-05T06:43:30Z","author_association":"CONTRIBUTOR","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 4.0.7\r\n\r\nWe have an issue on doctrine dbal with an assertion as annotation not being detected and the test being marked as risky on Windows:\r\n\r\n> This test did not perform any assertions\r\nOK, but incomplete, skipped, or risky tests!\r\n\r\nHere is a PR where I tried to isolate the issue as much as possible: https://github.com/doctrine/dbal/pull/3087, leaving only a class and its test.\r\n\r\n[The test code](https://github.com/greg0ire/dbal/blob/isolate_risky_test/tests/Doctrine/Tests/DBAL/FooTest.php):\r\n\r\n```php\r\n<?php\r\n\r\nnamespace Doctrine\\Tests\\DBAL\\Schema;\r\n\r\nuse Doctrine\\DBAL\\Foo;\r\n\r\nclass ColumnTest extends \\PHPUnit\\Framework\\TestCase\r\n{\r\n    /**\r\n     * @group legacy\r\n     * @expectedDeprecation Hi\r\n     */\r\n    public function testThatIsGoingToBeRisky() : void\r\n    {\r\n        new Foo();\r\n    }\r\n}\r\n```\r\n\r\nThe subsequent appveyor build: https://ci.appveyor.com/project/doctrine/dbal/build/1.0.114/job/3nke06rul3e04598","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26807","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26807/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26807/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26807/events","html_url":"https://github.com/symfony/symfony/issues/26807","id":311420529,"number":26807,"title":"[Security] Backwards breaking change in SimpleAuthenticationProvider","user":{"login":"emarref","id":556594,"avatar_url":"https://avatars0.githubusercontent.com/u/556594?v=4","gravatar_id":"","url":"https://api.github.com/users/emarref","html_url":"https://github.com/emarref","followers_url":"https://api.github.com/users/emarref/followers","following_url":"https://api.github.com/users/emarref/following{/other_user}","gists_url":"https://api.github.com/users/emarref/gists{/gist_id}","starred_url":"https://api.github.com/users/emarref/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/emarref/subscriptions","organizations_url":"https://api.github.com/users/emarref/orgs","repos_url":"https://api.github.com/users/emarref/repos","events_url":"https://api.github.com/users/emarref/events{/privacy}","received_events_url":"https://api.github.com/users/emarref/received_events","type":"User","site_admin":false},"labels":[{"id":100079,"url":"https://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":99600,"url":"https://api.github.com/repos/symfony/symfony/labels/Security","name":"Security","color":"DDDDDD","default":false},{"id":237003792,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Needs%20Review","name":"Status: Needs Review","color":"ededed","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-04-04T23:04:10Z","updated_at":"2018-04-05T07:39:47Z","closed_at":"2018-04-04T23:09:37Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | yes\r\n| RFC?             | no\r\n| Symfony version  | 3.4.7\r\n\r\nThe update from 3.4.6 to 3.4.7 is producing a fatal error in the `SimpleAuthenticationProvider` class when an anonymous token is returned from the authenticator.\r\n\r\nThe specific change that I believe causes the issue is [cb9c92d06553f60a0b7b6b036c4b2a3c1813e738](https://github.com/symfony/symfony/commit/cb9c92d06553f60a0b7b6b036c4b2a3c1813e738?diff=unified#diff-2147e1b77fadc4352e73adffd0abfa89R43)\r\n\r\nI have a custom authenticator that implements the `SimplePreAuthenticatorInterface` as documented in the [How to Authenticate Users with API Keys](https://symfony.com/doc/current/security/api_key_authentication.html) docs. that may return an anonymous token. When the token is anonymous, the `getUser()` method on the token returns `\"anon.\"`. The `SimpleAuthenticationProvider` then attempts to pass this string to the `userChecker->checkPreAuth($user);` method which requires a `UserInterface` instance as an argument.\r\n\r\nIn versions `< 3.4.7` the anonymous token would be returned, or an exception thrown if no token was found. In `3.4.7` the above commit now does some pre/post user checks which do not support anonymous tokens.\r\n","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26805","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26805/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26805/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26805/events","html_url":"https://github.com/symfony/symfony/issues/26805","id":311387170,"number":26805,"title":"Web Profiler Bundle v4.0.7 breaks clearing cache in test env.","user":{"login":"tdbui22","id":3229541,"avatar_url":"https://avatars3.githubusercontent.com/u/3229541?v=4","gravatar_id":"","url":"https://api.github.com/users/tdbui22","html_url":"https://github.com/tdbui22","followers_url":"https://api.github.com/users/tdbui22/followers","following_url":"https://api.github.com/users/tdbui22/following{/other_user}","gists_url":"https://api.github.com/users/tdbui22/gists{/gist_id}","starred_url":"https://api.github.com/users/tdbui22/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/tdbui22/subscriptions","organizations_url":"https://api.github.com/users/tdbui22/orgs","repos_url":"https://api.github.com/users/tdbui22/repos","events_url":"https://api.github.com/users/tdbui22/events{/privacy}","received_events_url":"https://api.github.com/users/tdbui22/received_events","type":"User","site_admin":false},"labels":[{"id":100079,"url":"https://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":237003792,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Needs%20Review","name":"Status: Needs Review","color":"ededed","default":false},{"id":199779,"url":"https://api.github.com/repos/symfony/symfony/labels/WebProfilerBundle","name":"WebProfilerBundle","color":"DDDDDD","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-04-04T20:52:59Z","updated_at":"2018-04-05T07:40:01Z","closed_at":"2018-04-04T22:57:14Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | yes\r\n| RFC?             | yes/no\r\n| Symfony version  | v4.0.7\r\n\r\nThe changes to the web-profiler-bundle v4.0.7 causes this error\r\n[Symfony\\Component\\Routing\\Exception\\RouteNotFoundException]\r\n  Unable to generate a URL for the named route \"_profiler_open_file\" as such route does not exist.\r\n\r\nWhen clearing cache with test env.\r\nAPP_ENV=test bin/console cache:clear\r\n\r\nIn v4.0.6 the Resource/config/profiler.xml in the web-profiler-bundle had the service id debug.file_link_formatter using straight arguments whereas in v4.0.7 it is using a factory and uses the router to generate the url which the route does not exists in the test env.\r\n","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26798","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26798/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26798/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26798/events","html_url":"https://github.com/symfony/symfony/issues/26798","id":311294052,"number":26798,"title":"Cache warmer priority change in 4.0.7","user":{"login":"jaikdean","id":348408,"avatar_url":"https://avatars3.githubusercontent.com/u/348408?v=4","gravatar_id":"","url":"https://api.github.com/users/jaikdean","html_url":"https://github.com/jaikdean","followers_url":"https://api.github.com/users/jaikdean/followers","following_url":"https://api.github.com/users/jaikdean/following{/other_user}","gists_url":"https://api.github.com/users/jaikdean/gists{/gist_id}","starred_url":"https://api.github.com/users/jaikdean/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jaikdean/subscriptions","organizations_url":"https://api.github.com/users/jaikdean/orgs","repos_url":"https://api.github.com/users/jaikdean/repos","events_url":"https://api.github.com/users/jaikdean/events{/privacy}","received_events_url":"https://api.github.com/users/jaikdean/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":5,"created_at":"2018-04-04T16:05:03Z","updated_at":"2018-04-07T04:45:25Z","closed_at":"2018-04-07T04:45:25Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | yes\r\n| RFC?             | no\r\n| Symfony version  | 4.0.7\r\n\r\nSince updating from 4.0.6 to 4.0.7, it appears the priorities of our cache warmers has changed.\r\n\r\nThe output from debugging the DI container is exactly the same in both versions:\r\n\r\n```bash\r\n$ php bin/console debug:container --tag=kernel.cache_warmer --show-private\r\n\r\nSymfony Container Public and Private Services Tagged with \"kernel.cache_warmer\" Tag\r\n===================================================================================\r\n\r\n ---------------------------------------- ---------- --------------------------------------------------------------------- \r\n  Service ID                               priority   Class name                                                           \r\n ---------------------------------------- ---------- --------------------------------------------------------------------- \r\n  App\\Cors\\CorsPathsCacheWarmer                       App\\Cors\\CorsPathsCacheWarmer                                        \r\n  annotations.cache_warmer                            Symfony\\Bundle\\FrameworkBundle\\CacheWarmer\\AnnotationsCacheWarmer    \r\n  doctrine.orm.proxy_cache_warmer                     Symfony\\Bridge\\Doctrine\\CacheWarmer\\ProxyCacheWarmer                 \r\n  router.cache_warmer                                 Symfony\\Bundle\\FrameworkBundle\\CacheWarmer\\RouterCacheWarmer         \r\n  serializer.mapping.cache_warmer                     Symfony\\Bundle\\FrameworkBundle\\CacheWarmer\\SerializerCacheWarmer     \r\n  sonata.admin.route.cache_warmup                     Sonata\\AdminBundle\\Route\\RoutesCacheWarmUp                           \r\n  templating.cache_warmer.template_paths   20         Symfony\\Bundle\\FrameworkBundle\\CacheWarmer\\TemplatePathsCacheWarmer  \r\n  translation.warmer                                  Symfony\\Bundle\\FrameworkBundle\\CacheWarmer\\TranslationsCacheWarmer   \r\n  twig.cache_warmer                                   Symfony\\Bundle\\TwigBundle\\CacheWarmer\\TemplateCacheCacheWarmer       \r\n  twig.template_cache_warmer                          Symfony\\Bundle\\TwigBundle\\CacheWarmer\\TemplateCacheWarmer            \r\n  validator.mapping.cache_warmer                      Symfony\\Bundle\\Framew
8000
orkBundle\\CacheWarmer\\ValidatorCacheWarmer      \r\n ---------------------------------------- ---------- --------------------------------------------------------------------- \r\n```\r\n\r\nClearing the cache in 4.0.6 works, whereas our `App\\Cors\\CorsPathsCacheWarmer` causes an exception in 4.0.7. We have fixed this by setting a large negative priority on this warmer, but that wasn't required in any previous version from 3.4.0 upwards.\r\n\r\n```bash\r\n$ php bin/console cache:clear -vvv\r\n\r\nIn DelegatingLoader.php line 65:\r\n                                                                               \r\n  [Symfony\\Component\\Config\\Exception\\FileLoaderLoadException]                 \r\n  Cannot load resource \"kernel:loadRoutes\". Make sure there is a loader suppo  \r\n  rting the \"service\" type.                                                    \r\n                                                                               \r\n\r\nException trace:\r\n Symfony\\Bundle\\FrameworkBundle\\Routing\\DelegatingLoader->load() at /var/www/symfony/vendor/symfony/framework-bundle/Routing/Router.php:56\r\n Symfony\\Bundle\\FrameworkBundle\\Routing\\Router->getRouteCollection() at /var/www/symfony/vendor/symfony/routing/Router.php:363\r\n Symfony\\Component\\Routing\\Router->getGeneratorDumperInstance() at /var/www/symfony/vendor/symfony/routing/Router.php:328\r\n Symfony\\Component\\Routing\\Router->Symfony\\Component\\Routing\\{closure}() at n/a:n/a\r\n call_user_func() at /var/www/symfony/vendor/symfony/config/ResourceCheckerConfigCacheFactory.php:43\r\n Symfony\\Component\\Config\\ResourceCheckerConfigCacheFactory->cache() at /var/www/symfony/vendor/symfony/routing/Router.php:336\r\n Symfony\\Component\\Routing\\Router->getGenerator() at /var/www/symfony/vendor/symfony/routing/Router.php:240\r\n Symfony\\Component\\Routing\\Router->generate() at /var/www/symfony/var/cache/dev/Container94xlEbi/srcDevDebugProjectContainer.php:2882\r\n Container94xlEbi\\srcDevDebugProjectContainer->getDebug_FileLinkFormatterService() at /var/www/symfony/var/cache/dev/Container94xlEbi/srcDevDebugProjectContainer.php:2681\r\n Container94xlEbi\\srcDevDebugProjectContainer->getTwigService() at /var/www/symfony/var/cache/dev/Container94xlEbi/getTwigSwiftMailerService.php:15\r\n require() at /var/www/symfony/var/cache/dev/Container94xlEbi/srcDevDebugProjectContainer.php:617\r\n Container94xlEbi\\srcDevDebugProjectContainer->load() at /var/www/symfony/var/cache/dev/Container94xlEbi/getDoctrine_Dbal_DefaultConnectionService.php:50\r\n require() at /var/www/symfony/var/cache/dev/Container94xlEbi/srcDevDebugProjectContainer.php:617\r\n Container94xlEbi\\srcDevDebugProjectContainer->load() at /var/www/symfony/var/cache/dev/Container94xlEbi/getDoctrine_Orm_DefaultEntityManagerService.php:55\r\n require() at /var/www/symfony/var/cache/dev/Container94xlEbi/srcDevDebugProjectContainer.php:617\r\n Container94xlEbi\\srcDevDebugProjectContainer->load() at /var/www/symfony/var/cache/dev/Container94xlEbi/srcDevDebugProjectContainer.php:642\r\n Container94xlEbi\\srcDevDebugProjectContainer->getAdminUserAdminService() at /var/www/symfony/vendor/symfony/dependency-injection/Container.php:241\r\n Symfony\\Component\\DependencyInjection\\Container->get() at /var/www/symfony/vendor/sonata-project/admin-bundle/src/Admin/Pool.php:268\r\n Sonata\\AdminBundle\\Admin\\Pool->getInstance() at /var/www/symfony/vendor/sonata-project/admin-bundle/src/Route/AdminPoolLoader.php:58\r\n Sonata\\AdminBundle\\Route\\AdminPoolLoader->load() at /var/www/symfony/vendor/symfony/config/Loader/FileLoader.php:153\r\n Symfony\\Component\\Config\\Loader\\FileLoader->doImport() at /var/www/symfony/vendor/symfony/config/Loader/FileLoader.php:90\r\n Symfony\\Component\\Config\\Loader\\FileLoader->import() at /var/www/symfony/vendor/symfony/routing/Loader/YamlFileLoader.php:153\r\n Symfony\\Component\\Routing\\Loader\\YamlFileLoader->parseImport() at /var/www/symfony/vendor/symfony/routing/Loader/YamlFileLoader.php:83\r\n Symfony\\Component\\Routing\\Loader\\YamlFileLoader->load() at /var/www/symfony/vendor/symfony/config/Loader/FileLoader.php:153\r\n Symfony\\Component\\Config\\Loader\\FileLoader->doImport() at /var/www/symfony/vendor/symfony/config/Loader/FileLoader.php:90\r\n Symfony\\Component\\Config\\Loader\\FileLoader->import() at /var/www/symfony/vendor/symfony/routing/Loader/GlobFileLoader.php:32\r\n Symfony\\Component\\Routing\\Loader\\GlobFileLoader->load() at /var/www/symfony/vendor/symfony/routing/RouteCollectionBuilder.php:374\r\n Symfony\\Component\\Routing\\RouteCollectionBuilder->load() at /var/www/symfony/vendor/symfony/routing/RouteCollectionBuilder.php:62\r\n Symfony\\Component\\Routing\\RouteCollectionBuilder->import() at /var/www/symfony/src/Kernel.php:74\r\n App\\Kernel->configureRoutes() at /var/www/symfony/vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php:92\r\n App\\Kernel->loadRoutes() at n/a:n/a\r\n call_user_func() at /var/www/symfony/vendor/symfony/routing/Loader/ObjectRouteLoader.php:65\r\n Symfony\\Component\\Routing\\Loader\\ObjectRouteLoader->load() at /var/www/symfony/vendor/symfony/config/Loader/DelegatingLoader.php:40\r\n Symfony\\Component\\Config\\Loader\\DelegatingLoader->load() at /var/www/symfony/vendor/symfony/framework-bundle/Routing/DelegatingLoader.php:70\r\n Symfony\\Bundle\\FrameworkBundle\\Routing\\DelegatingLoader->load() at /var/www/symfony/vendor/symfony/framework-bundle/Routing/Router.php:56\r\n Symfony\\Bundle\\FrameworkBundle\\Routing\\Router->getRouteCollection() at /var/www/symfony/src/Cors/CorsPathsCacheWarmer.php:42\r\n App\\Cors\\CorsPathsCacheWarmer->warmUp() at /var/www/symfony/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php:48\r\n Symfony\\Component\\HttpKernel\\CacheWarmer\\CacheWarmerAggregate->warmUp() at /var/www/symfony/vendor/symfony/http-kernel/Kernel.php:554\r\n Symfony\\Component\\HttpKernel\\Kernel->initializeContainer() at /var/www/symfony/vendor/symfony/http-kernel/Kernel.php:125\r\n Symfony\\Component\\HttpKernel\\Kernel->boot() at /var/www/symfony/vendor/symfony/framework-bundle/Console/Application.php:64\r\n Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun() at /var/www/symfony/vendor/symfony/console/Application.php:143\r\n Symfony\\Component\\Console\\Application->run() at /var/www/symfony/bin/console:39\r\n```","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26796","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26796/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26796/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26796/events","html_url":"https://github.com/symfony/symfony/issues/26796","id":311268936,"number":26796,"title":"Unable to register extension \"Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension\" as extensions have already been initialized","user":{"login":"ivoba","id":471254,"avatar_url":"https://avatars0.githubusercontent.com/u/471254?v=4","gravatar_id":"","url":"https://api.github.com/users/ivoba","html_url":"https://github.com/ivoba","followers_url":"https://api.github.com/users/ivoba/followers","following_url":"https://api.github.com/users/ivoba/following{/other_user}","gists_url":"https://api.github.com/users/ivoba/gists{/gist_id}","starred_url":"https://api.github.com/users/ivoba/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ivoba/subscriptions","organizations_url":"https://api.github.com/users/ivoba/orgs","repos_url":"https://api.github.com/users/ivoba/repos","events_url":"https://api.github.com/users/ivoba/events{/privacy}","received_events_url":"https://api.github.com/users/ivoba/received_events","type":"User","site_admin":false},"labels":[{"id":337187802,"url":"https://api.github.com/repos/symfony/symfony/labels/TwigBridge","name":"TwigBridge","color":"dddddd","default":false},{"id":2932845,"url":"https://api.github.com/repos/symfony/symfony/labels/Unconfirmed","name":"Unconfirmed","color":"444444","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":14,"created_at":"2018-04-04T15:03:02Z","updated_at":"2018-04-07T07:20:48Z","closed_at":"2018-04-07T07:20:48Z","author_association":"CONTRIBUTOR","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 3.4.7\r\n\r\n<!--\r\n- Please fill in this template according to your issue.\r\n- For support request or how-tos, visit https://symfony.com/support\r\n- Otherwise, replace this comment by the description of your issue.\r\n-->\r\n\r\nSince upgrading from 3.4.6 to 3.4.7 i see a warning during `composer install` and also with `cache:clear`\r\n\r\n> [WARNING] Some commands could not be registered:                               \r\n> \r\n> In ExtensionSet.php line 156:\r\n>                                                                                \r\n>   Unable to register extension \"Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension\" as extensions have already been initialized. \r\n\r\nAny idea what could cause this?","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26793","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26793/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26793/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26793/events","html_url":"https://github.com/symfony/symfony/issues/26793","id":311233944,"number":26793,"title":"[Sf 3.4.7] Circular reference detected for service \"routing.loader\" on cache clear","user":{"login":"mmendjeli","id":38075039,"avatar_url":"https://avatars3.githubusercontent.com/u/38075039?v=4","gravatar_id":"","url":"https://api.github.com/users/mmendjeli","html_url":"https://github.com/mmendjeli","followers_url":"https://api.github.com/users/mmendjeli/followers","following_url":"https://api.github.com/users/mmendjeli/following{/other_user}","gists_url":"https://api.github.com/users/mmendjeli/gists{/gist_id}","starred_url":"https://api.github.com/users/mmendjeli/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/mmendjeli/subscriptions","organizations_url":"https://api.github.com/users/mmendjeli/orgs","repos_url":"https://api.github.com/users/mmendjeli/repos","events_url":"https://api.github.com/users/mmendjeli/events{/privacy}","received_events_url":"https://api.github.com/users/mmendjeli/received_events","type":"User","site_admin":false},"labels":[{"id":100079,"url":"https://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":237003792,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Needs%20Review","name":"Status: Needs Review","color":"ededed","default":false},{"id":199779,"url":"https://api.github.com/repos/symfony/symfony/labels/WebProfilerBundle","name":"WebProfilerBundle","color":"DDDDDD","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-04-04T13:38:58Z","updated_at":"2018-04-04T13:40:47Z","closed_at":"2018-04-04T13:40:33Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | yes/no\r\n| RFC?             | yes/no\r\n| Symfony version  | 3.4.7\r\n\r\n<!--\r\n- Please fill in this template according to your issue.\r\n- For support request or how-tos, visit https://symfony.com/support\r\n- Otherwise, replace this comment by the description of your issue.\r\n-->\r\nHello,\r\n\r\nUpdating one of our project from Sf 3.4.4 to 3.4.7 i see an error at cache:clear  command or any other cli command from the console.\r\n\r\n```\r\n./app/console cache:clear --no-warmup --env=local (same for dev)\r\n\r\nIn Container.php line 297:\r\n\r\n  Circular reference detected for service \"routing.loader\", path: \"routing.loader\".\r\n```\r\n\r\nTry to check our routing import but did not found any duplicate... anyway it is only appearing when updating to 3.4.7 .\r\n\r\nDid something changed related to this subject? do we need to take care of something in special in our configs?\r\n\r\nThx","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26789","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26789/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26789/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26789/events","html_url":"https://github.com/symfony/symfony/issues/26789","id":311209244,"number":26789,"title":"SF 3.4: Circular Reference detected for service \"routing.loader\"","user":{"login":"antondachauer","id":24891375,"avatar_url":"https://avatars1.githubusercontent.com/u/24891375?v=4","gravatar_id":"","url":"https://api.github.com/users/antondachauer","html_url":"https://github.com/antondachauer","followers_url":"https://api.github.com/users/antondachauer/followers","following_url":"https://api.github.com/users/antondachauer/following{/other_user}","gists_url":"https://api.github.com/users/antondachauer/gists{/gist_id}","starred_url":"https://api.github.com/users/antondachauer/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/antondachauer/subscriptions","organizations_url":"https://api.github.com/users/antondachauer/orgs","repos_url":"https://api.github.com/users/antondachauer/repos","events_url":"https://api.github.com/users/antondachauer/events{/privacy}","received_events_url":"https://api.github.com/users/antondachauer/received_events","type":"User","site_admin":false},"labels":[{"id":100079,"url":"https://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":237003792,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Needs%20Review","name":"Status: Needs Review","color":"ededed","default":false},{"id":199779,"url":"https://api.github.com/repos/symfony/symfony/labels/WebProfilerBundle","name":"WebProfilerBundle","color":"DDDDDD","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-04-04T12:29:54Z","updated_at":"2018-04-04T13:35:22Z","closed_at":"2018-04-04T13:00:22Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | yes/no\r\n| RFC?             | yes/no\r\n| Symfony version  | 3.4.7\r\n\r\nI have a Symfony 3.4 project and code from an old project (SF 2.1) - I want to migrade the code from the old project to the new one. In none of these both projects exists any service.\r\n\r\nBy running `php bin/console` I get the error `Circular reference detected for service \"routing.loader\", path: \"routing.loader\".` -> nothing works.\r\n\r\nException trace:\r\n```\r\n Symfony\\Component\\DependencyInjection\\Container->get() at /private/var/www/html/treeconsult/test/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Routing/Router.php:56\r\n Symfony\\Bundle\\FrameworkBundle\\Routing\\Router->getRouteCollection() at /private/var/www/html/treeconsult/test/vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php:363\r\n Symfony\\Component\\Routing\\Router->getGeneratorDumperInstance() at /private/var/www/html/treeconsult/test/vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php:328\r\n Symfony\\Component\\Routing\\Router->Symfony\\Component\\Routing\\{closure}() at n/a:n/a\r\n call_user_func() at /private/var/www/html/treeconsult/test/vendor/symfony/symfony/src/Symfony/Component/Config/ResourceCheckerConfigCacheFactory.php:43\r\n Symfony\\Component\\Config\\ResourceCheckerConfigCacheFactory->cache() at /private/var/www/html/treeconsult/test/vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php:336\r\n Symfony\\Component\\Routing\\Router->getGenerator() at /private/var/www/html/treeconsult/test/vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php:240\r\n Symfony\\Component\\Routing\\Router->generate() at /private/var/www/html/treeconsult/test/var/cache/dev/ContainerYqoe0c9/appDevDebugProjectContainer.php:1444\r\n ContainerYqoe0c9\\appDevDebugProjectContainer->getDebug_FileLinkFormatterService() at /private/var/www/html/treeconsult/test/var/cache/dev/ContainerYqoe0c9/appDevDebugProjectContainer.php:1009\r\n ContainerYqoe0c9\\appDevDebugProjectContainer->getTwigService() at /private/var/www/html/treeconsult/test/var/cache/dev/ContainerYqoe0c9/getAssetic_AssetManagerService.php:21\r\n require() at /private/var/www/html/treeconsult/test/var/cache/dev/ContainerYqoe0c9/appDevDebugProjectContainer.php:840\r\n ContainerYqoe0c9\\appDevDebugProjectContainer->load() at /private/var/www/html/treeconsult/test/var/cache/dev/ContainerYqoe0c9/getRouting_LoaderService.php:46\r\n require() at /private/var/www/html/treeconsult/test/var/cache/dev/ContainerYqoe0c9/appDevDebugProjectContainer.php:840\r\n ContainerYqoe0c9\\appDevDebugProjectContainer->load() at /private/var/www/html/treeconsult/test/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:304\r\n Symfony\\Component\\DependencyInjection\\Container->get() at /private/var/www/html/treeconsult/test/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Routing/Router.php:56\r\n Symfony\\Bundle\\FrameworkBundle\\Routing\\Router->getRouteCollection() at /private/var/www/html/treeconsult/test/vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php:363\r\n Symfony\\Component\\Routing\\Router->getGeneratorDumperInstance() at /private/var/www/html/treeconsult/test/vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php:328\r\n Symfony\\Component\\Routing\\Router->Symfony\\Component\\Routing\\{closure}() at n/a:n/a\r\n call_user_func() at /private/var/www/html/treeconsult/test/vendor/symfony/symfony/src/Symfony/Component/Config/ResourceCheckerConfigCacheFactory.php:43\r\n Symfony\\Component\\Config\\ResourceCheckerConfigCacheFactory->cache() at /private/var/www/html/treeconsult/test/vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php:336\r\n Symfony\\Component\\Routing\\Router->getGenerator() at /private/var/www/html/treeconsult/test/vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php:240\r\n Symfony\\Component\\Routing\\Router->generate() at /private/var/www/html/treeconsult/test/var/cache/dev/ContainerYqoe0c9/appDevDebugProjectContainer.php:1444\r\n ContainerYqoe0c9\\appDevDebugProjectContainer->getDebug_FileLinkFormatterService() at /private/var/www/html/treeconsult/test/var/cache/dev/ContainerYqoe0c9/appDevDebugProjectContainer.php:1292\r\n ContainerYqoe0c9\\appDevDebugProjectContainer->getDebug_DebugHandlersListenerService() at /private/var/www/html/treeconsult/test/var/cache/dev/ContainerYqoe0c9/appDevDebugProjectContainer.php:1365\r\n ContainerYqoe0c9\\appDevDebugProjectContainer->ContainerYqoe0c9\\{closure}() at /private/var/www/html/treeconsult/test/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:229\r\n Symfony\\Component\\EventDispatcher\\EventDispatcher->sortListeners() at /private/var/www/html/treeconsult/test/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:61\r\n Symfony\\Component\\EventDispatcher\\EventDispatcher->getListeners() at /private/var/www/html/treeconsult/test/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php:128\r\n Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher->getListeners() at /private/var/www/html/treeconsult/test/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php:250\r\n Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->preProcess() at /private/var/www/html/treeconsult/test/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php:134\r\n Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->dispatch() at /private/var/www/html/treeconsult/test/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:961\r\n Symfony\\Component\\Console\\Application->doRunCommand() at /private/var/www/html/treeconsult/test/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:86\r\n Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand() at /private/var/www/html/treeconsult/test/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:248\r\n Symfony\\Component\\Console\\Application->doRun() at /private/var/www/html/treeconsult/test/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:74\r\n Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun() at /private/var/www/html/treeconsult/test/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:148\r\n Symfony\\Component\\Console\\Application->run() at /private/var/www/html/treeconsult/test/bin/console:27\r\n```\r\n\r\nInstalled packages (`composer info`):\r\n```\r\ncomposer/ca-bundle                   1.1.1   Lets you find a path to the system CA bundle, and includes a fallback to the Mozilla CA bundle.\r\ndoctrine/annotations                 v1.6.0  Docblock Annotations Parser\r\ndoctrine/cache                       v1.7.1  Caching library offering an object-oriented API for many cache backends\r\ndoctrine/collections                 v1.5.0  Collections Abstraction library\r\ndoctrine/common                      v2.8.1  Common Library for Doctrine projects\r\ndoctrine/dbal                        v2.7.0  Database Abstraction Layer\r\ndoctrine/doctrine-bundle             1.8.1   Symfony DoctrineBundle\r\ndoctrine/doctrine-cache-bundle       1.3.3   Symfony Bundle for Doctrine Cache\r\ndoctrine/inflector                   v1.3.0  Common String Manipulations with regard to casing and singular/plural rules.\r\ndoctrine/instantiator                1.1.0   A small, lightweight utility to instantiate objects in PHP without invoking their constructors\r\ndoctrine/lexer                       v1.0.1  Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.\r\ndoctrine/orm                         v2.6.1  Object-Relational-Mapper for PHP\r\nfig/link-util                        1.0.0   Common utility implementations for HTTP links\r\nfriendsofsymfony/user-bundle         v2.1.2  Symfony FOSUserBundle\r\nincenteev/composer-parameter-handler v2.1.3  Composer script handling your ignored parameter file\r\njdorn/sql-formatter                  v1.2.17 a PHP SQL highlighting library\r\nkriswallsmith/assetic                v1.4.0  Asset Management for PHP\r\nmonolog/monolog                      1.23.0  Sends your logs to files, sockets, inboxes, databases and various web services\r\nparagonie/random_compat              v2.0.11 PHP 5.x polyfill for random_bytes() and random_int() from PHP 7\r\npsr/cache                            1.0.1   Common interface for caching libraries\r\npsr/container                        1.0.0   Common Container Interface (PHP FIG PSR-11)\r\npsr/link                             1.0.0   Common interfaces for HTTP links\r\npsr/log                              1.0.2   Common interface for logging libraries\r\npsr/simple-cache                     1.0.1   Common interfaces for simple caching\r\nsensio/distribution-bundle           v5.0.21 Base bundle for Symfony Distributions\r\nsensio/framework-extra-bundle        v5.1.6  This bundle provides a way to configure your controllers with annotations\r\nsensio/generator-bundle              v3.1.7  This bundle generates code for you\r\nsensiolabs/security-checker          v4.1.8  A security checker for your composer.lock\r\nswiftmailer/swiftmailer              v5.4.9  Swiftmailer, free feature-rich PHP mailer\r\nsymfony/assetic-bundle               v2.8.2  Integrates Assetic into Symfony2\r\nsymfony/monolog-bundle               v3.2.0  Symfony MonologBundle\r\nsymfony/phpunit-bridge               v3.4.7  Symfony PHPUnit Bridge\r\nsymfony/polyfill-apcu                v1.7.0  Symfony polyfill backporting apcu_* functions to lower PHP versions\r\nsymfony/polyfill-intl-icu            v1.7.0  Symfony polyfill for intl's ICU-related data and classes\r\nsymfony/polyfill-mbstring            v1.7.0  Symfony polyfill for the Mbstring extension\r\nsymfony/polyfill-php56               v1.7.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions\r\nsymfony/polyfill-php70               v1.7.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions\r\nsymfony/polyfill-util                v1.7.0  Symfony utilities for portability of PHP codes\r\nsymfony/swiftmailer-bundle           v2.6.7  Symfony SwiftmailerBundle\r\nsymfony/symfony                      v3.4.7  The Symfony PHP framework\r\ntwig/twig                            v2.4.8  Twig, the flexible, fast, and secure template language for PHP\r\n```\r\n\r\nAny ideas how to fix it? Thanks!","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26784","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26784/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26784/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26784/events","html_url":"https://github.com/symfony/symfony/issues/26784","id":311098230,"number":26784,"title":"web-profiler-bundle update from v4.0.5 to v4.0.7 breaks","user":{"login":"alcohol","id":21414,"avatar_url":"https://avatars0.githubusercontent.com/u/21414?v=4","gravatar_id":"","url":"https://api.github.com/users/alcohol","html_url":"https://github.com/alcohol","followers_url":"https://api.github.com/users/alcohol/followers","following_url":"https://api.github.com/users/alcohol/following{/other_user}","gists_url":"https://api.github.com/users/alcohol/gists{/gist_id}","starred_url":"https://api.github.com/users/alcohol/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/alcohol/subscriptions","organizations_url":"https://api.github.com/users/alcohol/orgs","repos_url":"https://api.github.com/users/alcohol/repos","events_url":"https://api.github.com/users/alcohol/events{/privacy}","received_events_url":"https://api.github.com/users/alcohol/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":13,"created_at":"2018-04-04T06:14:47Z","updated_at":"2018-04-04T08:55:08Z","closed_at":"2018-04-04T06:32:21Z","author_association":"CONTRIBUTOR","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | maybe?\r\n| Feature request? | no\r\n| BC Break report? | maybe?\r\n| RFC?             | no\r\n| Symfony version  | 4.0.x\r\n\r\nRelated project commit: https://github.com/alcohol/paste.robbast.nl/commit/1c1a1da627627751acfa510b672027019f96f210\r\nRelated travis build: https://travis-ci.org/alcohol/paste.robbast.nl/jobs/361979916\r\n\r\nI use only a few Symfony components, so maybe that is why it does not work as expected; when updating `web-profiler-bundle` from [v4.0.5 to v4.0.7](https://github.com/symfony/web-profiler-bundle/compare/v4.0.5...v4.0.7) all my web-tests started to fail because the application cannot generate a route due to a missing parameter or something (should flex not have auto-updated the configuration or is this route not part of the default config of the profiler \"bundle\"?).\r\n\r\n```\r\nSymfony\\Component\\Routing\\Exception\\RouteNotFoundException: \r\nUnable to generate a URL for the named route \"_profiler_open_file\" as such route does not exist.\r\n```\r\n\r\nDid I screw up the whole way flex is supposed to be used and such? :p\r\n\r\n","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26780","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26780/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26780/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26780/events","html_url":"https://github.com/symfony/symfony/issues/26780","id":310971568,"number":26780,"title":"[DependencyInjection] Circular reference detected for service \"routing.loader\", path: \"routing.loader\" ","user":{"login":"phansys","id":1231441,"avatar_url":"https://avatars0.githubusercontent.com/u/1231441?v=4","gravatar_id":"","url":"https://api.github.com/users/phansys","html_url":"https://github.com/phansys","followers_url":"https://api.github.com/users/phansys/followers","following_url":"https://api.github.com/users/phansys/following{/other_user}","gists_url":"https://api.github.com/users/phansys/gists{/gist_id}","starred_url":"https://api.github.com/users/phansys/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/phansys/subscriptions","organizations_url":"https://api.github.com/users/phansys/orgs","repos_url":"https://api.github.com/users/phansys/repos","events_url":"https://api.github.com/users/phansys/events{/privacy}","received_events_url":"https://api.github.com/users/phansys/received_events","type":"User","site_admin":false},"labels":[{"id":100079,"url":"https://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":237003792,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Needs%20Review","name":"Status: Needs Review","color":"ededed","default":false},{"id":199779,"url":"https://api.github.com/repos/symfony/symfony/labels/WebProfilerBundle","name":"WebProfilerBundle","color":"DDDDDD","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-04-03T19:43:46Z","updated_at":"2018-04-04T06:08:23Z","closed_at":"2018-04-04T06:08:14Z","author_association":"CONTRIBUTOR","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 3.4.7\r\n\r\nAfter updating from 3.4.6 to 3.4.7, following exception is thrown while `cache:clear` execution if `AsseticBundle` is enabled:\r\n```\r\n[Symfony\\Component\\DependencyInjection\\Exception\\ServiceCircularReferenceException]  \r\n  Circular reference detected for service \"routing.loader\", path: \"routing.loader\".\r\n```\r\nExample using `symfony/framework-standard-edition`: https://github.com/phansys/symfony-standard/commit/f6b3c3b32935f096e48f9bead6a2c6d6f2d920e6.","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26779","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26779/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26779/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26779/events","html_url":"https://github.com/symfony/symfony/issues/26779","id":310931785,"number":26779,"title":"can not valid form from ajax request after  migrating from symfony 2.7 to symfony 2.8","user":{"login":"persiasama","id":26333225,"avatar_url":"https://avatars3.githubusercontent.com/u/26333225?v=4","gravatar_id":"","url":"https://api.github.com/users/persiasama","html_url":"https://github.com/persiasama","followers_url":"https://api.github.com/users/persiasama/followers","following_url":"https://api.github.com/users/persiasama/following{/other_user}","gists_url":"https://api.github.com/users/persiasama/gists{/gist_id}","starred_url":"https://api.github.com/users/persiasama/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/persiasama/subscriptions","organizations_url":"https://api.github.com/users/persiasama/orgs","repos_url":"https://api.github.com/users/persiasama/repos","events_url":"https://api.github.com/users/persiasama/events{/privacy}","received_events_url":"https://api.github.com/users/persiasama/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-04-03T17:41:32Z","updated_at":"2018-04-05T13:34:13Z","cl
8000
osed_at":"2018-04-03T18:13:37Z","author_association":"NONE","body":" ##Hi\r\nI recently made a migration from symfony 2.7 to 2.8.\r\nI was using web service in my front office like this\r\n\r\n```\r\nxxxxxx/webservcice/post/\r\n{\r\n      \"blan_form\":{\r\n      \"datesKnown\":true,\r\n      \"duration\":1,\r\n      \"fromDate\":1522713600000,\r\n      \"toDate\":1522713.6,\r\n      \"name\":\"qdqsdsqd\"\r\n      },\"_token\":\"ZBMpqZoQNLf1NpCnDAelbjkW-35BF2bqqLmYZQknNJ8\"\r\n}\r\n```\r\n\r\nIn my controller in was using form factory to handle the request by my form\r\n\r\n```\r\n\r\n    public function postCreateTripAction(Request $request)\r\n    {\r\n        $this->tokenAuthorization($request);\r\n        $manager = $this->get('tb_trip_manager');\r\n        $trip = $manager->createTrip();\r\n        $form = $this->get('tb_trip.form_factory')->createForm($trip, array('method' => Request::METHOD_POST));\r\n        $form->handleRequest($request);\r\n        if ($form->isValid()) {\r\n            if (!$manager->isNewTrip($trip)) {\r\n                return $this->getViewHandler()->handle($this->onHandleTripError($trip));\r\n            }\r\n            $manager->saveTrip($trip, Request::METHOD_POST);\r\n            return $this->getViewHandler()->handle($this->onHandleTripSuccess($trip));\r\n        }\r\n        return $this->getViewHandler()->handle($this->onHandleTripError($form));\r\n    }\r\n\r\n```\r\nI declare my form like service\r\n```\r\n\r\n\r\n    tb_trip.form_type.default:\r\n        class: \"%trip_type.class%\"\r\n        arguments: [ \"%tb_trip.model.trip.class%\" ]\r\n        tags:\r\n            - { name: form.type }\r\n\r\n\r\n```\r\nMy form \r\n\r\n```\r\nclass TripType extends AbstractType\r\n{\r\n    /**\r\n     * @param FormBuilderInterface $builder\r\n     * @param array $options\r\n     */\r\n    public function buildForm(FormBuilderInterface $builder, array $options)\r\n    {\r\n        $builder\r\n            ->add(\r\n                'name',\r\n                'text',\r\n                array(\r\n                    'required' => false,\r\n                    'label' => 'Name of trip',\r\n                )\r\n            )\r\n            ->add(\r\n                'description',\r\n                'textarea',\r\n                array(\r\n                    'required' => false,\r\n                    'label' => 'Description of trip',\r\n                )\r\n            )\r\n\r\n            ->add(\r\n                'startingDest',\r\n                'text',\r\n                array(\r\n                    'required' => false,\r\n                    'label' => 'Staring destination of trip',\r\n                )\r\n            )\r\n            ->add(\r\n                'fromDate',\r\n                'integer',\r\n                array(\r\n                    'required' => false,\r\n                    'label' => 'from date of trip',\r\n                )\r\n            )\r\n            ->add(\r\n                'toDate',\r\n                'integer',\r\n                array(\r\n                    'required' => false,\r\n                    'label' => 'Ed date of trip',\r\n                )\r\n            )\r\n            ->add(\r\n                'cover',\r\n                new ImageType(),\r\n                array(\r\n                    'required' => false,\r\n                    'label' => 'The cover of this entry',\r\n                )\r\n            )\r\n            ->add(\r\n                'duration',\r\n                'integer',\r\n                array(\r\n                    'required' => false,\r\n                    'label' => 'Duration of trip',\r\n                )\r\n            )\r\n            ->add(\r\n                'published',\r\n                'checkbox',\r\n                array(\r\n                    'required' => false,\r\n                    'label' => 'privacy of trip',\r\n                )\r\n            )\r\n            ->add(\r\n                'mapLines',\r\n                'checkbox',\r\n                array(\r\n                    'required' => false,\r\n                    'label' => 'show  trip lines',\r\n                )\r\n            )\r\n            ->add(\r\n                'datesKnown',\r\n                'checkbox',\r\n                array(\r\n                    'required' => false,\r\n                    'label' => 'Boolean to check if dates known or not',\r\n\r\n                )\r\n            )\r\n            ->add(\r\n                'themes',\r\n                'entity',\r\n                array(\r\n                    'class' => 'TB\\Bundle\\PlatformBundle\\Entity\\Theme',\r\n                    'property' => 'name',\r\n                    'multiple' => true,\r\n                    'label' => 'Array of trip themes',\r\n                )\r\n            );\r\n\r\n    }\r\n\r\n    /**\r\n     * @param OptionsResolverInterface $resolver\r\n     */\r\n    public function setDefaultOptions(OptionsResolverInterface $resolver)\r\n    {\r\n        $resolver->setDefaults(\r\n            array(\r\n                'data_class' => \\TB\\Bundle\\PlatformBundle\\Entity\\Blan::class,\r\n                'csrf_protection' => false,\r\n            )\r\n        );\r\n    }\r\n\r\n    /**\r\n     * Get block prefix\r\n     * @return string\r\n     */\r\n    public function getBlockPrefix()\r\n    {\r\n        return 'blan_form';\r\n    }\r\n\r\n    /**\r\n     * Get name\r\n     * @return string\r\n     */\r\n    public function getName()\r\n    {\r\n        return $this->getBlockPrefix();\r\n    }\r\n}\r\n\r\n\r\n```\r\n\r\nbut now i got this error \r\n\r\nCould not load type \"blan_form\"\"\r\n\r\nblan_form normally is the name of my form \r\n\r\nAny Idea? thanks\r\n","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26778","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26778/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26778/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26778/events","html_url":"https://github.com/symfony/symfony/issues/26778","id":310915069,"number":26778,"title":"Cache warmup issues while migrating from 3.x to 4.x","user":{"login":"phansys","id":1231441,"avatar_url":"https://avatars0.githubusercontent.com/u/1231441?v=4","gravatar_id":"","url":"https://api.github.com/users/phansys","html_url":"https://github.com/phansys","followers_url":"https://api.github.com/users/phansys/followers","following_url":"https://api.github.com/users/phansys/following{/other_user}","gists_url":"https://api.github.com/users/phansys/gists{/gist_id}","starred_url":"https://api.github.com/users/phansys/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/phansys/subscriptions","organizations_url":"https://api.github.com/users/phansys/orgs","repos_url":"https://api.github.com/users/phansys/repos","events_url":"https://api.github.com/users/phansys/events{/privacy}","received_events_url":"https://api.github.com/users/phansys/received_events","type":"User","site_admin":false},"labels":[{"id":520300257,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Waiting%20feedback","name":"Status: Waiting feedback","color":"fef2c0","default":false},{"id":2932845,"url":"https://api.github.com/repos/symfony/symfony/labels/Unconfirmed","name":"Unconfirmed","color":"444444","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":10,"created_at":"2018-04-03T16:49:14Z","updated_at":"2018-04-05T14:03:32Z","closed_at":"2018-04-05T14:03:31Z","author_association":"CONTRIBUTOR","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 4.0.6\r\n\r\nI'm migrating an existing 3.x based project to 4.x. I have also updated the directory structure to make it compatible with Flex and started using environment variables instead static parameters, but I'm having some issues that were not present over 3.x. I understand these issues can be also caused by another dependency not directly related with any of `symfony/*` components, but this specific issue seems really weird for me.\r\nI'm using SonataAdminBundle and I have a trait responsible to expose a method called `setAuthorizationChecker()` (which receives an instance of `AuthorizationCheckerInterface`). This trait is used by some of the admins I have configured:\r\n\r\n<details>\r\n\r\n```php\r\nnamespace App\\Admin;\r\n\r\nuse Symfony\\Component\\Security\\Core\\Authorization\\AuthorizationCheckerInterface;\r\n\r\ntrait SecurityCheckerAdminTrait\r\n{\r\n    /**\r\n     * @var AuthorizationCheckerInterface\r\n     */\r\n    private $authorizationChecker;\r\n\r\n    /**\r\n     * @param AuthorizationCheckerInterface $authorizationChecker\r\n     */\r\n    public function setAuthorizationChecker(AuthorizationCheckerInterface $authorizationChecker): void\r\n    {\r\n        $this->authorizationChecker = $authorizationChecker;\r\n    }\r\n}\r\n```\r\n\r\n```php\r\n\r\nnamespace App\\Admin;\r\n\r\nuse Sonata\\AdminBundle\\Admin\\AbstractAdmin;\r\n\r\nclass UserAdmin extends AbstractAdmin\r\n{\r\n    use SecurityCheckerAdminTrait;\r\n}\r\n```\r\n\r\n```yaml\r\n# config/admin.yml (imported via \"imports\" from \"config/services.yaml\"\r\n\r\nadmin.user:\r\n    class: App\\Admin\\UserAdmin\r\n    arguments: [~, App\\Entity\\User, ~]\r\n    calls:\r\n        - [setAuthorizationChecker, ['@security.authorization_checker']]\r\n    tags:\r\n        - { name: sonata.admin, manager_type: orm, group: customer, label: admin.user }\r\n```\r\n</details>\r\n\r\n\r\nThe weird part comes when I try to execute `cache:clear` command:\r\n```\r\nPHP Fatal error:  Uncaught Symfony\\Component\\Debug\\Exception\\UndefinedMethodException: Attempted to call an undefined method named \"setAuthorizationChecker\" of class \"App\\Admin\\UserAdmin\". in /var/www/html/app/var/cache/local/ContainerNb6MoTM/srcLocalDebugProjectContainer.php:1542\r\n```\r\nI've edited the cached container in order to debug this issue, but I have no clue about how it is caused, since the used trait is present at output of `class_uses()`, but `method_exists()` and `is_callable()` calls return `false` (which is consistent with the thrown exception):\r\n```php\r\n// srcLocalDebugProjectContainer.php\r\n\r\nvar_dump(get_class($instance)); // outputs: string(19) \"App\\Admin\\UserAdmin\"\r\nvar_dump(class_uses($instance)); // outputs: array(1) { [\"App\\Admin\\SecurityCheckerAdminTrait\"]=>  string(35) \"App\\Admin\\SecurityCheckerAdminTrait\" }\r\nvar_dump(method_exists($instance, 'setAuthorizationChecker')); // outputs: bool(false)\r\nvar_dump(is_callable([$instance, 'setAuthorizationChecker'])); // outputs: bool(false)\r\nvar_dump(method_exists('App\\Admin\\SecurityCheckerAdminTrait', 'setAuthorizationChecker')); // outputs: bool(true)\r\n$instance->setAuthorizationChecker($o); // Raises the exception\r\n```\r\n\r\nAs I mentioned before, I'm not sure if this issue comes from Symfony itself, but I have found other problems too (like lazy services trying to be instantiated while cache warmup, when there was no attempt in 3.x).\r\n\r\nAny help is welcome, thank you in advance.\r\n","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26775","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26775/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26775/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26775/events","html_url":"https://github.com/symfony/symfony/issues/26775","id":310875402,"number":26775,"title":"[Security] SimpleAuthenticationProvider is broken","user":{"login":"leofeyer","id":1192057,"avatar_url":"https://avatars0.githubusercontent.com/u/1192057?v=4","gravatar_id":"","url":"https://api.github.com/users/leofeyer","html_url":"https://github.com/leofeyer","followers_url":"https://api.github.com/users/leofeyer/followers","following_url":"https://api.github.com/users/leofeyer/following{/other_user}","gists_url":"https://api.github.com/users/leofeyer/gists{/gist_id}","starred_url":"https://api.github.com/users/leofeyer/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/leofeyer/subscriptions","organizations_url":"https://api.github.com/users/leofeyer/orgs","repos_url":"https://api.github.com/users/leofeyer/repos","events_url":"https://api.github.com/users/leofeyer/events{/privacy}","received_events_url":"https://api.github.com/users/leofeyer/received_events","type":"User","site_admin":false},"labels":[{"id":100079,"url":"https://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":99600,"url":"https://api.github.com/repos/symfony/symfony/labels/Security","name":"Security","color":"DDDDDD","default":false},{"id":237003792,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Needs%20Review","name":"Status: Needs Review","color":"ededed","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":7,"created_at":"2018-04-03T15:02:56Z","updated_at":"2018-04-08T07:45:35Z","closed_at":"2018-04-04T13:33:30Z","author_association":"CONTRIBUTOR","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | yes\r\n| RFC?             | no\r\n| Symfony version  | 3.4.7\r\n\r\nThe changes from #26370 break the simple authentication provider.\r\n\r\nhttps://github.com/symfony/symfony/blob/341682e079a2f00765d1768d0ecc3016b8c66dd3/src/Symfony/Component/Security/Core/Authentication/Provider/SimpleAuthenticationProvider.php#L47-L48\r\n\r\n`$authToken->getUser()` returns a \"UserInterface instance, an object implementing a __toString method, or the username as a regular string\", however the `UserChecker::checkPreAuth()` method allows a UserInterface instance only. An anonymous token results in the following exception:\r\n\r\n```\r\nType error: Argument 1 passed to Symfony\\Component\\Security\\Core\\User\\UserChecker::checkPreAuth() must be an instance of Symfony\\Component\\Security\\Core\\User\\UserInterface, string given, called in …/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/SimpleAuthenticationProvider.php on line 49\r\n```\r\n\r\n@i3or1s /cc","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26766","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26766/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26766/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26766/events","html_url":"https://github.com/symfony/symfony/issues/26766","id":310812422,"number":26766,"title":"Twig_Error_Syntax  Unknown \"abbr_class\" filter.","user":{"login":"aBanhidy","id":2663069,"avatar_url":"https://avatars0.githubusercontent.com/u/2663069?v=4","gravatar_id":"","url":"https://api.github.com/users/aBanhidy","html_url":"https://github.com/aBanhidy","followers_url":"https://api.github.com/users/aBanhidy/followers","following_url":"https://api.github.com/users/aBanhidy/following{/other_user}","gists_url":"https://api.github.com/users/aBanhidy/gists{/gist_id}","starred_url":"https://api.github.com/users/aBanhidy/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/aBanhidy/subscriptions","organizations_url":"https://api.github.com/users/aBanhidy/orgs","repos_url":"https://api.github.com/users/aBanhidy/repos","events_url":"https://api.github.com/users/aBanhidy/events{/privacy}","received_events_url":"https://api.github.com/users/aBanhidy/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-04-03T12:18:10Z","updated_at":"2018-04-03T12:34:25Z","closed_at":"2018-04-03T12:34:25Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 3.6.7\r\n\r\nI've just run composer update and updated my system form Symfony 3.4.6 to 3.4.7. Result is:\r\n\r\n- Twig_Error_Syntax Unknown \"abbr_class\" filter.\r\n- ServiceCircularReferenceException Circular reference detected for service \"routing.loader\", path: \"routing.loader\".\r\n\r\nI would like to ask some help what I have to do to resolve them. If I drop away this updates my application works fine.\r\n\r\nThanks and sry if there is already an opened issue with same topic.\r\n\r\n","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26759","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26759/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26759/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26759/events","html_url":"https://github.com/symfony/symfony/issues/26759","id":310775631,"number":26759,"title":"Disallowed HTTP verbs throw 404 instead of 405","user":{"login":"tehplague","id":1062568,"avatar_url":"https://avatars3.githubusercontent.com/u/1062568?v=4","gravatar_id":"","url":"https://api.github.com/users/tehplague","html_url":"https://github.com/tehplague","followers_url":"https://api.github.com/users/tehplague/followers","following_url":"https://api.github.com/users/tehplague/following{/other_user}","gists_url":"https://api.github.com/users/tehplague/gists{/gist_id}","starred_url":"https://api.github.com/users/tehplague/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/tehplague/subscriptions","organizations_url":"https://api.github.com/users/tehplague/orgs","repos_url":"https://api.github.com/users/tehplague/repos","events_url":"https://api.github.com/users/tehplague/events{/privacy}","received_events_url":"https://api.github.com/users/tehplague/received_events","type":"User","site_admin":false},"labels":[{"id":100079,"url":"https://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":111254,"url":"https://api.github.com/repos/symfony/symfony/labels/Routing","name":"Routing","color":"DDDDDD","default":false},{"id":237003792,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Needs%20Review","name":"Status: Needs Review","color":"ededed","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2018-04-03T10:14:51Z","updated_at":"2018-04-04T13:31:26Z","closed_at":"2018-04-04T13:31:26Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | yes\r\n| RFC?             | no\r\n| Symfony version  | 4.0.7\r\n\r\nSymfony 4.0.7 now throws an HTTP 404 (Not Found) when you perform a request with a method excluded in the route configuration (e.g. when there are only routes supporting GET and you perform a POST). Previously (tested with 4.0.6) this used to be a HTTP 405 (Method not allowed) that IMHO fits better in this case. At least, if this behaviour was desired, it breaks BC.","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26757","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26757/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26757/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26757/events","html_url":"https://github.com/symfony/symfony/issues/26757","id":310760988,"number":26757,"title":"[Finder] Results returns realpath instead of path specified in search","user":{"login":"helhum","id":904370,"avatar_url":"https://avatars2.githubusercontent.com/u/904370?v=4","gravatar_id":"","url":"https://api.github.com/users/helhum","html_url":"https://github.com/helhum","followers_url":"https://api.github.com/users/helhum/followers","following_url":"https://api.github.com/users/helhum/following{/other_user}","gists_url":"https://api.github.com/users/helhum/gists{/gist_id}","starred_url":"https://api.github.com/users/helhum/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/helhum/subscriptions","organizations_url":"https://api.github.com/users/helhum/orgs","repos_url":"https://api.github.com/users/helhum/repos","events_url":"https://api.github.com/users/helhum/events{/privacy}","received_events_url":"https://api.github.com/users/helhum/received_events","type":"User","site_admin":false},"labels":[{"id":231677,"url":"https://api.github.com/repos/symfony/symfony/labels/BC%20Break","name":"BC Break","color":"e10c02","default":false},{"id":100079,"url":"https://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":148418,"url":"https://api.github.com/repos/symfony/symfony/labels/Finder","name":"Finder","color":"DDDDDD","default":false},{"id":237003792,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Needs%20Review","name":"Status: Needs Review","color":"ededed","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-04-03T09:32:03Z","updated_at":"2018-04-04T04:56:22Z","closed_at":"2018-04-04T04:56:22Z","author_association":"CONTRIBUTOR","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | yes\r\n| RFC?             | no\r\n| Symfony version  | 4.0.7\r\n\r\nThis commit https://github.com/symfony/symfony/commit/e17a63457aa0e9b2598173a16da5ffcf0a8f7198 marks a breaking change (introduced in 4.0.7)\r\n\r\nSetup:\r\n\r\nSearch path: `/path/to/linked-folder/*/`\r\nThis is a path to a symlink to `/path/to/actual-folder/`\r\n\r\nCalling code:\r\n\r\n```php\r\n$finder\r\n    ->name('ext_emconf.php')\r\n    ->followLinks()\r\n    ->depth(0)\r\n    ->ignoreUnreadableDirs()\r\n    ->in($packageBasePath);\r\n\r\nforeach ($finder as $fileInfo) {\r\n    echo $fileInfo->getPathname() . PHP_EOL;\r\n}\r\n```\r\n\r\nOutput with symfony/finder 4.0.6:\r\n\r\n```\r\n/path/to/linked-folder/foo/composer.json\r\n```\r\n\r\nOutput with symfony/finder 4.0.7:\r\n\r\n```\r\n/path/to/actual-folder/foo/composer.json\r\n```\r\n\r\n~~While it can be argued, that `\\Symfony\\Component\\Finder\\SplFileInfo` now behaves consistently with `\\SplFileInfo`, which always returns the realpath,\r\nit still is a breaking change from a consumer perspective, e.g. when the returned path is validated against a base path (`/path/to/linked-folder/`), which now fails because the symlinks are resolved by realpath.~~\r\n","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26756","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26756/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26756/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26756/events","html_url":"https://github.com/symfony/symfony/issues/26756","id":310749415,"number":26756,"title":"HTTPS redirect loop","user":{"login":"maluramichael","id":1489383,"avatar_url":"https://avatars2.githubusercontent.com/u/1489383?v=4","gravatar_id":"","url":"https://api.github.com/users/maluramichael","html_url":"https://github.com/maluramichael","followers_url":"https://api.github.com/users/maluramichael/followers","following_url":"https://api.github.com/users/maluramichael/following{/other_user}","gists_url":"https://api.github.com/users/maluramichael/gists{/gist_id}","starred_url":"https://api.github.com/users/maluramichael/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/maluramichael/subscriptions","organizations_url":"https://api.github.com/users/maluramichael/orgs","repos_url":"https://api.github.com/users/maluramichael/repos","events_url":"https://api.github.com/users/maluramichael/events{/privacy}","received_events_url":"https://api.github.com/users/maluramichael/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-04-03T08:57:21Z","updated_at":"2018-04-03T10:28:39Z","closed_at":"2018-04-03T10:28:39Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | no\r\n| Feature request? |no\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 3.0.9\r\n\r\nIam trying to force our site to https but it only goes into a redirect loop. I confirmed that it has something to do with symfony because i added an `echo \"Hello\"; die();` to the app.php and it worked fine.\r\n\r\nHere my nginx config\r\n\r\n```\r\nserver {\r\n    server_name api.camigo.info;\r\n    listen 80;\r\n    return 302 https://$server_name$request_uri;\r\n}\r\n\r\nserver {\r\n    server_name api.camigo.info;\r\n    root /var/www/camigo-web-app/web;\r\n\r\n    error_log /var/log/nginx/camigo_api_error.log;\r\n    access_log /var/log/nginx/camigo_api_access.log;\r\n\r\n    listen 443 ssl; # managed by Certbot\r\n    ssl_certificate /etc/letsencrypt/live/api.camigo.info/fullchain.pem; # managed by Certbot\r\n    ssl_certificate_key /etc/letsencrypt/live/api.camigo.info/privkey.pem; # managed by Certbot\r\n    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot\r\n    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot\r\n\r\n    location / {\r\n        # try to serve file directly, fallback to app.php\r\n        try_files $uri /app.php$is_args$args;\r\n    }\r\n    location ~ ^/app\\.php(/|$) {\r\n        fastcgi_pass unix:/var/run/php/php7.1-fpm.sock;\r\n        fastcgi_split_path_info ^(.+\\.php)(/.*)$;\r\n        include fastcgi_params;\r\n        fastcgi_param HTTPS on;\r\n        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;\r\n        fastcgi_param DOCUMENT_ROOT $realpath_root;\r\n        internal;\r\n   }\r\n\r\n   # return 404 for all other php files not matching the front controller\r\n   # this prevents access to other php files you don't want to be accessible.\r\n   location ~ \\.php$ {\r\n     return 404;\r\n   }\r\n}\r\n```","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26755","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26755/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26755/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26755/events","html_url":"https://github.com/symfony/symfony/issues/26755","id":310736879,"number":26755,"title":"Circular reference detected for service \"routing.loader\"","user":{"login":"axzx","id":1436016,"avatar_url":"https://avatars2.githubusercontent.com/u/1436016?v=4","gravatar_id":"","url":"https://api.github.com/users/axzx","html_url":"https://github.com/axzx","followers_url":"https://api.github.com/users/axzx/followers","following_url":"https://api.github.com/users/axzx/following{/other_user}","gists_url":"https://api.github.com/users/axzx/gists{/gist_id}","starred_url":"https://api.github.com/users/axzx/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/axzx/subscriptions","organizations_url":"https://api.github.com/users/axzx/orgs","repos_url":"https://api.github.com/users/axzx/repos","events_url":"https://api.github.com/users/axzx/events{/privacy}","received_events_url":"https://api.github.com/users/axzx/received_events","type":"User","site_admin":false},"labels":[{"id":100079,"url":"https://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":237003792,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Needs%20Review","name":"Status: Needs Review","color":"ededed","default":false},{"id":199779,"url":"https://api.github.com/repos/symfony/symfony/labels/WebProfilerBundle","name":"WebProfilerBundle","color":"DDDDDD","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":9,"created_at":"2018-04-03T08:15:15Z","updated_at":"2018-04-07T10:02:45Z","closed_at":"2018-04-03T12:22:27Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | yes\r\n| RFC?             | no\r\n| Symfony version  | 3.4.7\r\n\r\nafter `composer up`:\r\n\r\n```\r\n [RuntimeException]\r\n  An error occurred when executing the \"'cache:clear --no-warmup'\" command:\r\n\r\n  In Container.php line 297:\r\n\r\n    Circular reference detected for service \"routing.loader\", path: \"routing.loader\".\r\n```\r\n","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26754","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26754/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26754/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26754/events","html_url":"https://github.com/symfony/symfony/issues/26754","id":310715308,"number":26754,"title":"[WebProfilerBundle] Unable to generate a URL for the named route \"_profiler_open_file\"","user":{"login":"kunicmarko20","id":13528674,"avatar_url":"https://avatars3.githubusercontent.com/u/13528674?v=4","gravatar_id":"","url":"https://api.github.com/users/kunicmarko20","html_url":"https://github.com/kunicmarko20","followers_url":"https://api.github.com/users/kunicmarko20/followers","following_url":"https://api.github.com/users/kunicmarko20/following{/other_user}","gists_url":"https://api.github.com/users/kunicmarko20/gists{/gist_id}","starred_url":"https://api.github.com/users/kunicmarko20/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/kunicmarko20/subscriptions","organizations_url":"https://api.github.com/users/kunicmarko20/orgs","repos_url":"https://api.github.com/users/kunicmarko20/repos","events_url":"https://api.github.com/users/kunicmarko20/events{/privacy}","received_events_url":"https://api.github.com/users/kunicmarko20/received_events","type":"User","site_admin":false},"labels":[{"id":100079,"url":"https://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":237003792,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Needs%20Review","name":"Status: Needs Review","color":"ededed","default":false},{"id":199779,"url":"https://api.github.com/repos/symfony/symfony/labels/WebProfilerBundle","name":"WebProfilerBundle","color":"DDDDDD","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":20,"created_at":"2018-04-03T06:53:40Z","updated_at":"2018-04-06T16:40:43Z","closed_at":"2018-04-03T12:22:23Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | yes\r\n| RFC?             | no\r\n| Symfony version  | 4.0.7\r\n\r\n<!--\r\n- Please fill in this template according to your issue.\r\n- For support request or how-tos, visit https://symfony.com/support\r\n- Otherwise, replace this comment by the description of your issue.\r\n-->\r\n\r\nAfter updating to 4.0.7 I am getting this error:\r\n\r\n```\r\n$ bin/console cache:clear --env=test\r\n\r\nIn srcTestDebugProjectContainerUrlGenerator.php line 106:\r\n\r\n  Unable to generate a URL for the named route \"_profiler_open_file\" as such route does not exist.\r\n```\r\n\r\n@javiereguiluz pointed me to https://github.com/symfony/symfony/pull/26626, so I guess it is connected to that. Didn't have time to investigate more so I just downgraded to 4.0.6 and it works as expected.\r\n\r\n**Update:**\r\nDisabled WebProfilerBundle in test env as I do not need it and 4.0.7 works.","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26753","repository_url":"https://api.github.com/repos/sym
6e62
fony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26753/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26753/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26753/events","html_url":"https://github.com/symfony/symfony/issues/26753","id":310711867,"number":26753,"title":"[Security] Service \"security.authentication.provider.simple_form.secured_area\": The index \"3\" is not in the range [0, 2].  ","user":{"login":"andreybolonin","id":2576509,"avatar_url":"https://avatars2.githubusercontent.com/u/2576509?v=4","gravatar_id":"","url":"https://api.github.com/users/andreybolonin","html_url":"https://github.com/andreybolonin","followers_url":"https://api.github.com/users/andreybolonin/followers","following_url":"https://api.github.com/users/andreybolonin/following{/other_user}","gists_url":"https://api.github.com/users/andreybolonin/gists{/gist_id}","starred_url":"https://api.github.com/users/andreybolonin/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/andreybolonin/subscriptions","organizations_url":"https://api.github.com/users/andreybolonin/orgs","repos_url":"https://api.github.com/users/andreybolonin/repos","events_url":"https://api.github.com/users/andreybolonin/events{/privacy}","received_events_url":"https://api.github.com/users/andreybolonin/received_events","type":"User","site_admin":false},"labels":[{"id":100079,"url":"https://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":99600,"url":"https://api.github.com/repos/symfony/symfony/labels/Security","name":"Security","color":"DDDDDD","default":false},{"id":58752396,"url":"https://api.github.com/repos/symfony/symfony/labels/SecurityBundle","name":"SecurityBundle","color":"DDDDDD","default":false},{"id":237003792,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Needs%20Review","name":"Status: Needs Review","color":"ededed","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":6,"created_at":"2018-04-03T06:38:45Z","updated_at":"2018-04-04T12:33:15Z","closed_at":"2018-04-04T12:33:15Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 4.0.7\r\n\r\n`bin/console -v`\r\n```\r\nIn Definition.php line 262:\r\n                                                                                                                  \r\n  [Symfony\\Component\\DependencyInjection\\Exception\\OutOfBoundsException]                                          \r\n  Service \"security.authentication.provider.simple_form.secured_area\": The index \"3\" is not in the range [0, 2].  \r\n                                                                                                                  \r\n\r\nException trace:\r\n Symfony\\Component\\DependencyInjection\\Definition->replaceArgument() at /Users/andreybolonin/www/asat/vendor/symfony/dependency-injection/Compiler/ResolveChildDefinitionsPass.php:150\r\n Symfony\\Component\\DependencyInjection\\Compiler\\ResolveChildDefinitionsPass->doResolveDefinition() at /Users/andreybolonin/www/asat/vendor/symfony/dependency-injection/Compiler/ResolveChildDefinitionsPass.php:58\r\n Symfony\\Component\\DependencyInjection\\Compiler\\ResolveChildDefinitionsPass->resolveDefinition() at /Users/andreybolonin/www/asat/vendor/symfony/dependency-injection/Compiler/ResolveChildDefinitionsPass.php:39\r\n Symfony\\Component\\DependencyInjection\\Compiler\\ResolveChildDefinitionsPass->processValue() at /Users/andreybolonin/www/asat/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:60\r\n Symfony\\Component\\DependencyInjection\\Compiler\\AbstractRecursivePass->processValue() at /Users/andreybolonin/www/asat/vendor/symfony/dependency-injection/Compiler/ResolveChildDefinitionsPass.php:31\r\n Symfony\\Component\\DependencyInjection\\Compiler\\ResolveChildDefinitionsPass->processValue() at /Users/andreybolonin/www/asat/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:39\r\n Symfony\\Component\\DependencyInjection\\Compiler\\AbstractRecursivePass->process() at /Users/andreybolonin/www/asat/vendor/symfony/dependency-injection/Compiler/Compiler.php:95\r\n Symfony\\Component\\DependencyInjection\\Compiler\\Compiler->compile() at /Users/andreybolonin/www/asat/vendor/symfony/dependency-injection/ContainerBuilder.php:713\r\n Symfony\\Component\\DependencyInjection\\ContainerBuilder->compile() at /Users/andreybolonin/www/asat/vendor/symfony/http-kernel/Kernel.php:513\r\n Symfony\\Component\\HttpKernel\\Kernel->initializeContainer() at /Users/andreybolonin/www/asat/vendor/symfony/http-kernel/Kernel.php:125\r\n Symfony\\Component\\HttpKernel\\Kernel->boot() at /Users/andreybolonin/www/asat/vendor/symfony/framework-bundle/Console/Application.php:64\r\n Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun() at /Users/andreybolonin/www/asat/vendor/symfony/console/Application.php:143\r\n Symfony\\Component\\Console\\Application->run() at /Users/andreybolonin/www/asat/bin/console:39\r\n\r\n```\r\nOn 4.0.6 works perfectly.\r\n`security.yaml`\r\n```\r\n# To get started with security, check out the documentation:\r\n# https://symfony.com/doc/current/security.html\r\nsecurity:\r\n    encoders:\r\n        App\\Entity\\User:\r\n            algorithm: bcrypt\r\n            cost: 13\r\n\r\n    role_hierarchy:\r\n        ROLE_ADMIN: [ROLE_SELLER, ROLE_BUYER, ROLE_BROKER, ROLE_MANAGER, ROLE_ACCOUNTANT]\r\n        ROLE_MANAGER: ~\r\n        ROLE_ACCOUNTANT: ~\r\n\r\n    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded\r\n    providers:\r\n        our_db_provider:\r\n            entity:\r\n                class: App\\Entity\\User\r\n                property: email\r\n    firewalls:\r\n        # disables authentication for assets and the profiler, adapt it according to your needs\r\n        dev:\r\n            pattern: ^/(_(profiler|wdt)|css|images|js)/\r\n            security: false\r\n\r\n        secured_area:\r\n            pattern: ^/(admin|cabinet|backoffice)\r\n            anonymous: ~\r\n            provider: our_db_provider\r\n            logout_on_user_change: true\r\n            simple_form:\r\n                login_path: /admin/login\r\n                check_path: /admin/login_check\r\n                authenticator: App\\Security\\PasswordAuthenticator\r\n                default_target_path: after_login\r\n                require_previous_session: false\r\n            logout:\r\n                path:   /admin/logout\r\n                target: /admin/login\r\n\r\n    access_control:\r\n        - { path: ^/admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }\r\n        - { path: ^/admin/register, role: IS_AUTHENTICATED_ANONYMOUSLY }\r\n        - { path: ^/admin, role: [ROLE_ADMIN, ROLE_MANAGER, ROLE_ACCOUNTANT] }\r\n        - { path: ^/cabinet, role: [ROLE_SELLER, ROLE_BUYER, ROLE_BROKER, ROLE_MANAGER, ROLE_ACCOUNTANT] }\r\n        - { path: ^/backoffice, role: ROLE_ADMIN }\r\n```","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26750","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26750/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26750/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26750/events","html_url":"https://github.com/symfony/symfony/issues/26750","id":310672897,"number":26750,"title":"Call to a member function guessExtension() on string","user":{"login":"TsongSteven","id":22741324,"avatar_url":"https://avatars3.githubusercontent.com/u/22741324?v=4","gravatar_id":"","url":"https://api.github.com/users/TsongSteven","html_url":"https://github.com/TsongSteven","followers_url":"https://api.github.com/users/TsongSteven/followers","following_url":"https://api.github.com/users/TsongSteven/following{/other_user}","gists_url":"https://api.github.com/users/TsongSteven/gists{/gist_id}","starred_url":"https://api.github.com/users/TsongSteven/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/TsongSteven/subscriptions","organizations_url":"https://api.github.com/users/TsongSteven/orgs","repos_url":"https://api.github.com/users/TsongSteven/repos","events_url":"https://api.github.com/users/TsongSteven/events{/privacy}","received_events_url":"https://api.github.com/users/TsongSteven/received_events","type":"User","site_admin":false},"labels":[{"id":100079,"url":"https://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":99594,"url":"https://api.github.com/repos/symfony/symfony/labels/Form","name":"Form","color":"DDDDDD","default":false},{"id":125366,"url":"https://api.github.com/repos/symfony/symfony/labels/HttpFoundation","name":"HttpFoundation","color":"DDDDDD","default":false},{"id":237003792,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Needs%20Review","name":"Status: Needs Review","color":"ededed","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-04-03T02:35:47Z","updated_at":"2018-04-03T05:52:25Z","closed_at":"2018-04-03T05:52:25Z","author_association":"NONE","body":"| Symfony version  | x 4.0.x\r\n\r\n\r\nForm:\r\n```php\r\n<?php\r\n\r\nnamespace App\\Form;\r\nuse App\\Entity\\Image;\r\nuse Symfony\\Component\\Form\\AbstractType;\r\nuse Symfony\\Component\\Form\\FormBuilderInterface;\r\nuse Symfony\\Component\\OptionsResolver\\OptionsResolver;\r\nuse Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType; \r\nuse Symfony\\Component\\Form\\Extension\\Core\\Type\\TextType; \r\nuse Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType;\r\n\r\nclass ImageUploadType extends AbstractType\r\n{\r\n    public function buildForm(FormBuilderInterface $builder, array $options)\r\n    {\r\n        $builder\r\n            ->add('title', TextType::class)\r\n            ->add('description', TextType::class)\r\n            ->add('image', FileType::class, array('label'=>'Upload Image'))\r\n            ->add('submit', SubmitType::class)\r\n        ;\r\n    }\r\n\r\n    public function configureOptions(OptionsResolver $resolver)\r\n    {\r\n        $resolver->setDefaults([\r\n            'data_class' => Image::class,\r\n        ]);\r\n    }\r\n}\r\n```\r\n\r\nController: \r\n\r\n```php\r\n<?php\r\nnamespace App\\Controller;\r\nuse App\\Entity\\Image;\r\nuse App\\Form\\ImageUploadType;\r\nuse Symfony\\Component\\Routing\\Annotation\\Route;\r\nuse Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller;\r\nuse Symfony\\Component\\HttpFoundation\\Request;\r\n\r\nclass ImageUploadController extends Controller\r\n{\r\n    /**\r\n     * @Route(\"/\", name=\"image_upload\")\r\n     */\r\n    public function indexAction(Request $request)\r\n    {\r\n        $em = $this->getDoctrine()->getManager();\r\n        $imageEn = new Image();\r\n\r\n         $form = $this->createForm(ImageUploadType::class, $imageEn);\r\n\r\n         $form->handleRequest($request);\r\n\r\n         if($form->isSubmitted() && $form->isValid()){\r\n\r\n            /** @var Symfony\\Component\\HttpFoundation\\File\\UploadedFile $file */\r\n\r\n            $file = $imageEn->getImage();\r\n            dump($imageEn->getImage());\r\n\r\n            $fileName = md5(uniqid()).'.'.$file->guessExtension();\r\n\r\n            $file->move($this->getParameter('image_directory'), $fileName);\r\n\r\n            $imageEn->setImage($fileName);\r\n            $em->persist($imageEn);\r\n            $em->flush();\r\n\r\n            $this->addFlash('notice', 'Post Submitted Successfully!!!');\r\n\r\n            return $this->redirectToRoute('image_upload');\r\n            \r\n         }\r\n\r\n         return $this->render('image/image.html.twig', array(\r\n\r\n            'imageform' => $form->createView()\r\n         ));\r\n    }\r\n} \r\n```\r\n\r\nAnd when I dump($file);\r\nI get: \"C:\\xampp\\tmp\\php6F66.tmp\"\r\n\r\nEntity:\r\n\r\n```php\r\n<?php\r\n\r\n     App\\Entity;\r\n\r\n     use Doctrine\\ORM\\Mapping as ORM;\r\n     use Symfony\\Component\\Validator\\Constraints as Assert;\r\n\r\n     /**\r\n     * @ORM\\Entity(repositoryClass=\"App\\Repository\\ImageRepository\")\r\n     */\r\n    class Image\r\n    {\r\n        /**\r\n        * @ORM\\Id()\r\n          * @ORM\\GeneratedValue()\r\n        * @ORM\\Column(type=\"integer\")\r\n        */\r\n    private $id;\r\n\r\n    /**\r\n     * @ORM\\Column(type=\"string\", length=255)\r\n     */\r\n    private $title;\r\n\r\n    /**\r\n     * @ORM\\Column(type=\"string\", length=255)\r\n     */\r\n    private $description;\r\n\r\n    /**\r\n     * @ORM\\Column(type=\"string\", length=255)\r\n     * @Assert\\NotBlank(message=\"Please upload image\")\r\n     * @Assert\\File(mimeTypes={\"image/jpeg\"})\r\n     */\r\n    private $image;\r\n\r\n    public function getId()\r\n    {\r\n        return $this->id;\r\n    }\r\n\r\n    public function getTitle(): ?string\r\n    {\r\n        return $this->title;\r\n    }\r\n\r\n    public function setTitle(string $title): self\r\n    {\r\n        $this->title = $title;\r\n\r\n        return $this;\r\n    }\r\n\r\n    public function getDescription(): ?string\r\n    {\r\n        return $this->description;\r\n    }\r\n\r\n    public function setDescription(string $description): self\r\n    {\r\n        $this->description = $description;\r\n\r\n        return $this;\r\n    }\r\n\r\n    public function getImage(): ?string\r\n    {\r\n        return $this->image;\r\n    }\r\n\r\n    public function setImage(string $image): self\r\n    {\r\n        $this->image = $image;\r\n\r\n        return $this;\r\n    }\r\n}\r\n```\r\n\r\nI posted this issue in stackoverflow twice, but none(who ever answered), had an idea. I even asked few Symfony developers they were unable to detect an issue.","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26748","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26748/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26748/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26748/events","html_url":"https://github.com/symfony/symfony/issues/26748","id":310525825,"number":26748,"title":"problem with cache:clear -e=prod","user":{"login":"murman-lexus","id":13753245,"avatar_url":"https://avatars0.githubusercontent.com/u/13753245?v=4","gravatar_id":"","url":"https://api.github.com/users/murman-lexus","html_url":"https://github.com/murman-lexus","followers_url":"https://api.github.com/users/murman-lexus/followers","following_url":"https://api.github.com/users/murman-lexus/following{/other_user}","gists_url":"https://api.github.com/users/murman-lexus/gists{/gist_id}","starred_url":"https://api.github.com/users/murman-lexus/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/murman-lexus/subscriptions","organizations_url":"https://api.github.com/users/murman-lexus/orgs","repos_url":"https://api.github.com/users/murman-lexus/repos","events_url":"https://api.github.com/users/murman-lexus/events{/privacy}","received_events_url":"https://api.github.com/users/murman-lexus/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-04-02T16:04:33Z","updated_at":"2018-04-02T17:25:20Z","closed_at":"2018-04-02T17:25:20Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | yes/no\r\n| RFC?             | no\r\n| Symfony version  | 3.4.6\r\n\r\n<!--\r\nHello. after update from 3.3 --> 3.4.6 \r\nbroken console command cache:clear:\r\n**php bin/console cache:clear -e=prod**\r\n\r\n```\r\nError:\r\nIn FileLocator.php line 44:\r\n                                                                                                  \r\n  The file \"~/project_dir/app/config/config_=prod.yml\" does not exist. \r\n```\r\n\r\n\r\n**php bin/console cache:clear --env=prod (works correct)**\r\n\r\n-->\r\n","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26747","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26747/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26747/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26747/events","html_url":"https://github.com/symfony/symfony/issues/26747","id":310484425,"number":26747,"title":"Unable to resolve env() in (Security) configuration","user":{"login":"sstok","id":904790,"avatar_url":"https://avatars1.githubusercontent.com/u/904790?v=4","gravatar_id":"","url":"https://api.github.com/users/sstok","html_url":"https://github.com/sstok","followers_url":"https://api.github.com/users/sstok/followers","following_url":"https://api.github.com/users/sstok/following{/other_user}","gists_url":"https://api.github.com/users/sstok/gists{/gist_id}","starred_url":"https://api.github.com/users/sstok/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/sstok/subscriptions","organizations_url":"https://api.github.com/users/sstok/orgs","repos_url":"https://api.github.com/users/sstok/repos","events_url":"https://api.github.com/users/sstok/events{/privacy}","received_events_url":"https://api.github.com/users/sstok/received_events","type":"User","site_admin":false},"labels":[{"id":100079,"url":"https://api.github.com/repos/symfony/symfony/labels/Bug","name":"Bug","color":"e10c02","default":false},{"id":99863,"url":"https://api.github.com/repos/symfony/symfony/labels/DependencyInjection","name":"DependencyInjection","color":"DDDDDD","default":false},{"id":237003792,"url":"https://api.github.com/repos/symfony/symfony/labels/Status:%20Needs%20Review","name":"Status: Needs Review","color":"ededed","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":{"url":"https://api.github.com/repos/symfony/symfony/milestones/17","html_url":"https://github.com/symfony/symfony/milestone/17","labels_url":"https://api.github.com/repos/symfony/symfony/milestones/17/labels","id":2795131,"number":17,"title":"4.1","description":"https://symfony.com/roadmap?version=4.1#checker","creator":{"login":"nicolas-grekas","id":243674,"avatar_url":"https://avatars3.githubusercontent.com/u/243674?v=4","gravatar_id":"","url":"https://api.github.com/users/nicolas-grekas","html_url":"https://github.com/nicolas-grekas","followers_url":"https://api.github.com/users/nicolas-grekas/followers","following_url":"https://api.github.com/users/nicolas-grekas/following{/other_user}","gists_url":"https://api.github.com/users/nicolas-grekas/gists{/gist_id}","starred_url":"https://api.github.com/users/nicolas-grekas/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/nicolas-grekas/subscriptions","organizations_url":"https://api.github.com/users/nicolas-grekas/orgs","repos_url":"https://api.github.com/users/nicolas-grekas/repos","events_url":"https://api.github.com/users/nicolas-grekas/events{/privacy}","received_events_url":"https://api.github.com/users/nicolas-grekas/received_events","type":"User","site_admin":false},"open_issues":111,"closed_issues":324,"state":"open","created_at":"2017-09-26T15:40:00Z","updated_at":"2018-04-08T14:42:33Z","due_on":"2018-05-31T07:00:00Z","closed_at":null},"comments":11,"created_at":"2018-04-02T13:26:47Z","updated_at":"2018-04-06T05:33:54Z","closed_at":"2018-04-06T05:33:54Z","author_association":"CONTRIBUTOR","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes\r\n| Feature request? | no\r\n| BC Break report? | no\r\n| RFC?             | no\r\n| Symfony version  | 4.1-dev \r\n\r\nSince (I suspect) #23888 using `env()` in a firewall configuration no longer works.\r\n\r\n`The path \"security.firewalls.main.remember_me.secret\" cannot contain an empty value, but got \"\".`\r\n\r\n<details>\r\n\r\n```\r\nIn VariableNode.php line 85:\r\n\r\n  [Symfony\\Component\\Config\\Definition\\Exception\\InvalidConfigurationException]\r\n  The path \"security.firewalls.main.remember_me.secret\" cannot contain an empty value, but got \"\".\r\n\r\n\r\nException trace:\r\n Symfony\\Component\\Config\\Definition\\VariableNode->finalizeValue() at /Users/sebastiaanstok/Sites/symfony-41/my_project/vendor/symfony/config/Definition/BaseNode.php:413\r\n Symfony\\Component\\Config\\Definition\\BaseNode->finalize() at /Users/sebastiaanstok/Sites/symfony-41/my_project/vendor/symfony/config/Definition/BaseNode.php:402\r\n Symfony\\Component\\Config\\Definition\\BaseNode->finalize() at /Users/sebastiaanstok/Sites/symfony-41/my_project/vendor/symfony/config/Definition/ArrayNode.php:248\r\n Symfony\\Component\\Config\\Definition\\ArrayNode->finalizeValue() at /Users/sebastiaanstok/Sites/symfony-41/my_project/vendor/symfony/config/Definition/BaseNode.php:413\r\n Symfony\\Component\\Config\\Definition\\BaseNode->finalize() at /Users/sebastiaanstok/Sites/symfony-41/my_project/vendor/symfony/config/Definition/ArrayNode.php:248\r\n Symfony\\Component\\Config\\Definition\\ArrayNode->finalizeValue() at /Users/sebastiaanstok/Sites/symfony-41/my_project/vendor/symfony/config/Definition/BaseNode.php:413\r\n Symfony\\Component\\Config\\Definition\\BaseNode->finalize() at /Users/sebastiaanstok/Sites/symfony-41/my_project/vendor/symfony/config/Definition/PrototypedArrayNode.php:195\r\n Symfony\\Component\\Config\\Definition\\PrototypedArrayNode->finalizeValue() at /Users/sebastiaanstok/Sites/symfony-41/my_project/vendor/symfony/config/Definition/BaseNode.php:413\r\n Symfony\\Component\\Config\\Definition\\BaseNode->finalize() at /Users/sebastiaanstok/Sites/symfony-41/my_project/vendor/symfony/config/Definition/ArrayNode.php:248\r\n Symfony\\Component\\Config\\Definition\\ArrayNode->finalizeValue() at /Users/sebastiaanstok/Sites/symfony-41/my_project/vendor/symfony/config/Definition/BaseNode.php:413\r\n Symfony\\Component\\Config\\Definition\\BaseNode->finalize() at /Users/sebastiaanstok/Sites/symfony-41/my_project/vendor/symfony/config/Definition/Processor.php:39\r\n Symfony\\Component\\Config\\Definition\\Processor->process() at /Users/sebastiaanstok/Sites/symfony-41/my_project/vendor/symfony/config/Definition/Processor.php:52\r\n Symfony\\Component\\Config\\Definition\\Processor->processConfiguration() at /Users/sebastiaanstok/Sites/symfony-41/my_project/vendor/symfony/dependency-injection/Compiler/ValidateEnvPlaceholdersPass.php:80\r\n Symfony\\Component\\DependencyInjection\\Compiler\\ValidateEnvPlaceholdersPass->process() at /Users/sebastiaanstok/Sites/symfony-41/my_project/vendor/symfony/dependency-injection/Compiler/Compiler.php:95\r\n Symfony\\Component\\DependencyInjection\\Compiler\\Compiler->compile() at /Users/sebastiaanstok/Sites/symfony-41/my_project/vendor/symfony/dependency-injection/ContainerBuilder.php:717\r\n Symfony\\Component\\DependencyInjection\\ContainerBuilder->compile() at /Users/sebastiaanstok/Sites/symfony-41/my_project/vendor/symfony/http-kernel/Kernel.php:513\r\n Symfony\\Component\\HttpKernel\\Kernel->initializeContainer() at /Users/sebastiaanstok/Sites/symfony-41/my_project/vendor/symfony/http-kernel/Kernel.php:125\r\n Symfony\\Component\\HttpKernel\\Kernel->boot() at /Users/sebastiaanstok/Sites/symfony-41/my_project/vendor/symfony/framework-bundle/Console/Application.php:65\r\n Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun() at /Users/sebastiaanstok/Sites/symfony-41/my_project/vendor/symfony/console/Application.php:145\r\n Symfony\\Component\\Console\\Application->run() at /Users/sebastiaanstok/Sites/symfony-41/my_project/bin/console:39\r\n```\r\n</details>\r\n\r\n## To reproduce:\r\n\r\n```bash\r\ncomposer create-project symfony/website-skeleton my_project \r\ncomposer config minimum-stability dev\r\ncomposer remove symfony/lts\r\ncomposer update\r\n```\r\n\r\nNow update config/packages/security.yaml with:\r\n\r\n```yaml\r\nsecurity:\r\n    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers\r\n    providers:\r\n        in_memory: { memory: ~ }\r\n    firewalls:\r\n        dev:\r\n            pattern: ^/(_(profiler|wdt)|css|images|js)/\r\n            security: false\r\n        main:\r\n            anonymous: true\r\n\r\n            # activate different ways to authenticate\r\n\r\n            # http_basic: true\r\n            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate\r\n\r\n            form_login: true\r\n            # https://symfony.com/doc/current/security/form_login_setup.html\r\n            \r\n            remember_me:\r\n                secret:               '%env(APP_SECRET)%' # This used to work\r\n                token_provider:       ~\r\n                catch_exceptions:     true\r\n                name:                 MAIN_REMEMBERME\r\n                lifetime:             604800 # one week\r\n\r\n    # Easy way to control access for large sections of your site\r\n    # Note: Only the *first* access control that matches will be used\r\n    access_control:\r\n        # - { path: ^/admin, roles: ROLE_ADMIN }\r\n        # - { path: ^/profile, roles: ROLE_USER }\r\n```\r\n\r\nAnd run `bin/console cache:clear`.\r\n\r\nI tried debugging the system, but somewhere along execution the Configuration Resolver looses the value. All env variables are present, there are placeholders, and framework.secret works without any issues but the firewall remember_me fails for some unknown reason 🤔 ","score":1.0},{"url":"https://api.github.com/repos/symfony/symfony/issues/26746","repository_url":"https://api.github.com/repos/symfony/symfony","labels_url":"https://api.github.com/repos/symfony/symfony/issues/26746/labels{/name}","comments_url":"https://api.github.com/repos/symfony/symfony/issues/26746/comments","events_url":"https://api.github.com/repos/symfony/symfony/issues/26746/events","html_url":"https://github.com/symfony/symfony/issues/26746","id":310480344,"number":26746,"title":"An exception has been thrown during the rendering of a template (\"Could not load type \"fa_top_search\": class does not exist.\")","user":{"login":"jojivijay","id":3024750,"avatar_url":"https://avatars3.githubusercontent.com/u/3024750?v=4","gravatar_id":"","url":"https://api.github.com/users/jojivijay","html_url":"https://github.com/jojivijay","followers_url":"https://api.github.com/users/jojivijay/followers","following_url":"https://api.github.com/users/jojivijay/following{/other_user}","gists_url":"https://api.github.com/users/jojivijay/gists{/gist_id}","starred_url":"https://api.github.com/users/jojivijay/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jojivijay/subscriptions","organizations_url":"https://api.github.com/users/jojivijay/orgs","repos_url":"https://api.github.com/users/jojivijay/repos","events_url":"https://api.github.com/users/jojivijay/events{/privacy}","received_events_url":"https://api.github.com/users/jojivijay/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-04-02T13:08:15Z","updated_at":"2018-04-02T13:44:27Z","closed_at":"2018-04-02T13:44:27Z","author_association":"NONE","body":"| Q                | A\r\n| ---------------- | -----\r\n| Bug report?      | yes/no\r\n| Feature request? | yes/no\r\n| BC Break report? | yes/no\r\n| RFC?             | yes/no\r\n| Symfony version  | 3.4\r\n\r\nI am getting error like\r\nAn exception has been thrown during the rendering of a template (\"Could not load type \"fa_top_search\": class does not exist.\").\r\nwhile upgrading symfony 2.7 to 3 and 3.4\r\n","score":1.0}]}
0

