HTTP/1.1 200 OK
Transfer-Encoding: chunked
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Cache-Control: no-cache
Content-Security-Policy: default-src 'none'
Content-Type: application/json; charset=utf-8
Date: Sun, 13 May 2018 13:01:20 GMT
Link: <https://api.github.com/search/issues?q=repo%3Apadrino%2Fpadrino-framework+type%3Aissue+state%3Aclosed&page=2>; rel="next", <https://api.github.com/search/issues?q=repo%3Apadrino%2Fpadrino-framework+type%3Aissue+state%3Aclosed&page=34>; rel="last"
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Server: GitHub.com
Status: 200 OK
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Accepted-Oauth-Scopes: 
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Github-Media-Type: github.v3; format=json
X-Github-Request-Id: CDFD:4F41:3598B11:750B433:5AF83720
X-Oauth-Scopes: 
X-Ratelimit-Limit: 30
X-Ratelimit-Remaining: 5
X-Ratelimit-Reset: 1526216518
X-Runtime-Rack: 0.587656
X-Xss-Protection: 1; mode=block

8000
{"total_count":1314,"incomplete_results":false,"items":[{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2180","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2180/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2180/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2180/events","html_url":"https://github.com/padrino/padrino-framework/issues/2180","id":306201020,"number":2180,"title":"content_for fails in ","user":{"login":"noise-machines","id":5033974,"avatar_url":"https://avatars0.githubusercontent.com/u/5033974?v=4","gravatar_id":"","url":"https://api.github.com/users/noise-machines","html_url":"https://github.com/noise-machines","followers_url":"https://api.github.com/users/noise-machines/followers","following_url":"https://api.github.com/users/noise-machines/following{/other_user}","gists_url":"https://api.github.com/users/noise-machines/gists{/gist_id}","starred_url":"https://api.github.com/users/noise-machines/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/noise-machines/subscriptions","organizations_url":"https://api.github.com/users/noise-machines/orgs","repos_url":"https://api.github.com/users/noise-machines/repos","events_url":"https://api.github.com/users/noise-machines/events{/privacy}","received_events_url":"https://api.github.com/users/noise-machines/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":5,"created_at":"2018-03-18T00:05:19Z","updated_at":"2018-05-09T06:25:28Z","closed_at":"2018-05-09T04:18:02Z","author_association":"NONE","body":"#### Do you want to request a *feature* or report a *bug*?\r\n\r\nA bug.\r\n\r\n#### What is the current behavior?\r\n\r\nHere's a repo that reproduces the problem, forked from the Padrino blog tutorial repo:\r\nhttps://github.com/noise-machines/padrino_content_for_bug\r\n\r\nTo reproduce:\r\n\r\n1. Clone the repository above\r\n2. Start the development server\r\n3. Visit http://127.0.0.1:3000/posts\r\n4. At the top of the page, I expect to see \"Hi, body top!\", as defined in the `app/views/_body_top_content.haml` partial. But it's not there.\r\n\r\n#### What is the expected behavior?\r\n\r\n \"Hi, body top!\" should appear at the top of the page on http://127.0.0.1:3000/posts.\r\n\r\nIf you modify `app/views/layouts/application.haml` so that the call to `partial` comes *before* the call to `yield_content`, you see the expected behavior:\r\n\r\n```haml\r\n-# app/views/layouts/application.haml\r\n%body\r\n      = partial 'body_top_content' # calling `partial` here gives the expected behavior\r\n      = yield_content :body_top\r\n      = # partial 'body_top_content' # calling `partial` here gives the unexpected behavior\r\n      #header\r\n```\r\n\r\n#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?\r\n\r\n**Ruby**: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]\r\n**Padrino**: Padrino v. 0.14.1.1\r\n**Sinatra**: 2.0.0\r\n**Rack**: 2.0.3\r\n**OS**: macOS Sierra, 10.12.6\r\n\r\nI've never used Padrino before today, so I don't know if it worked in previous versions.\r\n","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2175","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2175/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2175/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2175/events","html_url":"https://github.com/padrino/padrino-framework/issues/2175","id":298741913,"number":2175,"title":"Padrino router blows up when trailing slash is added to regex route","user":{"login":"pdlug","id":1077,"avatar_url":"https://avatars3.githubusercontent.com/u/1077?v=4","gravatar_id":"","url":"https://api.github.com/users/pdlug","html_url":"https://github.com/pdlug","followers_url":"https://api.github.com/users/pdlug/followers","following_url":"https://api.github.com/users/pdlug/following{/other_user}","gists_url":"https://api.github.com/users/pdlug/gists{/gist_id}","starred_url":"https://api.github.com/users/pdlug/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/pdlug/subscriptions","organizations_url":"https://api.github.com/users/pdlug/orgs","repos_url":"https://api.github.com/users/pdlug/repos","events_url":"https://api.github.com/users/pdlug/events{/privacy}","received_events_url":"https://api.github.com/users/pdlug/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2018-02-20T20:44:43Z","updated_at":"2018-04-27T19:18:42Z","closed_at":"2018-04-27T19:18:42Z","author_association":"CONTRIBUTOR","body":"#### Do you want to request a *feature* or report a *bug*?\r\n\r\nbug\r\n\r\n#### What is the current behavior?\r\n\r\nA 500 error with stack trace results from defining a route with a regex and then adding a trailing slash when fetching it. \r\n\r\nExample controller:\r\n\r\n```ruby\r\nTestapp::App.controllers  do\r\n  get :ping, %r{\\A/ping} do\r\n    content_type :text\r\n    'pong'\r\n  end\r\nend\r\n```\r\n\r\n```bash\r\n% curl http://localhost:3000/ping\r\npong\r\n```\r\n\r\n```bash\r\n% curl http://localhost:3000/ping/\r\nNoMethodError: undefined method `names' for nil:NilClass\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/padrino-core-0.14.2/lib/padrino-core/path_router/matcher.rb:62:in `params_for'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/padrino-core-0.14.2/lib/padrino-core/path_router/route.rb:121:in `params_for'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/padrino-core-0.14.2/lib/padrino-core/path_router/compiler.rb:52:in `block in call_by_request'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/padrino-core-0.14.2/lib/padrino-core/path_router/compiler.rb:84:in `block in rotation'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/padrino-core-0.14.2/lib/padrino-core/path_router/compiler.rb:83:in `loop'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/padrino-core-0.14.2/lib/padrino-core/path_router/compiler.rb:83:in `with_object'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/padrino-core-0.14.2/lib/padrino-core/path_router/compiler.rb:83:in `rotation'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/padrino-core-0.14.2/lib/padrino-core/path_router/compiler.rb:49:in `call_by_request'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/padrino-core-0.14.2/lib/padrino-core/path_router.rb:43:in `call'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/padrino-core-0.14.2/lib/padrino-core/application/routing.rb:955:in `route!'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/padrino-core-0.14.2/lib/padrino-core/application/routing.rb:938:in `block in dispatch!'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/padrino-core-0.14.2/lib/padrino-core/application/routing.rb:936:in `dispatch!'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `block in call!'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `call!'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:913:in `call'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/rack-protection-2.0.0/lib/rack/protection/xss_header.rb:18:in `call'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/rack-protection-2.0.0/lib/rack/protection/json_csrf.rb:26:in `call'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/rack-protection-2.0.0/lib/rack/protection/frame_options.rb:31:in `call'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/rack-2.0.4/lib/rack/head.rb:12:in `call'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/rack-2.0.4/lib/rack/method_override.rb:22:in `call'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/padrino-core-0.14.2/lib/padrino-core/reloader/rack.rb:25:in `call'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/padrino-core-0.14.2/lib/padrino-core/logger.rb:485:in `call'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/sinatra-2.0.0/lib/sinatra/show_exceptions.rb:22:in `call'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/rack-2.0.4/lib/rack/session/abstract/id.rb:232:in `context'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/rack-2.0.4/lib/rack/session/abstract/id.rb:226:in `call'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1955:in `call'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1499:in `block in call'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1726:in `synchronize'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1499:in `call'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/padrino-core-0.14.2/lib/padrino-core/router.rb:84:in `block in call'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/padrino-core-0.14.2/lib/padrino-core/router.rb:75:in `each'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/padrino-core-0.14.2/lib/padrino-core/router.rb:75:in `call'\r\n\t/Users/paul/tmp/testapp/vendor/ruby/2.5.0/gems/rack-2.0.4/lib/rack/handler/webrick.rb:86:in `service'\r\n\t/Users/paul/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/webrick/httpserver.rb:140:in `service'\r\n\t/Users/paul/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/webrick/httpserver.rb:96:in `run'\r\n```\r\n\r\nIf you modify the controller to allow an optional trailing slash it does work:\r\n\r\n```ruby\r\nTestapp::App.controllers  do\r\n  get :ping, %r{\\A/ping?} do\r\n    content_type :text\r\n    'pong'\r\n  end\r\nend\r\n```\r\n\r\n```bash\r\n% curl http://localhost:3000/ping/ \r\npong\r\n```\r\n\r\n*If the current behavior is a bug, please provide the steps to reproduce it and if possible a minimal demo of the problem via https://github.com/ or https://gist.github.com/*\r\n\r\n#### What is the expected behavior?\r\n\r\nI'd expect it to work with an optional trailing slash or at a minimum just return a 404 not found.\r\n\r\n#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?\r\n\r\n* ruby 2.5.0\r\n* padrino 0.14.2\r\n* sinatra 2.0.1 (also tried 2.0.0 with same result)\r\n* rack 2.0.4\r\n* mustermann 1.0.2 (also tried mustermann 1.0.0 with same result)\r\n* Mac OS X 10.13.3","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2174","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2174/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2174/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2174/events","html_url":"https://github.com/padrino/padrino-framework/issues/2174","id":297926024,"number":2174,"title":"Params handling broken with sinatra 2.0.1","user":{"login":"pdlug","id":1077,"avatar_url":"https://avatars3.githubusercontent.com/u/1077?v=4","gravatar_id":"","url":"https://api.github.com/users/pdlug","html_url":"https://github.com/pdlug","followers_url":"https://api.github.com/users/pdlug/followers","following_url":"https://api.github.com/users/pdlug/following{/other_user}","gists_url":"https://api.github.com/users/pdlug/gists{/gist_id}","starred_url":"https://api.github.com/users/pdlug/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/pdlug/subscriptions","organizations_url":"https://api.github.com/users/pdlug/orgs","repos_url":"https://api.github.com/users/pdlug/repos","events_url":"https://api.github.com/users/pdlug/events{/privacy}","received_events_url":"https://api.github.com/users/pdlug/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":{"login":"namusyaka","id":309329,"avatar_url":"https://avatars0.githubusercontent.com/u/309329?v=4","gravatar_id":"","url":"https://api.github.com/users/namusyaka","html_url":"https://github.com/namusyaka","followers_url":"https://api.github.com/users/namusyaka/followers","following_url":"https://api.github.com/users/namusyaka/following{/other_user}","gists_url":"https://api.github.com/users/namusyaka/gists{/gist_id}","starred_url":"https://api.github.com/users/namusyaka/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/namusyaka/subscriptions","organizations_url":"https://api.github.com/users/namusyaka/orgs","repos_url":"https://api.github.com/users/namusyaka/repos","events_url":"https://api.github.com/users/namusyaka/events{/privacy}","received_events_url":"https://api.github.com/users/namusyaka/received_events","type":"User","site_admin":false},"assignees":[{"login":"namusyaka","id":309329,"avatar_url":"https://avatars0.githubusercontent.com/u/309329?v=4","gravatar_id":"","url":"https://api.github.com/users/namusyaka","html_url":"https://github.com/namusyaka","followers_url":"https://api.github.com/users/namusyaka/followers","following_url":"https://api.github.com/users/namusyaka/following{/other_user}","gists_url":"https://api.github.com/users/namusyaka/gists{/gist_id}","starred_url":"https://api.github.com/users/namusyaka/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/namusyaka/subscriptions","organizations_url":"https://api.github.com/users/namusyaka/orgs","repos_url":"https://api.github.com/users/namusyaka/repos","events_url":"https://api.github.com/users/namusyaka/events{/privacy}","received_events_url":"https://api.github.com/users/namusyaka/received_events","type":"User","site_admin":false}],"milestone":null,"comments":3,"created_at":"2018-02-16T21:31:16Z","updated_at":"2018-02-23T06:22:30Z","closed_at":"2018-02-23T06:22:30Z","author_association":"CONTRIBUTOR","body":"#### Do you want to request a *feature* or report a *bug*?\r\n\r\nbug\r\n\r\n#### What is the current behavior?\r\n\r\nUpgrading padrino 0.14.2 from sinatra 2.0.0 breaks params handling (at least for form encoded payloads). \r\n\r\nGiven a very simple route:\r\n\r\n```ruby\r\nTestapp::App.controllers  do\r\n  post :test do\r\n    content_type :text\r\n    params.to_s\r\n  end\r\nend\r\n```\r\n\r\nTesting this with sinatra 2.0.0 yields:\r\n\r\n```bash\r\n% curl  -d foo=bar http://localhost:3000/test\r\n{\"foo\"=>\"bar\"}\r\n```\r\n\r\nUpgrading to sinatra 2.0.0 shows empty params:\r\n\r\n```bash\r\n% curl  -d foo=bar http://localhost:3000/test\r\n{}\r\n```\r\n\r\n*If the current behavior is a bug, please provide the steps to reproduce it and if possible a minimal demo of the problem via https://github.com/ or https://gist.github.com/*\r\n\r\n#### What is the expected behavior?\r\n\r\n#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?\r\n\r\n* ruby 2.5.0\r\n* padrino 0.14.5\r\n* sinatra 2.0.1\r\n* rack 2.0.4\r\n* MacOS 10.13.3\r\n\r\nSinatra version is the only item that seems to make a difference (2.0.0 == works, 2.0.1 == broken).","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2165","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2165/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2165/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2165/events","html_url":"https://github.com/padrino/padrino-framework/issues/2165","id":279135283,"number":2165,"title":"Sequel gem doesn't support schema plugin","user":{"login":"Jason94","id":3255423,"avatar_url":"https://avatars0.githubusercontent.com/u/3255423?v=4","gravatar_id":"","url":"https://api.github.com/users/Jason94","html_url":"https://github.com/Jason94","followers_url":"https://api.github.com/users/Jason94/followers","following_url":"https://api.github.com/users/Jason94/following{/other_user}","gists_url":"https://api.github.com/users/Jason94/gists{/gist_id}","starred_url":"https://api.github.com/users/Jason94/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Jason94/subscriptions","organizations_url":"https://api.github.com/users/Jason94/orgs","repos_url":"https://api.github.com/users/Jason94/repos","events_url":"https://api.github.com/users/Jason94/events{/privacy}","received_events_url":"https://api.github.com/users/Jason94/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2017-12-04T20:21:34Z","updated_at":"2017-12-05T18:20:55Z","closed_at":"2017-12-05T18:20:55Z","author_association":"NONE","body":"#### Do you want to request a *feature* or report a *bug*?\r\nReporting a bug\r\n\r\n#### What is the current behavior?\r\n\r\nSee this [Stack Overflow post](https://stackoverflow.com/questions/46930661/padrino-g-cannot-load-such-file-sequel-plugins-schema/47641213#47641213).\r\n\r\nThe Sequel orm option is currently broken. The gem has apparently dropped the support of the schema plugin, which we use in padrino. This is a particular problem because it is used in the blog tutorial on the website, and will block new users from learning Padrino.\r\n\r\nIf the Schema gem is being used, when you try to execute any padrino command you get this error:\r\n```\r\n/home/jason/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sequel-5.3.0/lib/sequel/model/base.rb:914:in `require': cannot load such file -- sequel/plugins/schema (LoadError)\r\n\tfrom /home/jason/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sequel-5.3.0/lib/sequel/model/base.rb:914:in `plugin_module'\r\n\tfrom /home/jason/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sequel-5.3.0/lib/sequel/model/base.rb:533:in `plugin'\r\n\tfrom /home/jason/programming/workspace_other/blog-tutorial/config/database.rb:1:in `<top (required)>'\r\n```\r\nI fixed the problem by commenting out the first line of the config/database.rb file that loaded the plugin:\r\n``` ruby\r\n#Sequel::Model.plugin(:schema)\r\nSequel::Model.raise_on_save_failure = false # Do not throw exceptions on failure\r\nSequel::Model.db = case Padrino.env\r\n  when :development then Sequel.connect(\"sqlite://db/blog_tutorial_development.db\", :loggers => [logger])\r\n  when :production  then Sequel.connect(\"sqlite://db/blog_tutorial_production.db\",  :loggers => [logger])\r\n  when :test        then Sequel.connect(\"sqlite://db/blog_tutorial_test.db\",        :loggers => [logger])\r\nend\r\n```\r\n\r\nI tested the whole blog tutorial project like this, and everything seemed to work. I'm not sure if simply dropping the plugin load will fix the bug, or if there is some functionality that relies on the plugin that will have to be rewritten.\r\n\r\n#### What is the expected behavior?\r\nPadrino should work correctly with the schema gem.\r\n\r\n#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?\r\nRuby - 2.4.2\r\nPadrino - 0.14.1.1\r\nSinatra - 2.0\r\nRack - 2.0.3\r\nOS - Elementary OS 0.4.1","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2164","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2164/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2164/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2164/events","html_url":"https://github.com/padrino/padrino-framework/issues/2164","id":277737155,"number":2164,"title":"padrino gen task doesn't fit latest ruby conventions","user":{"login":"jorgefuertes","id":194590,"avatar_url":"https://avatars3.githubusercontent.com/u/194590?v=4","gravatar_id":"","url":"https://api.github.com/users/jorgefuertes","html_url":"https://github.com/jorgefuertes","followers_url":"https://api.github.com/users/jorgefuertes/followers","following_url":"https://api.github.com/users/jorgefuertes/following{/other_user}","gists_url":"https://api.github.com/users/jorgefuertes/gists{/gist_id}","starred_url":"https://api.github.com/users/jorgefuertes/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jorgefuertes/subscriptions","organizations_url":"https://api.github.com/users/jorgefuertes/orgs","repos_url":"https://api.github.com/users/jorgefuertes/repos","events_url":"https://api.github.com/users/jorgefuertes/events{/privacy}","received_events_url":"https://api.github.com/users/jorgefuertes/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2017-11-29T12:31:16Z","updated_at":"2017-12-09T23:47:03Z","closed_at":"2017-12-09T23:47:03Z","author_association":"CONTRIBUTOR","body":"#### Do you want to request a *feature* or report a *bug*?\r\n\r\nfeature\r\n\r\n#### What is the current behavior?\r\n\r\n```padrino gen task```generate this file:\r\n\r\n```ruby\r\nnamespace :main do\r\n  desc \"Just a test task\"\r\n  task :test => :environment do\r\n    # This is a custom task.\r\n  end\r\nend\r\n```\r\n\r\n#### What is the expected behavior?\r\n\r\nIn a better form it should be:\r\n\r\n```ruby\r\nnamespace :main do\r\n  desc 'Just a test task'\r\n  task test: :environment do\r\n    # This is a custom task.\r\n  end\r\nend\r\n```\r\n","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2163","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2163/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2163/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2163/events","html_url":"https://github.com/padrino/padrino-framework/issues/2163","id":277735729,"number":2163,"title":"padrino gen task bad argument parsing","user":{"login":"jorgefuertes","id":194590,"avatar_url":"https://avatars3.githubusercontent.com/u/194590?v=4","gravatar_id":"","url":"https://api.github.com/users/jorgefuertes","html_url":"https://github.com/jorgefuertes","followers_url":"https://api.github.com/users/jorgefuertes/followers","following_url":"https://api.github.com/users/jorgefuertes/following{/other_user}","gists_url":"https://api.github.com/users/jorgefuertes/gists{/gist_id}","starred_url":"https://api.github.com/users/jorgefuertes/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jorgefuertes/subscriptions","organizations_url":"https://api.github.com/users/jorgefuertes/orgs","repos_url":"https://api.github.com/users/jorgefuertes/repos","events_url":"https://api.github.com/users/jorgefuertes/events{/privacy}","received_events_url":"https://api.github.com/users/jorgefuertes/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2017-11-29T12:26:13Z","updated_at":"2017-12-09T08:01:00Z","closed_at":"2017-12-09T08:00:42Z","author_association":"CONTRIBUTOR","body":"#### Do you want to request a *feature* or report a *bug*?\r\n\r\nbug\r\n\r\n#### What is the current behavior?\r\n\r\n```shell\r\n$> padrino gen task -n main -d \"Just a test task\" test\r\ncreate  tasks/main_a.rake\r\n```\r\n\r\nGenerated file has wrong name and description:\r\n\r\n```ruby\r\nnamespace :main do\r\n  desc \"Just\"\r\n  task :a => :environment do\r\n    # This is a custom task.\r\n  end\r\nend\r\n```\r\n\r\n#### What is the expected behavior?\r\n\r\n```shell\r\ncreate tasks/main_test.rake\r\n```\r\n\r\nHaving this file the following content:\r\n\r\n```ruby\r\nnamespace :main do\r\n  desc \"Just a test task\"\r\n  task :test => :environment do\r\n    # This is a custom task.\r\n  end\r\nend\r\n```\r\n\r\n#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?\r\n\r\n- Ruby 2.4.4\r\n- Padrino v. 0.14.1.1\r\n\r\nBut never worked.\r\n","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2159","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2159/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2159/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2159/events","html_url":"https://github.com/padrino/padrino-framework/issues/2159","id":274163071,"number":2159,"title":"Weirdness in Resolv.getaddress","user":{"login":"thesp0nge","id":143166,"avatar_url":"https://avatars3.githubusercontent.com/u/143166?v=4","gravatar_id":"","url":"https://api.github.com/users/thesp0nge","html_url":"https://github.com/thesp0nge","followers_url":"https://api.github.com/users/thesp0nge/followers","following_url":"https://api.github.com/users/thesp0nge/following{/other_user}","gists_url":"https://api.github.com/users/thesp0nge/gists{/gist_id}","starred_url":"https://api.github.com/users/thesp0nge/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/thesp0nge/subscriptions","organizations_url":"https://api.github.com/users/thesp0nge/orgs","repos_url":"https://api.github.com/users/thesp0nge/repos","events_url":"https://api.github.com/users/thesp0nge/events{/privacy}","received_events_url":"https://api.github.com/users/thesp0nge/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":6,"created_at":"2017-11-15T13:50:52Z","updated_at":"2017-12-09T08:18:43Z","closed_at":"2017-12-09T08:18:43Z","author_association":"NONE","body":"#### I want to report a *bug*\r\n\r\n#### What is the current behavior?\r\nThe problem is in DNS resolution and the different behaviour is, on the same machine, same RVM environment, between padrino in console and irb when calling Resolv.getaddress\r\n\r\nFrom within a padrino console session, a DNS resolution went in timeout\r\n\r\n```\r\n2.4.0 :012 > Resolv.getaddress('www.google.it')\r\nResolv::ResolvError: no address for www.google.it\r\n\tfrom /Users/thesp0nge/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/resolv.rb:95:in `getaddress'\r\n\tfrom /Users/thesp0nge/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/resolv.rb:45:in `getaddress'\r\n\tfrom (irb):12\r\n\tfrom /Users/thesp0nge/.rvm/gems/ruby-2.4.0@engage/gems/padrino-core-0.14.1.1/lib/padrino-core/cli/base.rb:43:in `console'\r\n\tfrom /Users/thesp0nge/.rvm/gems/ruby-2.4.0@engage/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'\r\n\tfrom /Users/thesp0nge/.rvm/gems/ruby-2.4.0@engage/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'\r\n\tfrom /Users/thesp0nge/.rvm/gems/ruby-2.4.0@engage/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'\r\n\tfrom /Users/thesp0nge/.rvm/gems/ruby-2.4.0@engage/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'\r\n\tfrom /Users/thesp0nge/.rvm/gems/ruby-2.4.0@engage/gems/padrino-core-0.14.1.1/bin/padrino:9:in `<top (required)>'\r\n\tfrom /Users/thesp0nge/.rvm/gems/ruby-2.4.0@engage/bin/padrino:22:in `load'\r\n\tfrom /Users/thesp0nge/.rvm/gems/ruby-2.4.0@engage/bin/padrino:22:in `<main>'\r\n\tfrom /Users/thesp0nge/.rvm/gems/ruby-2.4.0@engage/bin/ruby_executable_hooks:15:in `eval'\r\n\tfrom /Users/thesp0nge/.rvm/gems/ruby-2.4.0@engage/bin/ruby_executable_hooks:15:in `<main>'\r\n```\r\n\r\nFrom an IRB session, same ruby version, same gemset, same machine, I've got and immediate resolution :\r\n```\r\n2.4.0 :004 > d.getaddress('www.google.it')\r\n => \"172.217.19.131\"\r\n```\r\n\r\n#### What is the expected behavior?\r\nAlso in Padrino, the address should be resolved\r\n\r\n#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? \r\n```\r\nruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]\r\nPadrino v. 0.14.1.1\r\nsinatra 2.0.0\r\nRack 1.3 (Release: 2.0.3)\r\nDarwin pollon 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64\r\n```","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2157","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2157/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2157/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2157/events","html_url":"https://github.com/padrino/padrino-framework/issues/2157","id":272081020,"number":2157,"title":"humanize NoMethodError on padrino-0.14.1.1","user":{"login":"constdrop","id":7455098,"avatar_url":"https://avatars0.githubusercontent.com/u/7455098?v=4","gravatar_id":"","url":"https://api.github.com/users/constdrop","html_url":"https://github.com/constdrop","followers_url":"https://api.github.com/users/constdrop/followers","following_url":"https://api.github.com/users/constdrop/following{/other_user}","gists_url":"https://api.github.com/users/constdrop/gists{/gist_id}","starred_url":"https://api.github.com/users/constdrop/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/constdrop/subscriptions","organizations_url":"https://api.github.com/users/constdrop/orgs","repos_url":"https://api.github.com/users/constdrop/repos","events_url":"https://api.github.com/users/constdrop/events{/privacy}","received_events_url":"https://api.github.com/users/constdrop/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2017-11-08T05:45:20Z","updated_at":"2017-12-09T08:15:39Z","closed_at":"2017-12-09T08:15:39Z","author_association":"NONE","body":"I used padrino-0.14.1.1 and activesupport-5.1.1 in combination. ruby version is 2.3.0, sinatra is 2.0.0.\r\nI generate padrino admin app. When I display the login page (/admin/sessions/new) the following error occurred and become 500 error page.\r\n\r\n    DEBUG -  TEMPLATE (0.0007s) /sessions/new\r\n    2017-11-07 20:23:01 - NoMethodError - undefined method `humanize' for \"login.title\":String:\r\n\t    /Path/to/app/'vendor/bundle' /ruby/2.3.0/gems/padrino-admin-0.14.1.1/lib/padrino-admin/helpers/view_helpers.rb:43:in `padrino_admin_translate'\r\n    ...\r\n\r\nI add the following require to the beginning of view_helpers.rb provisionaly.\r\n\r\n    require 'active_support'\r\n    require 'active_support/core_ext/string'\r\n\r\nI think it may not be a bug. But if it is a bug, could you fix it?\r\nIf it is not a bug, I think it is not good to edit Padrino's files because of my application problem. Please let me know if you have any other good countermeasures.\r\n\r\nI have posted to stackoverflow same issue.\r\nhttps://stackoverflow.com/questions/47168434/humanize-nomethoderror-on-padrino-0-14-1-1","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2155","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2155/labels{/name}","comments_url":"https:
8000
//api.github.com/repos/padrino/padrino-framework/issues/2155/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2155/events","html_url":"https://github.com/padrino/padrino-framework/issues/2155","id":267186655,"number":2155,"title":"rake db:create using datamapper fails with error","user":{"login":"mishaaq","id":91020,"avatar_url":"https://avatars0.githubusercontent.com/u/91020?v=4","gravatar_id":"","url":"https://api.github.com/users/mishaaq","html_url":"https://github.com/mishaaq","followers_url":"https://api.github.com/users/mishaaq/followers","following_url":"https://api.github.com/users/mishaaq/following{/other_user}","gists_url":"https://api.github.com/users/mishaaq/gists{/gist_id}","starred_url":"https://api.github.com/users/mishaaq/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/mishaaq/subscriptions","organizations_url":"https://api.github.com/users/mishaaq/orgs","repos_url":"https://api.github.com/users/mishaaq/repos","events_url":"https://api.github.com/users/mishaaq/events{/privacy}","received_events_url":"https://api.github.com/users/mishaaq/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2017-10-20T14:03:28Z","updated_at":"2017-10-20T14:16:51Z","closed_at":"2017-10-20T14:16:51Z","author_association":"NONE","body":"#### Do you want to request a *feature* or report a *bug*?\r\n\r\nBug\r\n\r\n#### What is the current behavior?\r\n\r\nApplication created with generator specifying datamapper as a ORM and sqlite as a database provider. Running `bundle exec rake db:create` fails with error.\r\n\r\n`$ bundle exec rake db:create\r\nrake aborted!\r\nNameError: uninitialized constant Utils\r\n/Users/zarlm/.rvm/gems/ruby-2.3.0/gems/padrino-gen-0.14.1.1/lib/padrino-gen/padrino-tasks/datamapper.rb:53:in `block (2 levels) in <top (required)>'\r\n/Users/zarlm/.rvm/gems/ruby-2.3.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'\r\n/Users/zarlm/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'\r\n/Users/zarlm/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'\r\nTasks: TOP => db:create => dm:create\r\n(See full trace by running task with --trace)`\r\n\r\n#### What is the expected behavior?\r\n\r\ndatabase successfully created\r\n\r\n#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?\r\n\r\nruby 2.3.0\r\npadrino 0.14.1.1","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2152","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2152/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2152/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2152/events","html_url":"https://github.com/padrino/padrino-framework/issues/2152","id":253254845,"number":2152,"title":"[BUG] Padrino cannot download plugins","user":{"login":"hron84","id":88636,"avatar_url":"https://avatars3.githubusercontent.com/u/88636?v=4","gravatar_id":"","url":"https://api.github.com/users/hron84","html_url":"https://github.com/hron84","followers_url":"https://api.github.com/users/hron84/followers","following_url":"https://api.github.com/users/hron84/following{/other_user}","gists_url":"https://api.github.com/users/hron84/gists{/gist_id}","starred_url":"https://api.github.com/users/hron84/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/hron84/subscriptions","organizations_url":"https://api.github.com/users/hron84/orgs","repos_url":"https://api.github.com/users/hron84/repos","events_url":"https://api.github.com/users/hron84/events{/privacy}","received_events_url":"https://api.github.com/users/hron84/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2017-08-28T08:00:19Z","updated_at":"2017-09-02T04:54:32Z","closed_at":"2017-09-02T04:54:32Z","author_association":"NONE","body":"#### What is the current behavior?\r\n\r\n`padrino gen plugin coffee` cannot download the plugin from GitHub\r\n\r\n```\r\n$ padrino gen plugin coffee\r\n       apply  https://raw.github.com/padrino/padrino-recipes/master/plugins/coffee_plugin.rb\r\n  The template at https://raw.github.com/padrino/padrino-recipes/master/plugins/coffee_plugin.rb could not be found!\r\n```\r\n\r\n#### What is the expected behavior?\r\n\r\n??? \r\n\r\n#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?\r\n\r\n```\r\nGems included by the bundle:\r\n  * activemodel (5.1.3)\r\n  * activerecord (5.1.3)\r\n  * activesupport (5.1.3)\r\n  * arel (8.0.0)\r\n  * bundler (1.15.4)\r\n  * coffee-script (2.4.1)\r\n  * coffee-script-source (1.12.2)\r\n  * concurrent-ruby (1.0.5)\r\n  * diff-lcs (1.3)\r\n  * enumerable-lazy (0.0.2)\r\n  * execjs (2.7.0)\r\n  * ffi (1.9.18)\r\n  * haml (5.0.2)\r\n  * i18n (0.8.6)\r\n  * mail (2.6.6)\r\n  * mime-types (2.99.3)\r\n  * minitest (5.10.3)\r\n  * moneta (0.8.1)\r\n  * mustermann (1.0.1)\r\n  * mustermann19 (0.4.4)\r\n  * mysql2 (0.4.9)\r\n  * padrino (0.14.1.1)\r\n  * padrino-admin (0.14.1.1)\r\n  * padrino-cache (0.14.1.1)\r\n  * padrino-core (0.14.1.1)\r\n  * padrino-gen (0.14.1.1)\r\n  * padrino-helpers (0.14.1.1)\r\n  * padrino-mailer (0.14.1.1)\r\n  * padrino-support (0.14.1.1)\r\n  * rack (2.0.3)\r\n  * rack-coffee (1.0.3)\r\n  * rack-protection (2.0.0)\r\n  * rack-test (0.7.0)\r\n  * rake (12.0.0)\r\n  * rb-fsevent (0.10.2)\r\n  * rb-inotify (0.9.10)\r\n  * rspec (3.6.0)\r\n  * rspec-core (3.6.0)\r\n  * rspec-expectations (3.6.0)\r\n  * rspec-mocks (3.6.0)\r\n  * rspec-support (3.6.0)\r\n  * sass (3.5.1)\r\n  * sass-listen (4.0.0)\r\n  * sinatra (2.0.0)\r\n  * temple (0.8.0)\r\n  * thor (0.20.0)\r\n  * thread_safe (0.3.6)\r\n  * tilt (2.0.8)\r\n  * tzinfo (1.2.3)\r\n```\r\nand\r\n```\r\nRubyGems Environment:\r\n  - RUBYGEMS VERSION: 2.6.11\r\n  - RUBY VERSION: 2.4.1 (2017-03-22 patchlevel 111) [x86_64-linux]\r\n  - INSTALLATION DIRECTORY: /home/hron/.rvm/gems/ruby-2.4.1@dhtv\r\n  - USER INSTALLATION DIRECTORY: /home/hron/.gem/ruby/2.4.0\r\n  - RUBY EXECUTABLE: /home/hron/.rvm/rubies/ruby-2.4.1/bin/ruby\r\n  - EXECUTABLE DIRECTORY: /home/hron/.rvm/gems/ruby-2.4.1@dhtv/bin\r\n  - SPEC CACHE DIRECTORY: /home/hron/.gem/specs\r\n  - SYSTEM CONFIGURATION DIRECTORY: /etc\r\n  - RUBYGEMS PLATFORMS:\r\n    - ruby\r\n    - x86_64-linux\r\n  - GEM PATHS:\r\n     - /home/hron/.rvm/gems/ruby-2.4.1@dhtv\r\n     - /home/hron/.rvm/gems/ruby-2.4.1@global\r\n  - GEM CONFIGURATION:\r\n     - :update_sources => true\r\n     - :verbose => true\r\n     - :backtrace => false\r\n     - :bulk_threshold => 1000\r\n     - \"gem\" => \"--no-rdoc --no-ri\"\r\n  - REMOTE SOURCES:\r\n     - https://rubygems.org/\r\n  - SHELL PATH:\r\n     - /home/hron/.rvm/gems/ruby-2.4.1@dhtv/bin\r\n     - /home/hron/.rvm/gems/ruby-2.4.1@global/bin\r\n     - /home/hron/.rvm/rubies/ruby-2.4.1/bin\r\n     - /home/hron/.rvm/bin\r\n# ... snip ....\r\n```","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2150","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2150/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2150/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2150/events","html_url":"https://github.com/padrino/padrino-framework/issues/2150","id":249313146,"number":2150,"title":"Project generator silently ignores invalid -a option","user":{"login":"white-monkey","id":5384589,"avatar_url":"https://avatars3.githubusercontent.com/u/5384589?v=4","gravatar_id":"","url":"https://api.github.com/users/white-monkey","html_url":"https://github.com/white-monkey","followers_url":"https://api.github.com/users/white-monkey/followers","following_url":"https://api.github.com/users/white-monkey/following{/other_user}","gists_url":"https://api.github.com/users/white-monkey/gists{/gist_id}","starred_url":"https://api.github.com/users/white-monkey/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/white-monkey/subscriptions","organizations_url":"https://api.github.com/users/white-monkey/orgs","repos_url":"https://api.github.com/users/white-monkey/repos","events_url":"https://api.github.com/users/white-monkey/events{/privacy}","received_events_url":"https://api.github.com/users/white-monkey/received_events","type":"User","site_admin":false},"labels":[{"id":22570558,"url":"https://api.github.com/repos/padrino/padrino-framework/labels/bug","name":"bug","color":"e10c02","default":true}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2017-08-10T11:15:07Z","updated_at":"2017-09-02T07:16:40Z","closed_at":"2017-09-02T07:16:40Z","author_association":"NONE","body":"With current version 0.14.1.1:\r\n\r\n```\r\n$ padrino g project test -d sequel -a access97\r\n```\r\n\r\nsuccessfully generates the project, even though the RDBMS value is obviously invalid, and uses sqlite as default. I would expect an error message instead.","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2148","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2148/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2148/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2148/events","html_url":"https://github.com/padrino/padrino-framework/issues/2148","id":248212099,"number":2148,"title":"Migration Error","user":{"login":"stoplion","id":231343,"avatar_url":"https://avatars2.githubusercontent.com/u/231343?v=4","gravatar_id":"","url":"https://api.github.com/users/stoplion","html_url":"https://github.com/stoplion","followers_url":"https://api.github.com/users/stoplion/followers","following_url":"https://api.github.com/users/stoplion/following{/other_user}","gists_url":"https://api.github.com/users/stoplion/gists{/gist_id}","starred_url":"https://api.github.com/users/stoplion/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/stoplion/subscriptions","organizations_url":"https://api.github.com/users/stoplion/orgs","repos_url":"https://api.github.com/users/stoplion/repos","events_url":"https://api.github.com/users/stoplion/events{/privacy}","received_events_url":"https://api.github.com/users/stoplion/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2017-08-05T22:04:33Z","updated_at":"2017-09-02T04:05:33Z","closed_at":"2017-09-02T04:05:33Z","author_association":"NONE","body":"ruby '2.4.1'\r\n'padrino', '0.14.1.1'\r\n\r\n`bundle exec rake db:migrate`\r\nusing sqlite\r\nOSX 10.12.5\r\n\r\n```\r\nrake aborted!\r\nStandardError: An error has occurred, this and all later migrations canceled:\r\n\r\nDirectly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:\r\n\r\n  class CreateAccounts < ActiveRecord::Migration[4.2]\r\n\r\n```\r\n\r\n\r\nI changed `class CreateAccounts < ActiveRecord::Migration`\r\nto `class CreateAccounts < ActiveRecord::Migration[5.0]`\r\nand it worked..\r\n","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2145","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2145/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2145/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2145/events","html_url":"https://github.com/padrino/padrino-framework/issues/2145","id":234406596,"number":2145,"title":"Padrino using wrong model in admin layout when using model name other than the default","user":{"login":"LarryFransson","id":762866,"avatar_url":"https://avatars3.githubusercontent.com/u/762866?v=4","gravatar_id":"","url":"https://api.github.com/users/LarryFransson","html_url":"https://github.com/LarryFransson","followers_url":"https://api.github.com/users/LarryFransson/followers","following_url":"https://api.github.com/users/LarryFransson/following{/other_user}","gists_url":"https://api.github.com/users/LarryFransson/gists{/gist_id}","starred_url":"https://api.github.com/users/LarryFransson/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/LarryFransson/subscriptions","organizations_url":"https://api.github.com/users/LarryFransson/orgs","repos_url":"https://api.github.com/users/LarryFransson/repos","events_url":"https://api.github.com/users/LarryFransson/events{/privacy}","received_events_url":"https://api.github.com/users/LarryFransson/received_events","type":"User","site_admin":false},"labels":[{"id":84384208,"url":"https://api.github.com/repos/padrino/padrino-framework/labels/admin","name":"admin","color":"006b75","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2017-06-08T04:11:08Z","updated_at":"2017-06-10T05:26:04Z","closed_at":"2017-06-10T05:26:04Z","author_association":"NONE","body":"#### Do you want to request a *feature* or report a *bug*?\r\nReporting a bug.\r\n#### What is the current behavior?\r\nWhen generating the admin layout, line 21 of `admin/views/layouts/application.haml` reads\r\n```\r\n %li.navbar-edit-account=link_to tag_icon(:user), url(:accounts, :edit, :id => current_account.id), :title => pat(:profile), :class => 'navbar-nav-link'\r\n```\r\neven when a model name other than the default has been specified.\r\n\r\nThis results in a runtime error:  `Padrino::Routing::UnrecognizedException at /admin/\r\nRoute mapping for url(:\"accounts edit\") could not be found`\r\n\r\n#### What is the expected behavior?\r\nThe layout should be generated using the appropriate model name in place of `:accounts`.\r\n\r\n#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?\r\nPadrino 0.14.1.1, Sinatra 2.0.0, Ruby 2.4.1, CentOS 7","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2144","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2144/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2144/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2144/events","html_url":"https://github.com/padrino/padrino-framework/issues/2144","id":234381205,"number":2144,"title":"Encoding problem under lastest padrino ","user":{"login":"jiyaping","id":689755,"avatar_url":"https://avatars2.githubusercontent.com/u/689755?v=4","gravatar_id":"","url":"https://api.github.com/users/jiyaping","html_url":"https://github.com/jiyaping","followers_url":"https://api.github.com/users/jiyaping/followers","following_url":"https://api.github.com/users/jiyaping/following{/other_user}","gists_url":"https://api.github.com/users/jiyaping/gists{/gist_id}","starred_url":"https://api.github.com/users/jiyaping/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jiyaping/subscriptions","organizations_url":"https://api.github.com/users/jiyaping/orgs","repos_url":"https://api.github.com/users/jiyaping/repos","events_url":"https://api.github.com/users/jiyaping/events{/privacy}","received_events_url":"https://api.github.com/users/jiyaping/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2017-06-08T00:44:34Z","updated_at":"2017-06-08T17:17:26Z","closed_at":"2017-06-08T17:17:25Z","author_association":"NONE","body":"Hi  @ujifgc  , As issue #2143  mentioned ,I have a project using padrino version 0.13.3.2 and upgrade to lastest version 0.14.1.1, Some encoding problem occured , as following:\r\n\r\n```\r\nE:\\aocproject>padrino g admin -e erb\r\nd:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/padrino-admin-0.14.1.1/lib/padrino-admin/generators/actions.rb:75:in `scan': invalid byte sequence in GBK (ArgumentError)\r\n        from d:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/padrino-admin-0.14.1.1/lib/padrino-admin/generators/actions.rb:75:in `fetch_app_name'\r\n        from d:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/padrino-admin-0.14.1.1/lib/padrino-admin/generators/admin_app.rb:57:in `create_admin'\r\n        from d:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'\r\n        from d:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'\r\n        from d:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'\r\n        from d:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'\r\n\r\n```\r\n\r\nIs there any solutions?  Thanks.","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2143","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2143/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2143/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2143/events","html_url":"https://github.com/padrino/padrino-framework/issues/2143","id":234247608,"number":2143,"title":"new created pradrino project show errors","user":{"login":"jiyaping","id":689755,"avatar_url":"https://avatars2.githubusercontent.com/u/689755?v=4","gravatar_id":"","url":"https://api.github.com/users/jiyaping","html_url":"https://github.com/jiyaping","followers_url":"https://api.github.com/users/jiyaping/followers","following_url":"https://api.github.com/users/jiyaping/following{/other_user}","gists_url":"https://api.github.com/users/jiyaping/gists{/gist_id}","starred_url":"https://api.github.com/users/jiyaping/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jiyaping/subscriptions","organizations_url":"https://api.github.com/users/jiyaping/orgs","repos_url":"https://api.github.com/users/jiyaping/repos","events_url":"https://api.github.com/users/jiyaping/events{/privacy}","received_events_url":"https://api.github.com/users/jiyaping/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2017-06-07T15:21:52Z","updated_at":"2017-06-07T17:02:47Z","closed_at":"2017-06-07T17:02:47Z","author_association":"NONE","body":"\r\nHi, I have created a padrino project and run padrino start command, visit the http://127.0.0.1:3000, show following errors:\r\n\r\n```\r\n[2017-06-07 23:09:05] INFO  WEBrick 1.3.1\r\n[2017-06-07 23:09:05] INFO  ruby 2.2.4 (2015-12-16) [i386-mingw32]\r\n[2017-06-07 23:09:05] INFO  WEBrick::HTTPServer#start: pid=1112 port=3000\r\n2017-06-07 23:09:10 - NoMethodError - undefined method `indifferent_params' for #<Testest::App:0x44cbe18>:\r\n        d:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/padrino-core-0.13.3.2/lib/padrino-core/application/routing.rb:933:in `dispatch!'\r\n        d:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `block in call!'\r\n        d:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'\r\n        d:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'\r\n.... ...\r\n```\r\n\r\nmy environments is:\r\npadrino 0.13.3.2\r\nruby 2.2.4p230 (2015-12-16 revision 53155) [i386-mingw32]\r\n\r\n","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2140","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2140/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2140/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2140/events","html_url":"https://github.com/padrino/padrino-framework/issues/2140","id":233474733,"number":2140,"title":"IRC channel maintenance","user":{"login":"adam12","id":17083,"avatar_url":"https://avatars1.githubusercontent.com/u/17083?v=4","gravatar_id":"","url":"https://api.github.com/users/adam12","html_url":"https://github.com/adam12","followers_url":"https://api.github.com/users/adam12/followers","following_url":"https://api.github.com/users/adam12/following{/other_user}","gists_url":"https://api.github.com/users/adam12/gists{/gist_id}","starred_url":"https://api.github.com/users/adam12/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/adam12/subscriptions","organizations_url":"https://api.github.com/users/adam12/orgs","repos_url":"https://api.github.com/users/adam12/repos","events_url":"https://api.github.com/users/adam12/events{/privacy}","received_events_url":"https://api.github.com/users/adam12/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2017-06-05T01:27:48Z","updated_at":"2017-06-05T18:20:38Z","closed_at":"2017-06-05T18:20:38Z","author_association":"CONTRIBUTOR","body":"Some of us (@wikimatze and me @adam12) have been idling in the channel and helping users, but some things have been difficult without operator status (like updating channel title).\r\n\r\n@skade implemented a temporary fix a while ago, but it would be great to have a more permanent fix.\r\n\r\nI opened discussions with Freenode staff, and it was suggested that the project be registered with them through a short email.\r\n\r\nThe format of that email to follow this: https://gist.github.com/AbstractBeliefs/f82487dc7d7db54d7c94740c25c08084\r\n\r\nTo be submitted here:\r\nprojects@freenode.net\r\n\r\nBy someone from this list: \r\nhttps://github.com/orgs/padrino/people\r\n\r\nAnd then we can update the list of operators.\r\n\r\nIs this something we can get taken care of?\r\n\r\ncc @achiu (channel founder)","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2139","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2139/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2139/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2139/events","html_url":"https://github.com/padrino/padrino-framework/issues/2139","id":233469759,"number":2139,"title":"json are not parse properly into params when content-type application/json","user":{"login":"faustoct","id":3135444,"avatar_url":"https://avatars0.githubusercontent.com/u/3135444?v=4","gravatar_id":"","url":"https://api.github.com/users/faustoct","html_url":"https://github.com/faustoct","followers_url":"https://api.github.com/users/faustoct/followers","following_url":"https://api.github.com/users/faustoct/following{/other_user}","gists_url":"https://api.github.com/users/faustoct/gists{/gist_id}","starred_url":"https://api.github.com/users/faustoct/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/faustoct/subscriptions","organizations_url":"https://api.github.com/users/faustoct/orgs","repos_url":"https://api.github.com/users/faustoct/repos","events_url":"https://api.github.com/users/faustoct/events{/privacy}","received_events_url":"https://api.github.com/users/faustoct/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2017-06-05T00:12:46Z","updated_at":"2017-06-05T11:47:47Z","closed_at":"2017-06-05T06:11:32Z","author_association":"NONE","body":"#### Do you want to request a *feature* or report a *bug*?\r\nbug\r\n\r\n#### What is the current behavior?\r\nwhen upgarded to 0.14.2 version $.post('/something',{val: 1},function(){}) stopped working\r\n\r\n*If the current behavior is a bug, please provide the steps to reproduce it and if possible a minimal demo of the problem via https://github.com/ or https://gist.github.com/*\r\n\r\n#### What is the expected behavior?\r\nshould get json through params variable\r\n\r\n#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?\r\npadrino 0.14.2\r\n","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2138","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2138/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2138/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2138/events","html_url":"https://github.com/padrino/padrino-framework/issues/2138","id":233462211,"number":2138,"title":"Rakefile fails","user":{"login":"faustoct","id":3135444,"avatar_url":"https://avatars0.githubusercontent.com/u/3135444?v=4","gravatar_id":"","url":"https://api.github.com/users/faustoct","html_url":"https://github.com/faustoct","followers_url":"https://api.github.com/users/faustoct/followers","following_url":"https://api.github.com/users/faustoct/following{/other_user}","gists_url":"https://api.github.com/users/faustoct/gists{/gist_id}","starred_url":"https://api.github.com/users/faustoct/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/faustoct/subscriptions","organizations_url":"https://api.github.com/users/faustoct/orgs","repos_url":"https://api.github.com/users/faustoct/repos","events_url":"https://api.github.com/users/faustoct/events{/privacy}","received_events_url":"https://api.github.com/users/faustoct/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":16,"created_at":"2017-06-04T21:46:31Z","updated_at":"2017-06-05T16:19:01Z","closed_at":"2017-06-05T16:10:53Z","author_association":"NONE","body":"#### Do you want to request a *feature* or report a *bug*?\r\nBug\r\n\r\n#### What is the current behavior?\r\nit fails when run: `bundle exec rake -P`\r\n\r\n*If the current behavior is a bug, please provide the steps to reproduce it and if possible a minimal demo of the problem via https://github.com/ or https://gist.github.com/*\r\n\r\n#### What is the expected behavior?\r\n\r\n#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?\r\n0.14.2\r\n\r\nSimple Rakefile can't finish execution (fails)\r\n\r\n    require 'bundler/setup'\r\n    require 'padrino-core/cli/rake'\r\n    PadrinoTasks.use(:mongoid)\r\n    PadrinoTasks.init\r\n\r\n\r\n\r\nError message\r\n```\r\n$ bundle exec rake -P\r\nrake aborted!\r\nSyntaxError: /Users/fausto/.rvm/gems/ruby-2.3.0/gems/padrino-gen-0.14.0.2/lib/padrino-gen/padrino-tasks/activerecord.rb:146: syntax error, unexpected tIDENTIFIER, expecting keyword_end\r\n      desc \"Runs the \"up\" for a given MIGRATION_VERSION.\"\r\n                        ^\r\n/Users/fausto/.rvm/gems/ruby-2.3.0/gems/padrino-gen-0.14.0.2/lib/padrino-gen/padrino-tasks/activerecord.rb:149: syntax error, unexpected tIDENTIFIER, expecting keyword_end\r\n      desc \"Runs the \"down\" for a given MIGRATION_VERSION.\"\r\n                          ^\r\n/Users/fausto/.rvm/gems/ruby-2.3.0/gems/padrino-core-0.14.0.2/lib/padrino-core/cli/rake.rb:15:in `init'\r\n/Users/fausto/Projects/coding/4linked/Rakefile:15:in `<top (required)>'\r\n/Users/fausto/.rvm/gems/ruby-2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'\r\n/Users/fausto/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'\r\n/Users/fausto/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'\r\n(See full trace by running task with --trace)\r\n```","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2136","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2136/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2136/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2136/events","html_url":"https://github.com/padrino/padrino-framework/issues/2136","id":229052294,"number":2136,"title":"Padrino 0.14.1 fails to start w/o haml","user":{"login":"pdlug","id":1077,"avatar_url":"https://avatars3.githubusercontent.com/u/1077?v=4","gravatar_id":"","url":"https://api.github.com/users/pdlug","html_url":"https://github.com/pdlug","followers_url":"https://api.github.com/users/pdlug/followers","following_url":"https://api.github.com/users/pdlug/following{/other_user}","gists_url":"https://api.github.com/users/pdlug/gists{/gist_id}","starred_url":"https://api.github.com/users/pdlug/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/pdlug/subscriptions","organizations_url":"https://api.github.com/users/pdlug/orgs","repos_url":"https://api.github.com/users/pdlug/repos","events_url":"https://api.github.com/users/pdlug/events{/privacy}","received_events_url":"https://api.github.com/users/pdlug/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2017-05-16T14:24:14Z","updated_at":"2017-05-16T20:43:40Z","closed_at":"2017-05-16T20:43:40Z","author_association":"CONTRIBUTOR","body":"Padrino 0.14.1 fails to start if haml is not in the bundle, this worked in 0.14.0.2 (probably related to the change to support hamlit?).\r\n\r\n```\r\nLoadError: cannot load such file -- haml\r\n/usr/src/app/vendor/ruby/2.4.0/gems/tilt-2.0.7/lib/tilt/haml.rb:2:in `require'\r\n/usr/src/app/vendor/ruby/2.4.0/gems/tilt-2.0.7/lib/tilt/haml.rb:2:in `<top (required)>'\r\n/usr/src/app/vendor/ruby/2.4.0/gems/tilt-2.0.7/lib/tilt/mapping.rb:243:in `require'\r\n/usr/src/app/vendor/ruby/2.4.0/gems/tilt-2.0.7/lib/tilt/mapping.rb:243:in `block in lazy_load'\r\n/usr/src/app/vendor/ruby/2.4.0/gems/tilt-2.0.7/lib/tilt/mapping.rb:241:in `each'\r\n/usr/src/app/vendor/ruby/2.4.0/gems/tilt-2.0.7/lib/tilt/mapping.rb:241:in `lazy_load'\r\n/usr/src/app/vendor/ruby/2.4.0/gems/tilt-2.0.7/lib/tilt/mapping.rb:216:in `lookup'\r\n/usr/src/app/vendor/ruby/2.4.0/gems/tilt-2.0.7/lib/tilt/mapping.rb:154:in `[]'\r\n/usr/src/app/vendor/ruby/2.4.0/gems/tilt-2.0.7/lib/tilt.rb:53:in `template_for'\r\n/usr/src/app/vendor/ruby/2.4.0/gems/padrino-helpers-0.14.1/lib/padrino-helpers/output_helpers/haml_handler.rb:5:in `<module:OutputHelpers>'\r\n/usr/src/app/vendor/ruby/2.4.0/gems/padrino-helpers-0.14.1/lib/padrino-helpers/output_helpers/haml_handler.rb:3:in `<module:Helpers>'\r\n/usr/src/app/vendor/ruby/2.4.0/gems/padrino-helpers-0.14.1/lib/padrino-helpers/output_helpers/haml_handler.rb:2:in `<module:Padrino>'\r\n/usr/src/app/vendor/ruby/2.4.0/gems/padrino-helpers-0.14.1/lib/padrino-helpers/output_helpers/haml_handler.rb:1:in `<top (required)>'\r\n/usr/src/app/vendor/ruby/2.4.0/gems/padrino-support-0.14.1/lib/padrino-support/file_set.rb:23:in `require'\r\n/usr/src/app/vendor/ruby/2.4.0/gems/padrino-support-0.14.1/lib/padrino-support/file_set.rb:23:in `block in glob_require'\r\n/usr/src/app/vendor/ruby/2.4.0/gems/padrino-support-0.14.1/lib/padrino-support/file_set.rb:14:in `block in glob'\r\n/usr/src/app/vendor/ruby/2.4.0/gems/padrino-support-0.14.1/lib/padrino-support/file_set.rb:14:in `each'\r\n/usr/src/app/vendor/ruby/2.4.0/gems/padrino-support-0.14.1/lib/padrino-support/file_set.rb:14:in `glob'\r\n/usr/src/app/vendor/ruby/2.4.0/gems/padrino-support-0.14.1/lib/padrino-support/file_set.rb:23:in `glob_require'\r\n/usr/src/app/vendor/ruby/2.4.0/gems/padrino-helpers-0.14.1/lib/padrino-helpers.rb:9:in `<top (required)>'\r\n/usr/src/app/vendor/ruby/2.4.0/gems/padrino-0.14.1/lib/padrino.rb:4
7d21
:in `require'\r\n/usr/src/app/vendor/ruby/2.4.0/gems/padrino-0.14.1/lib/padrino.rb:4:in `<top (required)>'\r\n```","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2135","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2135/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2135/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2135/events","html_url":"https://github.com/padrino/padrino-framework/issues/2135","id":228720541,"number":2135,"title":"Push updated version w/ fix for syntax error in activerecord padrino-gen tasks","user":{"login":"pdlug","id":1077,"avatar_url":"https://avatars3.githubusercontent.com/u/1077?v=4","gravatar_id":"","url":"https://api.github.com/users/pdlug","html_url":"https://github.com/pdlug","followers_url":"https://api.github.com/users/pdlug/followers","following_url":"https://api.github.com/users/pdlug/following{/other_user}","gists_url":"https://api.github.com/users/pdlug/gists{/gist_id}","starred_url":"https://api.github.com/users/pdlug/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/pdlug/subscriptions","organizations_url":"https://api.github.com/users/pdlug/orgs","repos_url":"https://api.github.com/users/pdlug/repos","events_url":"https://api.github.com/users/pdlug/events{/privacy}","received_events_url":"https://api.github.com/users/pdlug/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2017-05-15T13:47:30Z","updated_at":"2017-05-16T04:56:48Z","closed_at":"2017-05-16T04:56:48Z","author_association":"CONTRIBUTOR","body":"There's a syntax error in the padrino-gen activerecord tasks which was resolved with commit [4a80dca](https://github.com/padrino/padrino-framework/commit/4a80dca4ec0c52a9c7daa2e28d17c1d8cb024e4b). Can someone push an updated gem to resolve this? Thanks.","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2134","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2134/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2134/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2134/events","html_url":"https://github.com/padrino/padrino-framework/issues/2134","id":228547016,"number":2134,"title":"Rake Tasks for activerecord (up/down) broken?","user":{"login":"woeps","id":225755,"avatar_url":"https://avatars1.githubusercontent.com/u/225755?v=4","gravatar_id":"","url":"https://api.github.com/users/woeps","html_url":"https://github.com/woeps","followers_url":"https://api.github.com/users/woeps/followers","following_url":"https://api.github.com/users/woeps/following{/other_user}","gists_url":"https://api.github.com/users/woeps/gists{/gist_id}","starred_url":"https://api.github.com/users/woeps/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/woeps/subscriptions","organizations_url":"https://api.github.com/users/woeps/orgs","repos_url":"https://api.github.com/users/woeps/repos","events_url":"https://api.github.com/users/woeps/events{/privacy}","received_events_url":"https://api.github.com/users/woeps/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2017-05-14T14:57:58Z","updated_at":"2017-05-14T15:05:20Z","closed_at":"2017-05-14T15:05:20Z","author_association":"NONE","body":"#### Do you want to request a *feature* or report a *bug*?\r\nBug\r\n\r\n#### What is the current behavior?\r\nUpon running `padrino rake -T` I get:\r\n```\r\nrake aborted!\r\nSyntaxError: /usr/lib/ruby/gems/2.4.0/gems/padrino-gen-0.14.0.2/lib/padrino-gen/padrino-tasks/activerecord.rb:146: syntax error, unexpected tIDENTIFIER, expecting keyword_end\r\n      desc \"Runs the \"up\" for a given MIGRATION_VERSIO\r\n                        ^\r\n/usr/lib/ruby/gems/2.4.0/gems/padrino-gen-0.14.0.2/lib/padrino-gen/padrino-tasks/activerecord.rb:149: syntax error, unexpected tIDENTIFIER, expecting keyword_end\r\n      desc \"Runs the \"down\" for a given MIGRATION_VERSIO\r\n                          ^\r\n/usr/lib/ruby/gems/2.4.0/gems/padrino-gen-0.14.0.2/lib/padrino-gen/padrino-tasks/activerecord.rb:318: syntax error, unexpected keyword_end, expecting end-of-input\r\n  end\r\n     ^\r\n/run/media/chris/DATA/chris/Projects/Ruby/fms_core_prototype/Rakefile:6:in `<top (required)>'\r\n(See full trace by running task with --trace)\r\n```\r\n\r\n#### What is the expected behavior?\r\nGet the list of available Rake-Tasks printed out to the terminal.\r\n\r\n#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?\r\nI just updated Gems to:\r\n* Ruby 2.4.1p111\r\n* Padrino 0.14.0.2\r\n* Sinatra 2.0.0\r\n* Rack 2.0.2\r\n* OS: Linux (Manjaro Linux 17.0.1, Kernel: 4.9.24-1)\r\n\r\n#### Solution\r\nThe problem seems to lie in `padrino-gen-0.14.0.2/lib/padrino-gen/padrino-tasks/activerecord.rb` (like the errormessage states). More precisely: the used quotation marks\r\nCurrent code:\r\n```ruby\r\n# padrino-gen-0.14.0.2/lib/padrino-gen/padrino-tasks/activerecord.rb\r\n# Line 145\r\n      desc \"Runs the \"up\" for a given MIGRATION_VERSION.\"  # \"up\" is the problem\r\n      task(:up => :skeleton){ migrate_as(:up) }\r\n\r\n      desc \"Runs the \"down\" for a given MIGRATION_VERSION.\"  # \"down\" is the problem\r\n      task(:down => :skeleton){ migrate_as(:down) }\r\n```\r\nEscaping the quotation marks seems to resolve the issue:\r\n```ruby\r\n      desc \"Runs the \\\"up\\\" for a given MIGRATION_VERSION.\"  # \"up\" is the problem\r\n      task(:up => :skeleton){ migrate_as(:up) }\r\n\r\n      desc \"Runs the \\\"down\\\" for a given MIGRATION_VERSION.\"  # \"down\" is the problem\r\n      task(:down => :skeleton){ migrate_as(:down) }\r\n```","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2132","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2132/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2132/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2132/events","html_url":"https://github.com/padrino/padrino-framework/issues/2132","id":226871705,"number":2132,"title":"NoMethodError - undefined method `indifferent_params' with sinatra v2.0.0","user":{"login":"sue445","id":608755,"avatar_url":"https://avatars0.githubusercontent.com/u/608755?v=4","gravatar_id":"","url":"https://api.github.com/users/sue445","html_url":"https://github.com/sue445","followers_url":"https://api.github.com/users/sue445/followers","following_url":"https://api.github.com/users/sue445/following{/other_user}","gists_url":"https://api.github.com/users/sue445/gists{/gist_id}","starred_url":"https://api.github.com/users/sue445/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/sue445/subscriptions","organizations_url":"https://api.github.com/users/sue445/orgs","repos_url":"https://api.github.com/users/sue445/repos","events_url":"https://api.github.com/users/sue445/events{/privacy}","received_events_url":"https://api.github.com/users/sue445/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":5,"created_at":"2017-05-07T16:09:24Z","updated_at":"2017-06-04T21:44:16Z","closed_at":"2017-05-08T06:31:37Z","author_association":"CONTRIBUTOR","body":"#### Do you want to request a *feature* or report a *bug*?\r\nbug\r\n\r\n#### What is the current behavior?\r\n\r\nGemfile\r\n\r\n```ruby\r\ngem \"padrino\", \"0.14.0.1\"\r\ngem \"sinatra\", \"2.0.0\"\r\n```\r\n\r\nWhen boot padrino and access any action, padrino is crashed!\r\n\r\n```\r\nbundle exec padrino s\r\n\r\n(snip)\r\n\r\n2017-05-08 01:00:17 - NoMethodError - undefined method `indifferent_params' for #<Sebastian::App:0x007fb6600492f0>:\r\n\t/Users/sue445/dev/workspace/github.com/sue445/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/padrino-core-0.14.0.1/lib/padrino-core/application/routing.rb:933:in `dispatch!'\r\n\t/Users/sue445/dev/workspace/github.com/sue445/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `block in call!'\r\n\t/Users/sue445/dev/workspace/github.com/sue445/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'\r\n\t/Users/sue445/dev/workspace/github.com/sue445/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'\r\n\t/Users/sue445/dev/workspace/github.com/sue445/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'\r\n\t/Users/sue445/dev/workspace/github.com/sue445/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `call!'\r\n\t/Users/sue445/dev/workspace/github.com/sue445/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:913:in `call'\r\n\t/Users/sue445/dev/workspace/github.com/sue445/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/rollbar-2.14.1/lib/rollbar/middleware/rack.rb:20:in `block in call'\r\n\t/Users/sue445/dev/workspace/github.com/sue445/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/rollbar-2.14.1/lib/rollbar.rb:145:in `scoped'\r\n\t/Users/sue445/dev/workspace/github.com/sue445/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/rollbar-2.14.1/lib/rollbar/middleware/rack.rb:18:in `call'\r\n\t/Users/sue445/dev/workspace/github.com/sue445/sebastian-badge/lib/connection_pool_management_middleware.rb:7:in `block in call'\r\n\t/Users/sue445/dev/workspace/github.com/sue445/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'\r\n\t/Users/sue445/dev/workspace/github.com/sue445/sebastian-badge/lib/connection_pool_management_middleware.rb:7:in `call'\r\n```\r\n\r\n#### What is the expected behavior?\r\nno error\r\n\r\n#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?\r\n\r\n* Ruby: 2.4.1\r\n* Padrino: 0.14.0.1\r\n* Sinatra: 2.0.0\r\n* Rack: 2.0.1\r\n* OS: OSX 10.9.5\r\n\r\n> Did this work in previous versions?\r\n\r\nSinatra 2.0.0.rc2 is no problem. \r\n\r\nI think this is affecting.\r\nhttps://github.com/sinatra/sinatra/pull/1279","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2128","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2128/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2128/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2128/events","html_url":"https://github.com/padrino/padrino-framework/issues/2128","id":216273450,"number":2128,"title":"Layout is enabled when using partial","user":{"login":"krororo","id":3143443,"avatar_url":"https://avatars2.githubusercontent.com/u/3143443?v=4","gravatar_id":"","url":"https://api.github.com/users/krororo","html_url":"https://github.com/krororo","followers_url":"https://api.github.com/users/krororo/followers","following_url":"https://api.github.com/users/krororo/following{/other_user}","gists_url":"https://api.github.com/users/krororo/gists{/gist_id}","starred_url":"https://api.github.com/users/krororo/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/krororo/subscriptions","organizations_url":"https://api.github.com/users/krororo/orgs","repos_url":"https://api.github.com/users/krororo/repos","events_url":"https://api.github.com/users/krororo/events{/privacy}","received_events_url":"https://api.github.com/users/krororo/received_events","type":"User","site_admin":false},"labels":[{"id":22570558,"url":"https://api.github.com/repos/padrino/padrino-framework/labels/bug","name":"bug","color":"e10c02","default":true}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2017-03-23T02:49:53Z","updated_at":"2017-03-23T06:44:35Z","closed_at":"2017-03-23T05:46:46Z","author_association":"CONTRIBUTOR","body":"#### Do you want to request a *feature* or report a *bug*?\r\nbug\r\n\r\n#### What is the current behavior?\r\nfollowing example: \r\n\r\nlayouts/application.haml\r\n```haml\r\n!!!\r\n%html\r\n  #header\r\n    application\r\n  = yield\r\n```\r\n\r\nindex.haml\r\n```haml\r\nindex\r\n%br\r\n= partial 'foo'\r\n```\r\n\r\n_foo.haml\r\n```haml\r\nfoo\r\n```\r\n\r\nrenderd html is\r\n\r\n```html\r\n<!DOCTYPE html>\r\n<html>\r\n  <div id='header'>\r\n    application\r\n  </div>\r\n  index\r\n  <br>\r\n  <!DOCTYPE html>\r\n  <html>\r\n    <div id='header'>\r\n      application\r\n    </div>\r\n    foo\r\n  </html>\r\n</html>\r\n```\r\n#### What is the expected behavior?\r\n\r\nrendered\r\n\r\n```html\r\n<!DOCTYPE html>\r\n<html>\r\n  <div id='header'>\r\n    application\r\n  </div>\r\n  index\r\n  <br>\r\n  foo\r\n</html>\r\n```\r\n\r\n#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?\r\n\r\nPadrino 0.14.0\r\n\r\nIt works at padrino 0.13.3.3 \r\n","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2125","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2125/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2125/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2125/events","html_url":"https://github.com/padrino/padrino-framework/issues/2125","id":213320566,"number":2125,"title":"catching `LoadError` when loading `database.rb` leads to confusing errors","user":{"login":"fnordfish","id":12839,"avatar_url":"https://avatars0.githubusercontent.com/u/12839?v=4","gravatar_id":"","url":"https://api.github.com/users/fnordfish","html_url":"https://github.com/fnordfish","followers_url":"https://api.github.com/users/fnordfish/followers","following_url":"https://api.github.com/users/fnordfish/following{/other_user}","gists_url":"https://api.github.com/users/fnordfish/gists{/gist_id}","starred_url":"https://api.github.com/users/fnordfish/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/fnordfish/subscriptions","organizations_url":"https://api.github.com/users/fnordfish/orgs","repos_url":"https://api.github.com/users/fnordfish/repos","events_url":"https://api.github.com/users/fnordfish/events{/privacy}","received_events_url":"https://api.github.com/users/fnordfish/received_events","type":"User","site_admin":false},"labels":[{"id":22570558,"url":"https://api.github.com/repos/padrino/padrino-framework/labels/bug","name":"bug","color":"e10c02","default":true},{"id":24599835,"url":"https://api.github.com/repos/padrino/padrino-framework/labels/reloader","name":"reloader","color":"0b02e1","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2017-03-10T11:47:14Z","updated_at":"2017-03-13T09:24:34Z","closed_at":"2017-03-13T09:24:34Z","author_association":"CONTRIBUTOR","body":"I've run into an interesting to track down error using padrino 0.13.3.3 and sequel 4.44.0 (also see jeremyevans/sequel#1317)\r\n\r\nWhen a `LoadError` is raised inside `database.rb` it is going to get \"swallowed\" which leads to errors way later in the application.\r\n\r\nIn my particular case a `LoadError` was raised before the database connection could be established. Since the loader just carried on, it finally crashed when loading a model (which do some introspection on their database)\r\n\r\nWhile this behaviour is certainly useful for dealing with a common applications `/lib` directories, it hides very useful errors in important setup/init files.\r\nIs there any way to exclude the `database.rb` from this (otherwise useful) loading behaviour? ","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2124","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2124/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2124/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2124/events","html_url":"https://github.com/padrino/padrino-framework/issues/2124","id":210210094,"number":2124,"title":"how to handle subdomains per controllers","user":{"login":"faustoct","id":3135444,"avatar_url":"https://avatars0.githubusercontent.com/u/3135444?v=4","gravatar_id":"","url":"https://api.github.com/users/faustoct","html_url":"https://github.com/faustoct","followers_url":"https://api.github.com/users/faustoct/followers","following_url":"https://api.github.com/users/faustoct/following{/other_user}","gists_url":"https://api.github.com/users/faustoct/gists{/gist_id}","starred_url":"https://api.github.com/users/faustoct/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/faustoct/subscriptions","organizations_url":"https://api.github.com/users/faustoct/orgs","repos_url":"https://api.github.com/users/faustoct/repos","events_url":"https://api.github.com/users/faustoct/events{/privacy}","received_events_url":"https://api.github.com/users/faustoct/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":5,"created_at":"2017-02-25T04:36:37Z","updated_at":"2017-03-01T06:49:23Z","closed_at":"2017-03-01T06:21:16Z","author_association":"NONE","body":"How to handling subdomains in certain controllers:\r\nsub1.domain.com -> Controller::Sub1\r\nsub2.domain.com -> Controller::Sub2\r\nothers -> Controller::Basic\r\n\r\nhow to do it?","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2119","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2119/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2119/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2119/events","html_url":"https://github.com/padrino/padrino-framework/issues/2119","id":202299298,"number":2119,"title":"Add below line in Rakefile  \"require \"bundler/gem_tasks\"\"","user":{"login":"grasp","id":28118,"avatar_url":"https://avatars1.githubusercontent.com/u/28118?v=4","gravatar_id":"","url":"https://api.github.com/users/grasp","html_url":"https://github.com/grasp","followers_url":"https://api.github.com/users/grasp/followers","following_url":"https://api.github.com/users/grasp/following{/other_user}","gists_url":"https://api.github.com/users/grasp/gists{/gist_id}","starred_url":"https://api.github.com/users/grasp/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/grasp/subscriptions","organizations_url":"https://api.github.com/users/grasp/orgs","repos_url":"https://api.github.com/users/grasp/repos","events_url":"https://api.github.com/users/grasp/events{/privacy}","received_events_url":"https://api.github.com/users/grasp/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2017-01-21T07:22:16Z","updated_at":"2017-03-07T07:15:59Z","closed_at":"2017-03-07T07:15:59Z","author_association":"NONE","body":"#### Do you want to request a *feature* or report a *bug*?\r\n\r\nto add below line in Rakefile\r\n\"require \"bundler/gem_tasks\"\"\r\n\r\n#### What is the current behavior?\r\n\r\nwhen generate project as a gem, \"rake build\" command not work.\r\nrake did not find build task.\r\n\r\n*If the current behavior is a bug, please provide the steps to reproduce it and if possible a minimal demo of the problem via https://github.com/ or https://gist.github.com/*\r\n\r\npadrino g project abc -g \r\n\r\n#### What is the expected behavior?\r\n\r\nrake build should generate a gem under pkg folder automatically.\r\n\r\n#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?\r\n0.13.3","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2118","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2118/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2118/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2118/events","html_url":"https://github.com/padrino/padrino-framework/issues/2118","id":202057437,"number":2118,"title":"Allow for replacing padrino's logger with our own","user":{"login":"cburgmer","id":101613,"avatar_url":"https://avatars0.githubusercontent.com/u/101613?v=4","gravatar_id":"","url":"https://api.github.com/users/cburgmer","html_url":"https://github.com/cburgmer","followers_url":"https://api.github.com/users/cburgmer/followers","following_url":"https://api.github.com/users/cburgmer/following{/other_user}","gists_url":"https://api.github.com/users/cburgmer/gists{/gist_id}","starred_url":"https://api.github.com/users/cburgmer/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/cburgmer/subscriptions","organizations_url":"https://api.github.com/users/cburgmer/orgs","repos_url":"https://api.github.com/users/cburgmer/repos","events_url":"https://api.github.com/users/cburgmer/events{/privacy}","received_events_url":"https://api.github.com/users/cburgmer/received_events","type":"User","site_admin":false},"labels":[{"id":22570664,"url":"https://api.github.com/repos/padrino/padrino-framework/labels/enhancement","name":"enhancement","color":"e102d8","default":true}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2017-01-20T05:51:35Z","updated_at":"2017-03-21T06:45:18Z","closed_at":"2017-03-21T06:44:48Z","author_association":"NONE","body":"We want to modify the padrino logging output. The only viable way we found was to replace the default logger with our own instance:\r\n\r\n```\r\nlogger = Logger.new('log/production.log')\r\nlogger.formatter = proc do |s, d, p, m|\r\n   ...\r\nend\r\nPadrino.logger = logger\r\n```\r\n\r\nHowever, we are logging objects, not just strings. Just that they never arrive intact when the formatter is called. They just magically get turned into strings again. Turns out this line is responsible for that: https://github.com/padrino/padrino-framework/blob/master/padrino-core/lib/padrino-core/logger.rb#L78.\r\n\r\nWhy are we even triggering this code, if we have replaced the default logger? Turns out this line is doing this: https://github.com/padrino/padrino-framework/blob/master/padrino-core/lib/padrino-core/logger.rb#L316.\r\n\r\nOur current work around:\r\n\r\n```\r\n# Monkey patch the Logger to ignore the monkey patching on padrino's side\r\nclass Logger\r\n  def extend(*args)\r\n  end\r\n  def devel(*args)\r\n  end\r\n  def exception(boom, *args)\r\n    error(boom.message)\r\n  end\r\nend\r\n```\r\n\r\nLong story short: Please allow us to side-step this behaviour of Padrino, or at least allow us to log our arbitrary logging format. Human readable format is not cutting it for us, we want machines to understand.","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2117","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2117/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2117/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2117/events","html_url":"https://github.com/padrino/padrino-framework/issues/2117","id":201735767,"number":2117,"title":"WARNING! In Padrino >= 0.14.0 cli command `padrino rake` will NOT add './lib' folder to $LOAD_PATH. Please alter your `require` calls accordingly","user":{"login":"bigtunacan","id":1995168,"avatar_url":"https://avatars2.githubusercontent.com/u/1995168?v=4","gravatar_id":"","url":"https://api.github.com/users/bigtunacan","html_url":"https://github.com/bigtunacan","followers_url":"https://api.github.com/users/bigtunacan/followers","following_url":"https://api.github.com/users/bigtunacan/following{/other_user}","gists_url":"https://api.github.com/users/bigtunacan/gists{/gist_id}","starred_url":"https://api.github.com/users/bigtunacan/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/bigtunacan/subscriptions","organizations_url":"https://api.github.com/users/bigtunacan/orgs","repos_url":"https://api.github.com/users/bigtunacan/repos","events_url":"https://api.github.com/users/bigtunacan/events{/privacy}","received_events_url":"https://api.github.com/users/bigtunacan/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2017-01-19T00:55:33Z","updated_at":"2017-07-13T21:07:26Z","closed_at":"2017-01-19T06:01:27Z","author_association":"NONE","body":"In the latest version of Padrino I am receiving this WARNING\r\n\r\n`WARNING! In Padrino >= 0.14.0 cli command `padrino rake` will NOT add\r\n'./lib' folder to $LOAD_PATH. Please alter your `require` calls accordingly`\r\n\r\nIs there a way I can easily add this back in?  Was this change security related?","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2115","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2115/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2115/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2115/events","html_url":"https://github.com/padrino/padrino-framework/issues/2115","id":199837506,"number":2115,"title":"support `hamlit` as alternative HAML implementation?","user":{"login":"fnordfish","id":12839,"avatar_url":"https://avatars0.githubusercontent.com/u/12839?v=4","gravatar_id":"","url":"https://api.github.com/users/fnordfish","html_url":"https://github.com/fnordfish","followers_url":"https://api.github.com/users/fnordfish/followers","following_url":"https://api.github.com/users/fnordfish/following{/other_user}","gists_url":"https://api.github.com/users/fnordfish/gists{/gist_id}","starred_url":"https://api.github.com/users/fnordfish/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/fnordfish/subscriptions","organizations_url":"https://api.github.com/users/fnordfish/orgs","repos_url":"https://api.github.com/users/fnordfish/repos","events_url":"https://api.github.com/users/fnordfish/events{/privacy}","received_events_url":"https://api.github.com/users/fnordfish/received_events","type":"User","site_admin":false},"labels":[{"id":23892472,"url":"https://api.github.com/repos/padrino/padrino-framework/labels/feature","name":"feature","color":"d7e102","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":5,"created_at":"2017-01-10T14:36:32Z","updated_at":"2017-05-10T08:09:06Z","closed_at":"2017-05-10T08:09:06Z","author_association":"CONTRIBUTOR","body":"I was trying to replace \"haml\" with [hamlit](https://github.com/k0kubun/hamlit) in one of my padrino projects.\r\n\r\nHamlit is supposed to be a [limited](https://github.com/k0kubun/hamlit/blob/master/REFERENCE.md#limitations) drop in replacement. But somehow it does not work due to padrino's own management of template renders(?).\r\n\r\nMy fail-fast try looked like this:\r\n\r\n```ruby\r\nmodule Padrino::Helpers::OutputHelpers\r\n  class HamlHandler\r\n    def engine_matches?(block)\r\n      eval('!!defined?(_hamlit_compiler1)', block.binding)\r\n    end\r\n\r\n    def capture_from_template(*args, &block)\r\n      super.html_safe\r\n    end\r\nend\r\n```\r\n\r\n... which almost worked aside from tag helpers:\r\n\r\n\r\n```html\r\n&lt;div class=&#39;form-group&#39;&gt;\r\n&lt;label class=&#39;col-lg-2 control-label&#39; for=&#39;email&#39;&gt;Email&lt;/label&gt;\r\n&lt;div class=&#39;col-lg-10&#39;&gt;<input type=\"email\" name=\"email\" id=\"email\" autofocus=\"autofocus\" class=\"form-control\" />&lt;/div&gt;\r\n&lt;/div&gt;\r\n```\r\n\r\nAny ideas? (I also accept \"Do not use hamlit - it won't work with the admin\" is an answer :))","score":1.0},{"url":"https://api.github.com/repos/padrino/padrino-framework/issues/2113","repository_url":"https://api.github.com/repos/padrino/padrino-framework","labels_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2113/labels{/name}","comments_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2113/comments","events_url":"https://api.github.com/repos/padrino/padrino-framework/issues/2113/events","html_url":"https://github.com/padrino/padrino-framework/issues/2113","id":198793169,"number":2113,"title":"Padrino::Routing absolut_url ignored the default values on url map","user":{"login":"fidalgo","id":22743,"avatar_url":"https://avatars1.githubusercontent.com/u/22743?v=4","gravatar_id":"","url":"https://api.github.com/users/fidalgo","html_url":"https://github.com/fidalgo","followers_url":"https://api.github.com/users/fidalgo/followers","following_url":"https://api.github.com/users/fidalgo/following{/other_user}","gists_url":"https://api.github.com/users/fidalgo/gists{/gist_id}","starred_url":"https://api.github.com/users/fidalgo/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/fidalgo/subscriptions","organizations_url":"https://api.github.com/users/fidalgo/orgs","repos_url":"https://api.github.com/users/fidalgo/repos","events_url":"https://api.github.com/users/fidalgo/events{/privacy}","received_events_url":"https://api.github.com/users/fidalgo/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2017-01-04T19:42:34Z","updated_at":"2017-01-04T23:57:29Z","closed_at":"2017-01-04T23:57:29Z","author_association":"CONTRIBUTOR","body":"#### Do you want to request a *feature* or report a *bug*?\r\nbug\r\n\r\n#### What is the current behavior?\r\nApp.absolute_url() doesn't apply subsitution on the provided values in arguments and only uses the default values.\r\nYou can find an example in https://github.com/fidalgo/padrino-absolute-url\r\n[This line](https://github.com/fidalgo/padrino-absolute-url/blob/master/config.ru#L11) should print:\r\n`Path is http://localhost/face/a2a/CA123/agent/008/answered`\r\n\r\nAlso if you add the line:\r\n`assert_equal \"/pt\", @app.url(:index, lang: 'pt')` \r\n to https://github.com/padrino/padrino-framework/blob/master/padrino-core/test/test_routing.rb#L1245\r\n\r\nI would expect the test to pass\r\n#### What is the expected behavior?\r\nSee previous description\r\n#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?\r\nruby '2.3.3'\r\n'padrino', '0.13.3.3'\r\nsinatra (1.4.7)\r\nFedora Linux  25\r\n\r\nand I suspect it was working on padrino 0.10.6 (yeah a long long time ago)","score":1.0}]}
0

