HTTP/1.1 200 OK
Transfer-Encoding: chunked
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Cache-Control: no-cache
Content-Security-Policy: default-src 'none'
Content-Type: application/json; charset=utf-8
Date: Sun, 13 May 2018 13:01:08 GMT
Link: <https://api.github.com/search/issues?q=repo%3Apallets%2Fflask+type%3Aissue+state%3Aclosed&page=2>; rel="next", <https://api.github.com/search/issues?q=repo%3Apallets%2Fflask+type%3Aissue+state%3Aclosed&page=34>; rel="last"
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Server: GitHub.com
Status: 200 OK
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Accepted-Oauth-Scopes: 
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Github-Media-Type: github.v3; format=json
X-Github-Request-Id: CDDB:4F42:44DE7E6:8AC0759:5AF83714
X-Oauth-Scopes: 
X-Ratelimit-Limit: 30
X-Ratelimit-Remaining: 16
X-Ratelimit-Reset: 1526216518
X-Runtime-Rack: 0.466952
X-Xss-Protection: 1; mode=block

8000
{"total_count":1443,"incomplete_results":false,"items":[{"url":"https://api.github.com/repos/pallets/flask/issues/2772","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2772/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2772/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2772/events","html_url":"https://github.com/pallets/flask/issues/2772","id":322419794,"number":2772,"title":"\"flask init-db\" isn't working","user":{"login":"naveenmalla046","id":30531283,"avatar_url":"https://avatars3.githubusercontent.com/u/30531283?v=4","gravatar_id":"","url":"https://api.github.com/users/naveenmalla046","html_url":"https://github.com/naveenmalla046","followers_url":"https://api.github.com/users/naveenmalla046/followers","following_url":"https://api.github.com/users/naveenmalla046/following{/other_user}","gists_url":"https://api.github.com/users/naveenmalla046/gists{/gist_id}","starred_url":"https://api.github.com/users/naveenmalla046/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/naveenmalla046/subscriptions","organizations_url":"https://api.github.com/users/naveenmalla046/orgs","repos_url":"https://api.github.com/users/naveenmalla046/repos","events_url":"https://api.github.com/users/naveenmalla046/events{/privacy}","received_events_url":"https://api.github.com/users/naveenmalla046/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-05-11T20:10:59Z","updated_at":"2018-05-12T17:04:50Z","closed_at":"2018-05-12T15:20:31Z","author_association":"NONE","body":"This code must be placed in the __init__.py as per the documentation: http://flask.pocoo.org/docs/1.0/tutorial/database/    (Section: Register with the Application)\r\n\r\n    flaskr/__init__.py\r\n    def create_app():\r\n      app = ...\r\n      # existing code omitted\r\n\r\n    from . import db\r\n    db.init_app(app)\r\n\r\n    return app\r\n\r\n----------------------------------------------\r\n\r\nThis is the __init__.py code after copying that code\r\n\r\n    import os\r\n\r\n    from flask import Flask\r\n\r\n    def create_app(test_config=None):\r\n    # create and configure the app\r\n    app = Flask(__name__, instance_relative_config=True)\r\n    app.config.from_mapping(\r\n        SECRET_KEY='dev',\r\n        DATABASE=os.path.join(app.instance_path, 'flaskr.sqlite'),\r\n    )\r\n\r\n    if test_config is None:\r\n        # load the instance config, if it exists, when not testing\r\n        app.config.from_pyfile('config.py', silent=True)\r\n    else:\r\n        # load the test config if passed in\r\n        app.config.from_mapping(test_config)\r\n\r\n    # ensure the instance folder exists\r\n    try:\r\n        os.makedirs(app.instance_path)\r\n    except OSError:\r\n        pass\r\n\r\n    # a simple page that says hello\r\n    @app.route('/hello')\r\n    def hello():\r\n        return 'Hello, World!'\r\n   \r\n    #database \r\n    from . import db\r\n    db.init_app(app)\r\n\r\n    return app\r\n\r\n\r\nExpected output:\r\n\r\nRun the init-db command:\r\n\r\nflask init-db\r\nInitialized the database.\r\nThere will now be a flaskr.sqlite file in the instance folder in your project.\r\n\r\nI'm getting an error while executing the above command:\r\nflask init-db\r\nUsage: flask [OPTIONS] COMMAND [ARGS]...\r\n\r\nError: No such command \"init-db\".\r\n\r\nI even tried copying the exact code from the repo https://github.com/pallets/flask/blob/746b91dfced525651c9b71a3bd075a78d2b9262f/examples/tutorial/flaskr/__init__.py\r\nit is not working even though, same error.\r\n\r\nPls help me with this I'm new to flask and i'm stuck here. cannot proceed further in the documentation unless this code executes\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2768","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2768/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2768/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2768/events","html_url":"https://github.com/pallets/flask/issues/2768","id":321479644,"number":2768,"title":"Traceback shown when running `flask` without any args or an app","user":{"login":"ThiefMaster","id":179599,"avatar_url":"https://avatars1.githubusercontent.com/u/179599?v=4","gravatar_id":"","url":"https://api.github.com/users/ThiefMaster","html_url":"https://github.com/ThiefMaster","followers_url":"https://api.github.com/users/ThiefMaster/followers","following_url":"https://api.github.com/users/ThiefMaster/following{/other_user}","gists_url":"https://api.github.com/users/ThiefMaster/gists{/gist_id}","starred_url":"https://api.github.com/users/ThiefMaster/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ThiefMaster/subscriptions","organizations_url":"https://api.github.com/users/ThiefMaster/orgs","repos_url":"https://api.github.com/users/ThiefMaster/repos","events_url":"https://api.github.com/users/ThiefMaster/events{/privacy}","received_events_url":"https://api.github.com/users/ThiefMaster/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-05-09T08:35:46Z","updated_at":"2018-05-09T13:29:04Z","closed_at":"2018-05-09T13:29:04Z","author_association":"OWNER","body":"### Expected Behavior\r\n\r\nOnly the error message / usage information being printed\r\n\r\n### Actual Behavior\r\n\r\nA traceback shows up above the usage information.\r\n\r\n### Environment\r\n\r\n* Python version: 2.7.14\r\n* Flask version: 1.0.2\r\n* Werkzeug version: 0.14.1\r\n\r\n\r\n---\r\n\r\n\r\n```\r\n[adrian@blackhole:/tmp]> virtualenv testenv\r\nNew python executable in /tmp/testenv/bin/python2.7\r\nAlso creating executable in /tmp/testenv/bin/python\r\nInstalling setuptools, pip, wheel...done.\r\n\r\n[adrian@blackhole:/tmp]> ./testenv/bin/pip install flask\r\nCollecting flask\r\n  Using cached https://files.pythonhosted.org/packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl\r\nCollecting Werkzeug>=0.14 (from flask)\r\n  Using cached https://files.pythonhosted.org/packages/20/c4/12e3e56473e52375aa29c4764e70d1b8f3efa6682bef8d0aae04fe335243/Werkzeug-0.14.1-py2.py3-none-any.whl\r\nCollecting click>=5.1 (from flask)\r\n  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl\r\nCollecting itsdangerous>=0.24 (from flask)\r\nCollecting Jinja2>=2.10 (from flask)\r\n  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl\r\nCollecting MarkupSafe>=0.23 (from Jinja2>=2.10->flask)\r\nInstalling collected packages: Werkzeug, click, itsdangerous, MarkupSafe, Jinja2, flask\r\nSuccessfully installed Jinja2-2.10 MarkupSafe-1.0 Werkzeug-0.14.1 click-6.7 flask-1.0.2 itsdangerous-0.24\r\n\r\n\r\n[adrian@blackhole:/tmp]> ./testenv/bin/flask\r\nTraceback (most recent call last):\r\n  File \"/tmp/testenv/lib/python2.7/site-packages/flask/cli.py\", line 529, in list_commands\r\n    rv.update(info.load_app().cli.list_commands(ctx))\r\n  File \"/tmp/testenv/lib/python2.7/site-packages/flask/cli.py\", line 384, in load_app\r\n    'Could not locate a Flask application. You did not provide '\r\nNoAppException: Could not locate a Flask application. You did not provide the \"FLASK_APP\" environment variable, and a \"wsgi.py\" or \"app.py\" module was not found in the current directory.\r\nUsage: flask [OPTIONS] COMMAND [ARGS]...\r\n\r\n  A general utility script for Flask applications.\r\n\r\n  Provides commands from Flask, extensions, and the application. Loads the\r\n  application defined in the FLASK_APP environment variable, or from a\r\n  wsgi.py file. Setting the FLASK_ENV environment variable to 'development'\r\n  will enable debug mode.\r\n\r\n    $ export FLASK_APP=hello.py\r\n    $ export FLASK_ENV=development\r\n    $ flask run\r\n\r\nOptions:\r\n  --version  Show the flask version\r\n  --help     Show this message and exit.\r\n\r\nCommands:\r\n  routes  Show the routes for the app.\r\n  run     Runs a development server.\r\n  shell   Runs a shell in the app context.\r\n```","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2767","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2767/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2767/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2767/events","html_url":"https://github.com/pallets/flask/issues/2767","id":321399556,"number":2767,"title":"[Regression] Test client's response.status_code is always 500 when an exception is raised","user":{"login":"Depau","id":1151321,"avatar_url":"https://avatars2.githubusercontent.com/u/1151321?v=4","gravatar_id":"","url":"https://api.github.com/users/Depau","html_url":"https://github.com/Depau","followers_url":"https://api.github.com/users/Depau/followers","following_url":"https://api.github.com/users/Depau/following{/other_user}","gists_url":"https://api.github.com/users/Depau/gists{/gist_id}","starred_url":"https://api.github.com/users/Depau/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Depau/subscriptions","organizations_url":"https://api.github.com/users/Depau/orgs","repos_url":"https://api.github.com/users/Depau/repos","events_url":"https://api.github.com/users/Depau/events{/privacy}","received_events_url":"https://api.github.com/users/Depau/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-05-09T01:27:44Z","updated_at":"2018-05-09T13:27:03Z","closed_at":"2018-05-09T13:27:03Z","author_association":"NONE","body":"### Expected Behavior\r\nWhat used to happen before, i.e. on\r\n\r\n```python\r\nraise NotFound()\r\n```\r\n\r\nthe test client's response.status_code should be `404`.\r\n\r\n### Actual Behavior\r\n\r\nIt's always `500`.\r\n\r\n### Environment\r\n\r\nSee my failing Travis CI builds:\r\n- https://travis-ci.org/poliedro-polimi/Crowdfunding-Backend\r\n- One of the tests that fails because of this issue: [link](https://github.com/poliedro-polimi/Crowdfunding-Backend/blob/master/tests/test_views.py#L157)\r\n- Code that makes it fail: [link](https://github.com/poliedro-polimi/Crowdfunding-Backend/blob/master/poliedro_donate/blueprints/donations.py#L60)\r\n\r\n* Python version: >3.5, pypy3 (not tested on other versions)\r\n* Flask version: 1.0.2 from pypi (worked as expected in 0.12.2)\r\n* Werkzeug version: 0.14.1\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2763","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2763/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2763/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2763/events","html_url":"https://github.com/pallets/flask/issues/2763","id":321124448,"number":2763,"title":"Request files are left in memory","user":{"login":"AggressivelyMeows","id":25571984,"avatar_url":"https://avatars0.githubusercontent.com/u/25571984?v=4","gravatar_id":"","url":"https://api.github.com/users/AggressivelyMeows","html_url":"https://github.com/AggressivelyMeows","followers_url":"https://api.github.com/users/AggressivelyMeows/followers","following_url":"https://api.github.com/users/AggressivelyMeows/following{/other_user}","gists_url":"https://api.github.com/users/AggressivelyMeows/gists{/gist_id}","starred_url":"https://api.github.com/users/AggressivelyMeows/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AggressivelyMeows/subscriptions","organizations_url":"https://api.github.com/users/AggressivelyMeows/orgs","repos_url":"https://api.github.com/users/AggressivelyMeows/repos","events_url":"https://api.github.com/users/AggressivelyMeows/events{/privacy}","received_events_url":"https://api.github.com/users/AggressivelyMeows/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":6,"created_at":"2018-05-08T10:12:46Z","updated_at":"2018-05-08T14:28:00Z","closed_at":"2018-05-08T14:28:00Z","author_association":"NONE","body":"### Expected Behaviour\r\nWhen the request is over, the incoming files and JSON should be removed from memory\r\n\r\n### Actual Behavior\r\nThe files and other request data is left in memory with no apparent way to close the objects. i have tried using the python garbage collector but that fails to find the files and other related data.\r\n\r\nThe memory is silently used up until flask is killed by the host\r\n\r\n### Environment\r\n\r\n* Python version: 3.6\r\n* Flask version: 1.0.2\r\n* Werkzeug version: 2.10\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2762","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2762/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2762/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2762/events","html_url":"https://github.com/pallets/flask/issues/2762","id":320660854,"number":2762,"title":"url_for() breaks just before POSTing to a specific endpoint","user":{"login":"Kangaroux","id":2302541,"avatar_url":"https://avatars1.githubusercontent.com/u/2302541?v=4","gravatar_id":"","url":"https://api.github.com/users/Kangaroux","html_url":"https://github.com/Kangaroux","followers_url":"https://api.github.com/users/Kangaroux/followers","following_url":"https://api.github.com/users/Kangaroux/following{/other_user}","gists_url":"https://api.github.com/users/Kangaroux/gists{/gist_id}","starred_url":"https://api.github.com/users/Kangaroux/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Kangaroux/subscriptions","organizations_url":"https://api.github.com/users/Kangaroux/orgs","repos_url":"https://api.github.com/users/Kangaroux/repos","events_url":"https://api.github.com/users/Kangaroux/events{/privacy}","received_events_url":"https://api.github.com/users/Kangaroux/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-05-07T03:12:02Z","updated_at":"2018-05-07T04:20:04Z","closed_at":"2018-05-07T03:27:59Z","author_association":"NONE","body":"### The Problem\r\n\r\nI have a few routes which are as follows:\r\n\r\n```\r\napi.auth -> /api/auth\r\napi.user -> /api/user\r\n         -> /api/user/<user_id>\r\n```\r\n\r\nAnytime I do a POST to `api.auth`, the variable rules for my routes break when I call `url_for`.\r\n\r\n```python\r\n# Prints `/api/user/1`\r\nprint(url_for(\"api.user\", user_id=1))\r\n\r\n# Login\r\nclient.post(url_for(\"api.auth\"), json={\r\n  \"email\": \"test@test.com\",\r\n  \"password\": \"password123\"\r\n})\r\n\r\n# Prints `/api/user?user_id=1`\r\nprint(url_for(\"api.user\", user_id=1))\r\n\r\n# Logout\r\nclient.delete(url_for(\"api.auth\"))\r\n\r\n# Prints `/api/user/1`\r\nprint(url_for(\"api.user\", user_id=1))\r\n```\r\n\r\nThe URL lookups breaking are not a result of something in the `api.auth` views. If I call `url_for` in `post()` or `dispatch_request()` of my AuthAPI view class, it's already broken.\r\n\r\nCalling `client.post(url_for(\"api.auth\"), json={...})` multiple times does not undo the problem.\r\n\r\n### Relevant Code\r\n\r\n- The test that is failing: https://github.com/Kangaroux/Kanban/blob/master/tests/user/test_user.py#L75\r\n- The test app and client: https://github.com/Kangaroux/Kanban/blob/master/tests/conftest.py#L39\r\n- The full app factory: https://github.com/Kangaroux/Kanban/blob/master/config/app.py#L9\r\n\r\n### Environment\r\n\r\n* Python version: 3.6.5\r\n* Flask version: 1.0.2\r\n* Werkzeug version: 0.14.1\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2761","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2761/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2761/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2761/events","html_url":"https://github.com/pallets/flask/issues/2761","id":320589556,"number":2761,"title":"Proper Using Blueprint (prefixed with lang_code) URLs in Html","user":{"login":"ufo911","id":17232189,"avatar_url":"https://avatars1.githubusercontent.com/u/17232189?v=4","gravatar_id":"","url":"https://api.github.com/users/ufo911","html_url":"https://github.com/ufo911","followers_url":"https://api.github.com/users/ufo911/followers","following_url":"https://api.github.com/users/ufo911/following{/other_user}","gists_url":"https://api.github.com/users/ufo911/gists{/gist_id}","starred_url":"https://api.github.com/users/ufo911/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ufo911/subscriptions","organizations_url":"https://api.github.com/users/ufo911/orgs","repos_url":"https://api.github.com/users/ufo911/repos","events_url":"https://api.github.com/users/ufo911/events{/privacy}","received_events_url":"https://api.github.com/users/ufo911/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":true,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-05-06T12:41:56Z","updated_at":"2018-05-06T15:13:53Z","closed_at":"2018-05-06T13:43:59Z","author_association":"NONE","body":"Hello,\r\nthis may not be issue but please help me..\r\n\r\nI have solved the task getting lang code in URL some weeks ago and may anyone confirm it is relevant and good for any project ? \r\nhttps://stackoverflow.com/questions/49496761/two-language-flask-site-with-or-without-blueprints\r\n\r\nI have a problem using URLs in HTML\r\n\r\nHow is it relevant to use Blueprint URLs  in HTML ? \r\nfor example:\r\n\r\n    <a href=\"/{{sess_lang}}/home/hale/\">Home</a>\r\n\r\nI have to insert lang_code before Blueprint URL to go to the right page\r\nor \r\n    `<a href=\"home/hale/\">Home</a>`\r\n\r\nI have to use URL without  first slash ?!\r\n\r\n\r\nIn general this Blueprint must be main blueprint but I have to develop bigger App than any simple site and need help for such configuration about URLs ..\r\n\r\nIn addition I will be getting translations from Mongodb collection and need to switch language on any page without redirecting to any other page...\r\n\r\n**In addition can I change language without JS only with get request ? need example..**","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2760","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2760/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2760/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2760/events","html_url":"https://github.com/pallets/flask/issues/2760","id":320569690,"number":2760,"title":"send_file bug","user":{"login":"faststare08","id":20119233,"avatar_url":"https://avatars2.githubusercontent.com/u/20119233?v=4","gravatar_id":"","url":"https://api.github.com/users/faststare08","html_url":"https://github.com/faststare08","followers_url":"https://api.github.com/users/faststare08/followers","following_url":"https://api.github.com/users/faststare08/following{/other_user}","gists_url":"https://api.github.com/users/faststare08/gists{/gist_id}","starred_url":"https://api.github.com/users/faststare08/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/faststare08/subscriptions","organizations_url":"https://api.github.com/users/faststare08/orgs","repos_url":"https://api.github.com/users/faststare08/repos","events_url":"https://api.github.com/users/faststare08/events{/privacy}","received_events_url":"https://api.github.com/users/faststare08/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-05-06T07:25:08Z","updated_at":"2018-05-07T05:13:35Z","closed_at":"2018-05-06T15:31:49Z","author_association":"NONE","body":"**This issue tracker is a tool to address bugs in Flask itself.\r\nPlease use the #pocoo IRC channel on freenode or Stack Overflow for general\r\nquestions about using Flask or issues not related to Flask.**\r\n\r\nIf you'd like to report a bug in Flask, fill out the template below. Provide\r\nany any extra information that may be useful / related to your problem.\r\nIdeally, create an [MCVE](http://stackoverflow.com/help/mcve), which helps us\r\nunderstand the problem and helps check that it is not caused by something in\r\nyour code.\r\n\r\n---\r\n\r\n### Expected Behavior\r\nI expect \\n escape character every line of my specialized csv file but\r\nTell us what should happen.\r\nit never include the \\n escape character for every line of my csv when I send it to the user\r\n```python\r\nPaste a minimal example that causes the problem.\r\n```\r\nexample \r\nfoo bar\r\nspam and egg\r\n### Actual Behavior\r\nfoo barspam and egg\r\nTell us what happens instead.\r\n\r\n```pytb\r\nPaste the full traceback if there was an exception.\r\n```\r\nno trackback\r\n### Environment\r\n\r\n* Python version: pythonanywhere 3.6\r\n* Flask version: 0.12\r\n* Werkzeug version: 0.11.15\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2758","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2758/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2758/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2758/events","html_url":"https://github.com/pallets/flask/issues/2758","id":320496998,"number":2758,"title":"run \"flask init-db\" first before executing \"flask run\"","user":{"login":"MrMalleable","id":24931250,"avatar_url":"https://avatars2.githubusercontent.com/u/24931250?v=4","gravatar_id":"","url":"https://api.github.com/users/MrMalleable","html_url":"https://github.com/MrMalleable","followers_url":"https://api.github.com/users/MrMalleable/followers","following_url":"https://api.github.com/users/MrMalleable/following{/other_user}","gists_url":"https://api.github.com/users/MrMalleable/gists{/gist_id}","starred_url":"https://api.github.com/users/MrMalleable/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/MrMalleable/subscriptions","organizations_url":"https://api.github.com/users/MrMalleable/orgs","repos_url":"https://api.github.com/users/MrMalleable/repos","events_url":"https://api.github.com/users/MrMalleable/events{/privacy}","received_events_url":"https://api.github.com/users/MrMalleable/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-05-05T10:06:15Z","updated_at":"2018-05-05T11:46:38Z","closed_at":"2018-05-05T11:46:38Z","author_association":"NONE","body":"When i download this project on my computer , I followed the README.rst and executed these instructions ,but i found that there was something wrong , the database wasn't initialized.\r\n\r\nSo, before you run \"flask run\", be sure to run \"flask init-db\" first.","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2757","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2757/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2757/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2757/events","html_url":"https://github.com/pallets/flask/issues/2757","id":320190037,"number":2757,"title":"functions added by after_request execute in reversed order","user":{"login":"joshuaavalon","id":7152420,"avatar_url":"https://avatars0.githubusercontent.com/u/7152420?v=4","gravatar_id":"","url":"https://api.github.com/users/joshuaavalon","html_url":"https://github.com/joshuaavalon","followers_url":"https://api.github.com/users/joshuaavalon/followers","following_url":"https://api.github.com/users/joshuaavalon/following{/other_user}","gists_url":"https://api.github.com/users/joshuaavalon/gists{/gist_id}","starred_url":"https://api.github.com/users/joshuaavalon/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/joshuaavalon/subscriptions","organizations_url":"https://api.github.com/users/joshuaavalon/orgs","repos_url":"https://api.github.com/users/joshuaavalon/repos","events_url":"https://api.github.com/users/joshuaavalon/events{/privacy}","received_events_url":"https://api.github.com/users/joshuaavalon/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-05-04T08:24:38Z","updated_at":"2018-05-04T12:50:29Z","closed_at":"2018-05-04T12:15:22Z","author_association":"NONE","body":"### Expected Behavior\r\nPrint in following order:\r\n\r\nfoo\r\nbar\r\n\r\n```python\r\ndef foo(response):\r\n    print(\"foo\")\r\n    return response\r\ndef bar(response):\r\n    print(\"bar\")\r\n    return response\r\n\r\napp = Flask(__name__)\r\napp.after_request(foo)\r\napp.after_request(bar)\r\n```\r\n\r\n### Actual Behavior\r\nPrint in following order:\r\n\r\nbar\r\nfoo\r\n\r\n### Environment\r\n\r\n* Python version: 3.6.5\r\n* Flask version: 1.0.2\r\n* Werkzeug version: 0.14.1\r\n\r\nThis is very counter intuitive. Is there a reason to execute reversed order? It seems like it is reversed on purpose in `process_response` in `app.py`. The order actually matters. I found out this when I apply gzip and html minifier which gzip is apply first and the minifier is unable to read the data as string.\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2755","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2755/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2755/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2755/events","html_url":"https://github.com/pallets/flask/issues/2755","id":319882029,"number":2755,"title":"templates_auto_reload not taken into account","user":{"login":"romuald","id":113200,"avatar_url":"https://avatars0.githubusercontent.com/u/113200?v=4","gravatar_id":"","url":"https://api.github.com/users/romuald","html_url":"https://github.com/romuald","followers_url":"https://api.github.com/users/romuald/followers","following_url":"https://api.github.com/users/romuald/following{/other_user}","gists_url":"https://api.github.com/users/romuald/gists{/gist_id}","starred_url":"https://api.github.com/users/romuald/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/romuald/subscriptions","organizations_url":"https://api.github.com/users/romuald/orgs","repos_url":"https://api.github.com/users/romuald/repos","events_url":"https://api.github.com/users/romuald/events{/privacy}","received_events_url":"https://api.github.com/users/romuald/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":5,"created_at":"2018-05-03T11:28:36Z","updated_at":"2018-05-10T15:12:47Z","closed_at":"2018-05-07T09:39:52Z","author_association":"NONE","body":"### Synopsis\r\n\r\nIf the configuration templates_auto_reload is set up after has set up it's jinja environment (example: after setting up some filters), it is ignored by Flask\r\n\r\n### Expected Behavior\r\n\r\nTemplates should be reloaded when app.config['TEMPLATES_AUTO_RELOAD'] is set to True\r\n\r\n```python\r\n# application.py\r\nfrom flask import Flask, render_template\r\n\r\napp = Flask(__name__)\r\n\r\n@app.route('/')\r\ndef hello(name=None):\r\n    return render_template('hello.html', name=name)\r\n\r\n# Templates are reloaded if configuration is set up before the template filter\r\n# app.config.update({'TEMPLATES_AUTO_RELOAD': True})\r\n\r\n@app.template_filter('dummy')\r\ndef dummy(value):\r\n    return value\r\n\r\n# Setting this up here does not do anything\r\napp.config.update({'TEMPLATES_AUTO_RELOAD': True})\r\n\r\n# Neither does this:\r\napp.templates_auto_reload = True\r\n\r\napp.run()\r\n\r\n#% python application.py\r\n```\r\n\r\n### Actual Behavior\r\n\r\nThe option is ignored because the jinja environment was already created\r\n\r\n### Environment\r\n\r\n* Python version: 3.6.5\r\n* Flask version: 1.0.2\r\n* Werkzeug version: 0.14.1\r\n* debug is set to False in this case","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2751","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2751/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2751/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2751/events","html_url":"https://github.com/pallets/flask/issues/2751","id":319439231,"number":2751,"title":"`flask routes` crashes if there is no route available","user":{"login":"timothyqiu","id":372476,"avatar_url":"https://avatars3.githubusercontent.com/u/372476?v=4","gravatar_id":"","url":"https://api.github.com/users/timothyqiu","html_url":"https://github.com/timothyqiu","followers_url":"https://api.github.com/users/timothyqiu/followers","following_url":"https://api.github.com/users/timothyqiu/following{/other_user}","gists_url":"https://api.github.com/users/timothyqiu/gists{/gist_id}","starred_url":"https://api.github.com/users/timothyqiu/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/timothyqiu/subscriptions","organizations_url":"https://api.github.com/users/timothyqiu/orgs","repos_url":"https://api.github.com/users/timothyqiu/repos","events_url":"https://api.github.com/users/timothyqiu/events{/privacy}","received_events_url":"https://api.github.com/users/timothyqiu/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":{"url":"https://api.github.com/repos/pallets/flask/milestones/6","html_url":"https://github.com/pallets/flask/milestone/6","labels_url":"https://api.github.com/repos/pallets/flask/milestones/6/labels","id":3312307,"number":6,"title":"1.0.2","description":"","creator":{"login":"davidism","id":1242887,"avatar_url":"https://avatars1.githubusercontent.com/u/1242887?v=4","gravatar_id":"","url":"https://api.github.com/users/davidism","html_url":"https://github.com/davidism","followers_url":"https://api.github.com/users/davidism/followers","following_url":"https://api.github.com/users/davidism/following{/other_user}","gists_url":"https://api.github.com/users/davidism/gists{/gist_id}","starred_url":"https://api.github.com/users/davidism/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/davidism/subscriptions","organizations_url":"https://api.github.com/users/davidism/orgs","repos_url":"https://api.github.com/users/davidism/repos","events_url":"https://api.github.com/users/davidism/events{/privacy}","received_events_url":"https://api.github.com/users/davidism/received_events","type":"User","site_admin":false},"open_issues":0,"closed_issues":3,"state":"closed","created_at":"2018-05-01T18:49:18Z","updated_at":"2018-05-02T14:26:43Z","due_on":null,"closed_at":"2018-05-02T14:26:43Z"},"comments":0,"created_at":"2018-05-02T07:31:00Z","updated_at":"2018-05-02T13:16:18Z","closed_at":"2018-05-02T13:16:18Z","author_association":"NONE","body":"Flask has a route for static files by default, and I disabled that by setting `static_folder` to `None`.\r\n\r\n```python\r\nfrom flask import Flask\r\n\r\napp = Flask(__name__, static_folder=None)\r\n```\r\n\r\n### Expected Behavior\r\n\r\nWith the code above, I expect the output of `flask routes` to be like this:\r\n\r\n    Endpoint  Methods  Rule\r\n    --------  -------  -------------------
8000
----\r\n\r\nor some message saying there is no route available.\r\n\r\n### Actual Behavior\r\n\r\nBut it crashed instead:\r\n\r\n```pytb\r\nTraceback (most recent call last):\r\n  File \"/Users/timothy/.virtualenvs/sample/bin/flask\", line 11, in <module>\r\n    sys.exit(main())\r\n  File \"/Users/timothy/.virtualenvs/sample/lib/python3.6/site-packages/flask/cli.py\", line 890, in main\r\n    cli.main(args=args, prog_name=name)\r\n  File \"/Users/timothy/.virtualenvs/sample/lib/python3.6/site-packages/flask/cli.py\", line 557, in main\r\n    return super(FlaskGroup, self).main(*args, **kwargs)\r\n  File \"/Users/timothy/.virtualenvs/sample/lib/python3.6/site-packages/click/core.py\", line 697, in main\r\n    rv = self.invoke(ctx)\r\n  File \"/Users/timothy/.virtualenvs/sample/lib/python3.6/site-packages/click/core.py\", line 1066, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"/Users/timothy/.virtualenvs/sample/lib/python3.6/site-packages/click/core.py\", line 895, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File \"/Users/timothy/.virtualenvs/sample/lib/python3.6/site-packages/click/core.py\", line 535, in invoke\r\n    return callback(*args, **kwargs)\r\n  File \"/Users/timothy/.virtualenvs/sample/lib/python3.6/site-packages/click/decorators.py\", line 17, in new_func\r\n    return f(get_current_context(), *args, **kwargs)\r\n  File \"/Users/timothy/.virtualenvs/sample/lib/python3.6/site-packages/flask/cli.py\", line 412, in decorator\r\n    return __ctx.invoke(f, *args, **kwargs)\r\n  File \"/Users/timothy/.virtualenvs/sample/lib/python3.6/site-packages/click/core.py\", line 535, in invoke\r\n    return callback(*args, **kwargs)\r\n  File \"/Users/timothy/.virtualenvs/sample/lib/python3.6/site-packages/flask/cli.py\", line 841, in routes_command\r\n    max(len(rule.endpoint) for rule in rules),\r\nValueError: max() arg is an empty sequence\r\n```\r\n\r\n### Environment\r\n\r\n* Python version: 3.6.3\r\n* Flask version: 1.0.1\r\n* Werkzeug version: 0.14.1\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2750","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2750/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2750/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2750/events","html_url":"https://github.com/pallets/flask/issues/2750","id":319431956,"number":2750,"title":"Broken links on pypi","user":{"login":"guillaumevincent","id":943762,"avatar_url":"https://avatars1.githubusercontent.com/u/943762?v=4","gravatar_id":"","url":"https://api.github.com/users/guillaumevincent","html_url":"https://github.com/guillaumevincent","followers_url":"https://api.github.com/users/guillaumevincent/followers","following_url":"https://api.github.com/users/guillaumevincent/following{/other_user}","gists_url":"https://api.github.com/users/guillaumevincent/gists{/gist_id}","starred_url":"https://api.github.com/users/guillaumevincent/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/guillaumevincent/subscriptions","organizations_url":"https://api.github.com/users/guillaumevincent/orgs","repos_url":"https://api.github.com/users/guillaumevincent/repos","events_url":"https://api.github.com/users/guillaumevincent/events{/privacy}","received_events_url":"https://api.github.com/users/guillaumevincent/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-05-02T07:01:15Z","updated_at":"2018-05-02T07:02:35Z","closed_at":"2018-05-02T07:02:34Z","author_association":"NONE","body":"Hello,\r\non https://pypi.org/project/Flask/ `issue tracker` and `code` links in the left menu are pointing to `https://github.com/pallets/pallets-sphinx-themes/issues` not `https://github.com/pallets/flask/issues`.\r\n\r\n![screenshot from 2018-05-02 09-00-17](https://user-images.githubusercontent.com/943762/39509638-44544f30-4de7-11e8-8a03-c750c072e151.png)\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2744","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2744/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2744/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2744/events","html_url":"https://github.com/pallets/flask/issues/2744","id":318746797,"number":2744,"title":"Issue loading images when threading is enabled","user":{"login":"natedooley","id":31457788,"avatar_url":"https://avatars2.githubusercontent.com/u/31457788?v=4","gravatar_id":"","url":"https://api.github.com/users/natedooley","html_url":"https://github.com/natedooley","followers_url":"https://api.github.com/users/natedooley/followers","following_url":"https://api.github.com/users/natedooley/following{/other_user}","gists_url":"https://api.github.com/users/natedooley/gists{/gist_id}","starred_url":"https://api.github.com/users/natedooley/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/natedooley/subscriptions","organizations_url":"https://api.github.com/users/natedooley/orgs","repos_url":"https://api.github.com/users/natedooley/repos","events_url":"https://api.github.com/users/natedooley/events{/privacy}","received_events_url":"https://api.github.com/users/natedooley/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-04-29T20:24:14Z","updated_at":"2018-04-30T02:57:53Z","closed_at":"2018-04-30T02:57:53Z","author_association":"NONE","body":"I have a Flask app to display profiles based on LDAP data. After updating to 1.0 I'm having crashes when loading the data. Running the app with ```threaded=False``` works, but I'd like to have threads.\r\n\r\n---\r\n\r\n### Expected Behavior\r\n\r\nThe app would pull an image from the LDAP server and return it to the client. It would be displayed in HTML.\r\n\r\n```python\r\n@app.route(\"/image/<uid>\", methods=[\"GET\"])\r\ndef image(uid):\r\n    return get_image(uid)\r\n```\r\n\r\n```python\r\ndef get_image(uid):\r\n    account = ldap_get_member(uid)\r\n    return account.jpegPhoto\r\n```\r\n\r\n```html\r\n{% for m in members %}\r\n\t<a href=\"/user/{{ m['uid'] }}\" class=\"card-block clearfix\">\r\n\t\t<div class=\"card user-card\">\r\n\t\t\t<div class=\"card-profile-pic card-img-top card-img-top-crop\" style=\"background-image: url('/image/{{m['uid']}}');\" >\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t</a>\r\n{% endfor %}\r\n```\r\n\r\n### Actual Behavior\r\n\r\nThe application crashes some way through loading the images. It usually loads 1 or 2 before exiting like this.\r\n\r\nThis behavior is only observed when attempting to load a large amount of images, such as on a page with a group of users. It does not happen on a single profile which only loads a single image.\r\n\r\n```pytb\r\nflask_pyoidc.flask_pyoidc\r\n * Serving Flask app \"profiles\" (lazy loading)\r\n * Environment: production\r\n   WARNING: Do not use the development server in a production environment.\r\n   Use a production WSGI server instead.\r\n * Debug mode: on\r\n * Running on http://localhost:8080/ (Press CTRL+C to quit)\r\n * Restarting with stat\r\nflask_pyoidc.flask_pyoidc\r\n * Debugger is active!\r\n * Debugger PIN: 252-481-398\r\n/home/nate/.local/lib/python3.6/site-packages/flask/sessions.py:208: UserWarning: \"localhost\" is not a valid cookie domain, it must contain a \".\". Add an entry to your hosts file, for example \"localhost.localdomain\", and use that instead.\r\n  ' \"{rv}.localdomain\", and use that instead.'.format(rv=rv)\r\n127.0.0.1 - - [29/Apr/2018 15:55:42] \"GET /group/active HTTP/1.1\" 302 -\r\n127.0.0.1 - - [29/Apr/2018 15:55:42] \"GET /redirect_uri?state=sb25ldwdXoNE6xlu&session_state=3f2de3ad-d4f8-431e-8d9a-09cfb811322b&code=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..p7LHT5Z6Bzljz08mV4TzeQ.eG0Tnq9LJJ4OZtspH2qBOyYQkPsqp1gKYUATkQ8ANJbSsRmfI7wUgcEEgvNrVWq5ZcchfYeYqpxixCvVv0I53DdRkrS9IfNa4hv0UOFa4i7txNv1kxHBWfDnjULMTsP7exdpVc0fWxvO1S3fIHeuIm0kxaAsPBdt83wEmj147RnMhrHS6MTjAEICsBRehphzmLi1qWDn9aSoMISCTyc7kjqPikLCyMlpcn-7NPGgGVtQ4olCerE3lmNl-UqZFtYH.yZF3w47VEuMs4-hrboYW2w HTTP/1.1\" 302 -\r\nINFO:werkzeug:127.0.0.1 - - [29/Apr/2018 15:55:42] \"GET /redirect_uri?state=sb25ldwdXoNE6xlu&session_state=3f2de3ad-d4f8-431e-8d9a-09cfb811322b&code=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..p7LHT5Z6Bzljz08mV4TzeQ.eG0Tnq9LJJ4OZtspH2qBOyYQkPsqp1gKYUATkQ8ANJbSsRmfI7wUgcEEgvNrVWq5ZcchfYeYqpxixCvVv0I53DdRkrS9IfNa4hv0UOFa4i7txNv1kxHBWfDnjULMTsP7exdpVc0fWxvO1S3fIHeuIm0kxaAsPBdt83wEmj147RnMhrHS6MTjAEICsBRehphzmLi1qWDn9aSoMISCTyc7kjqPikLCyMlpcn-7NPGgGVtQ4olCerE3lmNl-UqZFtYH.yZF3w47VEuMs4-hrboYW2w HTTP/1.1\" 302 -\r\n127.0.0.1 - - [29/Apr/2018 15:55:43] \"GET /group/active HTTP/1.1\" 200 -\r\nINFO:werkzeug:127.0.0.1 - - [29/Apr/2018 15:55:43] \"GET /group/active HTTP/1.1\" 200 -\r\n127.0.0.1 - - [29/Apr/2018 15:55:43] \"GET /image/dooley HTTP/1.1\" 200 -\r\nINFO:werkzeug:127.0.0.1 - - [29/Apr/2018 15:55:43] \"GET /image/dooley HTTP/1.1\" 200 -\r\nFatal Python error: saving thread twice?\r\n\r\nThread 0x00007f0263fff700 (most recent call first):\r\n  File \"/usr/lib/python3.6/hmac.py\", line 93 in update\r\n  File \"/usr/lib/python3.6/hmac.py\", line 84 in __init__\r\n  File \"/usr/lib/python3.6/hmac.py\", line 144 in new\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/itsdangerous.py\", line 268 in get_signature\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/itsdangerous.py\", line 243 in verify_signature\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/itsdangerous.py\", line 362 in verify_signature\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/itsdangerous.py\", line 371 in unsign\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/itsdangerous.py\", line 422 in unsign\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/itsdangerous.py\", line 643 in loads\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/flask/sessions.py\", line 343 in open_session\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/flask/ctx.py\", line 377 in push\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/flask/app.py\", line 2283 in wsgi_app\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/flask/app.py\", line 2301 in __call__\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/werkzeug/debug/__init__.py\", line 288 in debug_application\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/werkzeug/serving.py\", line 260 in execute\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/werkzeug/serving.py\", line 270 in run_wsgi\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/werkzeug/serving.py\", line 328 in handle_one_request\r\n  File \"/usr/lib/python3.6/http/server.py\", line 418 in handle\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/werkzeug/serving.py\", line 293 in handle\r\n  File \"/usr/lib/python3.6/socketserver.py\", line 696 in __init__\r\n  File \"/usr/lib/python3.6/socketserver.py\", line 361 in finish_request\r\n  File \"/usr/lib/python3.6/socketserver.py\", line 639 in process_request_thread\r\n  File \"/usr/lib/python3.6/threading.py\", line 864 in run\r\n  File \"/usr/lib/python3.6/threading.py\", line 916 in _bootstrap_inner\r\n  File \"/usr/lib/python3.6/threading.py\", line 884 in _bootstrap\r\n\r\nThread 0x00007f0278997700 (most recent call first):\r\n  File \"/usr/lib/python3.6/socket.py\", line 586 in readinto\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/werkzeug/serving.py\", line 324 in handle_one_request\r\n  File \"/usr/lib/python3.6/http/server.py\", line 418 in handle\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/werkzeug/serving.py\", line 293 in handle\r\n  File \"/usr/lib/python3.6/socketserver.py\", line 696 in __init__\r\n  File \"/usr/lib/python3.6/socketserver.py\", line 361 in finish_request\r\n  File \"/usr/lib/python3.6/socketserver.py\", line 639 in process_request_thread\r\n  File \"/usr/lib/python3.6/threading.py\", line 864 in run\r\n  File \"/usr/lib/python3.6/threading.py\", line 916 in _bootstrap_inner\r\n  File \"/usr/lib/python3.6/threading.py\", line 884 in _bootstrap\r\n\r\nThread 0x00007f0279198700 (most recent call first):\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/ldap/ldapobject.py\", line 293 in _ldap_call\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/ldap/ldapobject.py\", line 792 in search_ext\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/ldap/ldapobject.py\", line 796 in search_ext_s\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/ldap/ldapobject.py\", line 1148 in _apply_method_s\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/ldap/ldapobject.py\", line 1210 in search_ext_s\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/ldap/ldapobject.py\", line 803 in search_s\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/csh_ldap/member.py\", line 26 in __init__\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/csh_ldap/__init__.py\", line 43 in get_member\r\n  File \"/home/nate/src/profiles/profiles/ldap.py\", line 49 in ldap_get_member\r\n  File \"/home/nate/src/profiles/profiles/ldap.py\", line 312 in get_image\r\n  File \"/home/nate/src/profiles/profiles/__init__.py\", line 133 in image\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/flask/app.py\", line 1791 in dispatch_request\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/flask/app.py\", line 1805 in full_dispatch_request\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/flask/app.py\", line 2284 in wsgi_app\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/flask/app.py\", line 2301 in __call__\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/werkzeug/debug/__init__.py\", line 288 in debug_application\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/werkzeug/serving.py\", line 260 in execute\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/werkzeug/serving.py\", line 270 in run_wsgi\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/werkzeug/serving.py\", line 328 in handle_one_request\r\n  File \"/usr/lib/python3.6/http/server.py\", line 418 in handle\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/werkzeug/serving.py\", line 293 in handle\r\n  File \"/usr/lib/python3.6/socketserver.py\", line 696 in __init__\r\n  File \"/usr/lib/python3.6/socketserver.py\", line 361 in finish_request\r\n  File \"/usr/lib/python3.6/socketserver.py\", line 639 in process_request_thread\r\n  File \"/usr/lib/python3.6/threading.py\", line 864 in run\r\n  File \"/usr/lib/python3.6/threading.py\", line 916 in _bootstrap_inner\r\n  File \"/usr/lib/python3.6/threading.py\", line 884 in _bootstrap\r\n\r\nCurrent thread 0x00007f0279999700 (most recent call first):\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/ldap/ldapobject.py\", line 293 in _ldap_call\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/ldap/ldapobject.py\", line 722 in result4\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/ldap/ldapobject.py\", line 715 in result3\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/ldap/ldapobject.py\", line 708 in result2\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/ldap/ldapobject.py\", line 704 in result\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/ldap/ldapobject.py\", line 797 in search_ext_s\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/ldap/ldapobject.py\", line 1148 in _apply_method_s\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/ldap/ldapobject.py\", line 1210 in search_ext_s\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/ldap/ldapobject.py\", line 803 in search_s\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/csh_ldap/member.py\", line 26 in __init__\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/csh_ldap/__init__.py\", line 43 in get_member\r\n  File \"/home/nate/src/profiles/profiles/ldap.py\", line 49 in ldap_get_member\r\n  File \"/home/nate/src/profiles/profiles/ldap.py\", line 312 in get_image\r\n  File \"/home/nate/src/profiles/profiles/__init__.py\", line 133 in image\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/flask/app.py\", line 1791 in dispatch_request\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/flask/app.py\", line 1805 in full_dispatch_request\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/flask/app.py\", line 2284 in wsgi_app\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/flask/app.py\", line 2301 in __call__\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/werkzeug/debug/__init__.py\", line 288 in debug_application\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/werkzeug/serving.py\", line 260 in execute\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/werkzeug/serving.py\", line 270 in run_wsgi\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/werkzeug/serving.py\", line 328 in handle_one_request\r\n  File \"/usr/lib/python3.6/http/server.py\", line 418 in handle\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/werkzeug/serving.py\", line 293 in handle\r\n  File \"/usr/lib/python3.6/socketserver.py\", line 696 in __init__\r\n  File \"/usr/lib/python3.6/socketserver.py\", line 361 in finish_request\r\n  File \"/usr/lib/python3.6/socketserver.py\", line 639 in process_request_thread\r\n  File \"/usr/lib/python3.6/threading.py\", line 864 in run\r\n  File \"/usr/lib/python3.6/threading.py\", line 916 in _bootstrap_inner\r\n  File \"/usr/lib/python3.6/threading.py\", line 884 in _bootstrap\r\n\r\nThread 0x00007f027a431700 (most recent call first):\r\n  File \"/usr/lib/python3.6/ssl.py\", line 689 in do_handshake\r\n  File \"/usr/lib/python3.6/ssl.py\", line 1068 in do_handshake\r\n  File \"/usr/lib/python3.6/ssl.py\", line 814 in __init__\r\n  File \"/usr/lib/python3.6/ssl.py\", line 407 in wrap_socket\r\n  File \"/usr/lib/python3.6/http/client.py\", line 1400 in connect\r\n  File \"/usr/lib/python3.6/http/client.py\", line 964 in send\r\n  File \"/usr/lib/python3.6/http/client.py\", line 1026 in _send_output\r\n  File \"/usr/lib/python3.6/http/client.py\", line 1234 in endheaders\r\n  File \"/usr/lib/python3.6/http/client.py\", line 1285 in _send_request\r\n  File \"/usr/lib/python3.6/http/client.py\", line 1239 in request\r\n  File \"/usr/lib/python3.6/urllib/request.py\", line 1318 in do_open\r\n  File \"/usr/lib/python3.6/urllib/request.py\", line 1361 in https_open\r\n  File \"/usr/lib/python3.6/urllib/request.py\", line 504 in _call_chain\r\n  File \"/usr/lib/python3.6/urllib/request.py\", line 544 in _open\r\n  File \"/usr/lib/python3.6/urllib/request.py\", line 526 in open\r\n  File \"/usr/lib/python3.6/urllib/request.py\", line 223 in urlopen\r\n  File \"/home/nate/src/profiles/profiles/ldap.py\", line 324 in get_image\r\n  File \"/home/nate/src/profiles/profiles/__init__.py\", line 133 in image\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/flask/app.py\", line 1791 in dispatch_request\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/flask/app.py\", line 1805 in full_dispatch_request\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/flask/app.py\", line 2284 in wsgi_app\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/flask/app.py\", line 2301 in __call__\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/werkzeug/debug/__init__.py\", line 288 in debug_application\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/werkzeug/serving.py\", line 260 in execute\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/werkzeug/serving.py\", line 270 in run_wsgi\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/werkzeug/serving.py\", line 328 in handle_one_request\r\n  File \"/usr/lib/python3.6/http/server.py\", line 418 in handle\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/werkzeug/serving.py\", line 293 in handle\r\n  File \"/usr/lib/python3.6/socketserver.py\", line 696 in __init__\r\n  File \"/usr/lib/python3.6/socketserver.py\", line 361 in finish_request\r\n  File \"/usr/lib/python3.6/socketserver.py\", line 639 in process_request_thread\r\n  File \"/usr/lib/python3.6/threading.py\", line 864 in run\r\n  File \"/usr/lib/python3.6/threading.py\", line 916 in _bootstrap_inner\r\n  File \"/usr/lib/python3.6/threading.py\", line 884 in _bootstrap\r\n\r\nThread 0x00007f027ac32700 (most recent call first):\r\n  File \"/usr/lib/python3.6/threading.py\", line 295 in wait\r\n  File \"/usr/lib/python3.6/threading.py\", line 551 in wait\r\n  File \"/usr/lib/python3.6/threading.py\", line 851 in start\r\n  File \"/usr/lib/python3.6/socketserver.py\", line 650 in process_request\r\n  File \"/usr/lib/python3.6/socketserver.py\", line 317 in _handle_request_noblock\r\n  File \"/usr/lib/python3.6/socketserver.py\", line 238 in serve_forever\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/werkzeug/serving.py\", line 612 in serve_forever\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/werkzeug/serving.py\", line 777 in inner\r\n  File \"/usr/lib/python3.6/threading.py\", line 864 in run\r\n  File \"/usr/lib/python3.6/threading.py\", line 916 in _bootstrap_inner\r\n  File \"/usr/lib/python3.6/threading.py\", line 884 in _bootstrap\r\n\r\nThread 0x00007f028a0fd540 (most recent call first):\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/werkzeug/_reloader.py\", line 164 in run\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/werkzeug/_reloader.py\", line 273 in run_with_reloader\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/werkzeug/serving.py\", line 812 in run_simple\r\n  File \"/home/nate/.local/lib/python3.6/site-packages/flask/app.py\", line 941 in run\r\n  File \"app.py\", line 4 in <module>\r\n\r\n```\r\n\r\n### Environment\r\n\r\n* Python version: 3.6.5\r\n* Flask version: 1.0\r\n* Werkzeug version: 0.14.1\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2743","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2743/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2743/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2743/events","html_url":"https://github.com/pallets/flask/issues/2743","id":318707851,"number":2743,"title":"Documentation search broken","user":{"login":"lepture","id":290496,"avatar_url":"https://avatars2.githubusercontent.com/u/290496?v=4","gravatar_id":"","url":"https://api.github.com/users/lepture","html_url":"https://github.com/lepture","followers_url":"https://api.github.com/users/lepture/followers","following_url":"https://api.github.com/users/lepture/following{/other_user}","gists_url":"https://api.github.com/users/lepture/gists{/gist_id}","starred_url":"https://api.github.com/users/lepture/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/lepture/subscriptions","organizations_url":"https://api.github.com/users/lepture/orgs","repos_url":"https://api.github.com/users/lepture/repos","events_url":"https://api.github.com/users/lepture/events{/privacy}","received_events_url":"https://api.github.com/users/lepture/received_events","type":"User","site_admin":false},"labels":[{"id":135583063,"url":"https://api.github.com/repos/pallets/flask/labels/bug","name":"bug","color":"d93f0b","default":true}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":{"url":"https://api.github.com/repos/pallets/flask/milestones/5","html_url":"https://github.com/pallets/flask/milestone/5","labels_url":"https://api.github.com/repos/pallets/flask/milestones/5/labels","id":3304290,"number":5,"title":"1.0.1","description":"","creator":{"login":"davidism","id":1242887,"avatar_url":"https://avatars1.githubusercontent.com/u/1242887?v=4","gravatar_id":"","url":"https://api.github.com/users/davidism","html_url":"https://github.com/davidism","followers_url":"https://api.github.com/users/davidism/followers","following_url":"https://api.github.com/users/davidism/following{/other_user}","gists_url":"https://api.github.com/users/davidism/gists{/gist_id}","starred_url":"https://api.github.com/users/davidism/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/davidism/subscriptions","organizations_url":"https://api.github.com/users/davidism/orgs","repos_url":"https://api.github.com/users/davidism/repos","events_url":"https://api.github.com/users/davidism/events{/privacy}","received_events_url":"https://api.github.com/users/davidism/received_events","type":"User","site_admin":false},"open_issues":0,"closed_issues":18,"state":"closed","created_at":"2018-04-27T13:46:37Z","updated_at":"2018-04-30T01:11:27Z","due_on":null,"closed_at":"2018-04-30T01:11:27Z"},"comments":2,"created_at":"2018-04-29T10:57:08Z","updated_at":"2018-04-30T00:55:44Z","closed_at":"2018-04-30T00:55:44Z","author_association":"MEMBER","body":"## How to reproduce\r\n\r\n1. Try search \"request\", it goes to this page: `http://flask.pocoo.org/docs/1.0/search/?q=request`\r\n2. Click on the result, it will be 404\r\n\r\n---\r\n\r\nThe urls built on the search page are wrong, for instance:\r\n\r\n```\r\nhttp://flask.pocoo.org/docs/1.0/search/api/?highlight=request#flask.request\r\n```\r\n\r\nShould be\r\n\r\n```\r\nhttp://flask.pocoo.org/docs/1.0/api/?highlight=request#flask.request\r\n```\r\n\r\n@davidism this should be fixed in the pallets themes.","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2742","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2742/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2742/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2742/events","html_url":"https://github.com/pallets/flask/issues/2742","id":318705699,"number":2742,"title":"Flask 1.0 backwards incompatible root url_prefix","user":{"login":"albertyw","id":3151040,"avatar_url":"https://avatars3.githubusercontent.com/u/3151040?v=4","gravatar_id":"","url":"https://api.github.com/users/albertyw","html_url":"https://github.com/albertyw","followers_url":"https://api.github.com/users/albertyw/followers","following_url":"https://api.github.com/users/albertyw/following{/other_user}","gists_url":"https://api.github.com/users/albertyw/gists{/gist_id}","starred_url":"https://api.github.com/users/albertyw/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/albertyw/subscriptions","organizations_url":"https://api.github.com/users/albertyw/orgs","repos_url":"https://api.github.com/users/albertyw/repos","events_url":"https://api.github.com/users/albertyw/events{/privacy}","received_events_url":"https://api.github.com/users/albertyw/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":{"url":"https://api.github.com/repos/pallets/flask/milestones/5","html_url":"https://github.com/pallets/flask/milestone/5","labels_url":"https://api.github.com/repos/pallets/flask/milestones/5/labels","id":3304290,"number":5,"title":"1.0.1","description":"","creator":{"login":"davidism","id":1242887,"avatar_url":"https://avatars1.githubusercontent.com/u/1242887?v=4","gravatar_id":"","url":"https://api.github.com/users/davidism","html_url":"https://github.com/davidism","followers_url":"https://api.github.com/users/davidism/followers","following_url":"https://api.github.com/users/davidism/following{/other_user}","gists_url":"https://api.github.com/users/davidism/gists{/gist_id}","starred_url":"https://api.github.com/users/davidism/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/davidism/subscriptions","organizations_url":"https://api.github.com/users/davidism/orgs","repos_url":"https://api.github.com/users/davidism/repos","events_url":"https://api.github.com/users/davidism/events{/privacy}","received_events_url":"https://api.github.com/users/davidism/received_events","type":"User","site_admin":false},"open_issues":0,"closed_issues":18,"state":"closed","created_at":"2018-04-27T13:46:37Z","updated_at":"2018-04-30T01:11:27Z","due_on":null,"closed_at":"2018-04-30T01:11:27Z"},"comments":1,"created_at":"2018-04-29T10:18:59Z","updated_at":"2018-04-29T22:47:15Z","closed_at":"2018-04-29T22:47:15Z","author_association":"NONE","body":"Some of the recent PRs in blueprint.py seem to make Flask 1.0 not backwards compatible with 0.x versions.  When `url_prefix=''`, `url_prefix='/'`, or `url_prefix` is not specified, a `ValueError('urls must start with a leading slash')` is now raised. \r\n\r\n### Expected Behavior\r\n\r\nI would have assumed, given the discussion in #2629, that `''` and maybe `/` would be acceptable url_prefixes to indicate the blueprint is meant for the root.\r\n\r\nAn example of a broken library is `flask-sitemap` (https://github.com/inveniosoftware/flask-sitemap/blob/master/flask_sitemap/__init__.py#L120) which uses\r\n\r\n```\r\n            app.register_blueprint(\r\n                self.blueprint,\r\n                url_prefix=app.config.get('SITEMAP_BLUEPRINT_URL_PREFIX') # default is '/'\r\n            )\r\n```\r\n\r\n\r\n### Actual Behavior\r\n\r\n In my testing, I continually get \r\n\r\n```  File \"/home/albertyw/.virtualenvs/baseflask/local/lib/python2.7/site-packages/flask_sitemap/__init__.py\", line 79, in __init__\r\n    self.init_app(app)\r\n  File \"/home/albertyw/.virtualenvs/baseflask/local/lib/python2.7/site-packages/flask_sitemap/__init__.py\", line 120, in init_app\r\n    url_prefix='' # app.config.get('SITEMAP_BLUEPRINT_URL_PREFIX')\r\n  File \"/home/albertyw/.virtualenvs/baseflask/local/lib/python2.7/site-packages/flask/app.py\", line 64, in wrapper_func\r\n    return f(self, *args, **kwargs)\r\n  File \"/home/albertyw/.virtualenvs/baseflask/local/lib/python2.7/site-packages/flask/app.py\", line 1113, in register_blueprint\r\n    blueprint.register(self, options, first_registration)\r\n  File \"/home/albertyw/.virtualenvs/baseflask/local/lib/python2.7/site-packages/flask/blueprints.py\", line 186, in register\r\n    deferred(state)\r\n  File \"/home/albertyw/.virtualenvs/baseflask/local/lib/python2.7/site-packages/flask/blueprints.py\", line 207, in <lambda>\r\n    s.add_url_rule(rule, endpoint, view_func, **options))\r\n  File \"/home/albertyw/.virtualenvs/baseflask/local/lib/python2.7/site-packages/flask/blueprints.py\", line 79, in add_url_rule\r\n    view_func, defaults=defaults, **options)\r\n  File \"/home/albertyw/.virtualenvs/baseflask/local/lib/python2.7/site-packages/flask/app.py\", line 64, in wrapper_func\r\n    return f(self, *args, **kwargs)\r\n  File \"/home/albertyw/.virtualenvs/baseflask/local/lib/python2.7/site-packages/flask/app.py\", line 1211, in add_url_rule\r\n    rule = self.url_rule_class(rule, methods=methods, **options)\r\n  File \"/home/albertyw/.virtualenvs/baseflask/local/lib/python2.7/site-packages/werkzeug/routing.py\", line 603, in __init__\r\n    raise ValueError('urls must start with a leading slash')\r\nValueError: urls must start with a leading slash\r\n```\r\n\r\nunless I set `url_prefix='//'`, in which case the url_prefix is the root.\r\n\r\n### Environment\r\n\r\n* Python version: python 2.7 and 3.6\r\n* Flask version: 1.0\r\n* Werkzeug version: 0.14.1\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2736","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2736/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2736/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2736/events","html_url":"https://github.com/pallets/flask/issues/2736","id":318482785,"number":2736,"title":"make_response changes breaks custom response class","user":{"login":"jesseops","id":4613566,"avatar_url":"https://avatars0.githubusercontent.com/u/4613566?v=4","gravatar_id":"","url":"https://api.github.com/users/jesseops","html_url":"https://github.com/jesseops","followers_url":"https://api.github.com/users/jesseops/followers","following_url":"https://api.github.com/users/jesseops/following{/other_user}","gists_url":"https://api.github.com/users/jesseops/gists{/gist_id}","starred_url":"https://api.github.com/users/jesseops/starred{
8000
/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jesseops/subscriptions","organizations_url":"https://api.github.com/users/jesseops/orgs","repos_url":"https://api.github.com/users/jesseops/repos","events_url":"https://api.github.com/users/jesseops/events{/privacy}","received_events_url":"https://api.github.com/users/jesseops/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":{"url":"https://api.github.com/repos/pallets/flask/milestones/5","html_url":"https://github.com/pallets/flask/milestone/5","labels_url":"https://api.github.com/repos/pallets/flask/milestones/5/labels","id":3304290,"number":5,"title":"1.0.1","description":"","creator":{"login":"davidism","id":1242887,"avatar_url":"https://avatars1.githubusercontent.com/u/1242887?v=4","gravatar_id":"","url":"https://api.github.com/users/davidism","html_url":"https://github.com/davidism","followers_url":"https://api.github.com/users/davidism/followers","following_url":"https://api.github.com/users/davidism/following{/other_user}","gists_url":"https://api.github.com/users/davidism/gists{/gist_id}","starred_url":"https://api.github.com/users/davidism/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/davidism/subscriptions","organizations_url":"https://api.github.com/users/davidism/orgs","repos_url":"https://api.github.com/users/davidism/repos","events_url":"https://api.github.com/users/davidism/events{/privacy}","received_events_url":"https://api.github.com/users/davidism/received_events","type":"User","site_admin":false},"open_issues":0,"closed_issues":18,"state":"closed","created_at":"2018-04-27T13:46:37Z","updated_at":"2018-04-30T01:11:27Z","due_on":null,"closed_at":"2018-04-30T01:11:27Z"},"comments":3,"created_at":"2018-04-27T17:05:04Z","updated_at":"2018-04-27T19:47:02Z","closed_at":"2018-04-27T19:47:01Z","author_association":"NONE","body":"### Expected Behavior\r\n\r\nI should be able to return a single value from my view(that is, not a tuple) and have my value passed to my custom response class. In this case I have a response class that detects whether JSON or pickle data was requested by the client and dumps the return value appropriately. This allows me to simply return a list or dict from my view without having to detect and dump the appropriate type.\r\n\r\n```python\r\n@mod.route('/')\r\ndef return_json_or_pickle():\r\n    return ['foo', 'bar', 'bat']\r\n```\r\n\r\nAs of Flask 0.12.2 this worked - make_response would pass the list to my custom response class and my client would get what it wanted.\r\n\r\n### Actual Behavior\r\n\r\nAs of 1.0, commit #2256 was merged which added an explicit check to see if the return value was a list; treating a list as a tuple return in that case. I now get a typeerror:\r\n\r\n```pytb\r\nTypeError: The view function did not return a valid response tuple. The tuple must have the form (body, status, headers), (body, status), or (body, headers).\r\n```\r\n\r\nIf I change my view function to return a tuple:\r\n\r\n```python\r\n@mod.route('/')\r\ndef return_json_or_pickle():\r\n    return ['foo', 'bar', 'bat'], 200\r\n```\r\nthe previous functionality is restored! This confirms that tuple handling is of course perfectly fine. I have a [pull request](https://github.com/pallets/flask/pull/2737) prepared which should do a very nice job of resolving the issue - it simply omits `list` from the type check in make_response. Since a list is not a valid response anyway, there's no reason I can see for it to be there.\r\n\r\n### Environment\r\n\r\n* Python version: 3.6\r\n* Flask version: 1.0\r\n* Werkzeug version: n/a\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2735","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2735/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2735/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2735/events","html_url":"https://github.com/pallets/flask/issues/2735","id":318458449,"number":2735,"title":"flask.abort() behavioral change in debug mode","user":{"login":"pypingou","id":1240038,"avatar_url":"https://avatars1.githubusercontent.com/u/1240038?v=4","gravatar_id":"","url":"https://api.github.com/users/pypingou","html_url":"https://github.com/pypingou","followers_url":"https://api.github.com/users/pypingou/followers","following_url":"https://api.github.com/users/pypingou/following{/other_user}","gists_url":"https://api.github.com/users/pypingou/gists{/gist_id}","starred_url":"https://api.github.com/users/pypingou/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/pypingou/subscriptions","organizations_url":"https://api.github.com/users/pypingou/orgs","repos_url":"https://api.github.com/users/pypingou/repos","events_url":"https://api.github.com/users/pypingou/events{/privacy}","received_events_url":"https://api.github.com/users/pypingou/received_events","type":"User","site_admin":false},"labels":[{"id":135583063,"url":"https://api.github.com/repos/pallets/flask/labels/bug","name":"bug","color":"d93f0b","default":true}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":{"url":"https://api.github.com/repos/pallets/flask/milestones/5","html_url":"https://github.com/pallets/flask/milestone/5","labels_url":"https://api.github.com/repos/pallets/flask/milestones/5/labels","id":3304290,"number":5,"title":"1.0.1","description":"","creator":{"login":"davidism","id":1242887,"avatar_url":"https://avatars1.githubusercontent.com/u/1242887?v=4","gravatar_id":"","url":"https://api.github.com/users/davidism","html_url":"https://github.com/davidism","followers_url":"https://api.github.com/users/davidism/followers","following_url":"https://api.github.com/users/davidism/following{/other_user}","gists_url":"https://api.github.com/users/davidism/gists{/gist_id}","starred_url":"https://api.github.com/users/davidism/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/davidism/subscriptions","organizations_url":"https://api.github.com/users/davidism/orgs","repos_url":"https://api.github.com/users/davidism/repos","events_url":"https://api.github.com/users/davidism/events{/privacy}","received_events_url":"https://api.github.com/users/davidism/received_events","type":"User","site_admin":false},"open_issues":0,"closed_issues":18,"state":"closed","created_at":"2018-04-27T13:46:37Z","updated_at":"2018-04-30T01:11:27Z","due_on":null,"closed_at":"2018-04-30T01:11:27Z"},"comments":4,"created_at":"2018-04-27T15:44:05Z","updated_at":"2018-04-29T12:07:29Z","closed_at":"2018-04-28T14:01:55Z","author_association":"NONE","body":"### Expected Behavior\r\n\r\nIn flask 1.0, calling flask.abort(400) returns a 500 error in debug mode\r\n\r\n```python\r\nimport flask\r\nimport werkzeug\r\n\r\nAPP = flask.Flask(__name__)\r\nprint(flask.__version__)\r\nprint(werkzeug.__version__)\r\n\r\n@APP.route('/<arg>')\r\ndef index(arg):\r\n    return flask.abort(400)\r\n\r\nAPP.debug = True\r\nAPP.run()\r\n```\r\n\r\n### Actual Behavior\r\n\r\nWhen ``App.debug = True`` is set:\r\n````\r\n127.0.0.1 - - [27/Apr/2018 17:39:16] \"GET /tes HTTP/1.1\" 500 -\r\nTraceback (most recent call last):\r\n  File \"/home/pingou/.local/share/virtualenvs/pag/lib/python2.7/site-packages/flask/app.py\", line 2301, in __call__\r\n    return self.wsgi_app(environ, start_response)\r\n  File \"/home/pingou/.local/share/virtualenvs/pag/lib/python2.7/site-packages/flask/app.py\", line 2287, in wsgi_app\r\n    response = self.handle_exception(e)\r\n  File \"/home/pingou/.local/share/virtualenvs/pag/lib/python2.7/site-packages/flask/app.py\", line 1733, in handle_exception\r\n    reraise(exc_type, exc_value, tb)\r\n  File \"/home/pingou/.local/share/virtualenvs/pag/lib/python2.7/site-packages/flask/app.py\", line 2284, in wsgi_app\r\n    response = self.full_dispatch_request()\r\n  File \"/home/pingou/.local/share/virtualenvs/pag/lib/python2.7/site-packages/flask/app.py\", line 1807, in full_dispatch_request\r\n    rv = self.handle_user_exception(e)\r\n  File \"/home/pingou/.local/share/virtualenvs/pag/lib/python2.7/site-packages/flask/app.py\", line 1710, in handle_user_exception\r\n    reraise(exc_type, exc_value, tb)\r\n  File \"/home/pingou/.local/share/virtualenvs/pag/lib/python2.7/site-packages/flask/app.py\", line 1805, in full_dispatch_request\r\n    rv = self.dispatch_request()\r\n  File \"/home/pingou/.local/share/virtualenvs/pag/lib/python2.7/site-packages/flask/app.py\", line 1791, in dispatch_request\r\n    return self.view_functions[rule.endpoint](**req.view_args)\r\n  File \"/home/pingou/reproducer.py\", line 12, in index\r\n    return flask.abort(400)\r\n  File \"/home/pingou/.local/share/virtualenvs/pag/lib/python2.7/site-packages/werkzeug/exceptions.py\", line 707, in abort\r\n    return _aborter(status, *args, **kwargs)\r\n  File \"/home/pingou/.local/share/virtualenvs/pag/lib/python2.7/site-packages/werkzeug/exceptions.py\", line 687, in __call__\r\n    raise self.mapping[code](*args, **kwargs)\r\nBadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.\r\n````\r\n\r\nCalling the endpoint via requests show:\r\n```\r\n>>> requests.get('http://127.0.0.1:5000/tes')\r\n<Response [500]>\r\n```\r\n\r\nWhen ``App.debug = True`` is commented out, I get the expected behavior:\r\n```\r\n>>> requests.get('http://127.0.0.1:5000/tes')\r\n<Response [400]>\r\n```\r\n\r\n### Environment\r\n\r\n* Python version: in this case 2.7.14\r\n* Flask version: 1.0\r\n* Werkzeug version: 0.14.1\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2734","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2734/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2734/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2734/events","html_url":"https://github.com/pallets/flask/issues/2734","id":318447486,"number":2734,"title":"Running pytest on flask 1.0 (ModuleNotFoundError: No module named 'flask.json.tag'; 'flask.json' is not a package)","user":{"login":"claygorman","id":4524500,"avatar_url":"https://avatars2.githubusercontent.com/u/4524500?v=4","gravatar_id":"","url":"https://api.github.com/users/claygorman","html_url":"https://github.com/claygorman","followers_url":"https://api.github.com/users/claygorman/followers","following_url":"https://api.github.com/users/claygorman/following{/other_user}","gists_url":"https://api.github.com/users/claygorman/gists{/gist_id}","starred_url":"https://api.github.com/users/claygorman/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/claygorman/subscriptions","organizations_url":"https://api.github.com/users/claygorman/orgs","repos_url":"https://api.github.com/users/claygorman/repos","events_url":"https://api.github.com/users/claygorman/events{/privacy}","received_events_url":"https://api.github.com/users/claygorman/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-04-27T15:13:39Z","updated_at":"2018-04-27T15:27:47Z","closed_at":"2018-04-27T15:27:47Z","author_association":"NONE","body":"### Expected Behavior\r\n\r\nWhen I run pytest on my code it should complete all tests successfully. This does work fine in 0.12.2.\r\n\r\n### Actual Behavior\r\n\r\nAfter upgrading to flask 1.0 I get a strange error when running pytest. I was hoping you might have some insight\r\n\r\n```pytb\r\nTraceback (most recent call last):\r\n  File \"/Volumes/Storage/Users/claygorman/.pyenv/versions/3.6.4/envs/testproj-1/lib/python3.6/site-packages/_pytest/config.py\", line 371, in _importconftest\r\n    mod = conftestpath.pyimport()\r\n  File \"/Volumes/Storage/Users/claygorman/.pyenv/versions/3.6.4/envs/testproj-1/lib/python3.6/site-packages/py/_path/local.py\", line 668, in pyimport\r\n    __import__(modname)\r\n  File \"/Volumes/Storage/Users/claygorman/.pyenv/versions/3.6.4/envs/testproj-1/lib/python3.6/site-packages/_pytest/assertion/rewrite.py\", line 213, in load_module\r\n    py.builtin.exec_(co, mod.__dict__)\r\n  File \"/Volumes/Storage/clay-dev/testproj/tests/conftest.py\", line 13, in <module>\r\n    from testproj import create_app\r\n  File \"/Volumes/Storage/clay-dev/testproj/testproj/__init__.py\", line 8, in <module>\r\n    from flask import Flask\r\n  File \"/Volumes/Storage/Users/claygorman/.pyenv/versions/3.6.4/envs/testproj-1/lib/python3.6/site-packages/flask/__init__.py\", line 21, in <module>\r\n    from .app import Flask, Request, Response\r\n  File \"/Volumes/Storage/Users/claygorman/.pyenv/versions/3.6.4/envs/testproj-1/lib/python3.6/site-packages/_pytest/assertion/rewrite.py\", line 213, in load_module\r\n    py.builtin.exec_(co, mod.__dict__)\r\n  File \"/Volumes/Storage/Users/claygorman/.pyenv/versions/3.6.4/envs/testproj-1/lib/python3.6/site-packages/flask/app.py\", line 34, in <module>\r\n    from .sessions import SecureCookieSessionInterface\r\n  File \"/Volumes/Storage/Users/claygorman/.pyenv/versions/3.6.4/envs/testproj-1/lib/python3.6/site-packages/_pytest/assertion/rewrite.py\", line 213, in load_module\r\n    py.builtin.exec_(co, mod.__dict__)\r\n  File \"/Volumes/Storage/Users/claygorman/.pyenv/versions/3.6.4/envs/testproj-1/lib/python3.6/site-packages/flask/sessions.py\", line 21, in <module>\r\n    from flask.json.tag import TaggedJSONSerializer\r\nModuleNotFoundError: No module named 'flask.json.tag'; 'flask.json' is not a package\r\nERROR: could not load /Volumes/Storage/clay-dev/testproj/tests/conftest.py\r\n\r\n```\r\n\r\n### Environment\r\n\r\n* Python version: 3.6.4\r\n* Flask version: 1.0\r\n* Werkzeug version: 0.14.1\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2732","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2732/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2732/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2732/events","html_url":"https://github.com/pallets/flask/issues/2732","id":318415588,"number":2732,"title":"support for \" url_for('api.book', book_id='${bookId}') \"","user":{"login":"fushall1104","id":10955562,"avatar_url":"https://avatars0.githubusercontent.com/u/10955562?v=4","gravatar_id":"","url":"https://api.github.com/users/fushall1104","html_url":"https://github.com/fushall1104","followers_url":"https://api.github.com/users/fushall1104/followers","following_url":"https://api.github.com/users/fushall1104/following{/other_user}","gists_url":"https://api.github.com/users/fushall1104/gists{/gist_id}","starred_url":"https://api.github.com/users/fushall1104/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/fushall1104/subscriptions","organizations_url":"https://api.github.com/users/fushall1104/orgs","repos_url":"https://api.github.com/users/fushall1104/repos","events_url":"https://api.github.com/users/fushall1104/events{/privacy}","received_events_url":"https://api.github.com/users/fushall1104/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-04-27T13:45:45Z","updated_at":"2018-04-27T13:48:54Z","closed_at":"2018-04-27T13:48:54Z","author_association":"NONE","body":"Could you add a optional param to flask.url_for ?  :) \r\nwhen I call  `url_for('api.book', book_id=\"${bookId}\")`, \r\nreturned value will be  `'/api/book/%{bookId}' `,\r\ninstead of `'/api/book/%24%7BbookId%7D' `\r\n\r\n> a snippet in index.html\r\n```html\r\n<script>\r\n    let bookId = '123';\r\n    let url = `{{ url_for('api.books', book_id='${bookId}') }}`\r\n\taxios.get(url)\r\n\t...\r\n\t...\r\n</script>\r\n```\r\n> a blueprint\r\n```python\r\napi = Blueprint(xx,xx,xx, url_prefix='api')\r\n@api.route('/book/<str: book_id>')\r\ndef books(book_id):\r\n    xxxxxx\r\n    xxxxxx\r\n    return xxx\r\n```\r\n\r\n\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2731","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2731/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2731/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2731/events","html_url":"https://github.com/pallets/flask/issues/2731","id":318404450,"number":2731,"title":"Flask 1.0 backwards-incompat with double-slash/no-slash re. #2629","user":{"login":"brianmhunt","id":135528,"avatar_url":"https://avatars1.githubusercontent.com/u/135528?v=4","gravatar_id":"","url":"https://api.github.com/users/brianmhunt","html_url":"https://github.com/brianmhunt","followers_url":"https://api.github.com/users/brianmhunt/followers","following_url":"https://api.github.com/users/brianmhunt/following{/other_user}","gists_url":"https://api.github.com/users/brianmhunt/gists{/gist_id}","starred_url":"https://api.github.com/users/brianmhunt/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/brianmhunt/subscriptions","organizations_url":"https://api.github.com/users/brianmhunt/orgs","repos_url":"https://api.github.com/users/brianmhunt/repos","events_url":"https://api.github.com/users/brianmhunt/events{/privacy}","received_events_url":"https://api.github.com/users/brianmhunt/received_events","type":"User","site_admin":false},"labels":[{"id":357932495,"url":"https://api.github.com/repos/pallets/flask/labels/blueprints","name":"blueprints","color":"1d76db","default":false},{"id":135583063,"url":"https://api.github.com/repos/pallets/flask/labels/bug","name":"bug","color":"d93f0b","default":true}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":{"url":"https://api.github.com/repos/pallets/flask/milestones/5","html_url":"https://github.com/pallets/flask/milestone/5","labels_url":"https://api.github.com/repos/pallets/flask/milestones/5/labels","id":3304290,"number":5,"title":"1.0.1","description":"","creator":{"login":"davidism","id":1242887,"avatar_url":"https://avatars1.githubusercontent.com/u/1242887?v=4","gravatar_id":"","url":"https://api.github.com/users/davidism","html_url":"https://github.com/davidism","followers_url":"https://api.github.com/users/davidism/followers","following_url":"https://api.github.com/users/davidism/following{/other_user}","gists_url":"https://api.github.com/users/davidism/gists{/gist_id}","starred_url":"https://api.github.com/users/davidism/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/davidism/subscriptions","organizations_url":"https://api.github.com/users/davidism/orgs","repos_url":"https://api.github.com/users/davidism/repos","events_url":"https://api.github.com/users/davidism/events{/privacy}","received_events_url":"https://api.github.com/users/davidism/received_events","type":"User","site_admin":false},"open_issues":0,"closed_issues":18,"state":"closed","created_at":"2018-04-27T13:46:37Z","updated_at":"2018-04-30T01:11:27Z","due_on":null,"closed_at":"2018-04-30T01:11:27Z"},"comments":1,"created_at":"2018-04-27T13:12:55Z","updated_at":"2018-04-27T19:47:01Z","closed_at":"2018-04-27T19:47:01Z","author_association":"NONE","body":"This is a major backwards-compat breaking change, but I suspect not the intended design and hopefully easy to fix.\r\n\r\nThe issue is related to PR #2629, and this example follows from that:\r\n\r\nGiven blueprint `bp` and app `app`:\r\n\r\n```python\r\n@bp.route('b/')\r\ndef tmp():\r\n    return \"URI should be '/a/b/\"\r\n\r\napp.register_blueprint(bp, url_prefix='/a/')\r\n```\r\n\r\nIn Flask 0.12 the URL is correctly `/a/b`, but in Flask 1.0 it's `/ab`.\r\n\r\nSince issue #2629 relates to resolve double-slashes, I imagine this is a bug (and not a design decision) - and the correct solution would be to remove a slash only when there are two.\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2728","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2728/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2728/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2728/events","html_url":"https://github.com/pallets/flask/issues/2728","id":318341243,"number":2728,"title":"Wrong wheel for Flask 0.12.3 in PyPI","user":{"login":"lafrech","id":1767010,"avatar_url":"https://avatars0.githubusercontent.com/u/1767010?v=4","gravatar_id":"","url":"https://api.github.com/users/lafrech","html_url":"https://github.com/lafrech","followers_url":"https://api.github.com/users/lafrech/followers","following_url":"https://api.github.com/users/lafrech/following{/other_user}","gists_url":"https://api.github.com/users/lafrech/gists{/gist_id}","starred_url":"https://api.github.com/users/lafrech/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/lafrech/subscriptions","organizations_url":"https://api.github.com/users/lafrech/orgs","repos_url":"https://api.github.com/users/lafrech/repos","events_url":"https://api.github.com/users/lafrech/events{/privacy}","received_events_url":"https://api.github.com/users/lafrech/received_events","type":"User","site_admin":false},"labels":[{"id":135583063,"url":"https://api.github.com/repos/pallets/flask/labels/bug","name":"bug","color":"d93f0b","default":true},{"id":384871623,"url":"https://api.github.com/repos/pallets/flask/labels/packaging","name":"packaging","color":"006b75","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":10,"created_at":"2018-04-27T09:34:05Z","updated_at":"2018-04-30T01:27:34Z","closed_at":"2018-04-30T01:27:34Z","author_association":"NONE","body":"https://pypi.org/project/Flask/0.12.3/#files\r\n\r\n*Flask-0.12.3-py2.py3-none-any.whl* contains a `flask/json` directory.\r\n\r\nIt does not correspond to the `0.12.3` tag. Looks like it is a more recent revision.\r\n\r\nThe .tag.gz looks fine (I just checked it contains `flask/json.py` and no `flask/json` directory).","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2726","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2726/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2726/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2726/events","html_url":"https://github.com/pallets/flask/issues/2726","id":318264494,"number":2726,"title":"New tuple requirement for response is restrictive","user":{"login":"harveyslash","id":7107410,"avatar_url":"https://avatars1.githubusercontent.com/u/7107410?v=4","gravatar_id":"","url":"https://api.github.com/users/harveyslash","html_url":"https://github.com/harveyslash","followers_url":"https://api.github.com/users/harveyslash/followers","following_url":"https://api.github.com/users/harveyslash/following{/other_user}","gists_url":"https://api.github.com/users/harveyslash/gists{/gist_id}","starred_url":"https://api.github.com/users/harveyslash/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/harveyslash/subscriptions","organizations_url":"https://api.github.com/users/harveyslash/orgs","repos_url":"https://api.github.com/users/harveyslash/repos","events_url":"https://api.github.com/users/harveyslash/events{/privacy}","received_events_url":"https://api.github.com/users/harveyslash/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":{"url":"https://api.github.com/repos/pallets/flask/milestones/5","html_url":"https://github.com/pallets/flask/milestone/5","labels_url":"https://api.github.com/repos/pallets/flask/milestones/5/labels","id":3304290,"number":5,"title":"1.0.1","description":"","creator":{"login":"davidism","id":1242887,"avatar_url":"https://avatars1.githubusercontent.com/u/1242887?v=4","gravatar_id":"","url":"https://api.github.com/users/davidism","html_url":"https://github.com/davidism","followers_url":"https://api.github.com/users/davidism/followers","following_url":"https://api.github.com/users/davidism/following{/other_user}","gists_url":"https://api.github.com/users/davidism/gists{/gist_id}","starred_url":"https://api.github.com/users/davidism/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/davidism/subscriptions","organizations_url":"https://api.github.com/users/davidism/orgs","repos_url":"https://api.github.com/users/davidism/repos","events_url":"https://api.github.com/users/davidism/events{/privacy}","received_events_url":"https://api.github.com/users/davidism/received_events","type":"User","site_admin":false},"open_issues":0,"closed_issues":18,"state":"closed","created_at":"2018-04-27T13:46:37Z","updated_at":"2018-04-30T01:11:27Z","due_on":null,"closed_at":"2018-04-30T01:11:27Z"},"comments":9,"created_at":"2018-04-27T03:17:59Z","updated_at":"2018-04-27T17:16:42Z","closed_at":"2018-04-27T12:47:00Z","author_association":"NONE","body":"\r\nI had written a simple wrapper to take all the response primitives, and jsonify them before returning to client like so: \r\n\r\n\r\n```python\r\nclass JSONifyResponseWrapper(Response):\r\n    default_mimetype = 'application/json'\r\n\r\n    @classmethod\r\n    def force_type(cls, rv, environ=None):\r\n        try:\r\n            rv = jsonify(rv)\r\n        finally:\r\n            return super(JSONifyResponseWrapper, cls).force_type(rv, environ)\r\n```\r\nThen i set app.response_class to the class above. \r\n\r\nHowever, in flask 1.0 , the routes are required to return a tuple. \r\nThis means if I have a route like this: \r\n\r\n```python\r\n@base_blueprint.route('', methods=['Post'])\r\ndef hello():\r\n    a = {\"hello\":\"world\"} \r\n   return a\r\n```\r\n\r\nThe client receives a valid json object. \r\n\r\nBut if I do this: \r\n\r\n```python\r\n@base_blueprint.route('', methods=['Post'])\r\ndef hello():\r\n    a = [i for i in range(100)]\r\n   return a\r\n```\r\nFlask will throw this error: \r\n\r\n> TypeError: The view function did not return a valid response tuple. The tuple must have the form (body, status, headers), (body, status), or (body, headers)`","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2725","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2725/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2725/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2725/events","html_url":"https://github.com/pallets/flask/issues/2725","id":318255598,"number":2725,"title":"[help] flask 1.0 app run in click ","user":{"login":"ngxlua","id":31426367,"avatar_url":"https://avatars3.githubusercontent.com/u/31426367?v=4","gravatar_id":"","url":"https://api.github.com/users/ngxlua","html_url":"https://github.com/ngxlua","followers_url":"https://api.github.com/users/ngxlua/followers","following_url":"https://api.github.com/users/ngxlua/following{/other_user}","gists_url":"https://api.github.com/users/ngxlua/gists{/gist_id}","starred_url":"https://api.github.com/users/ngxlua/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ngxlua/subscriptions","organizations_url":"https://api.github.com/users/ngxlua/orgs","repos_url":"https://api.github.com/users/ngxlua/repos","events_url":"https://api.github.com/users/ngxlua/events{/privacy}","received_events_url":"https://api.github.com/users/ngxlua/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":5,"created_at":"2018-04-27T02:18:56Z","updated_at":"2018-04-27T15:52:36Z","closed_at":"2018-04-27T15:52:36Z","author_association":"NONE","body":"### Expected Behavior\r\n\r\nWhen I try to upgrade to 1.0, my code is not compatible with 1.0 flask, how should I solve it?\r\n\r\n```python\r\n@cli.command(\"run\", help=\"run server\")\r\n@click.option('--mode', help=\"Application running mode\", default=\"dev\")\r\ndef runserver(mode, daemon, reload, preload, spew):\r\n    if mode == 'prod':\r\n        \"\"\"\r\n        do something\r\n        \"\"\"\r\n\r\n    app.run(host=app.config[\"HOST\"], port=app.config[\"PORT\"], use_reloader=True)\r\n\r\nif __name__ == '__main__':\r\n    sys.exit(cli.main())\r\n```\r\n\r\n### Actual Behavior\r\n\r\n```pytb\r\nmanage.py:110: Warning: Silently ignoring app.run() because the application is run from the flask command line executable.  Consider putting app.run() behind an if __name__ == \"__main__\" guard to silence this warning.\r\n  app.run(host=app.config[\"HOST\"], port=app.config[\"PORT\"], use_reloader=True)\r\n```\r\n\r\n### Environment\r\n\r\n* Python version: 3.6.4\r\n* Flask version: 1.0\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2723","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2723/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2723/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2723/events","html_url":"https://github.com/pallets/flask/issues/2723","id":318221921,"number":2723,"title":"Where are all the issues?","user":{"login":"westonplatter","id":492603,"avatar_url":"https://avatars1.githubusercontent.com/u/492603?v=4","gravatar_id":"","url":"https://api.github.com/users/westonplatter","html_url":"https://github.com/westonplatter","followers_url":"https://api.github.com/users/westonplatter/followers","following_url":"https://api.github.com/users/westonplatter/following{/other_user}","gists_url":"https://api.github.com/users/westonplatter/gists{/gist_id}","starred_url":"https://api.github.com/users/westonplatter/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/westonplatter/subscriptions","organizations_url":"https://api.github.com/users/westonplatter/orgs","repos_url":"https://api.github.com/users/westonplatter/repos","events_url":"https://api.github.com/users/westonplatter/events{/privacy}","received_events_url":"https://api.github.com/users/westonplatter/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-04-26T22:44:22Z","updated_at":"2018-04-26T23:06:49Z","closed_at":"2018-04-26T22:46:45Z","author_association":"NONE","body":"Asking because I'm interested in contributed and would think there are more than 18 issues.\r\n\r\nFeel free to close this.","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2722","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2722/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2722/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2722/events","html_url":"https://github.com/pallets/flask/issues/2722","id":318215773,"number":2722,"title":"Add a parameter to disable load dotenv using Flask CLI","user":{"login":"fabiocerqueira","id":58733,"avatar_url":"https://avatars0.githubusercontent.com/u/58733?v=4","gravatar_id":"","url":"https://api.github.com/users/fabiocerqueira","html_url":"https://github.com/fabiocerqueira","followers_url":"https://api.github.com/users/fabiocerqueira/followers","following_url":"https://api.github.com/users/fabiocerqueira/following{/other_user}","gists_url":"https://api.github.com/users/fabiocerqueira/gists{/gist_id}","starred_url":"https://api.github.com/users/fabiocerqueira/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/fabiocerqueira/subscriptions","organizations_url":"https://api.github.com/users/fabiocerqueira/orgs","repos_url":"https://api.github.com/users/fabiocerqueira/repos","events_url":"https://api.github.com/users/fabiocerqueira/events{/privacy}","received_events_url":"https://api.github.com/users/fabiocerqueira/received_events","type":"User","site_admin":false},"labels":[{"id":380608249,"url":"https://api.github.com/repos/pallets/flask/labels/cli","name":"cli","color":"1d76db","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":{"url":"http
3811
s://api.github.com/repos/pallets/flask/milestones/5","html_url":"https://github.com/pallets/flask/milestone/5","labels_url":"https://api.github.com/repos/pallets/flask/milestones/5/labels","id":3304290,"number":5,"title":"1.0.1","description":"","creator":{"login":"davidism","id":1242887,"avatar_url":"https://avatars1.githubusercontent.com/u/1242887?v=4","gravatar_id":"","url":"https://api.github.com/users/davidism","html_url":"https://github.com/davidism","followers_url":"https://api.github.com/users/davidism/followers","following_url":"https://api.github.com/users/davidism/following{/other_user}","gists_url":"https://api.github.com/users/davidism/gists{/gist_id}","starred_url":"https://api.github.com/users/davidism/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/davidism/subscriptions","organizations_url":"https://api.github.com/users/davidism/orgs","repos_url":"https://api.github.com/users/davidism/repos","events_url":"https://api.github.com/users/davidism/events{/privacy}","received_events_url":"https://api.github.com/users/davidism/received_events","type":"User","site_admin":false},"open_issues":0,"closed_issues":18,"state":"closed","created_at":"2018-04-27T13:46:37Z","updated_at":"2018-04-30T01:11:27Z","due_on":null,"closed_at":"2018-04-30T01:11:27Z"},"comments":7,"created_at":"2018-04-26T22:15:06Z","updated_at":"2018-04-29T21:27:18Z","closed_at":"2018-04-29T21:27:18Z","author_association":"NONE","body":"Running Flask CLI with pipenv using the new version(1.0) \r\n\r\n```\r\npipenv run flask run\r\n```\r\n\r\nI always get the tip message about the load_dotenv feature. Since pipenv [already load](https://docs.pipenv.org/advanced/#automatic-loading-of-env) the `.env` file, It might be interesting have some parameter to disable Flask to load `.env` and does not show the tip message.\r\n\r\n### Expected Behavior\r\n\r\nDisable load dotenv using the Flask CLI. Example:\r\n\r\n```\r\npipenv run flask run --ignore-dotenv\r\n```\r\n\r\nOr just remove the tip message and let it only in the documentation.\r\n\r\n### Actual Behavior\r\nShowing the dotenv tip message even if the developer doesn't want to use it\r\n`* Tip: There are .env files present. Do \"pip install python-dotenv\" to use them`\r\n\r\n### Environment\r\n\r\n* Python version: 3.6.4\r\n* Flask version: 1.0\r\n* Werkzeug version: 0.14.1\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2718","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2718/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2718/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2718/events","html_url":"https://github.com/pallets/flask/issues/2718","id":316722513,"number":2718,"title":"Why can not load a sklearn model by the request for Flask","user":{"login":"Wingoom","id":13585988,"avatar_url":"https://avatars1.githubusercontent.com/u/13585988?v=4","gravatar_id":"","url":"https://api.github.com/users/Wingoom","html_url":"https://github.com/Wingoom","followers_url":"https://api.github.com/users/Wingoom/followers","following_url":"https://api.github.com/users/Wingoom/following{/other_user}","gists_url":"https://api.github.com/users/Wingoom/gists{/gist_id}","starred_url":"https://api.github.com/users/Wingoom/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Wingoom/subscriptions","organizations_url":"https://api.github.com/users/Wingoom/orgs","repos_url":"https://api.github.com/users/Wingoom/repos","events_url":"https://api.github.com/users/Wingoom/events{/privacy}","received_events_url":"https://api.github.com/users/Wingoom/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-04-23T09:02:35Z","updated_at":"2018-04-23T13:01:33Z","closed_at":"2018-04-23T13:01:33Z","author_association":"NONE","body":"I saved a sklearn model by joblib.load()。\r\n```\r\n    model = RandomForestClassifier(n_estimators=100)\r\n    model.fit(feature_train, target_train)\r\n    joblib.dump(model, \"%s/%s\" % (model_path,\"RandomForest.pkl\"))\r\n```\r\n\r\nAnd I want to load the model through sending a request。\r\n```\r\n@app.route('/getClassification/',methods=['GET','POST'])\r\ndef classify():\r\n    load_model = joblib.load( \"%s/%s\" % (model_path,\"RandomForest.pkl\"))\r\n    return  \"test\"\r\n```\r\n```\r\ntry:\r\n    reponse = requests.post(monitor_url, data=params, timeout=60)\r\n    print reponse.content\r\nexcept Exception, e:\r\n    print e\r\n```\r\nBut the request never responded  until it Read timed out。\r\n\r\nI dont save a sklearn model ，instead I save a string for testing。\r\n```\r\njoblib.dump(\"111222\", \"%s/%s\" % (model_path,\"RandomForest.pkl\"))\r\n```\r\nIt loaded successfully。\r\n\r\nIf I load the model alone，no use request for Flask，It can also load successfully.\r\n\r\nWhy can not load  a sklearn model by the request for Flask\r\n\r\n### Environment\r\n\r\n* Python version: 2.7.14\r\n* Flask version:0.12.2\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2716","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2716/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2716/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2716/events","html_url":"https://github.com/pallets/flask/issues/2716","id":316542450,"number":2716,"title":"Port Issue","user":{"login":"PyDever","id":28792696,"avatar_url":"https://avatars3.githubusercontent.com/u/28792696?v=4","gravatar_id":"","url":"https://api.github.com/users/PyDever","html_url":"https://github.com/PyDever","followers_url":"https://api.github.com/users/PyDever/followers","following_url":"https://api.github.com/users/PyDever/following{/other_user}","gists_url":"https://api.github.com/users/PyDever/gists{/gist_id}","starred_url":"https://api.github.com/users/PyDever/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/PyDever/subscriptions","organizations_url":"https://api.github.com/users/PyDever/orgs","repos_url":"https://api.github.com/users/PyDever/repos","events_url":"https://api.github.com/users/PyDever/events{/privacy}","received_events_url":"https://api.github.com/users/PyDever/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-04-22T02:21:14Z","updated_at":"2018-04-22T04:31:37Z","closed_at":"2018-04-22T03:08:48Z","author_association":"NONE","body":"Not sure if this is a bug or a system issue.\n\n`(debug=True, port=3000)`\n\nyet my app still runs on `5000` (default port) \n      ","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2715","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2715/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2715/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2715/events","html_url":"https://github.com/pallets/flask/issues/2715","id":316465705,"number":2715,"title":"E-commerce","user":{"login":"KeithCu","id":662157,"avatar_url":"https://avatars0.githubusercontent.com/u/662157?v=4","gravatar_id":"","url":"https://api.github.com/users/KeithCu","html_url":"https://github.com/KeithCu","followers_url":"https://api.github.com/users/KeithCu/followers","following_url":"https://api.github.com/users/KeithCu/following{/other_user}","gists_url":"https://api.github.com/users/KeithCu/gists{/gist_id}","starred_url":"https://api.github.com/users/KeithCu/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/KeithCu/subscriptions","organizations_url":"https://api.github.com/users/KeithCu/orgs","repos_url":"https://api.github.com/users/KeithCu/repos","events_url":"https://api.github.com/users/KeithCu/events{/privacy}","received_events_url":"https://api.github.com/users/KeithCu/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":true,"assignee":null,"assignees":[],"milestone":null,"comments":5,"created_at":"2018-04-21T06:07:19Z","updated_at":"2018-04-21T07:24:15Z","closed_at":"2018-04-21T06:09:46Z","author_association":"NONE","body":"Flask is a very well-designed project to build many kinds of small to big websites, but you run into a problem if you want to do e-commerce.\r\n\r\nI think you should consider porting this to Flask:\r\nhttps://github.com/django-oscar/django-oscar\r\n\r\nIt seems to be the most popular Django e-commerce solution.\r\n\r\nI'm not sure how much would have to be changed. Note you would need to port over some of the plugins like for Paypal, which is 1200 lines.\r\n\r\nMaybe it is even possible to have some if Django and if Flask lines and keep it all in one codebase.\r\n\r\nI realize this is not an easy bug, but maybe if enough people are interested, something could happen one day.","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2714","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2714/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2714/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2714/events","html_url":"https://github.com/pallets/flask/issues/2714","id":316441472,"number":2714,"title":"Flask website has broken links","user":{"login":"KeithCu","id":662157,"avatar_url":"https://avatars0.githubusercontent.com/u/662157?v=4","gravatar_id":"","url":"https://api.github.com/users/KeithCu","html_url":"https://github.com/KeithCu","followers_url":"https://api.github.com/users/KeithCu/followers","following_url":"https://api.github.com/users/KeithCu/following{/other_user}","gists_url":"https://api.github.com/users/KeithCu/gists{/gist_id}","starred_url":"https://api.github.com/users/KeithCu/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/KeithCu/subscriptions","organizations_url":"https://api.github.com/users/KeithCu/orgs","repos_url":"https://api.github.com/users/KeithCu/repos","events_url":"https://api.github.com/users/KeithCu/events{/privacy}","received_events_url":"https://api.github.com/users/KeithCu/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-04-20T23:48:21Z","updated_at":"2018-04-21T01:50:07Z","closed_at":"2018-04-21T01:50:07Z","author_association":"NONE","body":"If you go to: http://flask.pocoo.org/\r\n\r\nAnd you try to click on the microblog link or the twitter clone link, neither of them work because the URLs have changed.","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2713","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2713/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2713/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2713/events","html_url":"https://github.com/pallets/flask/issues/2713","id":316390931,"number":2713,"title":"Support for more environment variables for Flask CLI","user":{"login":"JhossePaul","id":12739015,"avatar_url":"https://avatars0.githubusercontent.com/u/12739015?v=4","gravatar_id":"","url":"https://api.github.com/users/JhossePaul","html_url":"https://github.com/JhossePaul","followers_url":"https://api.github.com/users/JhossePaul/followers","following_url":"https://api.github.com/users/JhossePaul/following{/other_user}","gists_url":"https://api.github.com/users/JhossePaul/gists{/gist_id}","starred_url":"https://api.github.com/users/JhossePaul/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/JhossePaul/subscriptions","organizations_url":"https://api.github.com/users/JhossePaul/orgs","repos_url":"https://api.github.com/users/JhossePaul/repos","events_url":"https://api.github.com/users/JhossePaul/events{/privacy}","received_events_url":"https://api.github.com/users/JhossePaul/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":{"url":"https://api.github.com/repos/pallets/flask/milestones/2","html_url":"https://github.com/pallets/flask/milestone/2","labels_url":"https://api.github.com/repos/pallets/flask/milestones/2/labels","id":795954,"number":2,"title":"1.0","description":"","creator":{"login":"untitaker","id":837573,"avatar_url":"https://avatars0.githubusercontent.com/u/837573?v=4","gravatar_id":"","url":"https://api.github.com/users/untitaker","html_url":"https://github.com/untitaker","followers_url":"https://api.github.com/users/untitaker/followers","following_url":"https://api.github.com/users/untitaker/following{/other_user}","gists_url":"https://api.github.com/users/untitaker/gists{/gist_id}","starred_url":"https://api.github.com/users/untitaker/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/untitaker/subscriptions","organizations_url":"https://api.github.com/users/untitaker/orgs","repos_url":"https://api.github.com/users/untitaker/repos","events_url":"https://api.github.com/users/untitaker/events{/privacy}","received_events_url":"https://api.github.com/users/untitaker/received_events","type":"User","site_admin":false},"open_issues":0,"closed_issues":159,"state":"closed","created_at":"2014-09-19T15:47:20Z","updated_at":"2018-04-26T21:07:44Z","due_on":"2018-04-26T07:00:00Z","closed_at":"2018-04-26T21:07:44Z"},"comments":2,"created_at":"2018-04-20T19:49:49Z","updated_at":"2018-04-20T20:28:26Z","closed_at":"2018-04-20T20:25:27Z","author_association":"NONE","body":"It would be great to add support for more environment variables for Flask CLI. For example,\r\n```python\r\nFLASK_PORT=8080 flask run\r\n```\r\nshould run the app in port 8080 instead of default. Thus, we can have a single .flaskenv file that sets our environment and just `flask run` without further arguments.","score":1.0}]}
0

